// Code generated by protoc-gen-rpc-cgo-jni. DO NOT EDIT.
//
// Source: shared_so.proto

package com.ygrpc.examples.rpccgofluttersharedso

import androidx.annotation.Keep
import com.google.protobuf.MessageLite
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicInteger
import java.util.concurrent.atomic.AtomicBoolean

data class RpccgoResult<T>(val value: T?, val error: String?) {
    val ok: Boolean get() = error == null
    companion object {
        fun <T> success(value: T): RpccgoResult<T> = RpccgoResult(value, null)
        fun <T> failure(error: String): RpccgoResult<T> = RpccgoResult(null, error)
    }
}

object SharedSoDemoJni {
    private val rpccgoServerStreamIDs = AtomicInteger(1)

    /** Handle for a generated JNI callback stream. */
    class RpccgoCallbackStream internal constructor(
        private val cancelCallback: () -> Boolean,
        private val unregisterLifecycle: () -> Unit = {},
    ) : AutoCloseable {
        private val active = AtomicBoolean(true)

        /** Cancels the native stream and unregisters any generated lifecycle callback. */
        fun cancel(): Boolean {
            if (!active.compareAndSet(true, false)) return true
            unregisterLifecycle()
            return cancelCallback()
        }

        internal fun complete() {
            if (active.compareAndSet(true, false)) unregisterLifecycle()
        }

        override fun close() {
            cancel()
        }
    }

    private fun activityOwnedCallbackStream(owner: android.app.Activity, cancel: () -> Boolean): RpccgoCallbackStream {
        var stream: RpccgoCallbackStream? = null
        val callbacks = object : android.app.Application.ActivityLifecycleCallbacks {
            override fun onActivityCreated(activity: android.app.Activity, savedInstanceState: android.os.Bundle?) {}
            override fun onActivityStarted(activity: android.app.Activity) {}
            override fun onActivityResumed(activity: android.app.Activity) {}
            override fun onActivityPaused(activity: android.app.Activity) {}
            override fun onActivityStopped(activity: android.app.Activity) {}
            override fun onActivitySaveInstanceState(activity: android.app.Activity, outState: android.os.Bundle) {}
            override fun onActivityDestroyed(activity: android.app.Activity) {
                if (activity === owner) stream?.cancel()
            }
        }
        owner.application.registerActivityLifecycleCallbacks(callbacks)
        stream = RpccgoCallbackStream(cancel) { owner.application.unregisterActivityLifecycleCallbacks(callbacks) }
        return stream
    }

    private external fun sharedSoDemoComposeGreeting(request: ByteArray): ByteArray?
    private external fun sharedSoDemoComposeGreetingRegister(): ByteArray?
    private external fun sharedSoDemoIncrementRuntimeState(request: ByteArray): ByteArray?
    private external fun sharedSoDemoIncrementRuntimeStateRegister(): ByteArray?
    private external fun sharedSoDemoReadRuntimeState(request: ByteArray): ByteArray?
    private external fun sharedSoDemoReadRuntimeStateRegister(): ByteArray?
    @Keep
    interface SharedSoDemoWatchRuntimeStateListener {
        @Keep
        fun onRecv(responseBytes: ByteArray)
        @Keep
        fun onDone(error: String?)
    }

    interface SharedSoDemoWatchRuntimeStateServerHandler {
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse>
        fun Finish(): RpccgoResult<Unit>
        fun Cancel(): RpccgoResult<Unit>
    }

    private external fun sharedSoDemoWatchRuntimeStateStart(request: ByteArray): ByteArray?
    private external fun sharedSoDemoWatchRuntimeStateRecv(handle: Int): ByteArray?
    private external fun sharedSoDemoWatchRuntimeStateCancel(handle: Int): ByteArray?
    private external fun sharedSoDemoWatchRuntimeStateStartCallback(request: ByteArray, listener: SharedSoDemoWatchRuntimeStateListener): Boolean
    private external fun sharedSoDemoWatchRuntimeStateCancelCallback(): Boolean
    private external fun sharedSoDemoWatchRuntimeStateRegister(): ByteArray?
    interface SharedSoDemoCollectRuntimeStateServerHandler {
        fun Send(req: examples.flutter.sharedso.v1.IncrementRuntimeStateRequest): RpccgoResult<Unit>
        fun Finish(): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse>
        fun Cancel(): RpccgoResult<Unit>
    }

    private external fun sharedSoDemoCollectRuntimeStateStart(): ByteArray?
    private external fun sharedSoDemoCollectRuntimeStateSend(handle: Int, request: ByteArray): ByteArray?
    private external fun sharedSoDemoCollectRuntimeStateFinish(handle: Int): ByteArray?
    private external fun sharedSoDemoCollectRuntimeStateCancel(handle: Int): ByteArray?
    private external fun sharedSoDemoCollectRuntimeStateRegister(): ByteArray?
    @Keep
    interface SharedSoDemoStreamRuntimeStateListener {
        @Keep
        fun onRecv(responseBytes: ByteArray)
        @Keep
        fun onDone(error: String?)
    }

    interface SharedSoDemoStreamRuntimeStateServerHandler {
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse>
        fun Finish(): RpccgoResult<Unit>
        fun Cancel(): RpccgoResult<Unit>
    }

    private external fun sharedSoDemoStreamRuntimeStateStart(request: ByteArray): ByteArray?
    private external fun sharedSoDemoStreamRuntimeStateRecv(handle: Int): ByteArray?
    private external fun sharedSoDemoStreamRuntimeStateCancel(handle: Int): ByteArray?
    private external fun sharedSoDemoStreamRuntimeStateStartCallback(request: ByteArray, listener: SharedSoDemoStreamRuntimeStateListener): Boolean
    private external fun sharedSoDemoStreamRuntimeStateCancelCallback(): Boolean
    private external fun sharedSoDemoStreamRuntimeStateRegister(): ByteArray?
    @Keep
    interface SharedSoDemoChatRuntimeStateListener {
        @Keep
        fun onRecv(responseBytes: ByteArray)
        @Keep
        fun onDone(error: String?)
    }

    interface SharedSoDemoChatRuntimeStateServerHandler {
        fun Send(req: examples.flutter.sharedso.v1.IncrementRuntimeStateRequest): RpccgoResult<Unit>
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse>
        fun CloseSend(): RpccgoResult<Unit>
        fun Finish(): RpccgoResult<Unit>
        fun Cancel(): RpccgoResult<Unit>
    }

    private external fun sharedSoDemoChatRuntimeStateStart(): ByteArray?
    private external fun sharedSoDemoChatRuntimeStateSend(handle: Int, request: ByteArray): ByteArray?
    private external fun sharedSoDemoChatRuntimeStateRecv(handle: Int): ByteArray?
    private external fun sharedSoDemoChatRuntimeStateCloseSend(handle: Int): ByteArray?
    private external fun sharedSoDemoChatRuntimeStateFinish(handle: Int): ByteArray?
    private external fun sharedSoDemoChatRuntimeStateCancel(handle: Int): ByteArray?
    private external fun sharedSoDemoChatRuntimeStateStartCallback(listener: SharedSoDemoChatRuntimeStateListener): Boolean
    private external fun sharedSoDemoChatRuntimeStateCancelCallback(): Boolean
    private external fun sharedSoDemoChatRuntimeStateRegister(): ByteArray?
    private external fun androidDeviceSetTorch(request: ByteArray): ByteArray?
    private external fun androidDeviceSetTorchRegister(): ByteArray?
    @Keep
    interface AndroidDeviceWatchAndroidEchoListener {
        @Keep
        fun onRecv(responseBytes: ByteArray)
        @Keep
        fun onDone(error: String?)
    }

    interface AndroidDeviceWatchAndroidEchoServerHandler {
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.AndroidEchoResponse>
        fun Finish(): RpccgoResult<Unit>
        fun Cancel(): RpccgoResult<Unit>
    }

    private external fun androidDeviceWatchAndroidEchoStart(request: ByteArray): ByteArray?
    private external fun androidDeviceWatchAndroidEchoRecv(handle: Int): ByteArray?
    private external fun androidDeviceWatchAndroidEchoCancel(handle: Int): ByteArray?
    private external fun androidDeviceWatchAndroidEchoStartCallback(request: ByteArray, listener: AndroidDeviceWatchAndroidEchoListener): Boolean
    private external fun androidDeviceWatchAndroidEchoCancelCallback(): Boolean
    private external fun androidDeviceWatchAndroidEchoRegister(): ByteArray?
    interface AndroidDeviceCollectAndroidEchoServerHandler {
        fun Send(req: examples.flutter.sharedso.v1.AndroidEchoRequest): RpccgoResult<Unit>
        fun Finish(): RpccgoResult<examples.flutter.sharedso.v1.AndroidEchoResponse>
        fun Cancel(): RpccgoResult<Unit>
    }

    private external fun androidDeviceCollectAndroidEchoStart(): ByteArray?
    private external fun androidDeviceCollectAndroidEchoSend(handle: Int, request: ByteArray): ByteArray?
    private external fun androidDeviceCollectAndroidEchoFinish(handle: Int): ByteArray?
    private external fun androidDeviceCollectAndroidEchoCancel(handle: Int): ByteArray?
    private external fun androidDeviceCollectAndroidEchoRegister(): ByteArray?
    @Keep
    interface AndroidDeviceChatAndroidEchoListener {
        @Keep
        fun onRecv(responseBytes: ByteArray)
        @Keep
        fun onDone(error: String?)
    }

    interface AndroidDeviceChatAndroidEchoServerHandler {
        fun Send(req: examples.flutter.sharedso.v1.AndroidEchoRequest): RpccgoResult<Unit>
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.AndroidEchoResponse>
        fun CloseSend(): RpccgoResult<Unit>
        fun Finish(): RpccgoResult<Unit>
        fun Cancel(): RpccgoResult<Unit>
    }

    private external fun androidDeviceChatAndroidEchoStart(): ByteArray?
    private external fun androidDeviceChatAndroidEchoSend(handle: Int, request: ByteArray): ByteArray?
    private external fun androidDeviceChatAndroidEchoRecv(handle: Int): ByteArray?
    private external fun androidDeviceChatAndroidEchoCloseSend(handle: Int): ByteArray?
    private external fun androidDeviceChatAndroidEchoFinish(handle: Int): ByteArray?
    private external fun androidDeviceChatAndroidEchoCancel(handle: Int): ByteArray?
    private external fun androidDeviceChatAndroidEchoStartCallback(listener: AndroidDeviceChatAndroidEchoListener): Boolean
    private external fun androidDeviceChatAndroidEchoCancelCallback(): Boolean
    private external fun androidDeviceChatAndroidEchoRegister(): ByteArray?
    private external fun flutterDeviceDescribeFlutter(request: ByteArray): ByteArray?
    private external fun flutterDeviceDescribeFlutterRegister(): ByteArray?
    @Keep
    interface FlutterDeviceWatchFlutterEchoListener {
        @Keep
        fun onRecv(responseBytes: ByteArray)
        @Keep
        fun onDone(error: String?)
    }

    interface FlutterDeviceWatchFlutterEchoServerHandler {
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.FlutterEchoResponse>
        fun Finish(): RpccgoResult<Unit>
        fun Cancel(): RpccgoResult<Unit>
    }

    private external fun flutterDeviceWatchFlutterEchoStart(request: ByteArray): ByteArray?
    private external fun flutterDeviceWatchFlutterEchoRecv(handle: Int): ByteArray?
    private external fun flutterDeviceWatchFlutterEchoCancel(handle: Int): ByteArray?
    private external fun flutterDeviceWatchFlutterEchoStartCallback(request: ByteArray, listener: FlutterDeviceWatchFlutterEchoListener): Boolean
    private external fun flutterDeviceWatchFlutterEchoCancelCallback(): Boolean
    private external fun flutterDeviceWatchFlutterEchoRegister(): ByteArray?

    fun ComposeGreeting(req: examples.flutter.sharedso.v1.ComposeGreetingRequest): RpccgoResult<examples.flutter.sharedso.v1.ComposeGreetingResponse> =
        decodeResult(sharedSoDemoComposeGreeting(req.toByteArray())) { examples.flutter.sharedso.v1.ComposeGreetingResponse.parseFrom(it) }

    private var sharedSoDemoComposeGreetingServerHandler: ((examples.flutter.sharedso.v1.ComposeGreetingRequest) -> RpccgoResult<examples.flutter.sharedso.v1.ComposeGreetingResponse>)? = null

    fun RegisterComposeGreeting(handler: (examples.flutter.sharedso.v1.ComposeGreetingRequest) -> RpccgoResult<examples.flutter.sharedso.v1.ComposeGreetingResponse>): RpccgoResult<Unit> {
        sharedSoDemoComposeGreetingServerHandler = handler
        val result = decodeUnitResult(sharedSoDemoComposeGreetingRegister())
        if (!result.ok) sharedSoDemoComposeGreetingServerHandler = null
        return result
    }

    @Keep
    private fun sharedSoDemoComposeGreetingHandle(requestBytes: ByteArray): ByteArray = try {
        val handler = sharedSoDemoComposeGreetingServerHandler ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        encodeMessageResult(handler(examples.flutter.sharedso.v1.ComposeGreetingRequest.parseFrom(requestBytes)))
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server handler failed: ${e.message ?: e::class.java.name}")
    }

    fun IncrementRuntimeState(req: examples.flutter.sharedso.v1.IncrementRuntimeStateRequest): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse> =
        decodeResult(sharedSoDemoIncrementRuntimeState(req.toByteArray())) { examples.flutter.sharedso.v1.RuntimeStateResponse.parseFrom(it) }

    private var sharedSoDemoIncrementRuntimeStateServerHandler: ((examples.flutter.sharedso.v1.IncrementRuntimeStateRequest) -> RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse>)? = null

    fun RegisterIncrementRuntimeState(handler: (examples.flutter.sharedso.v1.IncrementRuntimeStateRequest) -> RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse>): RpccgoResult<Unit> {
        sharedSoDemoIncrementRuntimeStateServerHandler = handler
        val result = decodeUnitResult(sharedSoDemoIncrementRuntimeStateRegister())
        if (!result.ok) sharedSoDemoIncrementRuntimeStateServerHandler = null
        return result
    }

    @Keep
    private fun sharedSoDemoIncrementRuntimeStateHandle(requestBytes: ByteArray): ByteArray = try {
        val handler = sharedSoDemoIncrementRuntimeStateServerHandler ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        encodeMessageResult(handler(examples.flutter.sharedso.v1.IncrementRuntimeStateRequest.parseFrom(requestBytes)))
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server handler failed: ${e.message ?: e::class.java.name}")
    }

    fun ReadRuntimeState(req: examples.flutter.sharedso.v1.ReadRuntimeStateRequest): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse> =
        decodeResult(sharedSoDemoReadRuntimeState(req.toByteArray())) { examples.flutter.sharedso.v1.RuntimeStateResponse.parseFrom(it) }

    private var sharedSoDemoReadRuntimeStateServerHandler: ((examples.flutter.sharedso.v1.ReadRuntimeStateRequest) -> RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse>)? = null

    fun RegisterReadRuntimeState(handler: (examples.flutter.sharedso.v1.ReadRuntimeStateRequest) -> RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse>): RpccgoResult<Unit> {
        sharedSoDemoReadRuntimeStateServerHandler = handler
        val result = decodeUnitResult(sharedSoDemoReadRuntimeStateRegister())
        if (!result.ok) sharedSoDemoReadRuntimeStateServerHandler = null
        return result
    }

    @Keep
    private fun sharedSoDemoReadRuntimeStateHandle(requestBytes: ByteArray): ByteArray = try {
        val handler = sharedSoDemoReadRuntimeStateServerHandler ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        encodeMessageResult(handler(examples.flutter.sharedso.v1.ReadRuntimeStateRequest.parseFrom(requestBytes)))
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server handler failed: ${e.message ?: e::class.java.name}")
    }

    fun WatchRuntimeStateStart(req: examples.flutter.sharedso.v1.ReadRuntimeStateRequest): RpccgoResult<SharedSoDemoWatchRuntimeStateServerStream> {
        val handle = decodeHandleResult(sharedSoDemoWatchRuntimeStateStart(req.toByteArray()))
        if (!handle.ok) return RpccgoResult.failure(handle.error ?: "rpccgo: stream start failed")
        return RpccgoResult.success(SharedSoDemoWatchRuntimeStateServerStream(handle.value ?: 0))
    }
    fun WatchRuntimeStateStartCallback(req: examples.flutter.sharedso.v1.ReadRuntimeStateRequest, listener: SharedSoDemoWatchRuntimeStateListener): Boolean =
        sharedSoDemoWatchRuntimeStateStartCallback(req.toByteArray(), listener)
    fun WatchRuntimeStateStartCallback(owner: android.app.Activity, req: examples.flutter.sharedso.v1.ReadRuntimeStateRequest, listener: SharedSoDemoWatchRuntimeStateListener): RpccgoResult<RpccgoCallbackStream> {
        if (owner.isDestroyed) return RpccgoResult.failure("rpccgo: callback stream owner is destroyed")
        val callbackOpen = AtomicBoolean(true)
        var stream: RpccgoCallbackStream? = null
        val ownerListener = object : SharedSoDemoWatchRuntimeStateListener {
            override fun onRecv(responseBytes: ByteArray) {
                if (callbackOpen.get()) listener.onRecv(responseBytes)
            }

            override fun onDone(error: String?) {
                if (!callbackOpen.compareAndSet(true, false)) return
                stream?.complete()
                listener.onDone(error)
            }
        }
        stream = activityOwnedCallbackStream(owner) {
            callbackOpen.set(false)
            WatchRuntimeStateCancelCallback()
        }
        val activeStream = stream ?: return RpccgoResult.failure("rpccgo: callback stream owner registration failed")
        if (!WatchRuntimeStateStartCallback(req, ownerListener)) {
            activeStream.cancel()
            return RpccgoResult.failure("rpccgo: callback stream start failed")
        }
        return RpccgoResult.success(activeStream)
    }
    fun WatchRuntimeStateCancelCallback(): Boolean = sharedSoDemoWatchRuntimeStateCancelCallback()

    class SharedSoDemoWatchRuntimeStateServerStream internal constructor(private val handle: Int) {
        private val receiving = AtomicBoolean(false)
        private fun recvUnchecked(): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse> =
            decodeResult(SharedSoDemoJni.sharedSoDemoWatchRuntimeStateRecv(handle)) { examples.flutter.sharedso.v1.RuntimeStateResponse.parseFrom(it) }
        /** Receives one response. Do not call while RecvEach is running on this stream. */
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse> {
            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure("rpccgo: stream already has an active receiver")
            return try {
                recvUnchecked()
            } finally {
                receiving.set(false)
            }
        }
        fun Cancel(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.sharedSoDemoWatchRuntimeStateCancel(handle))
        /** Starts a background Recv loop. Do not mix with manual Recv calls on this stream. */
        fun RecvEach(onRecv: (examples.flutter.sharedso.v1.RuntimeStateResponse) -> Unit, onError: (String) -> Unit = {}): RpccgoResult<Thread> {
            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure("rpccgo: stream already has an active receiver")
            val worker = Thread {
                try {
                    while (true) {
                        val next = recvUnchecked()
                        if (!next.ok) {
                            onError(next.error ?: "rpccgo: stream recv failed")
                            return@Thread
                        }
                        val value = next.value ?: return@Thread
                        onRecv(value)
                    }
                } finally {
                    receiving.set(false)
                    Cancel()
                }
            }
            worker.start()
            return RpccgoResult.success(worker)
        }
    }

    private var sharedSoDemoWatchRuntimeStateServerStart: ((examples.flutter.sharedso.v1.ReadRuntimeStateRequest) -> RpccgoResult<SharedSoDemoWatchRuntimeStateServerHandler>)? = null
    private val sharedSoDemoWatchRuntimeStateServerStreams = ConcurrentHashMap<Int, SharedSoDemoWatchRuntimeStateServerHandler>()

    fun RegisterWatchRuntimeState(start: (examples.flutter.sharedso.v1.ReadRuntimeStateRequest) -> RpccgoResult<SharedSoDemoWatchRuntimeStateServerHandler>): RpccgoResult<Unit> {
        sharedSoDemoWatchRuntimeStateServerStart = start
        val result = decodeUnitResult(sharedSoDemoWatchRuntimeStateRegister())
        if (!result.ok) sharedSoDemoWatchRuntimeStateServerStart = null
        return result
    }

    @Keep
    private fun sharedSoDemoWatchRuntimeStateServerStart(requestBytes: ByteArray): ByteArray = try {
        val start = sharedSoDemoWatchRuntimeStateServerStart ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        val result = start(examples.flutter.sharedso.v1.ReadRuntimeStateRequest.parseFrom(requestBytes))
        if (!result.ok) return encodeErrorResult(result.error ?: "rpccgo: Kotlin server stream start failed")
        val stream = result.value ?: return encodeErrorResult("rpccgo: Kotlin server stream start returned null")
        val handle = nextServerStreamHandle()
        sharedSoDemoWatchRuntimeStateServerStreams[handle] = stream
        encodeHandleResult(handle)
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream start failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoWatchRuntimeStateServerRecv(handle: Int): ByteArray = try {
        val stream = sharedSoDemoWatchRuntimeStateServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeMessageResult(stream.Recv())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream recv failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoWatchRuntimeStateServerFinish(handle: Int): ByteArray = try {
        val stream = sharedSoDemoWatchRuntimeStateServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Finish())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream finish failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoWatchRuntimeStateServerCancel(handle: Int): ByteArray = try {
        val stream = sharedSoDemoWatchRuntimeStateServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Cancel())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream cancel failed: ${e.message ?: e::class.java.name}")
    }

    fun CollectRuntimeStateStart(): RpccgoResult<SharedSoDemoCollectRuntimeStateClientStream> {
        val handle = decodeHandleResult(sharedSoDemoCollectRuntimeStateStart())
        if (!handle.ok) return RpccgoResult.failure(handle.error ?: "rpccgo: stream start failed")
        return RpccgoResult.success(SharedSoDemoCollectRuntimeStateClientStream(handle.value ?: 0))
    }

    class SharedSoDemoCollectRuntimeStateClientStream internal constructor(private val handle: Int) {
        fun Send(req: examples.flutter.sharedso.v1.IncrementRuntimeStateRequest): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.sharedSoDemoCollectRuntimeStateSend(handle, req.toByteArray()))
        fun Finish(): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse> =
            decodeResult(SharedSoDemoJni.sharedSoDemoCollectRuntimeStateFinish(handle)) { examples.flutter.sharedso.v1.RuntimeStateResponse.parseFrom(it) }
        fun Cancel(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.sharedSoDemoCollectRuntimeStateCancel(handle))
    }

    private var sharedSoDemoCollectRuntimeStateServerStart: (() -> RpccgoResult<SharedSoDemoCollectRuntimeStateServerHandler>)? = null
    private val sharedSoDemoCollectRuntimeStateServerStreams = ConcurrentHashMap<Int, SharedSoDemoCollectRuntimeStateServerHandler>()

    fun RegisterCollectRuntimeState(start: () -> RpccgoResult<SharedSoDemoCollectRuntimeStateServerHandler>): RpccgoResult<Unit> {
        sharedSoDemoCollectRuntimeStateServerStart = start
        val result = decodeUnitResult(sharedSoDemoCollectRuntimeStateRegister())
        if (!result.ok) sharedSoDemoCollectRuntimeStateServerStart = null
        return result
    }

    @Keep
    private fun sharedSoDemoCollectRuntimeStateServerStart(): ByteArray = try {
        val start = sharedSoDemoCollectRuntimeStateServerStart ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        val result = start()
        if (!result.ok) return encodeErrorResult(result.error ?: "rpccgo: Kotlin server stream start failed")
        val stream = result.value ?: return encodeErrorResult("rpccgo: Kotlin server stream start returned null")
        val handle = nextServerStreamHandle()
        sharedSoDemoCollectRuntimeStateServerStreams[handle] = stream
        encodeHandleResult(handle)
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream start failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoCollectRuntimeStateServerSend(handle: Int, requestBytes: ByteArray): ByteArray = try {
        val stream = sharedSoDemoCollectRuntimeStateServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Send(examples.flutter.sharedso.v1.IncrementRuntimeStateRequest.parseFrom(requestBytes)))
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream send failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoCollectRuntimeStateServerFinish(handle: Int): ByteArray = try {
        val stream = sharedSoDemoCollectRuntimeStateServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeMessageResult(stream.Finish())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream finish failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoCollectRuntimeStateServerCancel(handle: Int): ByteArray = try {
        val stream = sharedSoDemoCollectRuntimeStateServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Cancel())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream cancel failed: ${e.message ?: e::class.java.name}")
    }

    fun StreamRuntimeStateStart(req: examples.flutter.sharedso.v1.ReadRuntimeStateRequest): RpccgoResult<SharedSoDemoStreamRuntimeStateServerStream> {
        val handle = decodeHandleResult(sharedSoDemoStreamRuntimeStateStart(req.toByteArray()))
        if (!handle.ok) return RpccgoResult.failure(handle.error ?: "rpccgo: stream start failed")
        return RpccgoResult.success(SharedSoDemoStreamRuntimeStateServerStream(handle.value ?: 0))
    }
    fun StreamRuntimeStateStartCallback(req: examples.flutter.sharedso.v1.ReadRuntimeStateRequest, listener: SharedSoDemoStreamRuntimeStateListener): Boolean =
        sharedSoDemoStreamRuntimeStateStartCallback(req.toByteArray(), listener)
    fun StreamRuntimeStateStartCallback(owner: android.app.Activity, req: examples.flutter.sharedso.v1.ReadRuntimeStateRequest, listener: SharedSoDemoStreamRuntimeStateListener): RpccgoResult<RpccgoCallbackStream> {
        if (owner.isDestroyed) return RpccgoResult.failure("rpccgo: callback stream owner is destroyed")
        val callbackOpen = AtomicBoolean(true)
        var stream: RpccgoCallbackStream? = null
        val ownerListener = object : SharedSoDemoStreamRuntimeStateListener {
            override fun onRecv(responseBytes: ByteArray) {
                if (callbackOpen.get()) listener.onRecv(responseBytes)
            }

            override fun onDone(error: String?) {
                if (!callbackOpen.compareAndSet(true, false)) return
                stream?.complete()
                listener.onDone(error)
            }
        }
        stream = activityOwnedCallbackStream(owner) {
            callbackOpen.set(false)
            StreamRuntimeStateCancelCallback()
        }
        val activeStream = stream ?: return RpccgoResult.failure("rpccgo: callback stream owner registration failed")
        if (!StreamRuntimeStateStartCallback(req, ownerListener)) {
            activeStream.cancel()
            return RpccgoResult.failure("rpccgo: callback stream start failed")
        }
        return RpccgoResult.success(activeStream)
    }
    fun StreamRuntimeStateCancelCallback(): Boolean = sharedSoDemoStreamRuntimeStateCancelCallback()

    class SharedSoDemoStreamRuntimeStateServerStream internal constructor(private val handle: Int) {
        private val receiving = AtomicBoolean(false)
        private fun recvUnchecked(): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse> =
            decodeResult(SharedSoDemoJni.sharedSoDemoStreamRuntimeStateRecv(handle)) { examples.flutter.sharedso.v1.RuntimeStateResponse.parseFrom(it) }
        /** Receives one response. Do not call while RecvEach is running on this stream. */
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse> {
            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure("rpccgo: stream already has an active receiver")
            return try {
                recvUnchecked()
            } finally {
                receiving.set(false)
            }
        }
        fun Cancel(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.sharedSoDemoStreamRuntimeStateCancel(handle))
        /** Starts a background Recv loop. Do not mix with manual Recv calls on this stream. */
        fun RecvEach(onRecv: (examples.flutter.sharedso.v1.RuntimeStateResponse) -> Unit, onError: (String) -> Unit = {}): RpccgoResult<Thread> {
            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure("rpccgo: stream already has an active receiver")
            val worker = Thread {
                try {
                    while (true) {
                        val next = recvUnchecked()
                        if (!next.ok) {
                            onError(next.error ?: "rpccgo: stream recv failed")
                            return@Thread
                        }
                        val value = next.value ?: return@Thread
                        onRecv(value)
                    }
                } finally {
                    receiving.set(false)
                    Cancel()
                }
            }
            worker.start()
            return RpccgoResult.success(worker)
        }
    }

    private var sharedSoDemoStreamRuntimeStateServerStart: ((examples.flutter.sharedso.v1.ReadRuntimeStateRequest) -> RpccgoResult<SharedSoDemoStreamRuntimeStateServerHandler>)? = null
    private val sharedSoDemoStreamRuntimeStateServerStreams = ConcurrentHashMap<Int, SharedSoDemoStreamRuntimeStateServerHandler>()

    fun RegisterStreamRuntimeState(start: (examples.flutter.sharedso.v1.ReadRuntimeStateRequest) -> RpccgoResult<SharedSoDemoStreamRuntimeStateServerHandler>): RpccgoResult<Unit> {
        sharedSoDemoStreamRuntimeStateServerStart = start
        val result = decodeUnitResult(sharedSoDemoStreamRuntimeStateRegister())
        if (!result.ok) sharedSoDemoStreamRuntimeStateServerStart = null
        return result
    }

    @Keep
    private fun sharedSoDemoStreamRuntimeStateServerStart(requestBytes: ByteArray): ByteArray = try {
        val start = sharedSoDemoStreamRuntimeStateServerStart ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        val result = start(examples.flutter.sharedso.v1.ReadRuntimeStateRequest.parseFrom(requestBytes))
        if (!result.ok) return encodeErrorResult(result.error ?: "rpccgo: Kotlin server stream start failed")
        val stream = result.value ?: return encodeErrorResult("rpccgo: Kotlin server stream start returned null")
        val handle = nextServerStreamHandle()
        sharedSoDemoStreamRuntimeStateServerStreams[handle] = stream
        encodeHandleResult(handle)
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream start failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoStreamRuntimeStateServerRecv(handle: Int): ByteArray = try {
        val stream = sharedSoDemoStreamRuntimeStateServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeMessageResult(stream.Recv())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream recv failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoStreamRuntimeStateServerFinish(handle: Int): ByteArray = try {
        val stream = sharedSoDemoStreamRuntimeStateServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Finish())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream finish failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoStreamRuntimeStateServerCancel(handle: Int): ByteArray = try {
        val stream = sharedSoDemoStreamRuntimeStateServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Cancel())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream cancel failed: ${e.message ?: e::class.java.name}")
    }

    fun ChatRuntimeStateStart(): RpccgoResult<SharedSoDemoChatRuntimeStateBidiStream> {
        val handle = decodeHandleResult(sharedSoDemoChatRuntimeStateStart())
        if (!handle.ok) return RpccgoResult.failure(handle.error ?: "rpccgo: stream start failed")
        return RpccgoResult.success(SharedSoDemoChatRuntimeStateBidiStream(handle.value ?: 0))
    }
    fun ChatRuntimeStateStartCallback(listener: SharedSoDemoChatRuntimeStateListener): Boolean =
        sharedSoDemoChatRuntimeStateStartCallback(listener)
    fun ChatRuntimeStateStartCallback(owner: android.app.Activity, listener: SharedSoDemoChatRuntimeStateListener): RpccgoResult<RpccgoCallbackStream> {
        if (owner.isDestroyed) return RpccgoResult.failure("rpccgo: callback stream owner is destroyed")
        val callbackOpen = AtomicBoolean(true)
        var stream: RpccgoCallbackStream? = null
        val ownerListener = object : SharedSoDemoChatRuntimeStateListener {
            override fun onRecv(responseBytes: ByteArray) {
                if (callbackOpen.get()) listener.onRecv(responseBytes)
            }

            override fun onDone(error: String?) {
                if (!callbackOpen.compareAndSet(true, false)) return
                stream?.complete()
                listener.onDone(error)
            }
        }
        stream = activityOwnedCallbackStream(owner) {
            callbackOpen.set(false)
            ChatRuntimeStateCancelCallback()
        }
        val activeStream = stream ?: return RpccgoResult.failure("rpccgo: callback stream owner registration failed")
        if (!ChatRuntimeStateStartCallback(ownerListener)) {
            activeStream.cancel()
            return RpccgoResult.failure("rpccgo: callback stream start failed")
        }
        return RpccgoResult.success(activeStream)
    }
    fun ChatRuntimeStateCancelCallback(): Boolean = sharedSoDemoChatRuntimeStateCancelCallback()

    class SharedSoDemoChatRuntimeStateBidiStream internal constructor(private val handle: Int) {
        fun Send(req: examples.flutter.sharedso.v1.IncrementRuntimeStateRequest): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.sharedSoDemoChatRuntimeStateSend(handle, req.toByteArray()))
        private val receiving = AtomicBoolean(false)
        private fun recvUnchecked(): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse> =
            decodeResult(SharedSoDemoJni.sharedSoDemoChatRuntimeStateRecv(handle)) { examples.flutter.sharedso.v1.RuntimeStateResponse.parseFrom(it) }
        /** Receives one response. Do not call while RecvEach is running on this stream. */
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse> {
            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure("rpccgo: stream already has an active receiver")
            return try {
                recvUnchecked()
            } finally {
                receiving.set(false)
            }
        }
        fun CloseSend(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.sharedSoDemoChatRuntimeStateCloseSend(handle))
        fun Finish(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.sharedSoDemoChatRuntimeStateFinish(handle))
        fun Cancel(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.sharedSoDemoChatRuntimeStateCancel(handle))
        /** Starts a background Recv loop. Do not mix with manual Recv calls on this stream. */
        fun RecvEach(onRecv: (examples.flutter.sharedso.v1.RuntimeStateResponse) -> Unit, onError: (String) -> Unit = {}): RpccgoResult<Thread> {
            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure("rpccgo: stream already has an active receiver")
            val worker = Thread {
                try {
                    while (true) {
                        val next = recvUnchecked()
                        if (!next.ok) {
                            onError(next.error ?: "rpccgo: stream recv failed")
                            return@Thread
                        }
                        val value = next.value ?: return@Thread
                        onRecv(value)
                    }
                } finally {
                    receiving.set(false)
                    Cancel()
                }
            }
            worker.start()
            return RpccgoResult.success(worker)
        }
    }

    private var sharedSoDemoChatRuntimeStateServerStart: (() -> RpccgoResult<SharedSoDemoChatRuntimeStateServerHandler>)? = null
    private val sharedSoDemoChatRuntimeStateServerStreams = ConcurrentHashMap<Int, SharedSoDemoChatRuntimeStateServerHandler>()

    fun RegisterChatRuntimeState(start: () -> RpccgoResult<SharedSoDemoChatRuntimeStateServerHandler>): RpccgoResult<Unit> {
        sharedSoDemoChatRuntimeStateServerStart = start
        val result = decodeUnitResult(sharedSoDemoChatRuntimeStateRegister())
        if (!result.ok) sharedSoDemoChatRuntimeStateServerStart = null
        return result
    }

    @Keep
    private fun sharedSoDemoChatRuntimeStateServerStart(): ByteArray = try {
        val start = sharedSoDemoChatRuntimeStateServerStart ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        val result = start()
        if (!result.ok) return encodeErrorResult(result.error ?: "rpccgo: Kotlin server stream start failed")
        val stream = result.value ?: return encodeErrorResult("rpccgo: Kotlin server stream start returned null")
        val handle = nextServerStreamHandle()
        sharedSoDemoChatRuntimeStateServerStreams[handle] = stream
        encodeHandleResult(handle)
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream start failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoChatRuntimeStateServerSend(handle: Int, requestBytes: ByteArray): ByteArray = try {
        val stream = sharedSoDemoChatRuntimeStateServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Send(examples.flutter.sharedso.v1.IncrementRuntimeStateRequest.parseFrom(requestBytes)))
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream send failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoChatRuntimeStateServerRecv(handle: Int): ByteArray = try {
        val stream = sharedSoDemoChatRuntimeStateServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeMessageResult(stream.Recv())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream recv failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoChatRuntimeStateServerCloseSend(handle: Int): ByteArray = try {
        val stream = sharedSoDemoChatRuntimeStateServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.CloseSend())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream close-send failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoChatRuntimeStateServerFinish(handle: Int): ByteArray = try {
        val stream = sharedSoDemoChatRuntimeStateServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Finish())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream finish failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun sharedSoDemoChatRuntimeStateServerCancel(handle: Int): ByteArray = try {
        val stream = sharedSoDemoChatRuntimeStateServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Cancel())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream cancel failed: ${e.message ?: e::class.java.name}")
    }

    fun SetTorch(req: examples.flutter.sharedso.v1.SetTorchRequest): RpccgoResult<examples.flutter.sharedso.v1.SetTorchResponse> =
        decodeResult(androidDeviceSetTorch(req.toByteArray())) { examples.flutter.sharedso.v1.SetTorchResponse.parseFrom(it) }

    private var androidDeviceSetTorchServerHandler: ((examples.flutter.sharedso.v1.SetTorchRequest) -> RpccgoResult<examples.flutter.sharedso.v1.SetTorchResponse>)? = null

    fun RegisterSetTorch(handler: (examples.flutter.sharedso.v1.SetTorchRequest) -> RpccgoResult<examples.flutter.sharedso.v1.SetTorchResponse>): RpccgoResult<Unit> {
        androidDeviceSetTorchServerHandler = handler
        val result = decodeUnitResult(androidDeviceSetTorchRegister())
        if (!result.ok) androidDeviceSetTorchServerHandler = null
        return result
    }

    @Keep
    private fun androidDeviceSetTorchHandle(requestBytes: ByteArray): ByteArray = try {
        val handler = androidDeviceSetTorchServerHandler ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        encodeMessageResult(handler(examples.flutter.sharedso.v1.SetTorchRequest.parseFrom(requestBytes)))
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server handler failed: ${e.message ?: e::class.java.name}")
    }

    fun WatchAndroidEchoStart(req: examples.flutter.sharedso.v1.AndroidEchoRequest): RpccgoResult<AndroidDeviceWatchAndroidEchoServerStream> {
        val handle = decodeHandleResult(androidDeviceWatchAndroidEchoStart(req.toByteArray()))
        if (!handle.ok) return RpccgoResult.failure(handle.error ?: "rpccgo: stream start failed")
        return RpccgoResult.success(AndroidDeviceWatchAndroidEchoServerStream(handle.value ?: 0))
    }
    fun WatchAndroidEchoStartCallback(req: examples.flutter.sharedso.v1.AndroidEchoRequest, listener: AndroidDeviceWatchAndroidEchoListener): Boolean =
        androidDeviceWatchAndroidEchoStartCallback(req.toByteArray(), listener)
    fun WatchAndroidEchoStartCallback(owner: android.app.Activity, req: examples.flutter.sharedso.v1.AndroidEchoRequest, listener: AndroidDeviceWatchAndroidEchoListener): RpccgoResult<RpccgoCallbackStream> {
        if (owner.isDestroyed) return RpccgoResult.failure("rpccgo: callback stream owner is destroyed")
        val callbackOpen = AtomicBoolean(true)
        var stream: RpccgoCallbackStream? = null
        val ownerListener = object : AndroidDeviceWatchAndroidEchoListener {
            override fun onRecv(responseBytes: ByteArray) {
                if (callbackOpen.get()) listener.onRecv(responseBytes)
            }

            override fun onDone(error: String?) {
                if (!callbackOpen.compareAndSet(true, false)) return
                stream?.complete()
                listener.onDone(error)
            }
        }
        stream = activityOwnedCallbackStream(owner) {
            callbackOpen.set(false)
            WatchAndroidEchoCancelCallback()
        }
        val activeStream = stream ?: return RpccgoResult.failure("rpccgo: callback stream owner registration failed")
        if (!WatchAndroidEchoStartCallback(req, ownerListener)) {
            activeStream.cancel()
            return RpccgoResult.failure("rpccgo: callback stream start failed")
        }
        return RpccgoResult.success(activeStream)
    }
    fun WatchAndroidEchoCancelCallback(): Boolean = androidDeviceWatchAndroidEchoCancelCallback()

    class AndroidDeviceWatchAndroidEchoServerStream internal constructor(private val handle: Int) {
        private val receiving = AtomicBoolean(false)
        private fun recvUnchecked(): RpccgoResult<examples.flutter.sharedso.v1.AndroidEchoResponse> =
            decodeResult(SharedSoDemoJni.androidDeviceWatchAndroidEchoRecv(handle)) { examples.flutter.sharedso.v1.AndroidEchoResponse.parseFrom(it) }
        /** Receives one response. Do not call while RecvEach is running on this stream. */
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.AndroidEchoResponse> {
            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure("rpccgo: stream already has an active receiver")
            return try {
                recvUnchecked()
            } finally {
                receiving.set(false)
            }
        }
        fun Cancel(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.androidDeviceWatchAndroidEchoCancel(handle))
        /** Starts a background Recv loop. Do not mix with manual Recv calls on this stream. */
        fun RecvEach(onRecv: (examples.flutter.sharedso.v1.AndroidEchoResponse) -> Unit, onError: (String) -> Unit = {}): RpccgoResult<Thread> {
            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure("rpccgo: stream already has an active receiver")
            val worker = Thread {
                try {
                    while (true) {
                        val next = recvUnchecked()
                        if (!next.ok) {
                            onError(next.error ?: "rpccgo: stream recv failed")
                            return@Thread
                        }
                        val value = next.value ?: return@Thread
                        onRecv(value)
                    }
                } finally {
                    receiving.set(false)
                    Cancel()
                }
            }
            worker.start()
            return RpccgoResult.success(worker)
        }
    }

    private var androidDeviceWatchAndroidEchoServerStart: ((examples.flutter.sharedso.v1.AndroidEchoRequest) -> RpccgoResult<AndroidDeviceWatchAndroidEchoServerHandler>)? = null
    private val androidDeviceWatchAndroidEchoServerStreams = ConcurrentHashMap<Int, AndroidDeviceWatchAndroidEchoServerHandler>()

    fun RegisterWatchAndroidEcho(start: (examples.flutter.sharedso.v1.AndroidEchoRequest) -> RpccgoResult<AndroidDeviceWatchAndroidEchoServerHandler>): RpccgoResult<Unit> {
        androidDeviceWatchAndroidEchoServerStart = start
        val result = decodeUnitResult(androidDeviceWatchAndroidEchoRegister())
        if (!result.ok) androidDeviceWatchAndroidEchoServerStart = null
        return result
    }

    @Keep
    private fun androidDeviceWatchAndroidEchoServerStart(requestBytes: ByteArray): ByteArray = try {
        val start = androidDeviceWatchAndroidEchoServerStart ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        val result = start(examples.flutter.sharedso.v1.AndroidEchoRequest.parseFrom(requestBytes))
        if (!result.ok) return encodeErrorResult(result.error ?: "rpccgo: Kotlin server stream start failed")
        val stream = result.value ?: return encodeErrorResult("rpccgo: Kotlin server stream start returned null")
        val handle = nextServerStreamHandle()
        androidDeviceWatchAndroidEchoServerStreams[handle] = stream
        encodeHandleResult(handle)
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream start failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun androidDeviceWatchAndroidEchoServerRecv(handle: Int): ByteArray = try {
        val stream = androidDeviceWatchAndroidEchoServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeMessageResult(stream.Recv())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream recv failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun androidDeviceWatchAndroidEchoServerFinish(handle: Int): ByteArray = try {
        val stream = androidDeviceWatchAndroidEchoServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Finish())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream finish failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun androidDeviceWatchAndroidEchoServerCancel(handle: Int): ByteArray = try {
        val stream = androidDeviceWatchAndroidEchoServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Cancel())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream cancel failed: ${e.message ?: e::class.java.name}")
    }

    fun CollectAndroidEchoStart(): RpccgoResult<AndroidDeviceCollectAndroidEchoClientStream> {
        val handle = decodeHandleResult(androidDeviceCollectAndroidEchoStart())
        if (!handle.ok) return RpccgoResult.failure(handle.error ?: "rpccgo: stream start failed")
        return RpccgoResult.success(AndroidDeviceCollectAndroidEchoClientStream(handle.value ?: 0))
    }

    class AndroidDeviceCollectAndroidEchoClientStream internal constructor(private val handle: Int) {
        fun Send(req: examples.flutter.sharedso.v1.AndroidEchoRequest): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.androidDeviceCollectAndroidEchoSend(handle, req.toByteArray()))
        fun Finish(): RpccgoResult<examples.flutter.sharedso.v1.AndroidEchoResponse> =
            decodeResult(SharedSoDemoJni.androidDeviceCollectAndroidEchoFinish(handle)) { examples.flutter.sharedso.v1.AndroidEchoResponse.parseFrom(it) }
        fun Cancel(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.androidDeviceCollectAndroidEchoCancel(handle))
    }

    private var androidDeviceCollectAndroidEchoServerStart: (() -> RpccgoResult<AndroidDeviceCollectAndroidEchoServerHandler>)? = null
    private val androidDeviceCollectAndroidEchoServerStreams = ConcurrentHashMap<Int, AndroidDeviceCollectAndroidEchoServerHandler>()

    fun RegisterCollectAndroidEcho(start: () -> RpccgoResult<AndroidDeviceCollectAndroidEchoServerHandler>): RpccgoResult<Unit> {
        androidDeviceCollectAndroidEchoServerStart = start
        val result = decodeUnitResult(androidDeviceCollectAndroidEchoRegister())
        if (!result.ok) androidDeviceCollectAndroidEchoServerStart = null
        return result
    }

    @Keep
    private fun androidDeviceCollectAndroidEchoServerStart(): ByteArray = try {
        val start = androidDeviceCollectAndroidEchoServerStart ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        val result = start()
        if (!result.ok) return encodeErrorResult(result.error ?: "rpccgo: Kotlin server stream start failed")
        val stream = result.value ?: return encodeErrorResult("rpccgo: Kotlin server stream start returned null")
        val handle = nextServerStreamHandle()
        androidDeviceCollectAndroidEchoServerStreams[handle] = stream
        encodeHandleResult(handle)
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream start failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun androidDeviceCollectAndroidEchoServerSend(handle: Int, requestBytes: ByteArray): ByteArray = try {
        val stream = androidDeviceCollectAndroidEchoServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Send(examples.flutter.sharedso.v1.AndroidEchoRequest.parseFrom(requestBytes)))
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream send failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun androidDeviceCollectAndroidEchoServerFinish(handle: Int): ByteArray = try {
        val stream = androidDeviceCollectAndroidEchoServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeMessageResult(stream.Finish())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream finish failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun androidDeviceCollectAndroidEchoServerCancel(handle: Int): ByteArray = try {
        val stream = androidDeviceCollectAndroidEchoServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Cancel())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream cancel failed: ${e.message ?: e::class.java.name}")
    }

    fun ChatAndroidEchoStart(): RpccgoResult<AndroidDeviceChatAndroidEchoBidiStream> {
        val handle = decodeHandleResult(androidDeviceChatAndroidEchoStart())
        if (!handle.ok) return RpccgoResult.failure(handle.error ?: "rpccgo: stream start failed")
        return RpccgoResult.success(AndroidDeviceChatAndroidEchoBidiStream(handle.value ?: 0))
    }
    fun ChatAndroidEchoStartCallback(listener: AndroidDeviceChatAndroidEchoListener): Boolean =
        androidDeviceChatAndroidEchoStartCallback(listener)
    fun ChatAndroidEchoStartCallback(owner: android.app.Activity, listener: AndroidDeviceChatAndroidEchoListener): RpccgoResult<RpccgoCallbackStream> {
        if (owner.isDestroyed) return RpccgoResult.failure("rpccgo: callback stream owner is destroyed")
        val callbackOpen = AtomicBoolean(true)
        var stream: RpccgoCallbackStream? = null
        val ownerListener = object : AndroidDeviceChatAndroidEchoListener {
            override fun onRecv(responseBytes: ByteArray) {
                if (callbackOpen.get()) listener.onRecv(responseBytes)
            }

            override fun onDone(error: String?) {
                if (!callbackOpen.compareAndSet(true, false)) return
                stream?.complete()
                listener.onDone(error)
            }
        }
        stream = activityOwnedCallbackStream(owner) {
            callbackOpen.set(false)
            ChatAndroidEchoCancelCallback()
        }
        val activeStream = stream ?: return RpccgoResult.failure("rpccgo: callback stream owner registration failed")
        if (!ChatAndroidEchoStartCallback(ownerListener)) {
            activeStream.cancel()
            return RpccgoResult.failure("rpccgo: callback stream start failed")
        }
        return RpccgoResult.success(activeStream)
    }
    fun ChatAndroidEchoCancelCallback(): Boolean = androidDeviceChatAndroidEchoCancelCallback()

    class AndroidDeviceChatAndroidEchoBidiStream internal constructor(private val handle: Int) {
        fun Send(req: examples.flutter.sharedso.v1.AndroidEchoRequest): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.androidDeviceChatAndroidEchoSend(handle, req.toByteArray()))
        private val receiving = AtomicBoolean(false)
        private fun recvUnchecked(): RpccgoResult<examples.flutter.sharedso.v1.AndroidEchoResponse> =
            decodeResult(SharedSoDemoJni.androidDeviceChatAndroidEchoRecv(handle)) { examples.flutter.sharedso.v1.AndroidEchoResponse.parseFrom(it) }
        /** Receives one response. Do not call while RecvEach is running on this stream. */
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.AndroidEchoResponse> {
            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure("rpccgo: stream already has an active receiver")
            return try {
                recvUnchecked()
            } finally {
                receiving.set(false)
            }
        }
        fun CloseSend(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.androidDeviceChatAndroidEchoCloseSend(handle))
        fun Finish(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.androidDeviceChatAndroidEchoFinish(handle))
        fun Cancel(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.androidDeviceChatAndroidEchoCancel(handle))
        /** Starts a background Recv loop. Do not mix with manual Recv calls on this stream. */
        fun RecvEach(onRecv: (examples.flutter.sharedso.v1.AndroidEchoResponse) -> Unit, onError: (String) -> Unit = {}): RpccgoResult<Thread> {
            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure("rpccgo: stream already has an active receiver")
            val worker = Thread {
                try {
                    while (true) {
                        val next = recvUnchecked()
                        if (!next.ok) {
                            onError(next.error ?: "rpccgo: stream recv failed")
                            return@Thread
                        }
                        val value = next.value ?: return@Thread
                        onRecv(value)
                    }
                } finally {
                    receiving.set(false)
                    Cancel()
                }
            }
            worker.start()
            return RpccgoResult.success(worker)
        }
    }

    private var androidDeviceChatAndroidEchoServerStart: (() -> RpccgoResult<AndroidDeviceChatAndroidEchoServerHandler>)? = null
    private val androidDeviceChatAndroidEchoServerStreams = ConcurrentHashMap<Int, AndroidDeviceChatAndroidEchoServerHandler>()

    fun RegisterChatAndroidEcho(start: () -> RpccgoResult<AndroidDeviceChatAndroidEchoServerHandler>): RpccgoResult<Unit> {
        androidDeviceChatAndroidEchoServerStart = start
        val result = decodeUnitResult(androidDeviceChatAndroidEchoRegister())
        if (!result.ok) androidDeviceChatAndroidEchoServerStart = null
        return result
    }

    @Keep
    private fun androidDeviceChatAndroidEchoServerStart(): ByteArray = try {
        val start = androidDeviceChatAndroidEchoServerStart ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        val result = start()
        if (!result.ok) return encodeErrorResult(result.error ?: "rpccgo: Kotlin server stream start failed")
        val stream = result.value ?: return encodeErrorResult("rpccgo: Kotlin server stream start returned null")
        val handle = nextServerStreamHandle()
        androidDeviceChatAndroidEchoServerStreams[handle] = stream
        encodeHandleResult(handle)
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream start failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun androidDeviceChatAndroidEchoServerSend(handle: Int, requestBytes: ByteArray): ByteArray = try {
        val stream = androidDeviceChatAndroidEchoServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Send(examples.flutter.sharedso.v1.AndroidEchoRequest.parseFrom(requestBytes)))
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream send failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun androidDeviceChatAndroidEchoServerRecv(handle: Int): ByteArray = try {
        val stream = androidDeviceChatAndroidEchoServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeMessageResult(stream.Recv())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream recv failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun androidDeviceChatAndroidEchoServerCloseSend(handle: Int): ByteArray = try {
        val stream = androidDeviceChatAndroidEchoServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.CloseSend())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream close-send failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun androidDeviceChatAndroidEchoServerFinish(handle: Int): ByteArray = try {
        val stream = androidDeviceChatAndroidEchoServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Finish())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream finish failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun androidDeviceChatAndroidEchoServerCancel(handle: Int): ByteArray = try {
        val stream = androidDeviceChatAndroidEchoServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Cancel())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream cancel failed: ${e.message ?: e::class.java.name}")
    }

    fun DescribeFlutter(req: examples.flutter.sharedso.v1.FlutterEchoRequest): RpccgoResult<examples.flutter.sharedso.v1.FlutterEchoResponse> =
        decodeResult(flutterDeviceDescribeFlutter(req.toByteArray())) { examples.flutter.sharedso.v1.FlutterEchoResponse.parseFrom(it) }

    private var flutterDeviceDescribeFlutterServerHandler: ((examples.flutter.sharedso.v1.FlutterEchoRequest) -> RpccgoResult<examples.flutter.sharedso.v1.FlutterEchoResponse>)? = null

    fun RegisterDescribeFlutter(handler: (examples.flutter.sharedso.v1.FlutterEchoRequest) -> RpccgoResult<examples.flutter.sharedso.v1.FlutterEchoResponse>): RpccgoResult<Unit> {
        flutterDeviceDescribeFlutterServerHandler = handler
        val result = decodeUnitResult(flutterDeviceDescribeFlutterRegister())
        if (!result.ok) flutterDeviceDescribeFlutterServerHandler = null
        return result
    }

    @Keep
    private fun flutterDeviceDescribeFlutterHandle(requestBytes: ByteArray): ByteArray = try {
        val handler = flutterDeviceDescribeFlutterServerHandler ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        encodeMessageResult(handler(examples.flutter.sharedso.v1.FlutterEchoRequest.parseFrom(requestBytes)))
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server handler failed: ${e.message ?: e::class.java.name}")
    }

    fun WatchFlutterEchoStart(req: examples.flutter.sharedso.v1.FlutterEchoRequest): RpccgoResult<FlutterDeviceWatchFlutterEchoServerStream> {
        val handle = decodeHandleResult(flutterDeviceWatchFlutterEchoStart(req.toByteArray()))
        if (!handle.ok) return RpccgoResult.failure(handle.error ?: "rpccgo: stream start failed")
        return RpccgoResult.success(FlutterDeviceWatchFlutterEchoServerStream(handle.value ?: 0))
    }
    fun WatchFlutterEchoStartCallback(req: examples.flutter.sharedso.v1.FlutterEchoRequest, listener: FlutterDeviceWatchFlutterEchoListener): Boolean =
        flutterDeviceWatchFlutterEchoStartCallback(req.toByteArray(), listener)
    fun WatchFlutterEchoStartCallback(owner: android.app.Activity, req: examples.flutter.sharedso.v1.FlutterEchoRequest, listener: FlutterDeviceWatchFlutterEchoListener): RpccgoResult<RpccgoCallbackStream> {
        if (owner.isDestroyed) return RpccgoResult.failure("rpccgo: callback stream owner is destroyed")
        val callbackOpen = AtomicBoolean(true)
        var stream: RpccgoCallbackStream? = null
        val ownerListener = object : FlutterDeviceWatchFlutterEchoListener {
            override fun onRecv(responseBytes: ByteArray) {
                if (callbackOpen.get()) listener.onRecv(responseBytes)
            }

            override fun onDone(error: String?) {
                if (!callbackOpen.compareAndSet(true, false)) return
                stream?.complete()
                listener.onDone(error)
            }
        }
        stream = activityOwnedCallbackStream(owner) {
            callbackOpen.set(false)
            WatchFlutterEchoCancelCallback()
        }
        val activeStream = stream ?: return RpccgoResult.failure("rpccgo: callback stream owner registration failed")
        if (!WatchFlutterEchoStartCallback(req, ownerListener)) {
            activeStream.cancel()
            return RpccgoResult.failure("rpccgo: callback stream start failed")
        }
        return RpccgoResult.success(activeStream)
    }
    fun WatchFlutterEchoCancelCallback(): Boolean = flutterDeviceWatchFlutterEchoCancelCallback()

    class FlutterDeviceWatchFlutterEchoServerStream internal constructor(private val handle: Int) {
        private val receiving = AtomicBoolean(false)
        private fun recvUnchecked(): RpccgoResult<examples.flutter.sharedso.v1.FlutterEchoResponse> =
            decodeResult(SharedSoDemoJni.flutterDeviceWatchFlutterEchoRecv(handle)) { examples.flutter.sharedso.v1.FlutterEchoResponse.parseFrom(it) }
        /** Receives one response. Do not call while RecvEach is running on this stream. */
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.FlutterEchoResponse> {
            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure("rpccgo: stream already has an active receiver")
            return try {
                recvUnchecked()
            } finally {
                receiving.set(false)
            }
        }
        fun Cancel(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.flutterDeviceWatchFlutterEchoCancel(handle))
        /** Starts a background Recv loop. Do not mix with manual Recv calls on this stream. */
        fun RecvEach(onRecv: (examples.flutter.sharedso.v1.FlutterEchoResponse) -> Unit, onError: (String) -> Unit = {}): RpccgoResult<Thread> {
            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure("rpccgo: stream already has an active receiver")
            val worker = Thread {
                try {
                    while (true) {
                        val next = recvUnchecked()
                        if (!next.ok) {
                            onError(next.error ?: "rpccgo: stream recv failed")
                            return@Thread
                        }
                        val value = next.value ?: return@Thread
                        onRecv(value)
                    }
                } finally {
                    receiving.set(false)
                    Cancel()
                }
            }
            worker.start()
            return RpccgoResult.success(worker)
        }
    }

    private var flutterDeviceWatchFlutterEchoServerStart: ((examples.flutter.sharedso.v1.FlutterEchoRequest) -> RpccgoResult<FlutterDeviceWatchFlutterEchoServerHandler>)? = null
    private val flutterDeviceWatchFlutterEchoServerStreams = ConcurrentHashMap<Int, FlutterDeviceWatchFlutterEchoServerHandler>()

    fun RegisterWatchFlutterEcho(start: (examples.flutter.sharedso.v1.FlutterEchoRequest) -> RpccgoResult<FlutterDeviceWatchFlutterEchoServerHandler>): RpccgoResult<Unit> {
        flutterDeviceWatchFlutterEchoServerStart = start
        val result = decodeUnitResult(flutterDeviceWatchFlutterEchoRegister())
        if (!result.ok) flutterDeviceWatchFlutterEchoServerStart = null
        return result
    }

    @Keep
    private fun flutterDeviceWatchFlutterEchoServerStart(requestBytes: ByteArray): ByteArray = try {
        val start = flutterDeviceWatchFlutterEchoServerStart ?: return encodeErrorResult("rpccgo: Kotlin server handler is not registered")
        val result = start(examples.flutter.sharedso.v1.FlutterEchoRequest.parseFrom(requestBytes))
        if (!result.ok) return encodeErrorResult(result.error ?: "rpccgo: Kotlin server stream start failed")
        val stream = result.value ?: return encodeErrorResult("rpccgo: Kotlin server stream start returned null")
        val handle = nextServerStreamHandle()
        flutterDeviceWatchFlutterEchoServerStreams[handle] = stream
        encodeHandleResult(handle)
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream start failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun flutterDeviceWatchFlutterEchoServerRecv(handle: Int): ByteArray = try {
        val stream = flutterDeviceWatchFlutterEchoServerStreams[handle] ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeMessageResult(stream.Recv())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream recv failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun flutterDeviceWatchFlutterEchoServerFinish(handle: Int): ByteArray = try {
        val stream = flutterDeviceWatchFlutterEchoServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Finish())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream finish failed: ${e.message ?: e::class.java.name}")
    }

    @Keep
    private fun flutterDeviceWatchFlutterEchoServerCancel(handle: Int): ByteArray = try {
        val stream = flutterDeviceWatchFlutterEchoServerStreams.remove(handle) ?: return encodeErrorResult("rpccgo: Kotlin server stream handle is invalid")
        encodeUnitResult(stream.Cancel())
    } catch (e: Exception) {
        encodeErrorResult("rpccgo: Kotlin server stream cancel failed: ${e.message ?: e::class.java.name}")
    }

    private fun decodeResultPayload(bytes: ByteArray?): RpccgoResult<ByteArray> {
        if (bytes == null) return RpccgoResult.failure("rpccgo: JNI returned null")
        if (bytes.size < 5) return RpccgoResult.failure("rpccgo: JNI returned malformed result")
        val ok = bytes[0].toInt() != 0
        val length = ByteBuffer.wrap(bytes, 1, 4).order(ByteOrder.BIG_ENDIAN).int
        if (length < 0 || length != bytes.size - 5) return RpccgoResult.failure("rpccgo: JNI returned invalid result length")
        val payload = bytes.copyOfRange(5, bytes.size)
        if (!ok) return RpccgoResult.failure(payload.toString(Charsets.UTF_8))
        return RpccgoResult.success(payload)
    }

    private fun <T> decodeResult(bytes: ByteArray?, parser: (ByteArray) -> T): RpccgoResult<T> {
        val payload = decodeResultPayload(bytes)
        if (!payload.ok) return RpccgoResult.failure(payload.error ?: "rpccgo: JNI call failed")
        return try {
            RpccgoResult.success(parser(payload.value ?: ByteArray(0)))
        } catch (e: Exception) {
            RpccgoResult.failure("rpccgo: JNI payload decode failed: ${e.message ?: e::class.java.name}")
        }
    }

    private fun decodeUnitResult(bytes: ByteArray?): RpccgoResult<Unit> =
        decodeResult(bytes) { Unit }

    private fun decodeHandleResult(bytes: ByteArray?): RpccgoResult<Int> {
        val payload = decodeResultPayload(bytes)
        if (!payload.ok) return RpccgoResult.failure(payload.error ?: "rpccgo: stream start failed")
        val value = payload.value ?: ByteArray(0)
        if (value.size != 4) return RpccgoResult.failure("rpccgo: JNI returned invalid stream handle")
        return RpccgoResult.success(ByteBuffer.wrap(value).order(ByteOrder.BIG_ENDIAN).int)
    }

    private fun encodeResultPayload(ok: Boolean, payload: ByteArray): ByteArray {
        val out = ByteArray(payload.size + 5)
        out[0] = if (ok) 1 else 0
        ByteBuffer.wrap(out, 1, 4).order(ByteOrder.BIG_ENDIAN).putInt(payload.size)
        payload.copyInto(out, 5)
        return out
    }

    private fun encodeErrorResult(error: String): ByteArray =
        encodeResultPayload(false, error.toByteArray(Charsets.UTF_8))

    private fun encodeUnitResult(result: RpccgoResult<Unit>): ByteArray {
        if (!result.ok) return encodeErrorResult(result.error ?: "rpccgo: Kotlin server returned failure")
        return encodeResultPayload(true, ByteArray(0))
    }

    private fun encodeMessageResult(result: RpccgoResult<out MessageLite>): ByteArray {
        if (!result.ok) return encodeErrorResult(result.error ?: "rpccgo: Kotlin server returned failure")
        val value = result.value ?: return encodeErrorResult("rpccgo: Kotlin server returned null response")
        return encodeResultPayload(true, value.toByteArray())
    }

    private fun encodeHandleResult(handle: Int): ByteArray {
        val payload = ByteArray(4)
        ByteBuffer.wrap(payload).order(ByteOrder.BIG_ENDIAN).putInt(handle)
        return encodeResultPayload(true, payload)
    }

    private fun nextServerStreamHandle(): Int {
        val next = rpccgoServerStreamIDs.getAndIncrement()
        return if (next == 0) rpccgoServerStreamIDs.getAndIncrement() else next
    }
}

