// Code generated by protoc-gen-rpc-cgo-jni. DO NOT EDIT.
//
// Source: shared_so.proto

package com.ygrpc.examples.rpccgofluttersharedso

import java.nio.ByteBuffer
import java.nio.ByteOrder

data class RpccgoResult<T>(val value: T?, val error: String?) {
    val ok: Boolean get() = error == null
    companion object {
        fun <T> success(value: T): RpccgoResult<T> = RpccgoResult(value, null)
        fun <T> failure(error: String): RpccgoResult<T> = RpccgoResult(null, error)
    }
}

object SharedSoDemoJni {
    private external fun sharedSoDemoComposeGreeting(request: ByteArray): ByteArray?
    private external fun sharedSoDemoIncrementRuntimeState(request: ByteArray): ByteArray?
    private external fun sharedSoDemoReadRuntimeState(request: ByteArray): ByteArray?
    private external fun sharedSoDemoWatchRuntimeStateStart(request: ByteArray): ByteArray?
    private external fun sharedSoDemoWatchRuntimeStateRecv(handle: Int): ByteArray?
    private external fun sharedSoDemoWatchRuntimeStateFinish(handle: Int): ByteArray?
    private external fun sharedSoDemoWatchRuntimeStateCancel(handle: Int): ByteArray?

    fun ComposeGreeting(req: examples.flutter.sharedso.v1.ComposeGreetingRequest): RpccgoResult<examples.flutter.sharedso.v1.ComposeGreetingResponse> =
        decodeResult(sharedSoDemoComposeGreeting(req.toByteArray())) { examples.flutter.sharedso.v1.ComposeGreetingResponse.parseFrom(it) }

    fun IncrementRuntimeState(req: examples.flutter.sharedso.v1.IncrementRuntimeStateRequest): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse> =
        decodeResult(sharedSoDemoIncrementRuntimeState(req.toByteArray())) { examples.flutter.sharedso.v1.RuntimeStateResponse.parseFrom(it) }

    fun ReadRuntimeState(req: examples.flutter.sharedso.v1.ReadRuntimeStateRequest): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse> =
        decodeResult(sharedSoDemoReadRuntimeState(req.toByteArray())) { examples.flutter.sharedso.v1.RuntimeStateResponse.parseFrom(it) }

    fun StartWatchRuntimeState(req: examples.flutter.sharedso.v1.ReadRuntimeStateRequest): RpccgoResult<SharedSoDemoWatchRuntimeStateServerStream> {
        val handle = decodeHandleResult(sharedSoDemoWatchRuntimeStateStart(req.toByteArray()))
        if (!handle.ok) return RpccgoResult.failure(handle.error ?: "rpccgo: stream start failed")
        return RpccgoResult.success(SharedSoDemoWatchRuntimeStateServerStream(handle.value ?: 0))
    }

    class SharedSoDemoWatchRuntimeStateServerStream internal constructor(private val handle: Int) {
        fun Recv(): RpccgoResult<examples.flutter.sharedso.v1.RuntimeStateResponse> =
            decodeResult(SharedSoDemoJni.sharedSoDemoWatchRuntimeStateRecv(handle)) { examples.flutter.sharedso.v1.RuntimeStateResponse.parseFrom(it) }
        fun Finish(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.sharedSoDemoWatchRuntimeStateFinish(handle))
        fun Cancel(): RpccgoResult<Unit> =
            decodeUnitResult(SharedSoDemoJni.sharedSoDemoWatchRuntimeStateCancel(handle))
    }

    private fun decodeResultPayload(bytes: ByteArray?): RpccgoResult<ByteArray> {
        if (bytes == null) return RpccgoResult.failure("rpccgo: JNI returned null")
        if (bytes.size < 5) return RpccgoResult.failure("rpccgo: JNI returned malformed result")
        val ok = bytes[0].toInt() != 0
        val length = ByteBuffer.wrap(bytes, 1, 4).order(ByteOrder.BIG_ENDIAN).int
        if (length < 0 || length != bytes.size - 5) return RpccgoResult.failure("rpccgo: JNI returned invalid result length")
        val payload = bytes.copyOfRange(5, bytes.size)
        if (!ok) return RpccgoResult.failure(payload.toString(Charsets.UTF_8))
        return RpccgoResult.success(payload)
    }

    private fun <T> decodeResult(bytes: ByteArray?, parser: (ByteArray) -> T): RpccgoResult<T> {
        val payload = decodeResultPayload(bytes)
        if (!payload.ok) return RpccgoResult.failure(payload.error ?: "rpccgo: JNI call failed")
        return try {
            RpccgoResult.success(parser(payload.value ?: ByteArray(0)))
        } catch (e: Exception) {
            RpccgoResult.failure("rpccgo: JNI payload decode failed: ${e.message ?: e::class.java.name}")
        }
    }

    private fun decodeUnitResult(bytes: ByteArray?): RpccgoResult<Unit> =
        decodeResult(bytes) { Unit }

    private fun decodeHandleResult(bytes: ByteArray?): RpccgoResult<Int> {
        val payload = decodeResultPayload(bytes)
        if (!payload.ok) return RpccgoResult.failure(payload.error ?: "rpccgo: stream start failed")
        val value = payload.value ?: ByteArray(0)
        if (value.size != 4) return RpccgoResult.failure("rpccgo: JNI returned invalid stream handle")
        return RpccgoResult.success(ByteBuffer.wrap(value).order(ByteOrder.BIG_ENDIAN).int)
    }
}

