// Code generated by protoc-gen-rpc-cgo. DO NOT EDIT.
//
// Source: shared_so.proto

package fluttersharedv1

import (
	context "context"
	errors "errors"
	fmt "fmt"
	io "io"
	connect "connectrpc.com/connect"
	time "time"
	rpcruntime "github.com/ygrpc/rpccgo/rpcruntime"
)

// rpccgo service runtime generated file for AndroidDevice

const androidDeviceServiceID rpcruntime.ServiceID = "examples.flutter.sharedso.v1.AndroidDevice"

// AndroidDeviceMessageServerUnavailableErr is returned when a message server registration is missing or invalid.
var AndroidDeviceMessageServerUnavailableErr = errors.New("rpccgo: message server is unavailable")

// ClearAndroidDeviceServer clears the current registered server for this service.
func ClearAndroidDeviceServer() error {
	return rpcruntime.ClearServer(androidDeviceServiceID)
}

// LoadAndroidDeviceRegisteredServer loads the current registered server record for this service.
func LoadAndroidDeviceRegisteredServer() (rpcruntime.RegisteredServer, error) {
	return rpcruntime.LoadServer(androidDeviceServiceID)
}

// RegisterAndroidDeviceConnectHandler registers the supplied connect handler server as the current server for this service.
func RegisterAndroidDeviceConnectHandler(handler AndroidDeviceHandler) error {
	if handler == nil {
		_ = rpcruntime.ClearServer(androidDeviceServiceID)
		return AndroidDeviceMessageServerUnavailableErr
	}
	err := rpcruntime.RegisterServer(androidDeviceServiceID, rpcruntime.RegisteredServer{
		Kind:   rpcruntime.ServerKindConnect,
		Server: handler,
	})
	if err != nil {
		_ = rpcruntime.ClearServer(androidDeviceServiceID)
		return err
	}
	return nil
}

// RegisterAndroidDeviceConnectRemoteServer registers the supplied connect remote server as the current server for this service.
func RegisterAndroidDeviceConnectRemoteServer(client AndroidDeviceClient) error {
	if client == nil {
		_ = rpcruntime.ClearServer(androidDeviceServiceID)
		return AndroidDeviceMessageServerUnavailableErr
	}
	err := rpcruntime.RegisterServer(androidDeviceServiceID, rpcruntime.RegisteredServer{
		Kind:   rpcruntime.ServerKindConnectRemote,
		Server: client,
	})
	if err != nil {
		_ = rpcruntime.ClearServer(androidDeviceServiceID)
		return err
	}
	return nil
}

func newandroidDeviceWatchTorchConnectDirectMessageStreamSession(ctx context.Context, handler AndroidDeviceHandler, req *SetTorchRequest) (rpcruntime.ServerStreamingClient[*SetTorchResponse], error) {
	if req == nil {
		return nil, errors.New("rpccgo: message request is nil")
	}
	client, stream, streamCtx := rpcruntime.NewServerStreaming[*SetTorchResponse](ctx, rpcruntime.LocalStreamOptions{
		ResponseBuffer: 1,
		StreamClosed:   errors.New("rpccgo: message stream is closed"),
		NilResponse:    errors.New("rpccgo: message response is nil"),
	})
	go func() {
		conn := &rpcruntime.ConnectStreamingHandlerConn{SendFunc: func(message any) error {
			resp, ok := message.(*SetTorchResponse)
			if !ok || resp == nil {
				return errors.New("rpccgo: connect handler stream response type mismatch")
			}
			return stream.Send(streamCtx, resp)
		}}
		stream.Complete(handler.WatchTorch(streamCtx, req, rpcruntime.NewConnectServerStream[SetTorchResponse](conn)))
	}()
	return client, nil
}

func newandroidDeviceWatchTorchConnectRemoteMessageStreamSession(ctx context.Context, client interface {
	WatchTorch(context.Context, *SetTorchRequest) (*connect.ServerStreamForClient[SetTorchResponse], error)
}, req *SetTorchRequest) (*androidDeviceWatchTorchConnectRemoteMessageStreamSession, error) {
	if req == nil {
		return nil, errors.New("rpccgo: message request is nil")
	}
	streamCtx, cancel := context.WithCancel(ctx)
	stream, err := client.WatchTorch(streamCtx, req)
	if err != nil {
		cancel()
		return nil, err
	}
	return &androidDeviceWatchTorchConnectRemoteMessageStreamSession{stream: stream, cancel: cancel}, nil
}

type androidDeviceWatchTorchConnectRemoteMessageStreamSession struct {
	stream *connect.ServerStreamForClient[SetTorchResponse]
	cancel context.CancelFunc
}

func (s *androidDeviceWatchTorchConnectRemoteMessageStreamSession) Recv(ctx context.Context) (*SetTorchResponse, error) {
	_ = ctx
	if s == nil {
		return nil, errors.New("rpccgo: connect remote server stream is nil")
	}
	if s.stream == nil {
		return nil, errors.New("rpccgo: connect remote server stream is nil")
	}
	if !s.stream.Receive() {
		if err := s.stream.Err(); err != nil {
			return nil, err
		}
		return nil, io.EOF
	}
	msg := s.stream.Msg()
	if msg == nil {
		return nil, errors.New("rpccgo: message response is nil")
	}
	return msg, nil
}

func (s *androidDeviceWatchTorchConnectRemoteMessageStreamSession) Finish(ctx context.Context) error {
	_ = ctx
	if s == nil || s.stream == nil {
		return nil
	}
	if s.cancel != nil {
		defer s.cancel()
	}
	return s.stream.Close()
}

func (s *androidDeviceWatchTorchConnectRemoteMessageStreamSession) Cancel(ctx context.Context) error {
	_ = ctx
	if s == nil || s.stream == nil {
		return nil
	}
	if s.cancel != nil {
		s.cancel()
	}
	return nil
}

func newandroidDeviceCollectTorchConnectDirectMessageStreamSession(ctx context.Context, handler AndroidDeviceHandler) rpcruntime.ClientStreamingClient[*SetTorchRequest, *SetTorchResponse] {
	client, stream, streamCtx := rpcruntime.NewClientStreaming[*SetTorchRequest, *SetTorchResponse](ctx, rpcruntime.LocalStreamOptions{
		RequestBuffer: 16,
		StreamClosed:  errors.New("rpccgo: message stream is closed"),
		NilRequest:    errors.New("rpccgo: message request is nil"),
	})
	go func() {
		conn := &rpcruntime.ConnectStreamingHandlerConn{ReceiveFunc: func(message any) error {
			target, ok := message.(*SetTorchRequest)
			if !ok || target == nil {
				return errors.New("rpccgo: connect handler stream request type mismatch")
			}
			req, err := stream.Recv(streamCtx)
			if err != nil {
				return err
			}
			*target = *req
			return nil
		}}
		resp, err := handler.CollectTorch(streamCtx, rpcruntime.NewConnectClientStream[SetTorchRequest](conn))
		stream.Complete(resp, err)
	}()
	return client
}

func newandroidDeviceCollectTorchConnectRemoteMessageStreamSession(ctx context.Context, client interface {
	CollectTorch(context.Context) (*connect.ClientStreamForClientSimple[SetTorchRequest, SetTorchResponse], error)
}) (*androidDeviceCollectTorchConnectRemoteMessageStreamSession, error) {
	streamCtx, cancel := context.WithCancel(ctx)
	stream, err := client.CollectTorch(streamCtx)
	if err != nil {
		cancel()
		return nil, err
	}
	return &androidDeviceCollectTorchConnectRemoteMessageStreamSession{stream: stream, cancel: cancel}, nil
}

type androidDeviceCollectTorchConnectRemoteMessageStreamSession struct {
	stream *connect.ClientStreamForClientSimple[SetTorchRequest, SetTorchResponse]
	cancel context.CancelFunc
}

func (s *androidDeviceCollectTorchConnectRemoteMessageStreamSession) Send(ctx context.Context, req *SetTorchRequest) error {
	_ = ctx
	if req == nil {
		return errors.New("rpccgo: message request is nil")
	}
	if s == nil || s.stream == nil {
		return errors.New("rpccgo: connect remote client stream is nil")
	}
	return s.stream.Send(req)
}

func (s *androidDeviceCollectTorchConnectRemoteMessageStreamSession) Finish(ctx context.Context) (*SetTorchResponse, error) {
	_ = ctx
	if s == nil {
		return nil, errors.New("rpccgo: connect remote client stream is nil")
	}
	if s.stream == nil {
		return nil, errors.New("rpccgo: connect remote client stream is nil")
	}
	defer func() {
		if s.cancel != nil {
			s.cancel()
		}
	}()
	resp, err := s.stream.CloseAndReceive()
	if err != nil {
		return nil, err
	}
	if resp == nil {
		return nil, errors.New("rpccgo: message response is nil")
	}
	return resp, nil
}

func (s *androidDeviceCollectTorchConnectRemoteMessageStreamSession) Cancel(ctx context.Context) error {
	_ = ctx
	if s != nil && s.stream != nil {
		closed := make(chan struct{})
		go func() {
			_, _ = s.stream.CloseAndReceive()
			close(closed)
		}()
		timer := time.NewTimer(100 * time.Millisecond)
		select {
		case <-closed:
			timer.Stop()
			return nil
		case <-timer.C:
		}
		if s.cancel != nil {
			s.cancel()
		}
		select {
		case <-closed:
		case <-time.After(500 * time.Millisecond):
		}
		return nil
	}
	if s != nil && s.cancel != nil {
		s.cancel()
	}
	return nil
}

func newandroidDeviceChatTorchConnectDirectMessageStreamSession(ctx context.Context, handler AndroidDeviceHandler) rpcruntime.BidiStreamingClient[*SetTorchRequest, *SetTorchResponse] {
	client, stream, streamCtx := rpcruntime.NewBidiStreaming[*SetTorchRequest, *SetTorchResponse](ctx, rpcruntime.LocalStreamOptions{
		RequestBuffer:  16,
		ResponseBuffer: 1,
		StreamClosed:   errors.New("rpccgo: message stream is closed"),
		NilRequest:     errors.New("rpccgo: message request is nil"),
		NilResponse:    errors.New("rpccgo: message response is nil"),
	})
	go func() {
		conn := &rpcruntime.ConnectStreamingHandlerConn{
			ReceiveFunc: func(message any) error {
				target, ok := message.(*SetTorchRequest)
				if !ok || target == nil {
					return errors.New("rpccgo: connect handler bidi request type mismatch")
				}
				req, err := stream.Recv(streamCtx)
				if err != nil {
					return err
				}
				*target = *req
				return nil
			},
			SendFunc: func(message any) error {
				resp, ok := message.(*SetTorchResponse)
				if !ok || resp == nil {
					return errors.New("rpccgo: connect handler bidi response type mismatch")
				}
				return stream.Send(streamCtx, resp)
			},
		}
		stream.Complete(handler.ChatTorch(streamCtx, rpcruntime.NewConnectBidiStream[SetTorchRequest, SetTorchResponse](conn)))
	}()
	return client
}

func newandroidDeviceChatTorchConnectRemoteMessageStreamSession(ctx context.Context, client interface {
	ChatTorch(context.Context) (*connect.BidiStreamForClientSimple[SetTorchRequest, SetTorchResponse], error)
}) (*androidDeviceChatTorchConnectRemoteMessageStreamSession, error) {
	streamCtx, cancel := context.WithCancel(ctx)
	stream, err := client.ChatTorch(streamCtx)
	if err != nil {
		cancel()
		return nil, err
	}
	return &androidDeviceChatTorchConnectRemoteMessageStreamSession{stream: stream, cancel: cancel}, nil
}

type androidDeviceChatTorchConnectRemoteMessageStreamSession struct {
	stream *connect.BidiStreamForClientSimple[SetTorchRequest, SetTorchResponse]
	cancel context.CancelFunc
}

func (s *androidDeviceChatTorchConnectRemoteMessageStreamSession) Send(ctx context.Context, req *SetTorchRequest) error {
	_ = ctx
	if req == nil {
		return errors.New("rpccgo: message request is nil")
	}
	if s == nil || s.stream == nil {
		return errors.New("rpccgo: connect remote bidi stream is nil")
	}
	return s.stream.Send(req)
}

func (s *androidDeviceChatTorchConnectRemoteMessageStreamSession) Recv(ctx context.Context) (*SetTorchResponse, error) {
	_ = ctx
	if s == nil || s.stream == nil {
		return nil, errors.New("rpccgo: connect remote bidi stream is nil")
	}
	resp, err := s.stream.Receive()
	if err != nil {
		return nil, err
	}
	if resp == nil {
		return nil, errors.New("rpccgo: message response is nil")
	}
	return resp, nil
}

func (s *androidDeviceChatTorchConnectRemoteMessageStreamSession) Finish(ctx context.Context) error {
	_ = ctx
	if s == nil || s.stream == nil {
		return nil
	}
	if s.cancel != nil {
		defer s.cancel()
	}
	return s.stream.CloseResponse()
}

func (s *androidDeviceChatTorchConnectRemoteMessageStreamSession) Cancel(ctx context.Context) error {
	_ = ctx
	if s == nil || s.stream == nil {
		return nil
	}
	if s.cancel != nil {
		s.cancel()
	}
	return nil
}

func (s *androidDeviceChatTorchConnectRemoteMessageStreamSession) CloseSend(ctx context.Context) error {
	_ = ctx
	if s == nil || s.stream == nil {
		return nil
	}
	return s.stream.CloseRequest()
}

// InvokeAndroidDeviceMessageSetTorch invokes the current registered server using the message contract for SetTorch.
func InvokeAndroidDeviceMessageSetTorch(ctx context.Context, req *SetTorchRequest) (*SetTorchResponse, error) {
	if req == nil {
		return nil, errors.New("rpccgo: message request is nil")
	}
	registered, err := rpcruntime.LoadServer(androidDeviceServiceID)
	if err != nil {
		return nil, err
	}
	switch registered.Kind {
	case rpcruntime.ServerKindCGOMessage:
		server, ok := registered.Server.(AndroidDeviceCGOMessageServer)
		if !ok {
			return nil, fmt.Errorf("rpccgo: AndroidDevice cgo message registered server has invalid type")
		}
		resp, err := server.SetTorch(ctx, req)
		if err != nil {
			return nil, err
		}
		if resp == nil {
			return nil, errors.New("rpccgo: message response is nil")
		}
		return resp, nil
	case rpcruntime.ServerKindConnect:
		server, ok := registered.Server.(AndroidDeviceHandler)
		if !ok {
			return nil, fmt.Errorf("rpccgo: AndroidDevice connect handler registered server has invalid type")
		}
		messageResp, err := server.SetTorch(ctx, req)
		if err != nil {
			return nil, err
		}
		if messageResp == nil {
			return nil, errors.New("rpccgo: message response is nil")
		}
		return messageResp, nil
	case rpcruntime.ServerKindConnectRemote:
		server, ok := registered.Server.(AndroidDeviceClient)
		if !ok {
			return nil, fmt.Errorf("rpccgo: AndroidDevice connect remote registered server has invalid type")
		}
		messageResp, err := server.SetTorch(ctx, req)
		if err != nil {
			return nil, err
		}
		if messageResp == nil {
			return nil, errors.New("rpccgo: message response is nil")
		}
		return messageResp, nil
	default:
		return nil, fmt.Errorf("rpccgo: AndroidDevice registered server kind %d is unsupported for message calls", registered.Kind)
	}
}

// AndroidDeviceMessageWatchTorchStart starts a message contract stream for WatchTorch on the current registered server.
func AndroidDeviceMessageWatchTorchStart(ctx context.Context, req *SetTorchRequest) (rpcruntime.StreamHandle, error) {
	if req == nil {
		return 0, errors.New("rpccgo: message request is nil")
	}
	registered, err := rpcruntime.LoadServer(androidDeviceServiceID)
	if err != nil {
		return 0, err
	}
	switch registered.Kind {
	case rpcruntime.ServerKindCGOMessage:
		server, ok := registered.Server.(AndroidDeviceCGOMessageServer)
		if !ok {
			return 0, fmt.Errorf("rpccgo: AndroidDevice cgo message registered server has invalid type")
		}
		source, err := androidDeviceWatchTorchCGOMessageStart(ctx, server, req)
		if err != nil {
			return 0, err
		}
		return rpcruntime.CreateStreamSession(rpcruntime.ServerKindCGOMessage, source)
	case rpcruntime.ServerKindConnect:
		server, ok := registered.Server.(AndroidDeviceHandler)
		if !ok {
			return 0, fmt.Errorf("rpccgo: AndroidDevice connect handler registered server has invalid type")
		}
		source, err := newandroidDeviceWatchTorchConnectDirectMessageStreamSession(ctx, server, req)
		if err != nil {
			return 0, err
		}
		return rpcruntime.CreateStreamSession(rpcruntime.ServerKindConnect, source)
	case rpcruntime.ServerKindConnectRemote:
		server, ok := registered.Server.(AndroidDeviceClient)
		if !ok {
			return 0, fmt.Errorf("rpccgo: AndroidDevice connect remote registered server has invalid type")
		}
		source, err := newandroidDeviceWatchTorchConnectRemoteMessageStreamSession(ctx, server, req)
		if err != nil {
			return 0, err
		}
		return rpcruntime.CreateStreamSession(rpcruntime.ServerKindConnectRemote, source)
	default:
		return 0, fmt.Errorf("rpccgo: AndroidDevice registered server kind %d is unsupported for message stream starts", registered.Kind)
	}
}

// AndroidDeviceMessageCollectTorchStart starts a message contract stream for CollectTorch on the current registered server.
func AndroidDeviceMessageCollectTorchStart(ctx context.Context) (rpcruntime.StreamHandle, error) {
	registered, err := rpcruntime.LoadServer(androidDeviceServiceID)
	if err != nil {
		return 0, err
	}
	switch registered.Kind {
	case rpcruntime.ServerKindCGOMessage:
		server, ok := registered.Server.(AndroidDeviceCGOMessageServer)
		if !ok {
			return 0, fmt.Errorf("rpccgo: AndroidDevice cgo message registered server has invalid type")
		}
		source, err := androidDeviceCollectTorchCGOMessageStart(ctx, server)
		if err != nil {
			return 0, err
		}
		return rpcruntime.CreateStreamSession(rpcruntime.ServerKindCGOMessage, source)
	case rpcruntime.ServerKindConnect:
		server, ok := registered.Server.(AndroidDeviceHandler)
		if !ok {
			return 0, fmt.Errorf("rpccgo: AndroidDevice connect handler registered server has invalid type")
		}
		source := newandroidDeviceCollectTorchConnectDirectMessageStreamSession(ctx, server)
		return rpcruntime.CreateStreamSession(rpcruntime.ServerKindConnect, source)
	case rpcruntime.ServerKindConnectRemote:
		server, ok := registered.Server.(AndroidDeviceClient)
		if !ok {
			return 0, fmt.Errorf("rpccgo: AndroidDevice connect remote registered server has invalid type")
		}
		source, err := newandroidDeviceCollectTorchConnectRemoteMessageStreamSession(ctx, server)
		if err != nil {
			return 0, err
		}
		return rpcruntime.CreateStreamSession(rpcruntime.ServerKindConnectRemote, source)
	default:
		return 0, fmt.Errorf("rpccgo: AndroidDevice registered server kind %d is unsupported for message stream starts", registered.Kind)
	}
}

// AndroidDeviceMessageChatTorchStart starts a message contract stream for ChatTorch on the current registered server.
func AndroidDeviceMessageChatTorchStart(ctx context.Context) (rpcruntime.StreamHandle, error) {
	registered, err := rpcruntime.LoadServer(androidDeviceServiceID)
	if err != nil {
		return 0, err
	}
	switch registered.Kind {
	case rpcruntime.ServerKindCGOMessage:
		server, ok := registered.Server.(AndroidDeviceCGOMessageServer)
		if !ok {
			return 0, fmt.Errorf("rpccgo: AndroidDevice cgo message registered server has invalid type")
		}
		source, err := androidDeviceChatTorchCGOMessageStart(ctx, server)
		if err != nil {
			return 0, err
		}
		return rpcruntime.CreateStreamSession(rpcruntime.ServerKindCGOMessage, source)
	case rpcruntime.ServerKindConnect:
		server, ok := registered.Server.(AndroidDeviceHandler)
		if !ok {
			return 0, fmt.Errorf("rpccgo: AndroidDevice connect handler registered server has invalid type")
		}
		source := newandroidDeviceChatTorchConnectDirectMessageStreamSession(ctx, server)
		return rpcruntime.CreateStreamSession(rpcruntime.ServerKindConnect, source)
	case rpcruntime.ServerKindConnectRemote:
		server, ok := registered.Server.(AndroidDeviceClient)
		if !ok {
			return 0, fmt.Errorf("rpccgo: AndroidDevice connect remote registered server has invalid type")
		}
		source, err := newandroidDeviceChatTorchConnectRemoteMessageStreamSession(ctx, server)
		if err != nil {
			return 0, err
		}
		return rpcruntime.CreateStreamSession(rpcruntime.ServerKindConnectRemote, source)
	default:
		return 0, fmt.Errorf("rpccgo: AndroidDevice registered server kind %d is unsupported for message stream starts", registered.Kind)
	}
}
