// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: shared_so.proto

package fluttersharedv1

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SharedSoDemoName is the fully-qualified name of the SharedSoDemo service.
	SharedSoDemoName = "examples.flutter.sharedso.v1.SharedSoDemo"
	// AndroidDeviceName is the fully-qualified name of the AndroidDevice service.
	AndroidDeviceName = "examples.flutter.sharedso.v1.AndroidDevice"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SharedSoDemoComposeGreetingProcedure is the fully-qualified name of the SharedSoDemo's
	// ComposeGreeting RPC.
	SharedSoDemoComposeGreetingProcedure = "/examples.flutter.sharedso.v1.SharedSoDemo/ComposeGreeting"
	// SharedSoDemoIncrementRuntimeStateProcedure is the fully-qualified name of the SharedSoDemo's
	// IncrementRuntimeState RPC.
	SharedSoDemoIncrementRuntimeStateProcedure = "/examples.flutter.sharedso.v1.SharedSoDemo/IncrementRuntimeState"
	// SharedSoDemoReadRuntimeStateProcedure is the fully-qualified name of the SharedSoDemo's
	// ReadRuntimeState RPC.
	SharedSoDemoReadRuntimeStateProcedure = "/examples.flutter.sharedso.v1.SharedSoDemo/ReadRuntimeState"
	// SharedSoDemoWatchRuntimeStateProcedure is the fully-qualified name of the SharedSoDemo's
	// WatchRuntimeState RPC.
	SharedSoDemoWatchRuntimeStateProcedure = "/examples.flutter.sharedso.v1.SharedSoDemo/WatchRuntimeState"
	// SharedSoDemoCollectRuntimeStateProcedure is the fully-qualified name of the SharedSoDemo's
	// CollectRuntimeState RPC.
	SharedSoDemoCollectRuntimeStateProcedure = "/examples.flutter.sharedso.v1.SharedSoDemo/CollectRuntimeState"
	// SharedSoDemoStreamRuntimeStateProcedure is the fully-qualified name of the SharedSoDemo's
	// StreamRuntimeState RPC.
	SharedSoDemoStreamRuntimeStateProcedure = "/examples.flutter.sharedso.v1.SharedSoDemo/StreamRuntimeState"
	// SharedSoDemoChatRuntimeStateProcedure is the fully-qualified name of the SharedSoDemo's
	// ChatRuntimeState RPC.
	SharedSoDemoChatRuntimeStateProcedure = "/examples.flutter.sharedso.v1.SharedSoDemo/ChatRuntimeState"
	// AndroidDeviceSetTorchProcedure is the fully-qualified name of the AndroidDevice's SetTorch RPC.
	AndroidDeviceSetTorchProcedure = "/examples.flutter.sharedso.v1.AndroidDevice/SetTorch"
	// AndroidDeviceWatchTorchProcedure is the fully-qualified name of the AndroidDevice's WatchTorch
	// RPC.
	AndroidDeviceWatchTorchProcedure = "/examples.flutter.sharedso.v1.AndroidDevice/WatchTorch"
	// AndroidDeviceCollectTorchProcedure is the fully-qualified name of the AndroidDevice's
	// CollectTorch RPC.
	AndroidDeviceCollectTorchProcedure = "/examples.flutter.sharedso.v1.AndroidDevice/CollectTorch"
	// AndroidDeviceChatTorchProcedure is the fully-qualified name of the AndroidDevice's ChatTorch RPC.
	AndroidDeviceChatTorchProcedure = "/examples.flutter.sharedso.v1.AndroidDevice/ChatTorch"
)

// SharedSoDemoClient is a client for the examples.flutter.sharedso.v1.SharedSoDemo service.
type SharedSoDemoClient interface {
	// ComposeGreeting returns a greeting that identifies the caller path.
	ComposeGreeting(context.Context, *ComposeGreetingRequest) (*ComposeGreetingResponse, error)
	// IncrementRuntimeState modifies state through the Flutter FFI path.
	IncrementRuntimeState(context.Context, *IncrementRuntimeStateRequest) (*RuntimeStateResponse, error)
	// ReadRuntimeState observes the same state through the Kotlin/JNI path.
	ReadRuntimeState(context.Context, *ReadRuntimeStateRequest) (*RuntimeStateResponse, error)
	// WatchRuntimeState streams runtime state snapshots through the Kotlin/JNI path.
	WatchRuntimeState(context.Context, *ReadRuntimeStateRequest) (*connect.ServerStreamForClient[RuntimeStateResponse], error)
	// CollectRuntimeState verifies client streaming through both Flutter FFI and Kotlin/JNI.
	CollectRuntimeState(context.Context) (*connect.ClientStreamForClientSimple[IncrementRuntimeStateRequest, RuntimeStateResponse], error)
	// StreamRuntimeState verifies server streaming through both Flutter FFI and Kotlin/JNI.
	StreamRuntimeState(context.Context, *ReadRuntimeStateRequest) (*connect.ServerStreamForClient[RuntimeStateResponse], error)
	// ChatRuntimeState verifies bidi streaming through both Flutter FFI and Kotlin/JNI.
	ChatRuntimeState(context.Context) (*connect.BidiStreamForClientSimple[IncrementRuntimeStateRequest, RuntimeStateResponse], error)
}

// NewSharedSoDemoClient constructs a client for the examples.flutter.sharedso.v1.SharedSoDemo
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSharedSoDemoClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SharedSoDemoClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sharedSoDemoMethods := File_shared_so_proto.Services().ByName("SharedSoDemo").Methods()
	return &sharedSoDemoClient{
		composeGreeting: connect.NewClient[ComposeGreetingRequest, ComposeGreetingResponse](
			httpClient,
			baseURL+SharedSoDemoComposeGreetingProcedure,
			connect.WithSchema(sharedSoDemoMethods.ByName("ComposeGreeting")),
			connect.WithClientOptions(opts...),
		),
		incrementRuntimeState: connect.NewClient[IncrementRuntimeStateRequest, RuntimeStateResponse](
			httpClient,
			baseURL+SharedSoDemoIncrementRuntimeStateProcedure,
			connect.WithSchema(sharedSoDemoMethods.ByName("IncrementRuntimeState")),
			connect.WithClientOptions(opts...),
		),
		readRuntimeState: connect.NewClient[ReadRuntimeStateRequest, RuntimeStateResponse](
			httpClient,
			baseURL+SharedSoDemoReadRuntimeStateProcedure,
			connect.WithSchema(sharedSoDemoMethods.ByName("ReadRuntimeState")),
			connect.WithClientOptions(opts...),
		),
		watchRuntimeState: connect.NewClient[ReadRuntimeStateRequest, RuntimeStateResponse](
			httpClient,
			baseURL+SharedSoDemoWatchRuntimeStateProcedure,
			connect.WithSchema(sharedSoDemoMethods.ByName("WatchRuntimeState")),
			connect.WithClientOptions(opts...),
		),
		collectRuntimeState: connect.NewClient[IncrementRuntimeStateRequest, RuntimeStateResponse](
			httpClient,
			baseURL+SharedSoDemoCollectRuntimeStateProcedure,
			connect.WithSchema(sharedSoDemoMethods.ByName("CollectRuntimeState")),
			connect.WithClientOptions(opts...),
		),
		streamRuntimeState: connect.NewClient[ReadRuntimeStateRequest, RuntimeStateResponse](
			httpClient,
			baseURL+SharedSoDemoStreamRuntimeStateProcedure,
			connect.WithSchema(sharedSoDemoMethods.ByName("StreamRuntimeState")),
			connect.WithClientOptions(opts...),
		),
		chatRuntimeState: connect.NewClient[IncrementRuntimeStateRequest, RuntimeStateResponse](
			httpClient,
			baseURL+SharedSoDemoChatRuntimeStateProcedure,
			connect.WithSchema(sharedSoDemoMethods.ByName("ChatRuntimeState")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sharedSoDemoClient implements SharedSoDemoClient.
type sharedSoDemoClient struct {
	composeGreeting       *connect.Client[ComposeGreetingRequest, ComposeGreetingResponse]
	incrementRuntimeState *connect.Client[IncrementRuntimeStateRequest, RuntimeStateResponse]
	readRuntimeState      *connect.Client[ReadRuntimeStateRequest, RuntimeStateResponse]
	watchRuntimeState     *connect.Client[ReadRuntimeStateRequest, RuntimeStateResponse]
	collectRuntimeState   *connect.Client[IncrementRuntimeStateRequest, RuntimeStateResponse]
	streamRuntimeState    *connect.Client[ReadRuntimeStateRequest, RuntimeStateResponse]
	chatRuntimeState      *connect.Client[IncrementRuntimeStateRequest, RuntimeStateResponse]
}

// ComposeGreeting calls examples.flutter.sharedso.v1.SharedSoDemo.ComposeGreeting.
func (c *sharedSoDemoClient) ComposeGreeting(ctx context.Context, req *ComposeGreetingRequest) (*ComposeGreetingResponse, error) {
	response, err := c.composeGreeting.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// IncrementRuntimeState calls examples.flutter.sharedso.v1.SharedSoDemo.IncrementRuntimeState.
func (c *sharedSoDemoClient) IncrementRuntimeState(ctx context.Context, req *IncrementRuntimeStateRequest) (*RuntimeStateResponse, error) {
	response, err := c.incrementRuntimeState.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ReadRuntimeState calls examples.flutter.sharedso.v1.SharedSoDemo.ReadRuntimeState.
func (c *sharedSoDemoClient) ReadRuntimeState(ctx context.Context, req *ReadRuntimeStateRequest) (*RuntimeStateResponse, error) {
	response, err := c.readRuntimeState.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// WatchRuntimeState calls examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState.
func (c *sharedSoDemoClient) WatchRuntimeState(ctx context.Context, req *ReadRuntimeStateRequest) (*connect.ServerStreamForClient[RuntimeStateResponse], error) {
	return c.watchRuntimeState.CallServerStream(ctx, connect.NewRequest(req))
}

// CollectRuntimeState calls examples.flutter.sharedso.v1.SharedSoDemo.CollectRuntimeState.
func (c *sharedSoDemoClient) CollectRuntimeState(ctx context.Context) (*connect.ClientStreamForClientSimple[IncrementRuntimeStateRequest, RuntimeStateResponse], error) {
	return c.collectRuntimeState.CallClientStreamSimple(ctx)
}

// StreamRuntimeState calls examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState.
func (c *sharedSoDemoClient) StreamRuntimeState(ctx context.Context, req *ReadRuntimeStateRequest) (*connect.ServerStreamForClient[RuntimeStateResponse], error) {
	return c.streamRuntimeState.CallServerStream(ctx, connect.NewRequest(req))
}

// ChatRuntimeState calls examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState.
func (c *sharedSoDemoClient) ChatRuntimeState(ctx context.Context) (*connect.BidiStreamForClientSimple[IncrementRuntimeStateRequest, RuntimeStateResponse], error) {
	return c.chatRuntimeState.CallBidiStreamSimple(ctx)
}

// SharedSoDemoHandler is an implementation of the examples.flutter.sharedso.v1.SharedSoDemo
// service.
type SharedSoDemoHandler interface {
	// ComposeGreeting returns a greeting that identifies the caller path.
	ComposeGreeting(context.Context, *ComposeGreetingRequest) (*ComposeGreetingResponse, error)
	// IncrementRuntimeState modifies state through the Flutter FFI path.
	IncrementRuntimeState(context.Context, *IncrementRuntimeStateRequest) (*RuntimeStateResponse, error)
	// ReadRuntimeState observes the same state through the Kotlin/JNI path.
	ReadRuntimeState(context.Context, *ReadRuntimeStateRequest) (*RuntimeStateResponse, error)
	// WatchRuntimeState streams runtime state snapshots through the Kotlin/JNI path.
	WatchRuntimeState(context.Context, *ReadRuntimeStateRequest, *connect.ServerStream[RuntimeStateResponse]) error
	// CollectRuntimeState verifies client streaming through both Flutter FFI and Kotlin/JNI.
	CollectRuntimeState(context.Context, *connect.ClientStream[IncrementRuntimeStateRequest]) (*RuntimeStateResponse, error)
	// StreamRuntimeState verifies server streaming through both Flutter FFI and Kotlin/JNI.
	StreamRuntimeState(context.Context, *ReadRuntimeStateRequest, *connect.ServerStream[RuntimeStateResponse]) error
	// ChatRuntimeState verifies bidi streaming through both Flutter FFI and Kotlin/JNI.
	ChatRuntimeState(context.Context, *connect.BidiStream[IncrementRuntimeStateRequest, RuntimeStateResponse]) error
}

// NewSharedSoDemoHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSharedSoDemoHandler(svc SharedSoDemoHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sharedSoDemoMethods := File_shared_so_proto.Services().ByName("SharedSoDemo").Methods()
	sharedSoDemoComposeGreetingHandler := connect.NewUnaryHandlerSimple(
		SharedSoDemoComposeGreetingProcedure,
		svc.ComposeGreeting,
		connect.WithSchema(sharedSoDemoMethods.ByName("ComposeGreeting")),
		connect.WithHandlerOptions(opts...),
	)
	sharedSoDemoIncrementRuntimeStateHandler := connect.NewUnaryHandlerSimple(
		SharedSoDemoIncrementRuntimeStateProcedure,
		svc.IncrementRuntimeState,
		connect.WithSchema(sharedSoDemoMethods.ByName("IncrementRuntimeState")),
		connect.WithHandlerOptions(opts...),
	)
	sharedSoDemoReadRuntimeStateHandler := connect.NewUnaryHandlerSimple(
		SharedSoDemoReadRuntimeStateProcedure,
		svc.ReadRuntimeState,
		connect.WithSchema(sharedSoDemoMethods.ByName("ReadRuntimeState")),
		connect.WithHandlerOptions(opts...),
	)
	sharedSoDemoWatchRuntimeStateHandler := connect.NewServerStreamHandlerSimple(
		SharedSoDemoWatchRuntimeStateProcedure,
		svc.WatchRuntimeState,
		connect.WithSchema(sharedSoDemoMethods.ByName("WatchRuntimeState")),
		connect.WithHandlerOptions(opts...),
	)
	sharedSoDemoCollectRuntimeStateHandler := connect.NewClientStreamHandlerSimple(
		SharedSoDemoCollectRuntimeStateProcedure,
		svc.CollectRuntimeState,
		connect.WithSchema(sharedSoDemoMethods.ByName("CollectRuntimeState")),
		connect.WithHandlerOptions(opts...),
	)
	sharedSoDemoStreamRuntimeStateHandler := connect.NewServerStreamHandlerSimple(
		SharedSoDemoStreamRuntimeStateProcedure,
		svc.StreamRuntimeState,
		connect.WithSchema(sharedSoDemoMethods.ByName("StreamRuntimeState")),
		connect.WithHandlerOptions(opts...),
	)
	sharedSoDemoChatRuntimeStateHandler := connect.NewBidiStreamHandler(
		SharedSoDemoChatRuntimeStateProcedure,
		svc.ChatRuntimeState,
		connect.WithSchema(sharedSoDemoMethods.ByName("ChatRuntimeState")),
		connect.WithHandlerOptions(opts...),
	)
	return "/examples.flutter.sharedso.v1.SharedSoDemo/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SharedSoDemoComposeGreetingProcedure:
			sharedSoDemoComposeGreetingHandler.ServeHTTP(w, r)
		case SharedSoDemoIncrementRuntimeStateProcedure:
			sharedSoDemoIncrementRuntimeStateHandler.ServeHTTP(w, r)
		case SharedSoDemoReadRuntimeStateProcedure:
			sharedSoDemoReadRuntimeStateHandler.ServeHTTP(w, r)
		case SharedSoDemoWatchRuntimeStateProcedure:
			sharedSoDemoWatchRuntimeStateHandler.ServeHTTP(w, r)
		case SharedSoDemoCollectRuntimeStateProcedure:
			sharedSoDemoCollectRuntimeStateHandler.ServeHTTP(w, r)
		case SharedSoDemoStreamRuntimeStateProcedure:
			sharedSoDemoStreamRuntimeStateHandler.ServeHTTP(w, r)
		case SharedSoDemoChatRuntimeStateProcedure:
			sharedSoDemoChatRuntimeStateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSharedSoDemoHandler returns CodeUnimplemented from all methods.
type UnimplementedSharedSoDemoHandler struct{}

func (UnimplementedSharedSoDemoHandler) ComposeGreeting(context.Context, *ComposeGreetingRequest) (*ComposeGreetingResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.SharedSoDemo.ComposeGreeting is not implemented"))
}

func (UnimplementedSharedSoDemoHandler) IncrementRuntimeState(context.Context, *IncrementRuntimeStateRequest) (*RuntimeStateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.SharedSoDemo.IncrementRuntimeState is not implemented"))
}

func (UnimplementedSharedSoDemoHandler) ReadRuntimeState(context.Context, *ReadRuntimeStateRequest) (*RuntimeStateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.SharedSoDemo.ReadRuntimeState is not implemented"))
}

func (UnimplementedSharedSoDemoHandler) WatchRuntimeState(context.Context, *ReadRuntimeStateRequest, *connect.ServerStream[RuntimeStateResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState is not implemented"))
}

func (UnimplementedSharedSoDemoHandler) CollectRuntimeState(context.Context, *connect.ClientStream[IncrementRuntimeStateRequest]) (*RuntimeStateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.SharedSoDemo.CollectRuntimeState is not implemented"))
}

func (UnimplementedSharedSoDemoHandler) StreamRuntimeState(context.Context, *ReadRuntimeStateRequest, *connect.ServerStream[RuntimeStateResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState is not implemented"))
}

func (UnimplementedSharedSoDemoHandler) ChatRuntimeState(context.Context, *connect.BidiStream[IncrementRuntimeStateRequest, RuntimeStateResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState is not implemented"))
}

// AndroidDeviceClient is a client for the examples.flutter.sharedso.v1.AndroidDevice service.
type AndroidDeviceClient interface {
	// SetTorch enables or disables the Android camera torch.
	SetTorch(context.Context, *SetTorchRequest) (*SetTorchResponse, error)
	// WatchTorch streams Android-owned torch state observations.
	WatchTorch(context.Context, *SetTorchRequest) (*connect.ServerStreamForClient[SetTorchResponse], error)
	// CollectTorch applies a client stream of torch requests and returns the last state.
	CollectTorch(context.Context) (*connect.ClientStreamForClientSimple[SetTorchRequest, SetTorchResponse], error)
	// ChatTorch applies each torch request and streams each resulting state back.
	ChatTorch(context.Context) (*connect.BidiStreamForClientSimple[SetTorchRequest, SetTorchResponse], error)
}

// NewAndroidDeviceClient constructs a client for the examples.flutter.sharedso.v1.AndroidDevice
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAndroidDeviceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AndroidDeviceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	androidDeviceMethods := File_shared_so_proto.Services().ByName("AndroidDevice").Methods()
	return &androidDeviceClient{
		setTorch: connect.NewClient[SetTorchRequest, SetTorchResponse](
			httpClient,
			baseURL+AndroidDeviceSetTorchProcedure,
			connect.WithSchema(androidDeviceMethods.ByName("SetTorch")),
			connect.WithClientOptions(opts...),
		),
		watchTorch: connect.NewClient[SetTorchRequest, SetTorchResponse](
			httpClient,
			baseURL+AndroidDeviceWatchTorchProcedure,
			connect.WithSchema(androidDeviceMethods.ByName("WatchTorch")),
			connect.WithClientOptions(opts...),
		),
		collectTorch: connect.NewClient[SetTorchRequest, SetTorchResponse](
			httpClient,
			baseURL+AndroidDeviceCollectTorchProcedure,
			connect.WithSchema(androidDeviceMethods.ByName("CollectTorch")),
			connect.WithClientOptions(opts...),
		),
		chatTorch: connect.NewClient[SetTorchRequest, SetTorchResponse](
			httpClient,
			baseURL+AndroidDeviceChatTorchProcedure,
			connect.WithSchema(androidDeviceMethods.ByName("ChatTorch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// androidDeviceClient implements AndroidDeviceClient.
type androidDeviceClient struct {
	setTorch     *connect.Client[SetTorchRequest, SetTorchResponse]
	watchTorch   *connect.Client[SetTorchRequest, SetTorchResponse]
	collectTorch *connect.Client[SetTorchRequest, SetTorchResponse]
	chatTorch    *connect.Client[SetTorchRequest, SetTorchResponse]
}

// SetTorch calls examples.flutter.sharedso.v1.AndroidDevice.SetTorch.
func (c *androidDeviceClient) SetTorch(ctx context.Context, req *SetTorchRequest) (*SetTorchResponse, error) {
	response, err := c.setTorch.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// WatchTorch calls examples.flutter.sharedso.v1.AndroidDevice.WatchTorch.
func (c *androidDeviceClient) WatchTorch(ctx context.Context, req *SetTorchRequest) (*connect.ServerStreamForClient[SetTorchResponse], error) {
	return c.watchTorch.CallServerStream(ctx, connect.NewRequest(req))
}

// CollectTorch calls examples.flutter.sharedso.v1.AndroidDevice.CollectTorch.
func (c *androidDeviceClient) CollectTorch(ctx context.Context) (*connect.ClientStreamForClientSimple[SetTorchRequest, SetTorchResponse], error) {
	return c.collectTorch.CallClientStreamSimple(ctx)
}

// ChatTorch calls examples.flutter.sharedso.v1.AndroidDevice.ChatTorch.
func (c *androidDeviceClient) ChatTorch(ctx context.Context) (*connect.BidiStreamForClientSimple[SetTorchRequest, SetTorchResponse], error) {
	return c.chatTorch.CallBidiStreamSimple(ctx)
}

// AndroidDeviceHandler is an implementation of the examples.flutter.sharedso.v1.AndroidDevice
// service.
type AndroidDeviceHandler interface {
	// SetTorch enables or disables the Android camera torch.
	SetTorch(context.Context, *SetTorchRequest) (*SetTorchResponse, error)
	// WatchTorch streams Android-owned torch state observations.
	WatchTorch(context.Context, *SetTorchRequest, *connect.ServerStream[SetTorchResponse]) error
	// CollectTorch applies a client stream of torch requests and returns the last state.
	CollectTorch(context.Context, *connect.ClientStream[SetTorchRequest]) (*SetTorchResponse, error)
	// ChatTorch applies each torch request and streams each resulting state back.
	ChatTorch(context.Context, *connect.BidiStream[SetTorchRequest, SetTorchResponse]) error
}

// NewAndroidDeviceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAndroidDeviceHandler(svc AndroidDeviceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	androidDeviceMethods := File_shared_so_proto.Services().ByName("AndroidDevice").Methods()
	androidDeviceSetTorchHandler := connect.NewUnaryHandlerSimple(
		AndroidDeviceSetTorchProcedure,
		svc.SetTorch,
		connect.WithSchema(androidDeviceMethods.ByName("SetTorch")),
		connect.WithHandlerOptions(opts...),
	)
	androidDeviceWatchTorchHandler := connect.NewServerStreamHandlerSimple(
		AndroidDeviceWatchTorchProcedure,
		svc.WatchTorch,
		connect.WithSchema(androidDeviceMethods.ByName("WatchTorch")),
		connect.WithHandlerOptions(opts...),
	)
	androidDeviceCollectTorchHandler := connect.NewClientStreamHandlerSimple(
		AndroidDeviceCollectTorchProcedure,
		svc.CollectTorch,
		connect.WithSchema(androidDeviceMethods.ByName("CollectTorch")),
		connect.WithHandlerOptions(opts...),
	)
	androidDeviceChatTorchHandler := connect.NewBidiStreamHandler(
		AndroidDeviceChatTorchProcedure,
		svc.ChatTorch,
		connect.WithSchema(androidDeviceMethods.ByName("ChatTorch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/examples.flutter.sharedso.v1.AndroidDevice/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AndroidDeviceSetTorchProcedure:
			androidDeviceSetTorchHandler.ServeHTTP(w, r)
		case AndroidDeviceWatchTorchProcedure:
			androidDeviceWatchTorchHandler.ServeHTTP(w, r)
		case AndroidDeviceCollectTorchProcedure:
			androidDeviceCollectTorchHandler.ServeHTTP(w, r)
		case AndroidDeviceChatTorchProcedure:
			androidDeviceChatTorchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAndroidDeviceHandler returns CodeUnimplemented from all methods.
type UnimplementedAndroidDeviceHandler struct{}

func (UnimplementedAndroidDeviceHandler) SetTorch(context.Context, *SetTorchRequest) (*SetTorchResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.AndroidDevice.SetTorch is not implemented"))
}

func (UnimplementedAndroidDeviceHandler) WatchTorch(context.Context, *SetTorchRequest, *connect.ServerStream[SetTorchResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.AndroidDevice.WatchTorch is not implemented"))
}

func (UnimplementedAndroidDeviceHandler) CollectTorch(context.Context, *connect.ClientStream[SetTorchRequest]) (*SetTorchResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.AndroidDevice.CollectTorch is not implemented"))
}

func (UnimplementedAndroidDeviceHandler) ChatTorch(context.Context, *connect.BidiStream[SetTorchRequest, SetTorchResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.AndroidDevice.ChatTorch is not implemented"))
}
