// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: shared_so.proto

package fluttersharedv1

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SharedSoDemoName is the fully-qualified name of the SharedSoDemo service.
	SharedSoDemoName = "examples.flutter.sharedso.v1.SharedSoDemo"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SharedSoDemoComposeGreetingProcedure is the fully-qualified name of the SharedSoDemo's
	// ComposeGreeting RPC.
	SharedSoDemoComposeGreetingProcedure = "/examples.flutter.sharedso.v1.SharedSoDemo/ComposeGreeting"
	// SharedSoDemoIncrementRuntimeStateProcedure is the fully-qualified name of the SharedSoDemo's
	// IncrementRuntimeState RPC.
	SharedSoDemoIncrementRuntimeStateProcedure = "/examples.flutter.sharedso.v1.SharedSoDemo/IncrementRuntimeState"
	// SharedSoDemoReadRuntimeStateProcedure is the fully-qualified name of the SharedSoDemo's
	// ReadRuntimeState RPC.
	SharedSoDemoReadRuntimeStateProcedure = "/examples.flutter.sharedso.v1.SharedSoDemo/ReadRuntimeState"
)

// SharedSoDemoClient is a client for the examples.flutter.sharedso.v1.SharedSoDemo service.
type SharedSoDemoClient interface {
	// ComposeGreeting returns a greeting that identifies the caller path.
	ComposeGreeting(context.Context, *ComposeGreetingRequest) (*ComposeGreetingResponse, error)
	// IncrementRuntimeState modifies state through the Flutter FFI path.
	IncrementRuntimeState(context.Context, *IncrementRuntimeStateRequest) (*RuntimeStateResponse, error)
	// ReadRuntimeState observes the same state through the Kotlin/JNI path.
	ReadRuntimeState(context.Context, *ReadRuntimeStateRequest) (*RuntimeStateResponse, error)
}

// NewSharedSoDemoClient constructs a client for the examples.flutter.sharedso.v1.SharedSoDemo
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSharedSoDemoClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SharedSoDemoClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sharedSoDemoMethods := File_shared_so_proto.Services().ByName("SharedSoDemo").Methods()
	return &sharedSoDemoClient{
		composeGreeting: connect.NewClient[ComposeGreetingRequest, ComposeGreetingResponse](
			httpClient,
			baseURL+SharedSoDemoComposeGreetingProcedure,
			connect.WithSchema(sharedSoDemoMethods.ByName("ComposeGreeting")),
			connect.WithClientOptions(opts...),
		),
		incrementRuntimeState: connect.NewClient[IncrementRuntimeStateRequest, RuntimeStateResponse](
			httpClient,
			baseURL+SharedSoDemoIncrementRuntimeStateProcedure,
			connect.WithSchema(sharedSoDemoMethods.ByName("IncrementRuntimeState")),
			connect.WithClientOptions(opts...),
		),
		readRuntimeState: connect.NewClient[ReadRuntimeStateRequest, RuntimeStateResponse](
			httpClient,
			baseURL+SharedSoDemoReadRuntimeStateProcedure,
			connect.WithSchema(sharedSoDemoMethods.ByName("ReadRuntimeState")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sharedSoDemoClient implements SharedSoDemoClient.
type sharedSoDemoClient struct {
	composeGreeting       *connect.Client[ComposeGreetingRequest, ComposeGreetingResponse]
	incrementRuntimeState *connect.Client[IncrementRuntimeStateRequest, RuntimeStateResponse]
	readRuntimeState      *connect.Client[ReadRuntimeStateRequest, RuntimeStateResponse]
}

// ComposeGreeting calls examples.flutter.sharedso.v1.SharedSoDemo.ComposeGreeting.
func (c *sharedSoDemoClient) ComposeGreeting(ctx context.Context, req *ComposeGreetingRequest) (*ComposeGreetingResponse, error) {
	response, err := c.composeGreeting.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// IncrementRuntimeState calls examples.flutter.sharedso.v1.SharedSoDemo.IncrementRuntimeState.
func (c *sharedSoDemoClient) IncrementRuntimeState(ctx context.Context, req *IncrementRuntimeStateRequest) (*RuntimeStateResponse, error) {
	response, err := c.incrementRuntimeState.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ReadRuntimeState calls examples.flutter.sharedso.v1.SharedSoDemo.ReadRuntimeState.
func (c *sharedSoDemoClient) ReadRuntimeState(ctx context.Context, req *ReadRuntimeStateRequest) (*RuntimeStateResponse, error) {
	response, err := c.readRuntimeState.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SharedSoDemoHandler is an implementation of the examples.flutter.sharedso.v1.SharedSoDemo
// service.
type SharedSoDemoHandler interface {
	// ComposeGreeting returns a greeting that identifies the caller path.
	ComposeGreeting(context.Context, *ComposeGreetingRequest) (*ComposeGreetingResponse, error)
	// IncrementRuntimeState modifies state through the Flutter FFI path.
	IncrementRuntimeState(context.Context, *IncrementRuntimeStateRequest) (*RuntimeStateResponse, error)
	// ReadRuntimeState observes the same state through the Kotlin/JNI path.
	ReadRuntimeState(context.Context, *ReadRuntimeStateRequest) (*RuntimeStateResponse, error)
}

// NewSharedSoDemoHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSharedSoDemoHandler(svc SharedSoDemoHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sharedSoDemoMethods := File_shared_so_proto.Services().ByName("SharedSoDemo").Methods()
	sharedSoDemoComposeGreetingHandler := connect.NewUnaryHandlerSimple(
		SharedSoDemoComposeGreetingProcedure,
		svc.ComposeGreeting,
		connect.WithSchema(sharedSoDemoMethods.ByName("ComposeGreeting")),
		connect.WithHandlerOptions(opts...),
	)
	sharedSoDemoIncrementRuntimeStateHandler := connect.NewUnaryHandlerSimple(
		SharedSoDemoIncrementRuntimeStateProcedure,
		svc.IncrementRuntimeState,
		connect.WithSchema(sharedSoDemoMethods.ByName("IncrementRuntimeState")),
		connect.WithHandlerOptions(opts...),
	)
	sharedSoDemoReadRuntimeStateHandler := connect.NewUnaryHandlerSimple(
		SharedSoDemoReadRuntimeStateProcedure,
		svc.ReadRuntimeState,
		connect.WithSchema(sharedSoDemoMethods.ByName("ReadRuntimeState")),
		connect.WithHandlerOptions(opts...),
	)
	return "/examples.flutter.sharedso.v1.SharedSoDemo/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SharedSoDemoComposeGreetingProcedure:
			sharedSoDemoComposeGreetingHandler.ServeHTTP(w, r)
		case SharedSoDemoIncrementRuntimeStateProcedure:
			sharedSoDemoIncrementRuntimeStateHandler.ServeHTTP(w, r)
		case SharedSoDemoReadRuntimeStateProcedure:
			sharedSoDemoReadRuntimeStateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSharedSoDemoHandler returns CodeUnimplemented from all methods.
type UnimplementedSharedSoDemoHandler struct{}

func (UnimplementedSharedSoDemoHandler) ComposeGreeting(context.Context, *ComposeGreetingRequest) (*ComposeGreetingResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.SharedSoDemo.ComposeGreeting is not implemented"))
}

func (UnimplementedSharedSoDemoHandler) IncrementRuntimeState(context.Context, *IncrementRuntimeStateRequest) (*RuntimeStateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.SharedSoDemo.IncrementRuntimeState is not implemented"))
}

func (UnimplementedSharedSoDemoHandler) ReadRuntimeState(context.Context, *ReadRuntimeStateRequest) (*RuntimeStateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("examples.flutter.sharedso.v1.SharedSoDemo.ReadRuntimeState is not implemented"))
}
