// Code generated by protoc-gen-rpc-cgo. DO NOT EDIT.
//
// Source: greeter.proto

package greeterv1

import (
	context "context"
	errors "errors"
	fmt "fmt"
	rpcruntime "rpccgo/rpcruntime"
	http "net/http"
	connect "connectrpc.com/connect"
	proto "google.golang.org/protobuf/proto"
)

// rpccgo message direct generated file for Greeter connect local server adapter

const GreeterConnectServiceName = "examples.connect.greeter.v1.Greeter"
const GreeterConnectServicePathPrefix = "/examples.connect.greeter.v1.Greeter/"
const GreeterSayHelloConnectProcedure = "/examples.connect.greeter.v1.Greeter/SayHello"
const GreeterCollectConnectProcedure = "/examples.connect.greeter.v1.Greeter/Collect"
const GreeterBroadcastConnectProcedure = "/examples.connect.greeter.v1.Greeter/Broadcast"
const GreeterChatConnectProcedure = "/examples.connect.greeter.v1.Greeter/Chat"

func NewGreeterConnectHandler(options ...connect.HandlerOption) (string, http.Handler) {
	greeterSayHelloConnectHandler := connect.NewUnaryHandler(GreeterSayHelloConnectProcedure, greeterConnectSayHello, options...)
	greeterCollectConnectHandler := connect.NewClientStreamHandler(GreeterCollectConnectProcedure, greeterConnectCollect, options...)
	greeterBroadcastConnectHandler := connect.NewServerStreamHandler(GreeterBroadcastConnectProcedure, greeterConnectBroadcast, options...)
	greeterChatConnectHandler := connect.NewBidiStreamHandler(GreeterChatConnectProcedure, greeterConnectChat, options...)
	return GreeterConnectServicePathPrefix, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GreeterSayHelloConnectProcedure:
			greeterSayHelloConnectHandler.ServeHTTP(w, r)
		case GreeterCollectConnectProcedure:
			greeterCollectConnectHandler.ServeHTTP(w, r)
		case GreeterBroadcastConnectProcedure:
			greeterBroadcastConnectHandler.ServeHTTP(w, r)
		case GreeterChatConnectProcedure:
			greeterChatConnectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

func greeterConnectSayHello(ctx context.Context, req *connect.Request[SayHelloRequest]) (*connect.Response[SayHelloResponse], error) {
	if req == nil || req.Msg == nil {
		return nil, errors.New("rpccgo: connect request is nil")
	}
	reqData, err := proto.Marshal(req.Msg)
	if err != nil {
		return nil, fmt.Errorf("rpccgo: connect request protobuf marshal failed: %w", err)
	}
	respData, err := InvokeGreeterMessageSayHello(ctx, reqData)
	if err != nil {
		return nil, err
	}
	resp := new(SayHelloResponse)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, fmt.Errorf("rpccgo: connect response protobuf unmarshal failed: %w", err)
	}
	return connect.NewResponse(resp), nil
}

func greeterConnectCollect(ctx context.Context, stream *connect.ClientStream[SayHelloRequest]) (*connect.Response[SayHelloResponse], error) {
	handle, err := StartGreeterMessageCollect(ctx)
	if err != nil {
		return nil, err
	}
	lifecycle := NewGreeterCollectMessageStream(handle)
	for stream.Receive() {
		reqData, err := proto.Marshal(stream.Msg())
		if err != nil {
			_ = lifecycle.Cancel(ctx)
			return nil, fmt.Errorf("rpccgo: connect stream request protobuf marshal failed: %w", err)
		}
		if err := lifecycle.Send(ctx, reqData); err != nil {
			_ = lifecycle.Cancel(ctx)
			return nil, err
		}
	}
	if err := stream.Err(); err != nil {
		_ = lifecycle.Cancel(ctx)
		return nil, err
	}
	respData, err := lifecycle.Finish(ctx)
	if err != nil {
		return nil, err
	}
	resp := new(SayHelloResponse)
	if err := proto.Unmarshal(respData, resp); err != nil {
		return nil, fmt.Errorf("rpccgo: connect stream response protobuf unmarshal failed: %w", err)
	}
	return connect.NewResponse(resp), nil
}

func greeterConnectBroadcast(ctx context.Context, req *connect.Request[SayHelloRequest], stream *connect.ServerStream[SayHelloResponse]) error {
	if req == nil || req.Msg == nil {
		return errors.New("rpccgo: connect request is nil")
	}
	reqData, err := proto.Marshal(req.Msg)
	if err != nil {
		return fmt.Errorf("rpccgo: connect stream request protobuf marshal failed: %w", err)
	}
	handle, err := StartGreeterMessageBroadcast(ctx, reqData)
	if err != nil {
		return err
	}
	lifecycle := NewGreeterBroadcastMessageStream(handle)
	return rpcruntime.RunServerStream(
		func() ([]byte, error) {
			return lifecycle.Recv(ctx)
		},
		func(respData []byte) error {
			resp := new(SayHelloResponse)
			if err := proto.Unmarshal(respData, resp); err != nil {
				return fmt.Errorf("rpccgo: connect stream response protobuf unmarshal failed: %w", err)
			}
			return stream.Send(resp)
		},
		func() error {
			return lifecycle.Done(ctx)
		},
		func() error {
			return lifecycle.Cancel(ctx)
		},
	)
}

func greeterConnectChat(ctx context.Context, stream *connect.BidiStream[SayHelloRequest, SayHelloResponse]) error {
	handle, err := StartGreeterMessageChat(ctx)
	if err != nil {
		return err
	}
	lifecycle := NewGreeterChatMessageStream(handle)
	return rpcruntime.RunBidiStream(
		func() (*SayHelloRequest, error) {
			return stream.Receive()
		},
		func(req *SayHelloRequest) error {
			reqData, err := proto.Marshal(req)
			if err != nil {
				return fmt.Errorf("rpccgo: connect bidi request protobuf marshal failed: %w", err)
			}
			return lifecycle.Send(ctx, reqData)
		},
		func() error {
			return lifecycle.CloseSend(ctx)
		},
		func() ([]byte, error) {
			return lifecycle.Recv(ctx)
		},
		func(respData []byte) error {
			resp := new(SayHelloResponse)
			if err := proto.Unmarshal(respData, resp); err != nil {
				return fmt.Errorf("rpccgo: connect bidi response protobuf unmarshal failed: %w", err)
			}
			return stream.Send(resp)
		},
		func() error {
			return lifecycle.Done(ctx)
		},
		func() error {
			return lifecycle.Cancel(ctx)
		},
	)
}
