// Code generated by protoc-gen-rpc-cgo. DO NOT EDIT.
//
// Source: greeter.proto

package greeterv1

import (
	context "context"
	errors "errors"
	fmt "fmt"
	io "io"
	sync "sync"
	rpcruntime "rpccgo/rpcruntime"
)

// rpccgo native generated file for Greeter go native server

var (
	greeterNativeRequestConverterNotImplemented = errors.New("rpccgo: native request converter is not implemented")
	greeterNativeStreamConverterNotImplemented  = errors.New("rpccgo: native stream converter is not implemented")
	greeterNativeStreamIsNil                    = errors.New("rpccgo: native stream is nil")
	greeterNativeStreamClosed                   = errors.New("rpccgo: native stream is closed")
)

// Greeter serves greeting RPCs for the Connect example.
type GreeterNativeServer interface {
	// SayHello returns a single greeting.
	SayHello(ctx context.Context, name *rpcruntime.RpcString, city *rpcruntime.RpcString) (string, error)
	// Collect accepts many requests and returns one greeting.
	Collect(ctx context.Context, stream GreeterCollectNativeClientStream) (string, error)
	// Broadcast accepts one request and streams greetings back.
	Broadcast(ctx context.Context, name *rpcruntime.RpcString, city *rpcruntime.RpcString, stream GreeterBroadcastNativeServerStream) error
	// Chat exchanges greeting requests and responses bidirectionally.
	Chat(ctx context.Context, stream GreeterChatNativeBidiStream) error
}

type GreeterCollectNativeClientStream interface {
	Recv(ctx context.Context) (*rpcruntime.RpcString, *rpcruntime.RpcString, error)
}

type GreeterBroadcastNativeServerStream interface {
	Send(ctx context.Context, message string) error
}

type GreeterChatNativeBidiStream interface {
	Recv(ctx context.Context) (*rpcruntime.RpcString, *rpcruntime.RpcString, error)
	Send(ctx context.Context, message string) error
}

type GreeterCollectNativeStreamSession interface {
	Send(ctx context.Context, name *rpcruntime.RpcString, city *rpcruntime.RpcString) error
	Finish(ctx context.Context) (string, error)
	Cancel(ctx context.Context) error
}

type GreeterBroadcastNativeStreamSession interface {
	Recv(ctx context.Context) (string, error)
	Finish(ctx context.Context) error
	Cancel(ctx context.Context) error
}

type GreeterChatNativeStreamSession interface {
	Send(ctx context.Context, name *rpcruntime.RpcString, city *rpcruntime.RpcString) error
	Recv(ctx context.Context) (string, error)
	CloseSend(ctx context.Context) error
	Finish(ctx context.Context) error
	Cancel(ctx context.Context) error
}

func SendGreeterNativeCollect(ctx context.Context, handle rpcruntime.StreamHandle, name *rpcruntime.RpcString, city *rpcruntime.RpcString) error {
	entry, err := rpcruntime.SendStreamSession(handle)
	if err != nil {
		return err
	}
	switch entry.Kind {
	case rpcruntime.ServerKindGoNative:
		source, ok := entry.Session.(GreeterCollectNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Send(ctx, name, city)
	case rpcruntime.ServerKindCGONative:
		source, ok := entry.Session.(GreeterCollectNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Send(ctx, name, city)
	case rpcruntime.ServerKindCGOMessage:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		messageReq, err := convertGreeterCollectNativeToMessageRequest(name, city)
		if err != nil {
			return err
		}
		return source.Send(ctx, messageReq)
	case rpcruntime.ServerKindConnect:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		messageReq, err := convertGreeterCollectNativeToMessageRequest(name, city)
		if err != nil {
			return err
		}
		return source.Send(ctx, messageReq)
	case rpcruntime.ServerKindConnectRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		messageReq, err := convertGreeterCollectNativeToMessageRequest(name, city)
		if err != nil {
			return err
		}
		return source.Send(ctx, messageReq)
	case rpcruntime.ServerKindGRPC:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		messageReq, err := convertGreeterCollectNativeToMessageRequest(name, city)
		if err != nil {
			return err
		}
		return source.Send(ctx, messageReq)
	case rpcruntime.ServerKindGRPCRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		messageReq, err := convertGreeterCollectNativeToMessageRequest(name, city)
		if err != nil {
			return err
		}
		return source.Send(ctx, messageReq)
	default:
		return fmt.Errorf("rpccgo: Greeter native stream session kind %d is unsupported", entry.Kind)
	}
}

func FinishGreeterNativeCollect(ctx context.Context, handle rpcruntime.StreamHandle) (string, error) {
	entry, err := rpcruntime.FinishStreamSession(handle)
	if err != nil {
		return "", rpcruntime.ErrStreamInvalidHandle
	}
	switch entry.Kind {
	case rpcruntime.ServerKindGoNative:
		source, ok := entry.Session.(GreeterCollectNativeStreamSession)
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindCGONative:
		source, ok := entry.Session.(GreeterCollectNativeStreamSession)
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindCGOMessage:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Finish(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterCollectMessageToNativeResponse(messageResp)
	case rpcruntime.ServerKindConnect:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Finish(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterCollectMessageToNativeResponse(messageResp)
	case rpcruntime.ServerKindConnectRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Finish(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterCollectMessageToNativeResponse(messageResp)
	case rpcruntime.ServerKindGRPC:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Finish(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterCollectMessageToNativeResponse(messageResp)
	case rpcruntime.ServerKindGRPCRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Finish(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterCollectMessageToNativeResponse(messageResp)
	default:
		return "", err
	}
}

func CancelGreeterNativeCollect(ctx context.Context, handle rpcruntime.StreamHandle) error {
	entry, err := rpcruntime.CancelStreamSession(handle)
	if err != nil {
		return err
	}
	switch entry.Kind {
	case rpcruntime.ServerKindGoNative:
		source, ok := entry.Session.(GreeterCollectNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindCGONative:
		source, ok := entry.Session.(GreeterCollectNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindCGOMessage:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindConnect:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindConnectRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindGRPC:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindGRPCRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageClientStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	default:
		return fmt.Errorf("rpccgo: Greeter native stream session kind %d is unsupported", entry.Kind)
	}
}

func RecvGreeterNativeBroadcast(ctx context.Context, handle rpcruntime.StreamHandle) (string, error) {
	entry, err := rpcruntime.RecvStreamSession(handle)
	if err != nil {
		return "", rpcruntime.ErrStreamInvalidHandle
	}
	switch entry.Kind {
	case rpcruntime.ServerKindGoNative:
		source, ok := entry.Session.(GreeterBroadcastNativeStreamSession)
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		return source.Recv(ctx)
	case rpcruntime.ServerKindCGONative:
		source, ok := entry.Session.(GreeterBroadcastNativeStreamSession)
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		return source.Recv(ctx)
	case rpcruntime.ServerKindCGOMessage:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Recv(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterBroadcastMessageToNativeResponse(messageResp)
	case rpcruntime.ServerKindConnect:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Recv(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterBroadcastMessageToNativeResponse(messageResp)
	case rpcruntime.ServerKindConnectRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Recv(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterBroadcastMessageToNativeResponse(messageResp)
	case rpcruntime.ServerKindGRPC:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Recv(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterBroadcastMessageToNativeResponse(messageResp)
	case rpcruntime.ServerKindGRPCRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Recv(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterBroadcastMessageToNativeResponse(messageResp)
	default:
		return "", err
	}
}

func FinishGreeterNativeBroadcast(ctx context.Context, handle rpcruntime.StreamHandle) error {
	entry, err := rpcruntime.FinishStreamSession(handle)
	if err != nil {
		return err
	}
	switch entry.Kind {
	case rpcruntime.ServerKindGoNative:
		source, ok := entry.Session.(GreeterBroadcastNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindCGONative:
		source, ok := entry.Session.(GreeterBroadcastNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindCGOMessage:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindConnect:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindConnectRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindGRPC:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindGRPCRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	default:
		return fmt.Errorf("rpccgo: Greeter native stream session kind %d is unsupported", entry.Kind)
	}
}

func CancelGreeterNativeBroadcast(ctx context.Context, handle rpcruntime.StreamHandle) error {
	entry, err := rpcruntime.CancelStreamSession(handle)
	if err != nil {
		return err
	}
	switch entry.Kind {
	case rpcruntime.ServerKindGoNative:
		source, ok := entry.Session.(GreeterBroadcastNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindCGONative:
		source, ok := entry.Session.(GreeterBroadcastNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindCGOMessage:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindConnect:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindConnectRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindGRPC:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindGRPCRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageServerStreamSession[*SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	default:
		return fmt.Errorf("rpccgo: Greeter native stream session kind %d is unsupported", entry.Kind)
	}
}

func SendGreeterNativeChat(ctx context.Context, handle rpcruntime.StreamHandle, name *rpcruntime.RpcString, city *rpcruntime.RpcString) error {
	entry, err := rpcruntime.SendStreamSession(handle)
	if err != nil {
		return err
	}
	switch entry.Kind {
	case rpcruntime.ServerKindGoNative:
		source, ok := entry.Session.(GreeterChatNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Send(ctx, name, city)
	case rpcruntime.ServerKindCGONative:
		source, ok := entry.Session.(GreeterChatNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Send(ctx, name, city)
	case rpcruntime.ServerKindCGOMessage:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		messageReq, err := convertGreeterChatNativeToMessageRequest(name, city)
		if err != nil {
			return err
		}
		return source.Send(ctx, messageReq)
	case rpcruntime.ServerKindConnect:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		messageReq, err := convertGreeterChatNativeToMessageRequest(name, city)
		if err != nil {
			return err
		}
		return source.Send(ctx, messageReq)
	case rpcruntime.ServerKindConnectRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		messageReq, err := convertGreeterChatNativeToMessageRequest(name, city)
		if err != nil {
			return err
		}
		return source.Send(ctx, messageReq)
	case rpcruntime.ServerKindGRPC:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		messageReq, err := convertGreeterChatNativeToMessageRequest(name, city)
		if err != nil {
			return err
		}
		return source.Send(ctx, messageReq)
	case rpcruntime.ServerKindGRPCRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		messageReq, err := convertGreeterChatNativeToMessageRequest(name, city)
		if err != nil {
			return err
		}
		return source.Send(ctx, messageReq)
	default:
		return fmt.Errorf("rpccgo: Greeter native stream session kind %d is unsupported", entry.Kind)
	}
}

func RecvGreeterNativeChat(ctx context.Context, handle rpcruntime.StreamHandle) (string, error) {
	entry, err := rpcruntime.RecvStreamSession(handle)
	if err != nil {
		return "", rpcruntime.ErrStreamInvalidHandle
	}
	switch entry.Kind {
	case rpcruntime.ServerKindGoNative:
		source, ok := entry.Session.(GreeterChatNativeStreamSession)
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		return source.Recv(ctx)
	case rpcruntime.ServerKindCGONative:
		source, ok := entry.Session.(GreeterChatNativeStreamSession)
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		return source.Recv(ctx)
	case rpcruntime.ServerKindCGOMessage:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Recv(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterChatMessageToNativeResponse(messageResp)
	case rpcruntime.ServerKindConnect:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Recv(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterChatMessageToNativeResponse(messageResp)
	case rpcruntime.ServerKindConnectRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Recv(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterChatMessageToNativeResponse(messageResp)
	case rpcruntime.ServerKindGRPC:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Recv(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterChatMessageToNativeResponse(messageResp)
	case rpcruntime.ServerKindGRPCRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return "", rpcruntime.ErrStreamInvalidHandle
		}
		messageResp, err := source.Recv(ctx)
		if err != nil {
			return "", err
		}
		return convertGreeterChatMessageToNativeResponse(messageResp)
	default:
		return "", err
	}
}

func CloseSendGreeterNativeChat(ctx context.Context, handle rpcruntime.StreamHandle) error {
	entry, err := rpcruntime.CloseSendStreamSession(handle)
	if err != nil {
		return err
	}
	switch entry.Kind {
	case rpcruntime.ServerKindGoNative:
		source, ok := entry.Session.(GreeterChatNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.CloseSend(ctx)
	case rpcruntime.ServerKindCGONative:
		source, ok := entry.Session.(GreeterChatNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.CloseSend(ctx)
	case rpcruntime.ServerKindCGOMessage:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.CloseSend(ctx)
	case rpcruntime.ServerKindConnect:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.CloseSend(ctx)
	case rpcruntime.ServerKindConnectRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.CloseSend(ctx)
	case rpcruntime.ServerKindGRPC:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.CloseSend(ctx)
	case rpcruntime.ServerKindGRPCRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.CloseSend(ctx)
	default:
		return fmt.Errorf("rpccgo: Greeter native stream session kind %d is unsupported", entry.Kind)
	}
}

func FinishGreeterNativeChat(ctx context.Context, handle rpcruntime.StreamHandle) error {
	entry, err := rpcruntime.FinishStreamSession(handle)
	if err != nil {
		return err
	}
	switch entry.Kind {
	case rpcruntime.ServerKindGoNative:
		source, ok := entry.Session.(GreeterChatNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindCGONative:
		source, ok := entry.Session.(GreeterChatNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindCGOMessage:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindConnect:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindConnectRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindGRPC:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	case rpcruntime.ServerKindGRPCRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Finish(ctx)
	default:
		return fmt.Errorf("rpccgo: Greeter native stream session kind %d is unsupported", entry.Kind)
	}
}

func CancelGreeterNativeChat(ctx context.Context, handle rpcruntime.StreamHandle) error {
	entry, err := rpcruntime.CancelStreamSession(handle)
	if err != nil {
		return err
	}
	switch entry.Kind {
	case rpcruntime.ServerKindGoNative:
		source, ok := entry.Session.(GreeterChatNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindCGONative:
		source, ok := entry.Session.(GreeterChatNativeStreamSession)
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindCGOMessage:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindConnect:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindConnectRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindGRPC:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	case rpcruntime.ServerKindGRPCRemote:
		source, ok := entry.Session.(rpcruntime.CGOMessageBidiStreamSession[*SayHelloRequest, *SayHelloResponse])
		if !ok {
			return rpcruntime.ErrStreamInvalidHandle
		}
		return source.Cancel(ctx)
	default:
		return fmt.Errorf("rpccgo: Greeter native stream session kind %d is unsupported", entry.Kind)
	}
}

type UnimplementedGreeterNativeServer struct{}

func (UnimplementedGreeterNativeServer) SayHello(ctx context.Context, name *rpcruntime.RpcString, city *rpcruntime.RpcString) (string, error) {
	return "", errors.New("rpccgo: Greeter.SayHello native server method is not implemented")
}

func (UnimplementedGreeterNativeServer) Collect(ctx context.Context, stream GreeterCollectNativeClientStream) (string, error) {
	return "", errors.New("rpccgo: Greeter.Collect native server method is not implemented")
}

func (UnimplementedGreeterNativeServer) Broadcast(ctx context.Context, name *rpcruntime.RpcString, city *rpcruntime.RpcString, stream GreeterBroadcastNativeServerStream) error {
	return errors.New("rpccgo: Greeter.Broadcast native server method is not implemented")
}

func (UnimplementedGreeterNativeServer) Chat(ctx context.Context, stream GreeterChatNativeBidiStream) error {
	return errors.New("rpccgo: Greeter.Chat native server method is not implemented")
}

func RegisterGreeterGoNativeServer(server GreeterNativeServer) error {
	if server == nil {
		return errors.New("rpccgo: Greeter go native server is nil")
	}
	return registerGreeterGoNativeServer(server)
}

func registerGreeterGoNativeServer(server GreeterNativeServer) error {
	if server == nil {
		_ = rpcruntime.ClearServer(greeterServiceID)
		return GreeterNativeServerUnavailableErr
	}
	err := rpcruntime.RegisterServer(greeterServiceID, rpcruntime.RegisteredServer{
		Kind:   rpcruntime.ServerKindGoNative,
		Server: server,
	})
	if err != nil {
		_ = rpcruntime.ClearServer(greeterServiceID)
		return err
	}
	return nil
}

func RegisterGreeterCGONativeServer(server GreeterNativeServer) error {
	if server == nil {
		_ = rpcruntime.ClearServer(greeterServiceID)
		return GreeterNativeServerUnavailableErr
	}
	err := rpcruntime.RegisterServer(greeterServiceID, rpcruntime.RegisteredServer{
		Kind:   rpcruntime.ServerKindCGONative,
		Server: server,
	})
	if err != nil {
		_ = rpcruntime.ClearServer(greeterServiceID)
		return err
	}
	return nil
}

func startGreeterGoNativeCollect(ctx context.Context, server GreeterNativeServer) (GreeterCollectNativeStreamSession, error) {
	streamCtx, cancel := context.WithCancel(ctx)
	session := &greeterCollectGoNativeClientStreamSession{
		ctx:      streamCtx,
		cancel:   cancel,
		requests: make(chan greeterCollectGoNativeClientStreamSessionRequest, 16),
		sendDone: make(chan struct{}),
		done:     make(chan struct{}),
	}
	go func() {
		defer close(session.done)
		session.result.message, session.result.err = server.Collect(streamCtx, session)
	}()
	return session, nil
}

type greeterCollectGoNativeClientStreamSessionRequest struct {
	name     *rpcruntime.RpcString
	city     *rpcruntime.RpcString
	received chan struct{}
}

type greeterCollectGoNativeClientStreamSessionResult struct {
	message string
	err     error
}

type greeterCollectGoNativeClientStreamSession struct {
	ctx           context.Context
	cancel        context.CancelFunc
	requests      chan greeterCollectGoNativeClientStreamSessionRequest
	sendDone      chan struct{}
	closeSendOnce sync.Once
	received      chan struct{}
	done          chan struct{}
	result        greeterCollectGoNativeClientStreamSessionResult
}

func (s *greeterCollectGoNativeClientStreamSession) Recv(ctx context.Context) (*rpcruntime.RpcString, *rpcruntime.RpcString, error) {
	select {
	case req := <-s.requests:
		close(req.received)
		return req.name, req.city, nil
	default:
	}
	select {
	case <-ctx.Done():
		return nil, nil, ctx.Err()
	case <-s.ctx.Done():
		return nil, nil, s.ctx.Err()
	case req := <-s.requests:
		close(req.received)
		return req.name, req.city, nil
	case <-s.sendDone:
		return nil, nil, io.EOF
	}
}

func (s *greeterCollectGoNativeClientStreamSession) Send(ctx context.Context, name *rpcruntime.RpcString, city *rpcruntime.RpcString) error {
	select {
	case <-s.sendDone:
		return greeterNativeStreamClosed
	default:
	}
	req := greeterCollectGoNativeClientStreamSessionRequest{name: name, city: city, received: make(chan struct{})}
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-s.ctx.Done():
		return s.ctx.Err()
	case <-s.done:
		if s.result.err != nil {
			return s.result.err
		}
		return greeterNativeStreamClosed
	case <-s.sendDone:
		return greeterNativeStreamClosed
	case s.requests <- req:
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-s.ctx.Done():
			return s.ctx.Err()
		case <-s.done:
			if s.result.err != nil {
				return s.result.err
			}
			return greeterNativeStreamClosed
		case <-s.sendDone:
			return greeterNativeStreamClosed
		case <-req.received:
			return nil
		}
	}
}

func (s *greeterCollectGoNativeClientStreamSession) Finish(ctx context.Context) (string, error) {
	s.closeSendOnce.Do(func() { close(s.sendDone) })
	select {
	case <-ctx.Done():
		return "", ctx.Err()
	case <-s.done:
		return s.result.message, s.result.err
	}
}

func (s *greeterCollectGoNativeClientStreamSession) Cancel(ctx context.Context) error {
	s.cancel()
	if s.received != nil {
		close(s.received)
		s.received = nil
	}
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-s.done:
		return nil
	}
}

func startGreeterGoNativeBroadcast(ctx context.Context, server GreeterNativeServer, name *rpcruntime.RpcString, city *rpcruntime.RpcString) (GreeterBroadcastNativeStreamSession, error) {
	streamCtx, cancel := context.WithCancel(ctx)
	session := &greeterBroadcastGoNativeServerStreamSession{
		ctx:       streamCtx,
		cancel:    cancel,
		responses: make(chan greeterBroadcastGoNativeServerStreamSessionResponse, 1),
		done:      make(chan struct{}),
	}
	go func() {
		defer close(session.done)
		defer close(session.responses)
		session.err = server.Broadcast(streamCtx, name, city, session)
	}()
	return session, nil
}

type greeterBroadcastGoNativeServerStreamSessionResponse struct {
	message  string
	received chan struct{}
}

type greeterBroadcastGoNativeServerStreamSession struct {
	ctx           context.Context
	cancel        context.CancelFunc
	responses     chan greeterBroadcastGoNativeServerStreamSessionResponse
	received      chan struct{}
	doneRequested bool
	done          chan struct{}
	err           error
}

func (s *greeterBroadcastGoNativeServerStreamSession) Send(ctx context.Context, message string) error {
	resp := greeterBroadcastGoNativeServerStreamSessionResponse{message: message, received: make(chan struct{})}
	select {
	case <-ctx.Done():
		if s.doneRequested {
			return io.EOF
		}
		return ctx.Err()
	case <-s.ctx.Done():
		if s.doneRequested {
			return io.EOF
		}
		return s.ctx.Err()
	case <-s.done:
		if s.err != nil {
			return s.err
		}
		return greeterNativeStreamClosed
	case s.responses <- resp:
		select {
		case <-ctx.Done():
			if s.doneRequested {
				return io.EOF
			}
			return ctx.Err()
		case <-s.ctx.Done():
			if s.doneRequested {
				return io.EOF
			}
			return s.ctx.Err()
		case <-s.done:
			if s.err != nil {
				return s.err
			}
			return greeterNativeStreamClosed
		case <-resp.received:
			if s.ctx.Err() != nil {
				if s.doneRequested {
					return io.EOF
				}
				return s.ctx.Err()
			}
			return nil
		}
	}
}

func (s *greeterBroadcastGoNativeServerStreamSession) Recv(ctx context.Context) (string, error) {
	if s.received != nil {
		close(s.received)
		s.received = nil
	}
	select {
	case <-ctx.Done():
		return "", ctx.Err()
	case <-s.ctx.Done():
		return "", s.ctx.Err()
	case resp, ok := <-s.responses:
		if ok {
			s.received = resp.received
			return resp.message, nil
		}
		if s.received != nil {
			close(s.received)
			s.received = nil
		}
		<-s.done
		if s.err != nil {
			return "", s.err
		}
		return "", io.EOF
	}
}

func (s *greeterBroadcastGoNativeServerStreamSession) Finish(ctx context.Context) error {
	s.doneRequested = true
	s.cancel()
	if s.received != nil {
		close(s.received)
		s.received = nil
	}
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-s.done:
		if errors.Is(s.err, context.Canceled) || errors.Is(s.err, io.EOF) {
			return nil
		}
		return s.err
	}
}

func (s *greeterBroadcastGoNativeServerStreamSession) Cancel(ctx context.Context) error {
	s.cancel()
	if s.received != nil {
		close(s.received)
		s.received = nil
	}
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-s.done:
		return nil
	}
}

func startGreeterGoNativeChat(ctx context.Context, server GreeterNativeServer) (GreeterChatNativeStreamSession, error) {
	streamCtx, cancel := context.WithCancel(ctx)
	session := &greeterChatGoNativeBidiStreamSession{
		ctx:              streamCtx,
		cancel:           cancel,
		requests:         make(chan greeterChatGoNativeBidiStreamSessionRequest, 16),
		sendDone:         make(chan struct{}),
		sendDoneReceived: make(chan struct{}),
		responses:        make(chan greeterChatGoNativeBidiStreamSessionResponse, 1),
		responseReady:    make(chan struct{}),
		requestReceived:  make(chan struct{}),
		done:             make(chan struct{}),
	}
	go func() {
		defer close(session.done)
		defer close(session.responses)
		session.err = server.Chat(streamCtx, &greeterChatGoNativeBidiStreamFacade{source: session})
	}()
	return session, nil
}

type greeterChatGoNativeBidiStreamSessionRequest struct {
	name     *rpcruntime.RpcString
	city     *rpcruntime.RpcString
	received chan struct{}
}

type greeterChatGoNativeBidiStreamSessionResponse struct {
	message  string
	received chan struct{}
}

type greeterChatGoNativeBidiStreamSession struct {
	ctx                  context.Context
	cancel               context.CancelFunc
	requests             chan greeterChatGoNativeBidiStreamSessionRequest
	sendDone             chan struct{}
	sendDoneReceived     chan struct{}
	sendDoneReceivedOnce sync.Once
	closeSendOnce        sync.Once
	responses            chan greeterChatGoNativeBidiStreamSessionResponse
	responseReady        chan struct{}
	responseReadyOnce    sync.Once
	requestReceived      chan struct{}
	requestReceivedOnce  sync.Once
	received             chan struct{}
	doneRequested        bool
	done                 chan struct{}
	err                  error
}

type greeterChatGoNativeBidiStreamFacade struct {
	source *greeterChatGoNativeBidiStreamSession
}

func (s *greeterChatGoNativeBidiStreamFacade) Recv(ctx context.Context) (*rpcruntime.RpcString, *rpcruntime.RpcString, error) {
	select {
	case req := <-s.source.requests:
		close(req.received)
		s.source.requestReceivedOnce.Do(func() { close(s.source.requestReceived) })
		return req.name, req.city, nil
	default:
	}
	select {
	case <-ctx.Done():
		return nil, nil, ctx.Err()
	case <-s.source.ctx.Done():
		return nil, nil, s.source.ctx.Err()
	case req := <-s.source.requests:
		close(req.received)
		s.source.requestReceivedOnce.Do(func() { close(s.source.requestReceived) })
		return req.name, req.city, nil
	case <-s.source.sendDone:
		s.source.sendDoneReceivedOnce.Do(func() { close(s.source.sendDoneReceived) })
		return nil, nil, io.EOF
	}
}

func (s *greeterChatGoNativeBidiStreamFacade) Send(ctx context.Context, message string) error {
	resp := greeterChatGoNativeBidiStreamSessionResponse{message: message, received: make(chan struct{})}
	select {
	case <-ctx.Done():
		if s.source.doneRequested {
			return io.EOF
		}
		return ctx.Err()
	case <-s.source.ctx.Done():
		if s.source.doneRequested {
			return io.EOF
		}
		return s.source.ctx.Err()
	case <-s.source.done:
		if s.source.err != nil {
			return s.source.err
		}
		return greeterNativeStreamClosed
	case s.source.responses <- resp:
		s.source.responseReadyOnce.Do(func() { close(s.source.responseReady) })
		select {
		case <-ctx.Done():
			if s.source.doneRequested {
				return io.EOF
			}
			return ctx.Err()
		case <-s.source.ctx.Done():
			if s.source.doneRequested {
				return io.EOF
			}
			return s.source.ctx.Err()
		case <-s.source.done:
			if s.source.err != nil {
				return s.source.err
			}
			return greeterNativeStreamClosed
		case <-resp.received:
			if s.source.ctx.Err() != nil {
				if s.source.doneRequested {
					return io.EOF
				}
				return s.source.ctx.Err()
			}
			return nil
		}
	}
}

func (s *greeterChatGoNativeBidiStreamSession) Send(ctx context.Context, name *rpcruntime.RpcString, city *rpcruntime.RpcString) error {
	select {
	case <-s.sendDone:
		return greeterNativeStreamClosed
	default:
	}
	req := greeterChatGoNativeBidiStreamSessionRequest{name: name, city: city, received: make(chan struct{})}
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-s.ctx.Done():
		return s.ctx.Err()
	case <-s.done:
		if s.err != nil {
			return s.err
		}
		return greeterNativeStreamClosed
	case <-s.sendDone:
		return greeterNativeStreamClosed
	case s.requests <- req:
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-s.ctx.Done():
			return s.ctx.Err()
		case <-s.done:
			if s.err != nil {
				return s.err
			}
			return greeterNativeStreamClosed
		case <-s.sendDone:
			return greeterNativeStreamClosed
		case <-s.responseReady:
			select {
			case <-ctx.Done():
				return ctx.Err()
			case <-s.ctx.Done():
				return s.ctx.Err()
			case <-s.done:
				if s.err != nil {
					return s.err
				}
				return greeterNativeStreamClosed
			case <-s.sendDone:
				return greeterNativeStreamClosed
			case <-s.requestReceived:
				return nil
			case <-req.received:
				return nil
			}
			return nil
		case <-req.received:
			return nil
		}
	}
}

func (s *greeterChatGoNativeBidiStreamSession) Recv(ctx context.Context) (string, error) {
	if s.received != nil {
		close(s.received)
		s.received = nil
	}
	select {
	case <-ctx.Done():
		return "", ctx.Err()
	case <-s.ctx.Done():
		return "", s.ctx.Err()
	case resp, ok := <-s.responses:
		if ok {
			s.responseReady = make(chan struct{})
			s.responseReadyOnce = sync.Once{}
			s.received = resp.received
			return resp.message, nil
		}
		if s.received != nil {
			close(s.received)
			s.received = nil
		}
		<-s.done
		if s.err != nil {
			return "", s.err
		}
		return "", io.EOF
	}
}

func (s *greeterChatGoNativeBidiStreamSession) CloseSend(ctx context.Context) error {
	s.closeSendOnce.Do(func() { close(s.sendDone) })
	return nil
}

func (s *greeterChatGoNativeBidiStreamSession) Finish(ctx context.Context) error {
	s.doneRequested = true
	s.cancel()
	if s.received != nil {
		close(s.received)
		s.received = nil
	}
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-s.done:
		if errors.Is(s.err, context.Canceled) || errors.Is(s.err, io.EOF) {
			return nil
		}
		return s.err
	}
}

func (s *greeterChatGoNativeBidiStreamSession) Cancel(ctx context.Context) error {
	s.cancel()
	if s.received != nil {
		close(s.received)
		s.received = nil
	}
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-s.done:
		return nil
	}
}
