// Code generated by protoc-gen-rpc-cgo. DO NOT EDIT.
//
// Source: greeter.proto

package greeterv1

import (
	context "context"
	errors "errors"
	rpcruntime "rpccgo/rpcruntime"
)

// rpccgo native generated file for Greeter go native server

// Greeter serves greeting RPCs for the Connect example.
type GreeterNativeServer interface {
	// SayHello returns a single greeting.
	SayHello(ctx context.Context, name *rpcruntime.RpcString, city *rpcruntime.RpcString) (string, error)
	// Collect accepts many requests and returns one greeting.
	Collect(ctx context.Context, stream GreeterCollectNativeClientStream) (string, error)
	// Broadcast accepts one request and streams greetings back.
	Broadcast(ctx context.Context, name *rpcruntime.RpcString, city *rpcruntime.RpcString, stream GreeterBroadcastNativeServerStream) error
	// Chat exchanges greeting requests and responses bidirectionally.
	Chat(ctx context.Context, stream GreeterChatNativeBidiStream) error
}

type GreeterCollectNativeClientStream interface {
	Recv(ctx context.Context) (*rpcruntime.RpcString, *rpcruntime.RpcString, error)
}

type GreeterBroadcastNativeServerStream interface {
	Send(ctx context.Context, message string) error
}

type GreeterChatNativeBidiStream interface {
	Recv(ctx context.Context) (*rpcruntime.RpcString, *rpcruntime.RpcString, error)
	Send(ctx context.Context, message string) error
}

type UnimplementedGreeterNativeServer struct{}

func (UnimplementedGreeterNativeServer) SayHello(ctx context.Context, name *rpcruntime.RpcString, city *rpcruntime.RpcString) (string, error) {
	return "", errors.New("rpccgo: Greeter.SayHello native server method is not implemented")
}

func (UnimplementedGreeterNativeServer) Collect(ctx context.Context, stream GreeterCollectNativeClientStream) (string, error) {
	return "", errors.New("rpccgo: Greeter.Collect native server method is not implemented")
}

func (UnimplementedGreeterNativeServer) Broadcast(ctx context.Context, name *rpcruntime.RpcString, city *rpcruntime.RpcString, stream GreeterBroadcastNativeServerStream) error {
	return errors.New("rpccgo: Greeter.Broadcast native server method is not implemented")
}

func (UnimplementedGreeterNativeServer) Chat(ctx context.Context, stream GreeterChatNativeBidiStream) error {
	return errors.New("rpccgo: Greeter.Chat native server method is not implemented")
}

func RegisterGreeterGoNativeServer(server GreeterNativeServer) error {
	if server == nil {
		return errors.New("rpccgo: Greeter go native server is nil")
	}
	return registerGreeterGoNativeServer(server)
}
