// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: stream.proto

package cgotest_mixconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	mix "github.com/ygrpc/rpccgo/cgotest/mix"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StreamServiceName is the fully-qualified name of the StreamService service.
	StreamServiceName = "cgotest.StreamService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StreamServiceUnaryCallProcedure is the fully-qualified name of the StreamService's UnaryCall RPC.
	StreamServiceUnaryCallProcedure = "/cgotest.StreamService/UnaryCall"
	// StreamServiceClientStreamCallProcedure is the fully-qualified name of the StreamService's
	// ClientStreamCall RPC.
	StreamServiceClientStreamCallProcedure = "/cgotest.StreamService/ClientStreamCall"
	// StreamServiceServerStreamCallProcedure is the fully-qualified name of the StreamService's
	// ServerStreamCall RPC.
	StreamServiceServerStreamCallProcedure = "/cgotest.StreamService/ServerStreamCall"
	// StreamServiceBidiStreamCallProcedure is the fully-qualified name of the StreamService's
	// BidiStreamCall RPC.
	StreamServiceBidiStreamCallProcedure = "/cgotest.StreamService/BidiStreamCall"
)

// StreamServiceClient is a client for the cgotest.StreamService service.
type StreamServiceClient interface {
	// Unary RPC.
	UnaryCall(context.Context, *mix.StreamRequest) (*mix.StreamResponse, error)
	// Client-streaming RPC: client sends a stream of requests, server responds once.
	ClientStreamCall(context.Context) (*connect.ClientStreamForClientSimple[mix.StreamRequest, mix.StreamResponse], error)
	// Server-streaming RPC: client sends one request, server responds with a stream.
	ServerStreamCall(context.Context, *mix.StreamRequest) (*connect.ServerStreamForClient[mix.StreamResponse], error)
	// Bidi-streaming RPC: both client and server send streams concurrently.
	BidiStreamCall(context.Context) (*connect.BidiStreamForClientSimple[mix.StreamRequest, mix.StreamResponse], error)
}

// NewStreamServiceClient constructs a client for the cgotest.StreamService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStreamServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StreamServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	streamServiceMethods := mix.File_stream_proto.Services().ByName("StreamService").Methods()
	return &streamServiceClient{
		unaryCall: connect.NewClient[mix.StreamRequest, mix.StreamResponse](
			httpClient,
			baseURL+StreamServiceUnaryCallProcedure,
			connect.WithSchema(streamServiceMethods.ByName("UnaryCall")),
			connect.WithClientOptions(opts...),
		),
		clientStreamCall: connect.NewClient[mix.StreamRequest, mix.StreamResponse](
			httpClient,
			baseURL+StreamServiceClientStreamCallProcedure,
			connect.WithSchema(streamServiceMethods.ByName("ClientStreamCall")),
			connect.WithClientOptions(opts...),
		),
		serverStreamCall: connect.NewClient[mix.StreamRequest, mix.StreamResponse](
			httpClient,
			baseURL+StreamServiceServerStreamCallProcedure,
			connect.WithSchema(streamServiceMethods.ByName("ServerStreamCall")),
			connect.WithClientOptions(opts...),
		),
		bidiStreamCall: connect.NewClient[mix.StreamRequest, mix.StreamResponse](
			httpClient,
			baseURL+StreamServiceBidiStreamCallProcedure,
			connect.WithSchema(streamServiceMethods.ByName("BidiStreamCall")),
			connect.WithClientOptions(opts...),
		),
	}
}

// streamServiceClient implements StreamServiceClient.
type streamServiceClient struct {
	unaryCall        *connect.Client[mix.StreamRequest, mix.StreamResponse]
	clientStreamCall *connect.Client[mix.StreamRequest, mix.StreamResponse]
	serverStreamCall *connect.Client[mix.StreamRequest, mix.StreamResponse]
	bidiStreamCall   *connect.Client[mix.StreamRequest, mix.StreamResponse]
}

// UnaryCall calls cgotest.StreamService.UnaryCall.
func (c *streamServiceClient) UnaryCall(ctx context.Context, req *mix.StreamRequest) (*mix.StreamResponse, error) {
	response, err := c.unaryCall.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ClientStreamCall calls cgotest.StreamService.ClientStreamCall.
func (c *streamServiceClient) ClientStreamCall(ctx context.Context) (*connect.ClientStreamForClientSimple[mix.StreamRequest, mix.StreamResponse], error) {
	return c.clientStreamCall.CallClientStreamSimple(ctx)
}

// ServerStreamCall calls cgotest.StreamService.ServerStreamCall.
func (c *streamServiceClient) ServerStreamCall(ctx context.Context, req *mix.StreamRequest) (*connect.ServerStreamForClient[mix.StreamResponse], error) {
	return c.serverStreamCall.CallServerStream(ctx, connect.NewRequest(req))
}

// BidiStreamCall calls cgotest.StreamService.BidiStreamCall.
func (c *streamServiceClient) BidiStreamCall(ctx context.Context) (*connect.BidiStreamForClientSimple[mix.StreamRequest, mix.StreamResponse], error) {
	return c.bidiStreamCall.CallBidiStreamSimple(ctx)
}

// StreamServiceHandler is an implementation of the cgotest.StreamService service.
type StreamServiceHandler interface {
	// Unary RPC.
	UnaryCall(context.Context, *mix.StreamRequest) (*mix.StreamResponse, error)
	// Client-streaming RPC: client sends a stream of requests, server responds once.
	ClientStreamCall(context.Context, *connect.ClientStream[mix.StreamRequest]) (*mix.StreamResponse, error)
	// Server-streaming RPC: client sends one request, server responds with a stream.
	ServerStreamCall(context.Context, *mix.StreamRequest, *connect.ServerStream[mix.StreamResponse]) error
	// Bidi-streaming RPC: both client and server send streams concurrently.
	BidiStreamCall(context.Context, *connect.BidiStream[mix.StreamRequest, mix.StreamResponse]) error
}

// NewStreamServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStreamServiceHandler(svc StreamServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	streamServiceMethods := mix.File_stream_proto.Services().ByName("StreamService").Methods()
	streamServiceUnaryCallHandler := connect.NewUnaryHandlerSimple(
		StreamServiceUnaryCallProcedure,
		svc.UnaryCall,
		connect.WithSchema(streamServiceMethods.ByName("UnaryCall")),
		connect.WithHandlerOptions(opts...),
	)
	streamServiceClientStreamCallHandler := connect.NewClientStreamHandlerSimple(
		StreamServiceClientStreamCallProcedure,
		svc.ClientStreamCall,
		connect.WithSchema(streamServiceMethods.ByName("ClientStreamCall")),
		connect.WithHandlerOptions(opts...),
	)
	streamServiceServerStreamCallHandler := connect.NewServerStreamHandlerSimple(
		StreamServiceServerStreamCallProcedure,
		svc.ServerStreamCall,
		connect.WithSchema(streamServiceMethods.ByName("ServerStreamCall")),
		connect.WithHandlerOptions(opts...),
	)
	streamServiceBidiStreamCallHandler := connect.NewBidiStreamHandler(
		StreamServiceBidiStreamCallProcedure,
		svc.BidiStreamCall,
		connect.WithSchema(streamServiceMethods.ByName("BidiStreamCall")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cgotest.StreamService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StreamServiceUnaryCallProcedure:
			streamServiceUnaryCallHandler.ServeHTTP(w, r)
		case StreamServiceClientStreamCallProcedure:
			streamServiceClientStreamCallHandler.ServeHTTP(w, r)
		case StreamServiceServerStreamCallProcedure:
			streamServiceServerStreamCallHandler.ServeHTTP(w, r)
		case StreamServiceBidiStreamCallProcedure:
			streamServiceBidiStreamCallHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStreamServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStreamServiceHandler struct{}

func (UnimplementedStreamServiceHandler) UnaryCall(context.Context, *mix.StreamRequest) (*mix.StreamResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cgotest.StreamService.UnaryCall is not implemented"))
}

func (UnimplementedStreamServiceHandler) ClientStreamCall(context.Context, *connect.ClientStream[mix.StreamRequest]) (*mix.StreamResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cgotest.StreamService.ClientStreamCall is not implemented"))
}

func (UnimplementedStreamServiceHandler) ServerStreamCall(context.Context, *mix.StreamRequest, *connect.ServerStream[mix.StreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("cgotest.StreamService.ServerStreamCall is not implemented"))
}

func (UnimplementedStreamServiceHandler) BidiStreamCall(context.Context, *connect.BidiStream[mix.StreamRequest, mix.StreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("cgotest.StreamService.BidiStreamCall is not implemented"))
}
