// Code generated by protoc-gen-rpc-cgo-jni. DO NOT EDIT.
//
// Source: shared_so.proto

#include <mutex>

#include "rpccgo.jni.h"

std::mutex sharedSoDemoServerBridgeMu;
jobject sharedSoDemoServerBridge = nullptr;
jmethodID sharedSoDemoComposeGreetingServerHandle = nullptr;
jmethodID sharedSoDemoIncrementRuntimeStateServerHandle = nullptr;
jmethodID sharedSoDemoReadRuntimeStateServerHandle = nullptr;
jmethodID sharedSoDemoWatchRuntimeStateServerStart = nullptr;
jmethodID sharedSoDemoWatchRuntimeStateServerRecv = nullptr;
jmethodID sharedSoDemoWatchRuntimeStateServerFinish = nullptr;
jmethodID sharedSoDemoWatchRuntimeStateServerCancel = nullptr;
jmethodID sharedSoDemoCollectRuntimeStateServerStart = nullptr;
jmethodID sharedSoDemoCollectRuntimeStateServerSend = nullptr;
jmethodID sharedSoDemoCollectRuntimeStateServerFinish = nullptr;
jmethodID sharedSoDemoCollectRuntimeStateServerCancel = nullptr;
jmethodID sharedSoDemoStreamRuntimeStateServerStart = nullptr;
jmethodID sharedSoDemoStreamRuntimeStateServerRecv = nullptr;
jmethodID sharedSoDemoStreamRuntimeStateServerFinish = nullptr;
jmethodID sharedSoDemoStreamRuntimeStateServerCancel = nullptr;
jmethodID sharedSoDemoChatRuntimeStateServerStart = nullptr;
jmethodID sharedSoDemoChatRuntimeStateServerSend = nullptr;
jmethodID sharedSoDemoChatRuntimeStateServerRecv = nullptr;
jmethodID sharedSoDemoChatRuntimeStateServerCloseSend = nullptr;
jmethodID sharedSoDemoChatRuntimeStateServerFinish = nullptr;
jmethodID sharedSoDemoChatRuntimeStateServerCancel = nullptr;

bool ensureSharedSoDemoServerBridge(JNIEnv* env, jobject thiz) {
    if (env == nullptr || thiz == nullptr) { return false; }
    std::lock_guard<std::mutex> lock(sharedSoDemoServerBridgeMu);
    if (sharedSoDemoServerBridge == nullptr) {
        sharedSoDemoServerBridge = env->NewGlobalRef(thiz);
    }
    return sharedSoDemoServerBridge != nullptr;
}

jobject sharedSoDemoServerBridgeObject() {
    std::lock_guard<std::mutex> lock(sharedSoDemoServerBridgeMu);
    return sharedSoDemoServerBridge;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoComposeGreeting invokes examples.flutter.sharedso.v1.SharedSoDemo.ComposeGreeting through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoComposeGreeting(JNIEnv* env, jobject, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoComposeGreeting(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

int32_t onSharedSoDemoComposeGreetingServerHandle(uintptr_t requestPtr, int32_t requestLen, uintptr_t* responsePtr, int32_t* responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoComposeGreetingServerHandle == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray request = nullptr;
    int32_t requestErr = rpccgoRequestByteArray(env, requestPtr, requestLen, &request);
    if (requestErr != 0) { return requestErr; }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoComposeGreetingServerHandle, request));
    env->DeleteLocalRef(request);
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server unary handler threw"); }
    int32_t errID = rpccgoKotlinBytesResult(env, result, responsePtr, responseLen);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoComposeGreetingRegister invokes examples.flutter.sharedso.v1.SharedSoDemo.ComposeGreeting through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoComposeGreetingRegister(JNIEnv* env, jobject thiz) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    if (!ensureSharedSoDemoServerBridge(env, thiz)) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge registration failed"); }
    jclass bridgeClass = env->GetObjectClass(thiz);
    if (bridgeClass == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge class lookup failed"); }
    sharedSoDemoComposeGreetingServerHandle = env->GetMethodID(bridgeClass, "sharedSoDemoComposeGreetingHandle", "([B)[B");
    env->DeleteLocalRef(bridgeClass);
    if (env->ExceptionCheck()) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method lookup failed"); }
    if (sharedSoDemoComposeGreetingServerHandle == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoRegisterComposeGreeting(onSharedSoDemoComposeGreetingServerHandle);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoIncrementRuntimeState invokes examples.flutter.sharedso.v1.SharedSoDemo.IncrementRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoIncrementRuntimeState(JNIEnv* env, jobject, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoIncrementRuntimeState(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

int32_t onSharedSoDemoIncrementRuntimeStateServerHandle(uintptr_t requestPtr, int32_t requestLen, uintptr_t* responsePtr, int32_t* responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoIncrementRuntimeStateServerHandle == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray request = nullptr;
    int32_t requestErr = rpccgoRequestByteArray(env, requestPtr, requestLen, &request);
    if (requestErr != 0) { return requestErr; }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoIncrementRuntimeStateServerHandle, request));
    env->DeleteLocalRef(request);
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server unary handler threw"); }
    int32_t errID = rpccgoKotlinBytesResult(env, result, responsePtr, responseLen);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoIncrementRuntimeStateRegister invokes examples.flutter.sharedso.v1.SharedSoDemo.IncrementRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoIncrementRuntimeStateRegister(JNIEnv* env, jobject thiz) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    if (!ensureSharedSoDemoServerBridge(env, thiz)) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge registration failed"); }
    jclass bridgeClass = env->GetObjectClass(thiz);
    if (bridgeClass == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge class lookup failed"); }
    sharedSoDemoIncrementRuntimeStateServerHandle = env->GetMethodID(bridgeClass, "sharedSoDemoIncrementRuntimeStateHandle", "([B)[B");
    env->DeleteLocalRef(bridgeClass);
    if (env->ExceptionCheck()) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method lookup failed"); }
    if (sharedSoDemoIncrementRuntimeStateServerHandle == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoRegisterIncrementRuntimeState(onSharedSoDemoIncrementRuntimeStateServerHandle);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoReadRuntimeState invokes examples.flutter.sharedso.v1.SharedSoDemo.ReadRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoReadRuntimeState(JNIEnv* env, jobject, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoReadRuntimeState(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

int32_t onSharedSoDemoReadRuntimeStateServerHandle(uintptr_t requestPtr, int32_t requestLen, uintptr_t* responsePtr, int32_t* responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoReadRuntimeStateServerHandle == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray request = nullptr;
    int32_t requestErr = rpccgoRequestByteArray(env, requestPtr, requestLen, &request);
    if (requestErr != 0) { return requestErr; }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoReadRuntimeStateServerHandle, request));
    env->DeleteLocalRef(request);
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server unary handler threw"); }
    int32_t errID = rpccgoKotlinBytesResult(env, result, responsePtr, responseLen);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoReadRuntimeStateRegister invokes examples.flutter.sharedso.v1.SharedSoDemo.ReadRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoReadRuntimeStateRegister(JNIEnv* env, jobject thiz) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    if (!ensureSharedSoDemoServerBridge(env, thiz)) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge registration failed"); }
    jclass bridgeClass = env->GetObjectClass(thiz);
    if (bridgeClass == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge class lookup failed"); }
    sharedSoDemoReadRuntimeStateServerHandle = env->GetMethodID(bridgeClass, "sharedSoDemoReadRuntimeStateHandle", "([B)[B");
    env->DeleteLocalRef(bridgeClass);
    if (env->ExceptionCheck()) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method lookup failed"); }
    if (sharedSoDemoReadRuntimeStateServerHandle == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoRegisterReadRuntimeState(onSharedSoDemoReadRuntimeStateServerHandle);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

std::mutex sharedSoDemoWatchRuntimeStateCallbackMu;
jobject sharedSoDemoWatchRuntimeStateCallbackListener = nullptr;
jmethodID sharedSoDemoWatchRuntimeStateCallbackOnRecv = nullptr;
jmethodID sharedSoDemoWatchRuntimeStateCallbackOnDone = nullptr;
int32_t sharedSoDemoWatchRuntimeStateCallbackHandle = 0;

void clearSharedSoDemoWatchRuntimeStateListenerCallback(JNIEnv* env) {
    std::lock_guard<std::mutex> lock(sharedSoDemoWatchRuntimeStateCallbackMu);
    if (env != nullptr && sharedSoDemoWatchRuntimeStateCallbackListener != nullptr) {
        env->DeleteGlobalRef(sharedSoDemoWatchRuntimeStateCallbackListener);
    }
    sharedSoDemoWatchRuntimeStateCallbackListener = nullptr;
    sharedSoDemoWatchRuntimeStateCallbackOnRecv = nullptr;
    sharedSoDemoWatchRuntimeStateCallbackOnDone = nullptr;
    sharedSoDemoWatchRuntimeStateCallbackHandle = 0;
}

bool cancelSharedSoDemoWatchRuntimeStateListenerCallback(JNIEnv* env) {
    int32_t handle = 0;
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoWatchRuntimeStateCallbackMu);
        handle = sharedSoDemoWatchRuntimeStateCallbackHandle;
    }
    if (handle == 0) {
        clearSharedSoDemoWatchRuntimeStateListenerCallback(env);
        return true;
    }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoWatchRuntimeStateCancel(handle);
    return errID == 0;
}

void onSharedSoDemoWatchRuntimeStateListenerRecv(int32_t, uintptr_t responsePtr, int32_t responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return;
    }
    std::lock_guard<std::mutex> lock(sharedSoDemoWatchRuntimeStateCallbackMu);
    if (sharedSoDemoWatchRuntimeStateCallbackListener == nullptr || sharedSoDemoWatchRuntimeStateCallbackOnRecv == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return;
    }
    jbyteArray payload = env->NewByteArray(responseLen);
    if (payload == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return;
    }
    if (responseLen > 0) {
        env->SetByteArrayRegion(payload, 0, responseLen, reinterpret_cast<const jbyte*>(responsePtr));
    }
    if (responsePtr != 0) { rpccgoRelease(responsePtr); }
    env->CallVoidMethod(sharedSoDemoWatchRuntimeStateCallbackListener, sharedSoDemoWatchRuntimeStateCallbackOnRecv, payload);
    env->DeleteLocalRef(payload);
    if (env->ExceptionCheck()) { env->ExceptionClear(); }
}

void onSharedSoDemoWatchRuntimeStateListenerDone(int32_t, int32_t errID) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return; }
    jobject listener = nullptr;
    jmethodID onDone = nullptr;
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoWatchRuntimeStateCallbackMu);
        listener = sharedSoDemoWatchRuntimeStateCallbackListener;
        onDone = sharedSoDemoWatchRuntimeStateCallbackOnDone;
    }
    if (listener != nullptr && onDone != nullptr) {
        jstring error = nullptr;
        if (errID != 0) {
            std::string text = rpccgoErrorString(errID);
            error = env->NewStringUTF(text.c_str());
        }
        env->CallVoidMethod(listener, onDone, error);
        if (error != nullptr) { env->DeleteLocalRef(error); }
        if (env->ExceptionCheck()) { env->ExceptionClear(); }
    }
    clearSharedSoDemoWatchRuntimeStateListenerCallback(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateStart invokes examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateStart(JNIEnv* env, jobject, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoWatchRuntimeStateStart(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &handle, nullptr, nullptr);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessHandle(env, handle);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateRecv invokes examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateRecv(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoWatchRuntimeStateRecv(static_cast<int32_t>(handle), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateCancel invokes examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateCancel(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoWatchRuntimeStateCancel(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateStartCallback invokes examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateStartCallback(JNIEnv* env, jobject, jbyteArray request, jobject listener) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return JNI_FALSE; }
    if (request == nullptr || listener == nullptr) { return JNI_FALSE; }
    cancelSharedSoDemoWatchRuntimeStateListenerCallback(env);
    jclass listenerClass = env->GetObjectClass(listener);
    jmethodID onRecv = env->GetMethodID(listenerClass, "onRecv", "([B)V");
    jmethodID onDone = env->GetMethodID(listenerClass, "onDone", "(Ljava/lang/String;)V");
    env->DeleteLocalRef(listenerClass);
    if (onRecv == nullptr || onDone == nullptr) { return JNI_FALSE; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return JNI_FALSE; }
    jobject globalListener = env->NewGlobalRef(listener);
    if (globalListener == nullptr) { return JNI_FALSE; }
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoWatchRuntimeStateCallbackMu);
        sharedSoDemoWatchRuntimeStateCallbackListener = globalListener;
        sharedSoDemoWatchRuntimeStateCallbackOnRecv = onRecv;
        sharedSoDemoWatchRuntimeStateCallbackOnDone = onDone;
    }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoWatchRuntimeStateStart(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &handle, onSharedSoDemoWatchRuntimeStateListenerRecv, onSharedSoDemoWatchRuntimeStateListenerDone);
    if (errID != 0) {
        clearSharedSoDemoWatchRuntimeStateListenerCallback(env);
        return JNI_FALSE;
    }
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoWatchRuntimeStateCallbackMu);
        sharedSoDemoWatchRuntimeStateCallbackHandle = handle;
    }
    return JNI_TRUE;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateCancelCallback invokes examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateCancelCallback(JNIEnv* env, jobject) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return JNI_FALSE; }
    return cancelSharedSoDemoWatchRuntimeStateListenerCallback(env) ? JNI_TRUE : JNI_FALSE;
}

int32_t onSharedSoDemoWatchRuntimeStateServerStart(uintptr_t requestPtr, int32_t requestLen, int32_t* stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoWatchRuntimeStateServerStart == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray request = nullptr;
    int32_t requestErr = rpccgoRequestByteArray(env, requestPtr, requestLen, &request);
    if (requestErr != 0) { return requestErr; }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoWatchRuntimeStateServerStart, request));
    env->DeleteLocalRef(request);
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream start threw"); }
    int32_t errID = rpccgoKotlinHandleResult(env, result, stream);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoWatchRuntimeStateServerRecv(int32_t stream, uintptr_t* responsePtr, int32_t* responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoWatchRuntimeStateServerRecv == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoWatchRuntimeStateServerRecv, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream response handler threw"); }
    int32_t errID = rpccgoKotlinBytesResult(env, result, responsePtr, responseLen);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoWatchRuntimeStateServerFinish(int32_t stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoWatchRuntimeStateServerFinish == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoWatchRuntimeStateServerFinish, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream control handler threw"); }
    int32_t errID = rpccgoKotlinUnitResult(env, result);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoWatchRuntimeStateServerCancel(int32_t stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoWatchRuntimeStateServerCancel == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoWatchRuntimeStateServerCancel, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream control handler threw"); }
    int32_t errID = rpccgoKotlinUnitResult(env, result);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateRegister invokes examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateRegister(JNIEnv* env, jobject thiz) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    if (!ensureSharedSoDemoServerBridge(env, thiz)) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge registration failed"); }
    jclass bridgeClass = env->GetObjectClass(thiz);
    if (bridgeClass == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge class lookup failed"); }
    sharedSoDemoWatchRuntimeStateServerStart = env->GetMethodID(bridgeClass, "sharedSoDemoWatchRuntimeStateServerStart", "([B)[B");
    sharedSoDemoWatchRuntimeStateServerRecv = env->GetMethodID(bridgeClass, "sharedSoDemoWatchRuntimeStateServerRecv", "(I)[B");
    sharedSoDemoWatchRuntimeStateServerFinish = env->GetMethodID(bridgeClass, "sharedSoDemoWatchRuntimeStateServerFinish", "(I)[B");
    sharedSoDemoWatchRuntimeStateServerCancel = env->GetMethodID(bridgeClass, "sharedSoDemoWatchRuntimeStateServerCancel", "(I)[B");
    env->DeleteLocalRef(bridgeClass);
    if (env->ExceptionCheck()) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method lookup failed"); }
    if (sharedSoDemoWatchRuntimeStateServerStart == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoWatchRuntimeStateServerRecv == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoWatchRuntimeStateServerFinish == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoWatchRuntimeStateServerCancel == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoRegisterWatchRuntimeState(onSharedSoDemoWatchRuntimeStateServerStart, onSharedSoDemoWatchRuntimeStateServerRecv, onSharedSoDemoWatchRuntimeStateServerFinish, onSharedSoDemoWatchRuntimeStateServerCancel);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateStart invokes examples.flutter.sharedso.v1.SharedSoDemo.CollectRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateStart(JNIEnv* env, jobject) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoCollectRuntimeStateStart(&handle);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessHandle(env, handle);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateSend invokes examples.flutter.sharedso.v1.SharedSoDemo.CollectRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateSend(JNIEnv* env, jobject, jint handle, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoCollectRuntimeStateSend(static_cast<int32_t>(handle), rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateFinish invokes examples.flutter.sharedso.v1.SharedSoDemo.CollectRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateFinish(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoCollectRuntimeStateFinish(static_cast<int32_t>(handle), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateCancel invokes examples.flutter.sharedso.v1.SharedSoDemo.CollectRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateCancel(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoCollectRuntimeStateCancel(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

int32_t onSharedSoDemoCollectRuntimeStateServerStart(int32_t* stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoCollectRuntimeStateServerStart == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoCollectRuntimeStateServerStart));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream start threw"); }
    int32_t errID = rpccgoKotlinHandleResult(env, result, stream);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoCollectRuntimeStateServerSend(int32_t stream, uintptr_t requestPtr, int32_t requestLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoCollectRuntimeStateServerSend == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray request = nullptr;
    int32_t requestErr = rpccgoRequestByteArray(env, requestPtr, requestLen, &request);
    if (requestErr != 0) { return requestErr; }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoCollectRuntimeStateServerSend, stream, request));
    env->DeleteLocalRef(request);
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream request handler threw"); }
    int32_t errID = rpccgoKotlinUnitResult(env, result);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoCollectRuntimeStateServerFinish(int32_t stream, uintptr_t* responsePtr, int32_t* responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoCollectRuntimeStateServerFinish == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoCollectRuntimeStateServerFinish, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream response handler threw"); }
    int32_t errID = rpccgoKotlinBytesResult(env, result, responsePtr, responseLen);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoCollectRuntimeStateServerCancel(int32_t stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoCollectRuntimeStateServerCancel == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoCollectRuntimeStateServerCancel, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream control handler threw"); }
    int32_t errID = rpccgoKotlinUnitResult(env, result);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateRegister invokes examples.flutter.sharedso.v1.SharedSoDemo.CollectRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateRegister(JNIEnv* env, jobject thiz) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    if (!ensureSharedSoDemoServerBridge(env, thiz)) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge registration failed"); }
    jclass bridgeClass = env->GetObjectClass(thiz);
    if (bridgeClass == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge class lookup failed"); }
    sharedSoDemoCollectRuntimeStateServerStart = env->GetMethodID(bridgeClass, "sharedSoDemoCollectRuntimeStateServerStart", "()[B");
    sharedSoDemoCollectRuntimeStateServerSend = env->GetMethodID(bridgeClass, "sharedSoDemoCollectRuntimeStateServerSend", "(I[B)[B");
    sharedSoDemoCollectRuntimeStateServerFinish = env->GetMethodID(bridgeClass, "sharedSoDemoCollectRuntimeStateServerFinish", "(I)[B");
    sharedSoDemoCollectRuntimeStateServerCancel = env->GetMethodID(bridgeClass, "sharedSoDemoCollectRuntimeStateServerCancel", "(I)[B");
    env->DeleteLocalRef(bridgeClass);
    if (env->ExceptionCheck()) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method lookup failed"); }
    if (sharedSoDemoCollectRuntimeStateServerStart == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoCollectRuntimeStateServerSend == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoCollectRuntimeStateServerFinish == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoCollectRuntimeStateServerCancel == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoRegisterCollectRuntimeState(onSharedSoDemoCollectRuntimeStateServerStart, onSharedSoDemoCollectRuntimeStateServerSend, onSharedSoDemoCollectRuntimeStateServerFinish, onSharedSoDemoCollectRuntimeStateServerCancel);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

std::mutex sharedSoDemoStreamRuntimeStateCallbackMu;
jobject sharedSoDemoStreamRuntimeStateCallbackListener = nullptr;
jmethodID sharedSoDemoStreamRuntimeStateCallbackOnRecv = nullptr;
jmethodID sharedSoDemoStreamRuntimeStateCallbackOnDone = nullptr;
int32_t sharedSoDemoStreamRuntimeStateCallbackHandle = 0;

void clearSharedSoDemoStreamRuntimeStateListenerCallback(JNIEnv* env) {
    std::lock_guard<std::mutex> lock(sharedSoDemoStreamRuntimeStateCallbackMu);
    if (env != nullptr && sharedSoDemoStreamRuntimeStateCallbackListener != nullptr) {
        env->DeleteGlobalRef(sharedSoDemoStreamRuntimeStateCallbackListener);
    }
    sharedSoDemoStreamRuntimeStateCallbackListener = nullptr;
    sharedSoDemoStreamRuntimeStateCallbackOnRecv = nullptr;
    sharedSoDemoStreamRuntimeStateCallbackOnDone = nullptr;
    sharedSoDemoStreamRuntimeStateCallbackHandle = 0;
}

bool cancelSharedSoDemoStreamRuntimeStateListenerCallback(JNIEnv* env) {
    int32_t handle = 0;
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoStreamRuntimeStateCallbackMu);
        handle = sharedSoDemoStreamRuntimeStateCallbackHandle;
    }
    if (handle == 0) {
        clearSharedSoDemoStreamRuntimeStateListenerCallback(env);
        return true;
    }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoStreamRuntimeStateCancel(handle);
    return errID == 0;
}

void onSharedSoDemoStreamRuntimeStateListenerRecv(int32_t, uintptr_t responsePtr, int32_t responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return;
    }
    std::lock_guard<std::mutex> lock(sharedSoDemoStreamRuntimeStateCallbackMu);
    if (sharedSoDemoStreamRuntimeStateCallbackListener == nullptr || sharedSoDemoStreamRuntimeStateCallbackOnRecv == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return;
    }
    jbyteArray payload = env->NewByteArray(responseLen);
    if (payload == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return;
    }
    if (responseLen > 0) {
        env->SetByteArrayRegion(payload, 0, responseLen, reinterpret_cast<const jbyte*>(responsePtr));
    }
    if (responsePtr != 0) { rpccgoRelease(responsePtr); }
    env->CallVoidMethod(sharedSoDemoStreamRuntimeStateCallbackListener, sharedSoDemoStreamRuntimeStateCallbackOnRecv, payload);
    env->DeleteLocalRef(payload);
    if (env->ExceptionCheck()) { env->ExceptionClear(); }
}

void onSharedSoDemoStreamRuntimeStateListenerDone(int32_t, int32_t errID) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return; }
    jobject listener = nullptr;
    jmethodID onDone = nullptr;
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoStreamRuntimeStateCallbackMu);
        listener = sharedSoDemoStreamRuntimeStateCallbackListener;
        onDone = sharedSoDemoStreamRuntimeStateCallbackOnDone;
    }
    if (listener != nullptr && onDone != nullptr) {
        jstring error = nullptr;
        if (errID != 0) {
            std::string text = rpccgoErrorString(errID);
            error = env->NewStringUTF(text.c_str());
        }
        env->CallVoidMethod(listener, onDone, error);
        if (error != nullptr) { env->DeleteLocalRef(error); }
        if (env->ExceptionCheck()) { env->ExceptionClear(); }
    }
    clearSharedSoDemoStreamRuntimeStateListenerCallback(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateStart invokes examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateStart(JNIEnv* env, jobject, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoStreamRuntimeStateStart(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &handle, nullptr, nullptr);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessHandle(env, handle);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateRecv invokes examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateRecv(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoStreamRuntimeStateRecv(static_cast<int32_t>(handle), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateCancel invokes examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateCancel(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoStreamRuntimeStateCancel(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateStartCallback invokes examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateStartCallback(JNIEnv* env, jobject, jbyteArray request, jobject listener) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return JNI_FALSE; }
    if (request == nullptr || listener == nullptr) { return JNI_FALSE; }
    cancelSharedSoDemoStreamRuntimeStateListenerCallback(env);
    jclass listenerClass = env->GetObjectClass(listener);
    jmethodID onRecv = env->GetMethodID(listenerClass, "onRecv", "([B)V");
    jmethodID onDone = env->GetMethodID(listenerClass, "onDone", "(Ljava/lang/String;)V");
    env->DeleteLocalRef(listenerClass);
    if (onRecv == nullptr || onDone == nullptr) { return JNI_FALSE; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return JNI_FALSE; }
    jobject globalListener = env->NewGlobalRef(listener);
    if (globalListener == nullptr) { return JNI_FALSE; }
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoStreamRuntimeStateCallbackMu);
        sharedSoDemoStreamRuntimeStateCallbackListener = globalListener;
        sharedSoDemoStreamRuntimeStateCallbackOnRecv = onRecv;
        sharedSoDemoStreamRuntimeStateCallbackOnDone = onDone;
    }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoStreamRuntimeStateStart(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &handle, onSharedSoDemoStreamRuntimeStateListenerRecv, onSharedSoDemoStreamRuntimeStateListenerDone);
    if (errID != 0) {
        clearSharedSoDemoStreamRuntimeStateListenerCallback(env);
        return JNI_FALSE;
    }
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoStreamRuntimeStateCallbackMu);
        sharedSoDemoStreamRuntimeStateCallbackHandle = handle;
    }
    return JNI_TRUE;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateCancelCallback invokes examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateCancelCallback(JNIEnv* env, jobject) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return JNI_FALSE; }
    return cancelSharedSoDemoStreamRuntimeStateListenerCallback(env) ? JNI_TRUE : JNI_FALSE;
}

int32_t onSharedSoDemoStreamRuntimeStateServerStart(uintptr_t requestPtr, int32_t requestLen, int32_t* stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoStreamRuntimeStateServerStart == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray request = nullptr;
    int32_t requestErr = rpccgoRequestByteArray(env, requestPtr, requestLen, &request);
    if (requestErr != 0) { return requestErr; }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoStreamRuntimeStateServerStart, request));
    env->DeleteLocalRef(request);
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream start threw"); }
    int32_t errID = rpccgoKotlinHandleResult(env, result, stream);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoStreamRuntimeStateServerRecv(int32_t stream, uintptr_t* responsePtr, int32_t* responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoStreamRuntimeStateServerRecv == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoStreamRuntimeStateServerRecv, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream response handler threw"); }
    int32_t errID = rpccgoKotlinBytesResult(env, result, responsePtr, responseLen);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoStreamRuntimeStateServerFinish(int32_t stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoStreamRuntimeStateServerFinish == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoStreamRuntimeStateServerFinish, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream control handler threw"); }
    int32_t errID = rpccgoKotlinUnitResult(env, result);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoStreamRuntimeStateServerCancel(int32_t stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoStreamRuntimeStateServerCancel == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoStreamRuntimeStateServerCancel, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream control handler threw"); }
    int32_t errID = rpccgoKotlinUnitResult(env, result);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateRegister invokes examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateRegister(JNIEnv* env, jobject thiz) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    if (!ensureSharedSoDemoServerBridge(env, thiz)) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge registration failed"); }
    jclass bridgeClass = env->GetObjectClass(thiz);
    if (bridgeClass == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge class lookup failed"); }
    sharedSoDemoStreamRuntimeStateServerStart = env->GetMethodID(bridgeClass, "sharedSoDemoStreamRuntimeStateServerStart", "([B)[B");
    sharedSoDemoStreamRuntimeStateServerRecv = env->GetMethodID(bridgeClass, "sharedSoDemoStreamRuntimeStateServerRecv", "(I)[B");
    sharedSoDemoStreamRuntimeStateServerFinish = env->GetMethodID(bridgeClass, "sharedSoDemoStreamRuntimeStateServerFinish", "(I)[B");
    sharedSoDemoStreamRuntimeStateServerCancel = env->GetMethodID(bridgeClass, "sharedSoDemoStreamRuntimeStateServerCancel", "(I)[B");
    env->DeleteLocalRef(bridgeClass);
    if (env->ExceptionCheck()) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method lookup failed"); }
    if (sharedSoDemoStreamRuntimeStateServerStart == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoStreamRuntimeStateServerRecv == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoStreamRuntimeStateServerFinish == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoStreamRuntimeStateServerCancel == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoRegisterStreamRuntimeState(onSharedSoDemoStreamRuntimeStateServerStart, onSharedSoDemoStreamRuntimeStateServerRecv, onSharedSoDemoStreamRuntimeStateServerFinish, onSharedSoDemoStreamRuntimeStateServerCancel);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

std::mutex sharedSoDemoChatRuntimeStateCallbackMu;
jobject sharedSoDemoChatRuntimeStateCallbackListener = nullptr;
jmethodID sharedSoDemoChatRuntimeStateCallbackOnRecv = nullptr;
jmethodID sharedSoDemoChatRuntimeStateCallbackOnDone = nullptr;
int32_t sharedSoDemoChatRuntimeStateCallbackHandle = 0;

void clearSharedSoDemoChatRuntimeStateListenerCallback(JNIEnv* env) {
    std::lock_guard<std::mutex> lock(sharedSoDemoChatRuntimeStateCallbackMu);
    if (env != nullptr && sharedSoDemoChatRuntimeStateCallbackListener != nullptr) {
        env->DeleteGlobalRef(sharedSoDemoChatRuntimeStateCallbackListener);
    }
    sharedSoDemoChatRuntimeStateCallbackListener = nullptr;
    sharedSoDemoChatRuntimeStateCallbackOnRecv = nullptr;
    sharedSoDemoChatRuntimeStateCallbackOnDone = nullptr;
    sharedSoDemoChatRuntimeStateCallbackHandle = 0;
}

bool cancelSharedSoDemoChatRuntimeStateListenerCallback(JNIEnv* env) {
    int32_t handle = 0;
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoChatRuntimeStateCallbackMu);
        handle = sharedSoDemoChatRuntimeStateCallbackHandle;
    }
    if (handle == 0) {
        clearSharedSoDemoChatRuntimeStateListenerCallback(env);
        return true;
    }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateCancel(handle);
    return errID == 0;
}

void onSharedSoDemoChatRuntimeStateListenerRecv(int32_t, uintptr_t responsePtr, int32_t responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return;
    }
    std::lock_guard<std::mutex> lock(sharedSoDemoChatRuntimeStateCallbackMu);
    if (sharedSoDemoChatRuntimeStateCallbackListener == nullptr || sharedSoDemoChatRuntimeStateCallbackOnRecv == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return;
    }
    jbyteArray payload = env->NewByteArray(responseLen);
    if (payload == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return;
    }
    if (responseLen > 0) {
        env->SetByteArrayRegion(payload, 0, responseLen, reinterpret_cast<const jbyte*>(responsePtr));
    }
    if (responsePtr != 0) { rpccgoRelease(responsePtr); }
    env->CallVoidMethod(sharedSoDemoChatRuntimeStateCallbackListener, sharedSoDemoChatRuntimeStateCallbackOnRecv, payload);
    env->DeleteLocalRef(payload);
    if (env->ExceptionCheck()) { env->ExceptionClear(); }
}

void onSharedSoDemoChatRuntimeStateListenerDone(int32_t, int32_t errID) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return; }
    jobject listener = nullptr;
    jmethodID onDone = nullptr;
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoChatRuntimeStateCallbackMu);
        listener = sharedSoDemoChatRuntimeStateCallbackListener;
        onDone = sharedSoDemoChatRuntimeStateCallbackOnDone;
    }
    if (listener != nullptr && onDone != nullptr) {
        jstring error = nullptr;
        if (errID != 0) {
            std::string text = rpccgoErrorString(errID);
            error = env->NewStringUTF(text.c_str());
        }
        env->CallVoidMethod(listener, onDone, error);
        if (error != nullptr) { env->DeleteLocalRef(error); }
        if (env->ExceptionCheck()) { env->ExceptionClear(); }
    }
    clearSharedSoDemoChatRuntimeStateListenerCallback(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateStart invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateStart(JNIEnv* env, jobject) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateStart(&handle, nullptr, nullptr);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessHandle(env, handle);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateSend invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateSend(JNIEnv* env, jobject, jint handle, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateSend(static_cast<int32_t>(handle), rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateRecv invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateRecv(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateRecv(static_cast<int32_t>(handle), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateCloseSend invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateCloseSend(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateCloseSend(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateFinish invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateFinish(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateFinish(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateCancel invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateCancel(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateCancel(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateStartCallback invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateStartCallback(JNIEnv* env, jobject, jobject listener) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return JNI_FALSE; }
    if (listener == nullptr) { return JNI_FALSE; }
    cancelSharedSoDemoChatRuntimeStateListenerCallback(env);
    jclass listenerClass = env->GetObjectClass(listener);
    jmethodID onRecv = env->GetMethodID(listenerClass, "onRecv", "([B)V");
    jmethodID onDone = env->GetMethodID(listenerClass, "onDone", "(Ljava/lang/String;)V");
    env->DeleteLocalRef(listenerClass);
    if (onRecv == nullptr || onDone == nullptr) { return JNI_FALSE; }
    jobject globalListener = env->NewGlobalRef(listener);
    if (globalListener == nullptr) { return JNI_FALSE; }
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoChatRuntimeStateCallbackMu);
        sharedSoDemoChatRuntimeStateCallbackListener = globalListener;
        sharedSoDemoChatRuntimeStateCallbackOnRecv = onRecv;
        sharedSoDemoChatRuntimeStateCallbackOnDone = onDone;
    }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateStart(&handle, onSharedSoDemoChatRuntimeStateListenerRecv, onSharedSoDemoChatRuntimeStateListenerDone);
    if (errID != 0) {
        clearSharedSoDemoChatRuntimeStateListenerCallback(env);
        return JNI_FALSE;
    }
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoChatRuntimeStateCallbackMu);
        sharedSoDemoChatRuntimeStateCallbackHandle = handle;
    }
    return JNI_TRUE;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateCancelCallback invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateCancelCallback(JNIEnv* env, jobject) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return JNI_FALSE; }
    return cancelSharedSoDemoChatRuntimeStateListenerCallback(env) ? JNI_TRUE : JNI_FALSE;
}

int32_t onSharedSoDemoChatRuntimeStateServerStart(int32_t* stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoChatRuntimeStateServerStart == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoChatRuntimeStateServerStart));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream start threw"); }
    int32_t errID = rpccgoKotlinHandleResult(env, result, stream);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoChatRuntimeStateServerSend(int32_t stream, uintptr_t requestPtr, int32_t requestLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoChatRuntimeStateServerSend == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray request = nullptr;
    int32_t requestErr = rpccgoRequestByteArray(env, requestPtr, requestLen, &request);
    if (requestErr != 0) { return requestErr; }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoChatRuntimeStateServerSend, stream, request));
    env->DeleteLocalRef(request);
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream request handler threw"); }
    int32_t errID = rpccgoKotlinUnitResult(env, result);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoChatRuntimeStateServerRecv(int32_t stream, uintptr_t* responsePtr, int32_t* responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoChatRuntimeStateServerRecv == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoChatRuntimeStateServerRecv, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream response handler threw"); }
    int32_t errID = rpccgoKotlinBytesResult(env, result, responsePtr, responseLen);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoChatRuntimeStateServerCloseSend(int32_t stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoChatRuntimeStateServerCloseSend == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoChatRuntimeStateServerCloseSend, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream control handler threw"); }
    int32_t errID = rpccgoKotlinUnitResult(env, result);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoChatRuntimeStateServerFinish(int32_t stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoChatRuntimeStateServerFinish == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoChatRuntimeStateServerFinish, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream control handler threw"); }
    int32_t errID = rpccgoKotlinUnitResult(env, result);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onSharedSoDemoChatRuntimeStateServerCancel(int32_t stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = sharedSoDemoServerBridgeObject();
    if (bridge == nullptr || sharedSoDemoChatRuntimeStateServerCancel == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, sharedSoDemoChatRuntimeStateServerCancel, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream control handler threw"); }
    int32_t errID = rpccgoKotlinUnitResult(env, result);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateRegister invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateRegister(JNIEnv* env, jobject thiz) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    if (!ensureSharedSoDemoServerBridge(env, thiz)) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge registration failed"); }
    jclass bridgeClass = env->GetObjectClass(thiz);
    if (bridgeClass == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge class lookup failed"); }
    sharedSoDemoChatRuntimeStateServerStart = env->GetMethodID(bridgeClass, "sharedSoDemoChatRuntimeStateServerStart", "()[B");
    sharedSoDemoChatRuntimeStateServerSend = env->GetMethodID(bridgeClass, "sharedSoDemoChatRuntimeStateServerSend", "(I[B)[B");
    sharedSoDemoChatRuntimeStateServerRecv = env->GetMethodID(bridgeClass, "sharedSoDemoChatRuntimeStateServerRecv", "(I)[B");
    sharedSoDemoChatRuntimeStateServerCloseSend = env->GetMethodID(bridgeClass, "sharedSoDemoChatRuntimeStateServerCloseSend", "(I)[B");
    sharedSoDemoChatRuntimeStateServerFinish = env->GetMethodID(bridgeClass, "sharedSoDemoChatRuntimeStateServerFinish", "(I)[B");
    sharedSoDemoChatRuntimeStateServerCancel = env->GetMethodID(bridgeClass, "sharedSoDemoChatRuntimeStateServerCancel", "(I)[B");
    env->DeleteLocalRef(bridgeClass);
    if (env->ExceptionCheck()) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method lookup failed"); }
    if (sharedSoDemoChatRuntimeStateServerStart == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoChatRuntimeStateServerSend == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoChatRuntimeStateServerRecv == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoChatRuntimeStateServerCloseSend == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoChatRuntimeStateServerFinish == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (sharedSoDemoChatRuntimeStateServerCancel == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoRegisterChatRuntimeState(onSharedSoDemoChatRuntimeStateServerStart, onSharedSoDemoChatRuntimeStateServerSend, onSharedSoDemoChatRuntimeStateServerRecv, onSharedSoDemoChatRuntimeStateServerCloseSend, onSharedSoDemoChatRuntimeStateServerFinish, onSharedSoDemoChatRuntimeStateServerCancel);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}
