// Code generated by protoc-gen-rpc-cgo-jni. DO NOT EDIT.
//
// Source: shared_so.proto

#include <mutex>

#include "rpccgo.jni.h"

std::mutex flutterDeviceServerBridgeMu;
jobject flutterDeviceServerBridge = nullptr;
jmethodID flutterDeviceDescribeFlutterServerHandle = nullptr;
jmethodID flutterDeviceWatchFlutterEchoServerStart = nullptr;
jmethodID flutterDeviceWatchFlutterEchoServerRecv = nullptr;
jmethodID flutterDeviceWatchFlutterEchoServerFinish = nullptr;
jmethodID flutterDeviceWatchFlutterEchoServerCancel = nullptr;

bool ensureFlutterDeviceServerBridge(JNIEnv* env, jobject thiz) {
    if (env == nullptr || thiz == nullptr) { return false; }
    std::lock_guard<std::mutex> lock(flutterDeviceServerBridgeMu);
    if (flutterDeviceServerBridge == nullptr) {
        flutterDeviceServerBridge = env->NewGlobalRef(thiz);
    }
    return flutterDeviceServerBridge != nullptr;
}

jobject flutterDeviceServerBridgeObject() {
    std::lock_guard<std::mutex> lock(flutterDeviceServerBridgeMu);
    return flutterDeviceServerBridge;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceDescribeFlutter invokes examples.flutter.sharedso.v1.FlutterDevice.DescribeFlutter through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceDescribeFlutter(JNIEnv* env, jobject, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1FlutterDeviceDescribeFlutter(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

int32_t onFlutterDeviceDescribeFlutterServerHandle(uintptr_t requestPtr, int32_t requestLen, uintptr_t* responsePtr, int32_t* responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = flutterDeviceServerBridgeObject();
    if (bridge == nullptr || flutterDeviceDescribeFlutterServerHandle == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray request = nullptr;
    int32_t requestErr = rpccgoRequestByteArray(env, requestPtr, requestLen, &request);
    if (requestErr != 0) { return requestErr; }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, flutterDeviceDescribeFlutterServerHandle, request));
    env->DeleteLocalRef(request);
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server unary handler threw"); }
    int32_t errID = rpccgoKotlinBytesResult(env, result, responsePtr, responseLen);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceDescribeFlutterRegister invokes examples.flutter.sharedso.v1.FlutterDevice.DescribeFlutter through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceDescribeFlutterRegister(JNIEnv* env, jobject thiz) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    if (!ensureFlutterDeviceServerBridge(env, thiz)) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge registration failed"); }
    jclass bridgeClass = env->GetObjectClass(thiz);
    if (bridgeClass == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge class lookup failed"); }
    flutterDeviceDescribeFlutterServerHandle = env->GetMethodID(bridgeClass, "flutterDeviceDescribeFlutterHandle", "([B)[B");
    env->DeleteLocalRef(bridgeClass);
    if (env->ExceptionCheck()) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method lookup failed"); }
    if (flutterDeviceDescribeFlutterServerHandle == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    int32_t errID = rpccgoMsgFluttersharedv1FlutterDeviceRegisterDescribeFlutter(onFlutterDeviceDescribeFlutterServerHandle);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

std::mutex flutterDeviceWatchFlutterEchoCallbackMu;
jobject flutterDeviceWatchFlutterEchoCallbackListener = nullptr;
jmethodID flutterDeviceWatchFlutterEchoCallbackOnRecv = nullptr;
jmethodID flutterDeviceWatchFlutterEchoCallbackOnDone = nullptr;
int32_t flutterDeviceWatchFlutterEchoCallbackHandle = 0;

void clearFlutterDeviceWatchFlutterEchoListenerCallback(JNIEnv* env) {
    std::lock_guard<std::mutex> lock(flutterDeviceWatchFlutterEchoCallbackMu);
    if (env != nullptr && flutterDeviceWatchFlutterEchoCallbackListener != nullptr) {
        env->DeleteGlobalRef(flutterDeviceWatchFlutterEchoCallbackListener);
    }
    flutterDeviceWatchFlutterEchoCallbackListener = nullptr;
    flutterDeviceWatchFlutterEchoCallbackOnRecv = nullptr;
    flutterDeviceWatchFlutterEchoCallbackOnDone = nullptr;
    flutterDeviceWatchFlutterEchoCallbackHandle = 0;
}

bool cancelFlutterDeviceWatchFlutterEchoListenerCallback(JNIEnv* env) {
    int32_t handle = 0;
    {
        std::lock_guard<std::mutex> lock(flutterDeviceWatchFlutterEchoCallbackMu);
        handle = flutterDeviceWatchFlutterEchoCallbackHandle;
    }
    if (handle == 0) {
        clearFlutterDeviceWatchFlutterEchoListenerCallback(env);
        return true;
    }
    int32_t errID = rpccgoMsgFluttersharedv1FlutterDeviceWatchFlutterEchoCancel(handle);
    return errID == 0;
}

void onFlutterDeviceWatchFlutterEchoListenerRecv(int32_t, uintptr_t responsePtr, int32_t responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return;
    }
    std::lock_guard<std::mutex> lock(flutterDeviceWatchFlutterEchoCallbackMu);
    if (flutterDeviceWatchFlutterEchoCallbackListener == nullptr || flutterDeviceWatchFlutterEchoCallbackOnRecv == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return;
    }
    jbyteArray payload = env->NewByteArray(responseLen);
    if (payload == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return;
    }
    if (responseLen > 0) {
        env->SetByteArrayRegion(payload, 0, responseLen, reinterpret_cast<const jbyte*>(responsePtr));
    }
    if (responsePtr != 0) { rpccgoRelease(responsePtr); }
    env->CallVoidMethod(flutterDeviceWatchFlutterEchoCallbackListener, flutterDeviceWatchFlutterEchoCallbackOnRecv, payload);
    env->DeleteLocalRef(payload);
    if (env->ExceptionCheck()) { env->ExceptionClear(); }
}

void onFlutterDeviceWatchFlutterEchoListenerDone(int32_t, int32_t errID) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return; }
    jobject listener = nullptr;
    jmethodID onDone = nullptr;
    {
        std::lock_guard<std::mutex> lock(flutterDeviceWatchFlutterEchoCallbackMu);
        listener = flutterDeviceWatchFlutterEchoCallbackListener;
        onDone = flutterDeviceWatchFlutterEchoCallbackOnDone;
    }
    if (listener != nullptr && onDone != nullptr) {
        jstring error = nullptr;
        if (errID != 0) {
            std::string text = rpccgoErrorString(errID);
            error = env->NewStringUTF(text.c_str());
        }
        env->CallVoidMethod(listener, onDone, error);
        if (error != nullptr) { env->DeleteLocalRef(error); }
        if (env->ExceptionCheck()) { env->ExceptionClear(); }
    }
    clearFlutterDeviceWatchFlutterEchoListenerCallback(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceWatchFlutterEchoStart invokes examples.flutter.sharedso.v1.FlutterDevice.WatchFlutterEcho through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceWatchFlutterEchoStart(JNIEnv* env, jobject, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1FlutterDeviceWatchFlutterEchoStart(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &handle, nullptr, nullptr);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessHandle(env, handle);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceWatchFlutterEchoRecv invokes examples.flutter.sharedso.v1.FlutterDevice.WatchFlutterEcho through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceWatchFlutterEchoRecv(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1FlutterDeviceWatchFlutterEchoRecv(static_cast<int32_t>(handle), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceWatchFlutterEchoCancel invokes examples.flutter.sharedso.v1.FlutterDevice.WatchFlutterEcho through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceWatchFlutterEchoCancel(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1FlutterDeviceWatchFlutterEchoCancel(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceWatchFlutterEchoStartCallback invokes examples.flutter.sharedso.v1.FlutterDevice.WatchFlutterEcho through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceWatchFlutterEchoStartCallback(JNIEnv* env, jobject, jbyteArray request, jobject listener) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return JNI_FALSE; }
    if (request == nullptr || listener == nullptr) { return JNI_FALSE; }
    cancelFlutterDeviceWatchFlutterEchoListenerCallback(env);
    jclass listenerClass = env->GetObjectClass(listener);
    jmethodID onRecv = env->GetMethodID(listenerClass, "onRecv", "([B)V");
    jmethodID onDone = env->GetMethodID(listenerClass, "onDone", "(Ljava/lang/String;)V");
    env->DeleteLocalRef(listenerClass);
    if (onRecv == nullptr || onDone == nullptr) { return JNI_FALSE; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return JNI_FALSE; }
    jobject globalListener = env->NewGlobalRef(listener);
    if (globalListener == nullptr) { return JNI_FALSE; }
    {
        std::lock_guard<std::mutex> lock(flutterDeviceWatchFlutterEchoCallbackMu);
        flutterDeviceWatchFlutterEchoCallbackListener = globalListener;
        flutterDeviceWatchFlutterEchoCallbackOnRecv = onRecv;
        flutterDeviceWatchFlutterEchoCallbackOnDone = onDone;
    }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1FlutterDeviceWatchFlutterEchoStart(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &handle, onFlutterDeviceWatchFlutterEchoListenerRecv, onFlutterDeviceWatchFlutterEchoListenerDone);
    if (errID != 0) {
        clearFlutterDeviceWatchFlutterEchoListenerCallback(env);
        return JNI_FALSE;
    }
    {
        std::lock_guard<std::mutex> lock(flutterDeviceWatchFlutterEchoCallbackMu);
        flutterDeviceWatchFlutterEchoCallbackHandle = handle;
    }
    return JNI_TRUE;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceWatchFlutterEchoCancelCallback invokes examples.flutter.sharedso.v1.FlutterDevice.WatchFlutterEcho through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceWatchFlutterEchoCancelCallback(JNIEnv* env, jobject) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return JNI_FALSE; }
    return cancelFlutterDeviceWatchFlutterEchoListenerCallback(env) ? JNI_TRUE : JNI_FALSE;
}

int32_t onFlutterDeviceWatchFlutterEchoServerStart(uintptr_t requestPtr, int32_t requestLen, int32_t* stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = flutterDeviceServerBridgeObject();
    if (bridge == nullptr || flutterDeviceWatchFlutterEchoServerStart == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray request = nullptr;
    int32_t requestErr = rpccgoRequestByteArray(env, requestPtr, requestLen, &request);
    if (requestErr != 0) { return requestErr; }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, flutterDeviceWatchFlutterEchoServerStart, request));
    env->DeleteLocalRef(request);
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream start threw"); }
    int32_t errID = rpccgoKotlinHandleResult(env, result, stream);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onFlutterDeviceWatchFlutterEchoServerRecv(int32_t stream, uintptr_t* responsePtr, int32_t* responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = flutterDeviceServerBridgeObject();
    if (bridge == nullptr || flutterDeviceWatchFlutterEchoServerRecv == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, flutterDeviceWatchFlutterEchoServerRecv, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream response handler threw"); }
    int32_t errID = rpccgoKotlinBytesResult(env, result, responsePtr, responseLen);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onFlutterDeviceWatchFlutterEchoServerFinish(int32_t stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = flutterDeviceServerBridgeObject();
    if (bridge == nullptr || flutterDeviceWatchFlutterEchoServerFinish == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, flutterDeviceWatchFlutterEchoServerFinish, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream control handler threw"); }
    int32_t errID = rpccgoKotlinUnitResult(env, result);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

int32_t onFlutterDeviceWatchFlutterEchoServerCancel(int32_t stream) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return rpccgoStoreErrorString("rpccgo: JNI environment is unavailable"); }
    jobject bridge = flutterDeviceServerBridgeObject();
    if (bridge == nullptr || flutterDeviceWatchFlutterEchoServerCancel == nullptr) { return rpccgoStoreErrorString("rpccgo: Kotlin server bridge is not registered"); }
    jbyteArray result = static_cast<jbyteArray>(env->CallObjectMethod(bridge, flutterDeviceWatchFlutterEchoServerCancel, stream));
    if (env->ExceptionCheck()) { return rpccgoExceptionError(env, "rpccgo: Kotlin server stream control handler threw"); }
    int32_t errID = rpccgoKotlinUnitResult(env, result);
    if (result != nullptr) { env->DeleteLocalRef(result); }
    return errID;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceWatchFlutterEchoRegister invokes examples.flutter.sharedso.v1.FlutterDevice.WatchFlutterEcho through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_flutterDeviceWatchFlutterEchoRegister(JNIEnv* env, jobject thiz) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    if (!ensureFlutterDeviceServerBridge(env, thiz)) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge registration failed"); }
    jclass bridgeClass = env->GetObjectClass(thiz);
    if (bridgeClass == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge class lookup failed"); }
    flutterDeviceWatchFlutterEchoServerStart = env->GetMethodID(bridgeClass, "flutterDeviceWatchFlutterEchoServerStart", "([B)[B");
    flutterDeviceWatchFlutterEchoServerRecv = env->GetMethodID(bridgeClass, "flutterDeviceWatchFlutterEchoServerRecv", "(I)[B");
    flutterDeviceWatchFlutterEchoServerFinish = env->GetMethodID(bridgeClass, "flutterDeviceWatchFlutterEchoServerFinish", "(I)[B");
    flutterDeviceWatchFlutterEchoServerCancel = env->GetMethodID(bridgeClass, "flutterDeviceWatchFlutterEchoServerCancel", "(I)[B");
    env->DeleteLocalRef(bridgeClass);
    if (env->ExceptionCheck()) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method lookup failed"); }
    if (flutterDeviceWatchFlutterEchoServerStart == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (flutterDeviceWatchFlutterEchoServerRecv == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (flutterDeviceWatchFlutterEchoServerFinish == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    if (flutterDeviceWatchFlutterEchoServerCancel == nullptr) { return rpccgoErrorResult(env, "rpccgo: JNI server bridge method is missing"); }
    int32_t errID = rpccgoMsgFluttersharedv1FlutterDeviceRegisterWatchFlutterEcho(onFlutterDeviceWatchFlutterEchoServerStart, onFlutterDeviceWatchFlutterEchoServerRecv, onFlutterDeviceWatchFlutterEchoServerFinish, onFlutterDeviceWatchFlutterEchoServerCancel);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}
