// Code generated by protoc-gen-rpc-cgo-jni. DO NOT EDIT.
//
// Source: shared_so.proto

#include <jni.h>
#include <stdint.h>
#include <stdlib.h>

#include <mutex>
#include <string>
#include <vector>

#include "librpccgo_flutter_shared.h"

JavaVM* javaVM = nullptr;

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
    javaVM = vm;
    // Android supports JNI 1.6; the JavaVM is also used to resolve JNIEnv on stream operation threads.
    return JNI_VERSION_1_6;
}

JNIEXPORT void JNICALL JNI_OnUnload(JavaVM*, void*) {
    javaVM = nullptr;
}

namespace {

class rpccgoJNIEnvScope {
public:
    explicit rpccgoJNIEnvScope(JNIEnv* current) : env(current), attached(false) {
        if (env != nullptr || javaVM == nullptr) { return; }
        void* rawEnv = nullptr;
        jint status = javaVM->GetEnv(&rawEnv, JNI_VERSION_1_6);
        if (status == JNI_OK) {
            env = static_cast<JNIEnv*>(rawEnv);
            return;
        }
        JNIEnv* attachedEnv = nullptr;
        if (status == JNI_EDETACHED && javaVM->AttachCurrentThread(&attachedEnv, nullptr) == JNI_OK) {
            env = attachedEnv;
            attached = true;
        }
    }
    ~rpccgoJNIEnvScope() {
        if (attached && javaVM != nullptr) { javaVM->DetachCurrentThread(); }
    }
    JNIEnv* env;

private:
    bool attached;
};

jbyteArray rpccgoJNIByteArray(JNIEnv* env, const std::vector<uint8_t>& data) {
    if (env == nullptr) { return nullptr; }
    jbyteArray array = env->NewByteArray(static_cast<jsize>(data.size()));
    if (array == nullptr) { return nullptr; }
    if (!data.empty()) {
        env->SetByteArrayRegion(array, 0, static_cast<jsize>(data.size()), reinterpret_cast<const jbyte*>(data.data()));
    }
    return array;
}

std::vector<uint8_t> rpccgoJNIBytes(JNIEnv* env, jbyteArray value, bool* ok) {
    if (ok != nullptr) { *ok = false; }
    if (env == nullptr || value == nullptr) { return {}; }
    jsize length = env->GetArrayLength(value);
    if (length < 0) { return {}; }
    std::vector<uint8_t> data(static_cast<size_t>(length));
    if (length != 0) {
        env->GetByteArrayRegion(value, 0, length, reinterpret_cast<jbyte*>(data.data()));
    }
    if (ok != nullptr) { *ok = !env->ExceptionCheck(); }
    return data;
}

void rpccgoWriteInt32(std::vector<uint8_t>* out, int32_t value) {
    out->push_back(static_cast<uint8_t>((value >> 24) & 0xff));
    out->push_back(static_cast<uint8_t>((value >> 16) & 0xff));
    out->push_back(static_cast<uint8_t>((value >> 8) & 0xff));
    out->push_back(static_cast<uint8_t>(value & 0xff));
}

jbyteArray rpccgoResult(JNIEnv* env, bool ok, const std::vector<uint8_t>& payload) {
    std::vector<uint8_t> out;
    out.reserve(payload.size() + 5);
    out.push_back(ok ? 1 : 0);
    rpccgoWriteInt32(&out, static_cast<int32_t>(payload.size()));
    out.insert(out.end(), payload.begin(), payload.end());
    return rpccgoJNIByteArray(env, out);
}

std::vector<uint8_t> rpccgoErrorText(int32_t errID) {
    uintptr_t textPtr = 0;
    int32_t textLen = 0;
    int32_t status = rpccgoTakeErrorText(errID, &textPtr, &textLen);
    if (status != 0 || textLen < 0 || textPtr == 0) {
        std::string fallback = "rpccgo: unknown error id " + std::to_string(errID);
        return std::vector<uint8_t>(fallback.begin(), fallback.end());
    }
    const uint8_t* data = reinterpret_cast<const uint8_t*>(textPtr);
    std::vector<uint8_t> text(data, data + textLen);
    rpccgoRelease(textPtr);
    return text;
}

jbyteArray rpccgoErrorResult(JNIEnv* env, const std::string& message) {
    return rpccgoResult(env, false, std::vector<uint8_t>(message.begin(), message.end()));
}

jbyteArray rpccgoErrorIDResult(JNIEnv* env, int32_t errID) {
    return rpccgoResult(env, false, rpccgoErrorText(errID));
}

jbyteArray rpccgoSuccessBytes(JNIEnv* env, uintptr_t responsePtr, int32_t responseLen) {
    if (responseLen < 0) { return rpccgoErrorResult(env, "rpccgo: response length is negative"); }
    if (responsePtr == 0 && responseLen != 0) { return rpccgoErrorResult(env, "rpccgo: response pointer is null"); }
    const uint8_t* data = reinterpret_cast<const uint8_t*>(responsePtr);
    std::vector<uint8_t> payload;
    if (responseLen != 0) { payload.assign(data, data + responseLen); }
    if (responsePtr != 0) { rpccgoRelease(responsePtr); }
    return rpccgoResult(env, true, payload);
}

jbyteArray rpccgoSuccessHandle(JNIEnv* env, int32_t handle) {
    std::vector<uint8_t> payload;
    rpccgoWriteInt32(&payload, handle);
    return rpccgoResult(env, true, payload);
}

jbyteArray rpccgoSuccessUnit(JNIEnv* env) {
    return rpccgoResult(env, true, {});
}

uintptr_t rpccgoVectorPtr(const std::vector<uint8_t>& data) {
    if (data.empty()) { return 0; }
    return reinterpret_cast<uintptr_t>(data.data());
}

std::string rpccgoErrorString(int32_t errID) {
    std::vector<uint8_t> text = rpccgoErrorText(errID);
    return std::string(text.begin(), text.end());
}

}  // namespace

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoComposeGreeting invokes examples.flutter.sharedso.v1.SharedSoDemo.ComposeGreeting through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoComposeGreeting(JNIEnv* env, jobject, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoComposeGreeting(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoIncrementRuntimeState invokes examples.flutter.sharedso.v1.SharedSoDemo.IncrementRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoIncrementRuntimeState(JNIEnv* env, jobject, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoIncrementRuntimeState(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoReadRuntimeState invokes examples.flutter.sharedso.v1.SharedSoDemo.ReadRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoReadRuntimeState(JNIEnv* env, jobject, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoReadRuntimeState(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

std::mutex sharedSoDemoWatchRuntimeStateCallbackMu;
jobject sharedSoDemoWatchRuntimeStateCallbackListener = nullptr;
jmethodID sharedSoDemoWatchRuntimeStateCallbackOnMessage = nullptr;
jmethodID sharedSoDemoWatchRuntimeStateCallbackOnDone = nullptr;
int32_t sharedSoDemoWatchRuntimeStateCallbackHandle = 0;

void clearSharedSoDemoWatchRuntimeStateListenerCallback(JNIEnv* env) {
    std::lock_guard<std::mutex> lock(sharedSoDemoWatchRuntimeStateCallbackMu);
    if (env != nullptr && sharedSoDemoWatchRuntimeStateCallbackListener != nullptr) {
        env->DeleteGlobalRef(sharedSoDemoWatchRuntimeStateCallbackListener);
    }
    sharedSoDemoWatchRuntimeStateCallbackListener = nullptr;
    sharedSoDemoWatchRuntimeStateCallbackOnMessage = nullptr;
    sharedSoDemoWatchRuntimeStateCallbackOnDone = nullptr;
    sharedSoDemoWatchRuntimeStateCallbackHandle = 0;
}

bool cancelSharedSoDemoWatchRuntimeStateListenerCallback(JNIEnv* env) {
    int32_t handle = 0;
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoWatchRuntimeStateCallbackMu);
        handle = sharedSoDemoWatchRuntimeStateCallbackHandle;
    }
    if (handle == 0) {
        clearSharedSoDemoWatchRuntimeStateListenerCallback(env);
        return true;
    }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoWatchRuntimeStateCancel(handle);
    clearSharedSoDemoWatchRuntimeStateListenerCallback(env);
    return errID == 0;
}

int32_t onSharedSoDemoWatchRuntimeStateListenerMessage(int32_t, uintptr_t responsePtr, int32_t responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return 0;
    }
    std::lock_guard<std::mutex> lock(sharedSoDemoWatchRuntimeStateCallbackMu);
    if (sharedSoDemoWatchRuntimeStateCallbackListener == nullptr || sharedSoDemoWatchRuntimeStateCallbackOnMessage == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return 0;
    }
    jbyteArray payload = env->NewByteArray(responseLen);
    if (payload == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return 0;
    }
    if (responseLen > 0) {
        env->SetByteArrayRegion(payload, 0, responseLen, reinterpret_cast<const jbyte*>(responsePtr));
    }
    if (responsePtr != 0) { rpccgoRelease(responsePtr); }
    env->CallVoidMethod(sharedSoDemoWatchRuntimeStateCallbackListener, sharedSoDemoWatchRuntimeStateCallbackOnMessage, payload);
    env->DeleteLocalRef(payload);
    if (env->ExceptionCheck()) { env->ExceptionClear(); }
    return 0;
}

int32_t onSharedSoDemoWatchRuntimeStateListenerDone(int32_t, int32_t errID) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return 0; }
    jobject listener = nullptr;
    jmethodID onDone = nullptr;
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoWatchRuntimeStateCallbackMu);
        listener = sharedSoDemoWatchRuntimeStateCallbackListener;
        onDone = sharedSoDemoWatchRuntimeStateCallbackOnDone;
    }
    if (listener != nullptr && onDone != nullptr) {
        jstring error = nullptr;
        if (errID != 0) {
            std::string text = rpccgoErrorString(errID);
            error = env->NewStringUTF(text.c_str());
        }
        env->CallVoidMethod(listener, onDone, error);
        if (error != nullptr) { env->DeleteLocalRef(error); }
        if (env->ExceptionCheck()) { env->ExceptionClear(); }
    }
    clearSharedSoDemoWatchRuntimeStateListenerCallback(env);
    return 0;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateStart invokes examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateStart(JNIEnv* env, jobject, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoWatchRuntimeStateStart(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &handle, nullptr, nullptr);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessHandle(env, handle);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateRecv invokes examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateRecv(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoWatchRuntimeStateRecv(static_cast<int32_t>(handle), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateCancel invokes examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateCancel(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoWatchRuntimeStateCancel(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateStartCallback invokes examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateStartCallback(JNIEnv* env, jobject, jbyteArray request, jobject listener) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    if (request == nullptr || listener == nullptr) { return JNI_FALSE; }
    cancelSharedSoDemoWatchRuntimeStateListenerCallback(env);
    jclass listenerClass = env->GetObjectClass(listener);
    jmethodID onMessage = env->GetMethodID(listenerClass, "onMessage", "([B)V");
    jmethodID onDone = env->GetMethodID(listenerClass, "onDone", "(Ljava/lang/String;)V");
    env->DeleteLocalRef(listenerClass);
    if (onMessage == nullptr || onDone == nullptr) { return JNI_FALSE; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    jobject globalListener = env->NewGlobalRef(listener);
    if (globalListener == nullptr) { return JNI_FALSE; }
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoWatchRuntimeStateCallbackMu);
        sharedSoDemoWatchRuntimeStateCallbackListener = globalListener;
        sharedSoDemoWatchRuntimeStateCallbackOnMessage = onMessage;
        sharedSoDemoWatchRuntimeStateCallbackOnDone = onDone;
    }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoWatchRuntimeStateStart(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &handle, onSharedSoDemoWatchRuntimeStateListenerMessage, onSharedSoDemoWatchRuntimeStateListenerDone);
    if (errID != 0) {
        clearSharedSoDemoWatchRuntimeStateListenerCallback(env);
        return JNI_FALSE;
    }
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoWatchRuntimeStateCallbackMu);
        sharedSoDemoWatchRuntimeStateCallbackHandle = handle;
    }
    return JNI_TRUE;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateCancelCallback invokes examples.flutter.sharedso.v1.SharedSoDemo.WatchRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoWatchRuntimeStateCancelCallback(JNIEnv* env, jobject) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    return cancelSharedSoDemoWatchRuntimeStateListenerCallback(env) ? JNI_TRUE : JNI_FALSE;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateStart invokes examples.flutter.sharedso.v1.SharedSoDemo.CollectRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateStart(JNIEnv* env, jobject) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoCollectRuntimeStateStart(&handle);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessHandle(env, handle);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateSend invokes examples.flutter.sharedso.v1.SharedSoDemo.CollectRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateSend(JNIEnv* env, jobject, jint handle, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoCollectRuntimeStateSend(static_cast<int32_t>(handle), rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateFinish invokes examples.flutter.sharedso.v1.SharedSoDemo.CollectRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateFinish(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoCollectRuntimeStateFinish(static_cast<int32_t>(handle), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateCancel invokes examples.flutter.sharedso.v1.SharedSoDemo.CollectRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoCollectRuntimeStateCancel(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoCollectRuntimeStateCancel(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

std::mutex sharedSoDemoStreamRuntimeStateCallbackMu;
jobject sharedSoDemoStreamRuntimeStateCallbackListener = nullptr;
jmethodID sharedSoDemoStreamRuntimeStateCallbackOnMessage = nullptr;
jmethodID sharedSoDemoStreamRuntimeStateCallbackOnDone = nullptr;
int32_t sharedSoDemoStreamRuntimeStateCallbackHandle = 0;

void clearSharedSoDemoStreamRuntimeStateListenerCallback(JNIEnv* env) {
    std::lock_guard<std::mutex> lock(sharedSoDemoStreamRuntimeStateCallbackMu);
    if (env != nullptr && sharedSoDemoStreamRuntimeStateCallbackListener != nullptr) {
        env->DeleteGlobalRef(sharedSoDemoStreamRuntimeStateCallbackListener);
    }
    sharedSoDemoStreamRuntimeStateCallbackListener = nullptr;
    sharedSoDemoStreamRuntimeStateCallbackOnMessage = nullptr;
    sharedSoDemoStreamRuntimeStateCallbackOnDone = nullptr;
    sharedSoDemoStreamRuntimeStateCallbackHandle = 0;
}

bool cancelSharedSoDemoStreamRuntimeStateListenerCallback(JNIEnv* env) {
    int32_t handle = 0;
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoStreamRuntimeStateCallbackMu);
        handle = sharedSoDemoStreamRuntimeStateCallbackHandle;
    }
    if (handle == 0) {
        clearSharedSoDemoStreamRuntimeStateListenerCallback(env);
        return true;
    }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoStreamRuntimeStateCancel(handle);
    clearSharedSoDemoStreamRuntimeStateListenerCallback(env);
    return errID == 0;
}

int32_t onSharedSoDemoStreamRuntimeStateListenerMessage(int32_t, uintptr_t responsePtr, int32_t responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return 0;
    }
    std::lock_guard<std::mutex> lock(sharedSoDemoStreamRuntimeStateCallbackMu);
    if (sharedSoDemoStreamRuntimeStateCallbackListener == nullptr || sharedSoDemoStreamRuntimeStateCallbackOnMessage == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return 0;
    }
    jbyteArray payload = env->NewByteArray(responseLen);
    if (payload == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return 0;
    }
    if (responseLen > 0) {
        env->SetByteArrayRegion(payload, 0, responseLen, reinterpret_cast<const jbyte*>(responsePtr));
    }
    if (responsePtr != 0) { rpccgoRelease(responsePtr); }
    env->CallVoidMethod(sharedSoDemoStreamRuntimeStateCallbackListener, sharedSoDemoStreamRuntimeStateCallbackOnMessage, payload);
    env->DeleteLocalRef(payload);
    if (env->ExceptionCheck()) { env->ExceptionClear(); }
    return 0;
}

int32_t onSharedSoDemoStreamRuntimeStateListenerDone(int32_t, int32_t errID) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return 0; }
    jobject listener = nullptr;
    jmethodID onDone = nullptr;
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoStreamRuntimeStateCallbackMu);
        listener = sharedSoDemoStreamRuntimeStateCallbackListener;
        onDone = sharedSoDemoStreamRuntimeStateCallbackOnDone;
    }
    if (listener != nullptr && onDone != nullptr) {
        jstring error = nullptr;
        if (errID != 0) {
            std::string text = rpccgoErrorString(errID);
            error = env->NewStringUTF(text.c_str());
        }
        env->CallVoidMethod(listener, onDone, error);
        if (error != nullptr) { env->DeleteLocalRef(error); }
        if (env->ExceptionCheck()) { env->ExceptionClear(); }
    }
    clearSharedSoDemoStreamRuntimeStateListenerCallback(env);
    return 0;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateStart invokes examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateStart(JNIEnv* env, jobject, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoStreamRuntimeStateStart(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &handle, nullptr, nullptr);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessHandle(env, handle);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateRecv invokes examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateRecv(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoStreamRuntimeStateRecv(static_cast<int32_t>(handle), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateCancel invokes examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateCancel(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoStreamRuntimeStateCancel(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateStartCallback invokes examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateStartCallback(JNIEnv* env, jobject, jbyteArray request, jobject listener) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    if (request == nullptr || listener == nullptr) { return JNI_FALSE; }
    cancelSharedSoDemoStreamRuntimeStateListenerCallback(env);
    jclass listenerClass = env->GetObjectClass(listener);
    jmethodID onMessage = env->GetMethodID(listenerClass, "onMessage", "([B)V");
    jmethodID onDone = env->GetMethodID(listenerClass, "onDone", "(Ljava/lang/String;)V");
    env->DeleteLocalRef(listenerClass);
    if (onMessage == nullptr || onDone == nullptr) { return JNI_FALSE; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    jobject globalListener = env->NewGlobalRef(listener);
    if (globalListener == nullptr) { return JNI_FALSE; }
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoStreamRuntimeStateCallbackMu);
        sharedSoDemoStreamRuntimeStateCallbackListener = globalListener;
        sharedSoDemoStreamRuntimeStateCallbackOnMessage = onMessage;
        sharedSoDemoStreamRuntimeStateCallbackOnDone = onDone;
    }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoStreamRuntimeStateStart(rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()), &handle, onSharedSoDemoStreamRuntimeStateListenerMessage, onSharedSoDemoStreamRuntimeStateListenerDone);
    if (errID != 0) {
        clearSharedSoDemoStreamRuntimeStateListenerCallback(env);
        return JNI_FALSE;
    }
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoStreamRuntimeStateCallbackMu);
        sharedSoDemoStreamRuntimeStateCallbackHandle = handle;
    }
    return JNI_TRUE;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateCancelCallback invokes examples.flutter.sharedso.v1.SharedSoDemo.StreamRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoStreamRuntimeStateCancelCallback(JNIEnv* env, jobject) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    return cancelSharedSoDemoStreamRuntimeStateListenerCallback(env) ? JNI_TRUE : JNI_FALSE;
}

std::mutex sharedSoDemoChatRuntimeStateCallbackMu;
jobject sharedSoDemoChatRuntimeStateCallbackListener = nullptr;
jmethodID sharedSoDemoChatRuntimeStateCallbackOnMessage = nullptr;
jmethodID sharedSoDemoChatRuntimeStateCallbackOnDone = nullptr;
int32_t sharedSoDemoChatRuntimeStateCallbackHandle = 0;

void clearSharedSoDemoChatRuntimeStateListenerCallback(JNIEnv* env) {
    std::lock_guard<std::mutex> lock(sharedSoDemoChatRuntimeStateCallbackMu);
    if (env != nullptr && sharedSoDemoChatRuntimeStateCallbackListener != nullptr) {
        env->DeleteGlobalRef(sharedSoDemoChatRuntimeStateCallbackListener);
    }
    sharedSoDemoChatRuntimeStateCallbackListener = nullptr;
    sharedSoDemoChatRuntimeStateCallbackOnMessage = nullptr;
    sharedSoDemoChatRuntimeStateCallbackOnDone = nullptr;
    sharedSoDemoChatRuntimeStateCallbackHandle = 0;
}

bool cancelSharedSoDemoChatRuntimeStateListenerCallback(JNIEnv* env) {
    int32_t handle = 0;
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoChatRuntimeStateCallbackMu);
        handle = sharedSoDemoChatRuntimeStateCallbackHandle;
    }
    if (handle == 0) {
        clearSharedSoDemoChatRuntimeStateListenerCallback(env);
        return true;
    }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateCancel(handle);
    clearSharedSoDemoChatRuntimeStateListenerCallback(env);
    return errID == 0;
}

int32_t onSharedSoDemoChatRuntimeStateListenerMessage(int32_t, uintptr_t responsePtr, int32_t responseLen) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return 0;
    }
    std::lock_guard<std::mutex> lock(sharedSoDemoChatRuntimeStateCallbackMu);
    if (sharedSoDemoChatRuntimeStateCallbackListener == nullptr || sharedSoDemoChatRuntimeStateCallbackOnMessage == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return 0;
    }
    jbyteArray payload = env->NewByteArray(responseLen);
    if (payload == nullptr) {
        if (responsePtr != 0) { rpccgoRelease(responsePtr); }
        return 0;
    }
    if (responseLen > 0) {
        env->SetByteArrayRegion(payload, 0, responseLen, reinterpret_cast<const jbyte*>(responsePtr));
    }
    if (responsePtr != 0) { rpccgoRelease(responsePtr); }
    env->CallVoidMethod(sharedSoDemoChatRuntimeStateCallbackListener, sharedSoDemoChatRuntimeStateCallbackOnMessage, payload);
    env->DeleteLocalRef(payload);
    if (env->ExceptionCheck()) { env->ExceptionClear(); }
    return 0;
}

int32_t onSharedSoDemoChatRuntimeStateListenerDone(int32_t, int32_t errID) {
    rpccgoJNIEnvScope envScope(nullptr);
    JNIEnv* env = envScope.env;
    if (env == nullptr) { return 0; }
    jobject listener = nullptr;
    jmethodID onDone = nullptr;
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoChatRuntimeStateCallbackMu);
        listener = sharedSoDemoChatRuntimeStateCallbackListener;
        onDone = sharedSoDemoChatRuntimeStateCallbackOnDone;
    }
    if (listener != nullptr && onDone != nullptr) {
        jstring error = nullptr;
        if (errID != 0) {
            std::string text = rpccgoErrorString(errID);
            error = env->NewStringUTF(text.c_str());
        }
        env->CallVoidMethod(listener, onDone, error);
        if (error != nullptr) { env->DeleteLocalRef(error); }
        if (env->ExceptionCheck()) { env->ExceptionClear(); }
    }
    clearSharedSoDemoChatRuntimeStateListenerCallback(env);
    return 0;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateStart invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateStart(JNIEnv* env, jobject) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateStart(&handle, nullptr, nullptr);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessHandle(env, handle);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateSend invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateSend(JNIEnv* env, jobject, jint handle, jbyteArray request) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    bool requestOK = false;
    std::vector<uint8_t> requestBytes = rpccgoJNIBytes(env, request, &requestOK);
    if (!requestOK) { return rpccgoErrorResult(env, "rpccgo: JNI request bytes are null or unreadable"); }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateSend(static_cast<int32_t>(handle), rpccgoVectorPtr(requestBytes), static_cast<int32_t>(requestBytes.size()));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateRecv invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateRecv(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    uintptr_t responsePtr = 0;
    int32_t responseLen = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateRecv(static_cast<int32_t>(handle), &responsePtr, &responseLen);
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessBytes(env, responsePtr, responseLen);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateCloseSend invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateCloseSend(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateCloseSend(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateFinish invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateFinish(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateFinish(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateCancel invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateCancel(JNIEnv* env, jobject, jint handle) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateCancel(static_cast<int32_t>(handle));
    if (errID != 0) { return rpccgoErrorIDResult(env, errID); }
    return rpccgoSuccessUnit(env);
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateStartCallback invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateStartCallback(JNIEnv* env, jobject, jobject listener) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    if (listener == nullptr) { return JNI_FALSE; }
    cancelSharedSoDemoChatRuntimeStateListenerCallback(env);
    jclass listenerClass = env->GetObjectClass(listener);
    jmethodID onMessage = env->GetMethodID(listenerClass, "onMessage", "([B)V");
    jmethodID onDone = env->GetMethodID(listenerClass, "onDone", "(Ljava/lang/String;)V");
    env->DeleteLocalRef(listenerClass);
    if (onMessage == nullptr || onDone == nullptr) { return JNI_FALSE; }
    jobject globalListener = env->NewGlobalRef(listener);
    if (globalListener == nullptr) { return JNI_FALSE; }
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoChatRuntimeStateCallbackMu);
        sharedSoDemoChatRuntimeStateCallbackListener = globalListener;
        sharedSoDemoChatRuntimeStateCallbackOnMessage = onMessage;
        sharedSoDemoChatRuntimeStateCallbackOnDone = onDone;
    }
    int32_t handle = 0;
    int32_t errID = rpccgoMsgFluttersharedv1SharedSoDemoChatRuntimeStateStart(&handle, onSharedSoDemoChatRuntimeStateListenerMessage, onSharedSoDemoChatRuntimeStateListenerDone);
    if (errID != 0) {
        clearSharedSoDemoChatRuntimeStateListenerCallback(env);
        return JNI_FALSE;
    }
    {
        std::lock_guard<std::mutex> lock(sharedSoDemoChatRuntimeStateCallbackMu);
        sharedSoDemoChatRuntimeStateCallbackHandle = handle;
    }
    return JNI_TRUE;
}

// Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateCancelCallback invokes examples.flutter.sharedso.v1.SharedSoDemo.ChatRuntimeState through the Android C++ JNI adapter.
extern "C" JNIEXPORT jboolean JNICALL Java_com_ygrpc_examples_rpccgofluttersharedso_SharedSoDemoJni_sharedSoDemoChatRuntimeStateCancelCallback(JNIEnv* env, jobject) {
    rpccgoJNIEnvScope envScope(env);
    env = envScope.env;
    if (env == nullptr) { return nullptr; }
    return cancelSharedSoDemoChatRuntimeStateListenerCallback(env) ? JNI_TRUE : JNI_FALSE;
}
