/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "stream.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cgotest_StreamRequest, cgotest_StreamRequest, 2)


PB_BIND(cgotest_StreamResponse, cgotest_StreamResponse, 2)



