// Code generated by protoc-gen-rpc-cgo. DO NOT EDIT.
//
// Source: greeter.proto

package main

import (
	proto "example.com/rpccgo-connect/proto"
)

/*
#include <stdint.h>
*/
import "C"

import (
	context "context"
	errors "errors"
	fmt "fmt"
	rpcruntime "github.com/ygrpc/rpccgo/rpcruntime"
	unsafe "unsafe"
)

// rpccgo native generated file for Greeter cgo native client

var greeterNativeClientUnsupportedField = errors.New("rpccgo: native unary client field codec is not implemented")
var greeterNativeClientStreamHandleInvalid = errors.New("rpccgo: native client stream handle is invalid")

func decodeGreeterSayHelloNativeUnaryRequest(NamePtr uintptr, NameLen int32, NameOwnership int32, CityPtr uintptr, CityLen int32, CityOwnership int32) (*rpcruntime.RpcString, *rpcruntime.RpcString, error) {
	var decoded rpcruntime.NativeReleaseStack
	if _, err := rpcruntime.LengthFromInt32(NameLen); err != nil {
		return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.name: %w", err), decoded.Release())
	}
	var nameValue *rpcruntime.RpcString
	if NamePtr == 0 || NameLen == 0 {
		nameValue = rpcruntime.EmptyRpcString()
	} else {
		var decodeErr error
		nameValue, decodeErr = rpcruntime.NewRpcStringChecked((*byte)(unsafe.Pointer(NamePtr)), NameLen, NameOwnership > 0)
		if decodeErr != nil {
			return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.name: %w", decodeErr), decoded.Release())
		}
	}
	decoded = append(decoded, nameValue)
	if _, err := rpcruntime.LengthFromInt32(CityLen); err != nil {
		return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.city: %w", err), decoded.Release())
	}
	var cityValue *rpcruntime.RpcString
	if CityPtr == 0 || CityLen == 0 {
		cityValue = rpcruntime.EmptyRpcString()
	} else {
		var decodeErr error
		cityValue, decodeErr = rpcruntime.NewRpcStringChecked((*byte)(unsafe.Pointer(CityPtr)), CityLen, CityOwnership > 0)
		if decodeErr != nil {
			return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.city: %w", decodeErr), decoded.Release())
		}
	}
	decoded = append(decoded, cityValue)
	return nameValue, cityValue, nil
}

func validateGreeterSayHelloNativeUnaryResponse(outMessagePtr *uintptr, outMessageLen *int32) error {
	if outMessagePtr == nil {
		return errors.New("rpccgo: native client output pointer is nil")
	}
	if outMessageLen == nil {
		return errors.New("rpccgo: native client output pointer is nil")
	}
	return nil
}

func encodeGreeterSayHelloNativeUnaryResponse(messageResult string, outMessagePtr *uintptr, outMessageLen *int32) error {
	if err := validateGreeterSayHelloNativeUnaryResponse(outMessagePtr, outMessageLen); err != nil {
		return err
	}
	messageLenValue, err := rpcruntime.LengthToInt32(len(messageResult))
	if err != nil {
		return err
	}
	data, messagePtrValue, err := rpcruntime.PinString(messageResult)
	_ = data
	if err != nil {
		return err
	}
	_ = messagePtrValue
	*outMessagePtr = messagePtrValue
	*outMessageLen = messageLenValue
	return nil
}

// rpccgoNativeGreeterv1GreeterSayHello invokes the native unary client entrypoint for examples.connect.greeter.v1.Greeter.SayHello.
//
//export rpccgoNativeGreeterv1GreeterSayHello
func rpccgoNativeGreeterv1GreeterSayHello(NamePtr C.uintptr_t, NameLen C.int32_t, NameOwnership C.int32_t, CityPtr C.uintptr_t, CityLen C.int32_t, CityOwnership C.int32_t, outMessagePtr *C.uintptr_t, outMessageLen *C.int32_t, outMessageOwnership *C.int32_t) C.int32_t {
	ctx := context.Background()
	if outMessagePtr != nil {
		*outMessagePtr = 0
	}
	if outMessageLen != nil {
		*outMessageLen = 0
	}
	if outMessageOwnership != nil {
		*outMessageOwnership = 0
	}
	if outMessagePtr == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: native client output pointer is nil")))
	}
	if outMessageLen == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: native client output pointer is nil")))
	}
	if err := validateGreeterSayHelloNativeUnaryResponse((*uintptr)(unsafe.Pointer(outMessagePtr)), (*int32)(unsafe.Pointer(outMessageLen))); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	nameValue, cityValue, err := decodeGreeterSayHelloNativeUnaryRequest(uintptr(NamePtr), int32(NameLen), int32(NameOwnership), uintptr(CityPtr), int32(CityLen), int32(CityOwnership))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	messageResult, err := proto.InvokeGreeterNativeSayHello(ctx, nameValue, cityValue)
	if cleanupErr := errors.Join(nameValue.Release(), cityValue.Release()); cleanupErr != nil {
		err = errors.Join(err, cleanupErr)
	}
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	if err := encodeGreeterSayHelloNativeUnaryResponse(messageResult, (*uintptr)(unsafe.Pointer(outMessagePtr)), (*int32)(unsafe.Pointer(outMessageLen))); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	return 0
}

func decodeGreeterCollectNativeClientStreamRequest(NamePtr uintptr, NameLen int32, NameOwnership int32, CityPtr uintptr, CityLen int32, CityOwnership int32) (*rpcruntime.RpcString, *rpcruntime.RpcString, error) {
	var decoded rpcruntime.NativeReleaseStack
	if _, err := rpcruntime.LengthFromInt32(NameLen); err != nil {
		return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.name: %w", err), decoded.Release())
	}
	var nameValue *rpcruntime.RpcString
	if NamePtr == 0 || NameLen == 0 {
		nameValue = rpcruntime.EmptyRpcString()
	} else {
		var decodeErr error
		nameValue, decodeErr = rpcruntime.NewRpcStringChecked((*byte)(unsafe.Pointer(NamePtr)), NameLen, NameOwnership > 0)
		if decodeErr != nil {
			return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.name: %w", decodeErr), decoded.Release())
		}
	}
	decoded = append(decoded, nameValue)
	if _, err := rpcruntime.LengthFromInt32(CityLen); err != nil {
		return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.city: %w", err), decoded.Release())
	}
	var cityValue *rpcruntime.RpcString
	if CityPtr == 0 || CityLen == 0 {
		cityValue = rpcruntime.EmptyRpcString()
	} else {
		var decodeErr error
		cityValue, decodeErr = rpcruntime.NewRpcStringChecked((*byte)(unsafe.Pointer(CityPtr)), CityLen, CityOwnership > 0)
		if decodeErr != nil {
			return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.city: %w", decodeErr), decoded.Release())
		}
	}
	decoded = append(decoded, cityValue)
	return nameValue, cityValue, nil
}

func validateGreeterCollectNativeClientStreamResponse(outMessagePtr *uintptr, outMessageLen *int32) error {
	if outMessagePtr == nil {
		return errors.New("rpccgo: native client output pointer is nil")
	}
	if outMessageLen == nil {
		return errors.New("rpccgo: native client output pointer is nil")
	}
	return nil
}

func encodeGreeterCollectNativeClientStreamResponse(messageResult string, outMessagePtr *uintptr, outMessageLen *int32) error {
	if err := validateGreeterCollectNativeClientStreamResponse(outMessagePtr, outMessageLen); err != nil {
		return err
	}
	messageLenValue, err := rpcruntime.LengthToInt32(len(messageResult))
	if err != nil {
		return err
	}
	data, messagePtrValue, err := rpcruntime.PinString(messageResult)
	_ = data
	if err != nil {
		return err
	}
	_ = messagePtrValue
	*outMessagePtr = messagePtrValue
	*outMessageLen = messageLenValue
	return nil
}

// rpccgoNativeGreeterv1GreeterCollectStart starts the native client-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Collect.
//
//export rpccgoNativeGreeterv1GreeterCollectStart
func rpccgoNativeGreeterv1GreeterCollectStart(stream *C.int32_t) C.int32_t {
	ctx := context.Background()
	if stream != nil {
		*stream = 0
	}
	if stream == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: native client handle pointer is nil")))
	}
	handle, err := proto.GreeterNativeCollectStart(ctx)
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	*stream = C.int32_t(int32(handle))
	return 0
}

// rpccgoNativeGreeterv1GreeterCollectSend sends native request values to the client-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Collect.
//
//export rpccgoNativeGreeterv1GreeterCollectSend
func rpccgoNativeGreeterv1GreeterCollectSend(stream C.int32_t, NamePtr C.uintptr_t, NameLen C.int32_t, NameOwnership C.int32_t, CityPtr C.uintptr_t, CityLen C.int32_t, CityOwnership C.int32_t) C.int32_t {
	ctx := context.Background()
	handle := int32(stream)
	var err error
	nameValue, cityValue, err := decodeGreeterCollectNativeClientStreamRequest(uintptr(NamePtr), int32(NameLen), int32(NameOwnership), uintptr(CityPtr), int32(CityLen), int32(CityOwnership))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	err = proto.GreeterNativeCollectSend(ctx, rpcruntime.StreamHandle(handle), nameValue, cityValue)
	if cleanupErr := errors.Join(nameValue.Release(), cityValue.Release()); cleanupErr != nil {
		err = errors.Join(err, cleanupErr)
	}
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	return 0
}

// rpccgoNativeGreeterv1GreeterCollectFinish finishes the native client-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Collect.
//
//export rpccgoNativeGreeterv1GreeterCollectFinish
func rpccgoNativeGreeterv1GreeterCollectFinish(stream C.int32_t, outMessagePtr *C.uintptr_t, outMessageLen *C.int32_t, outMessageOwnership *C.int32_t) C.int32_t {
	ctx := context.Background()
	if outMessagePtr != nil {
		*outMessagePtr = 0
	}
	if outMessageLen != nil {
		*outMessageLen = 0
	}
	if outMessageOwnership != nil {
		*outMessageOwnership = 0
	}
	if outMessagePtr == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: native client output pointer is nil")))
	}
	if outMessageLen == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: native client output pointer is nil")))
	}
	handle := int32(stream)
	if err := validateGreeterCollectNativeClientStreamResponse((*uintptr)(unsafe.Pointer(outMessagePtr)), (*int32)(unsafe.Pointer(outMessageLen))); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	var err error
	var messageResult string
	messageResult, err = proto.GreeterNativeCollectFinish(ctx, rpcruntime.StreamHandle(handle))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	if err := encodeGreeterCollectNativeClientStreamResponse(messageResult, (*uintptr)(unsafe.Pointer(outMessagePtr)), (*int32)(unsafe.Pointer(outMessageLen))); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	return 0
}

// rpccgoNativeGreeterv1GreeterCollectCancel cancels the native client-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Collect.
//
//export rpccgoNativeGreeterv1GreeterCollectCancel
func rpccgoNativeGreeterv1GreeterCollectCancel(stream C.int32_t) C.int32_t {
	ctx := context.Background()
	handle := int32(stream)
	var err error
	err = proto.GreeterNativeCollectCancel(ctx, rpcruntime.StreamHandle(handle))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	return 0
}

func decodeGreeterBroadcastNativeServerStreamRequest(NamePtr uintptr, NameLen int32, NameOwnership int32, CityPtr uintptr, CityLen int32, CityOwnership int32) (*rpcruntime.RpcString, *rpcruntime.RpcString, error) {
	var decoded rpcruntime.NativeReleaseStack
	if _, err := rpcruntime.LengthFromInt32(NameLen); err != nil {
		return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.name: %w", err), decoded.Release())
	}
	var nameValue *rpcruntime.RpcString
	if NamePtr == 0 || NameLen == 0 {
		nameValue = rpcruntime.EmptyRpcString()
	} else {
		var decodeErr error
		nameValue, decodeErr = rpcruntime.NewRpcStringChecked((*byte)(unsafe.Pointer(NamePtr)), NameLen, NameOwnership > 0)
		if decodeErr != nil {
			return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.name: %w", decodeErr), decoded.Release())
		}
	}
	decoded = append(decoded, nameValue)
	if _, err := rpcruntime.LengthFromInt32(CityLen); err != nil {
		return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.city: %w", err), decoded.Release())
	}
	var cityValue *rpcruntime.RpcString
	if CityPtr == 0 || CityLen == 0 {
		cityValue = rpcruntime.EmptyRpcString()
	} else {
		var decodeErr error
		cityValue, decodeErr = rpcruntime.NewRpcStringChecked((*byte)(unsafe.Pointer(CityPtr)), CityLen, CityOwnership > 0)
		if decodeErr != nil {
			return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.city: %w", decodeErr), decoded.Release())
		}
	}
	decoded = append(decoded, cityValue)
	return nameValue, cityValue, nil
}

func validateGreeterBroadcastNativeServerStreamResponse(outMessagePtr *uintptr, outMessageLen *int32) error {
	if outMessagePtr == nil {
		return errors.New("rpccgo: native client output pointer is nil")
	}
	if outMessageLen == nil {
		return errors.New("rpccgo: native client output pointer is nil")
	}
	return nil
}

func encodeGreeterBroadcastNativeServerStreamResponse(messageResult string, outMessagePtr *uintptr, outMessageLen *int32) error {
	if err := validateGreeterBroadcastNativeServerStreamResponse(outMessagePtr, outMessageLen); err != nil {
		return err
	}
	messageLenValue, err := rpcruntime.LengthToInt32(len(messageResult))
	if err != nil {
		return err
	}
	data, messagePtrValue, err := rpcruntime.PinString(messageResult)
	_ = data
	if err != nil {
		return err
	}
	_ = messagePtrValue
	*outMessagePtr = messagePtrValue
	*outMessageLen = messageLenValue
	return nil
}

// rpccgoNativeGreeterv1GreeterBroadcastStart starts the native server-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Broadcast.
//
//export rpccgoNativeGreeterv1GreeterBroadcastStart
func rpccgoNativeGreeterv1GreeterBroadcastStart(NamePtr C.uintptr_t, NameLen C.int32_t, NameOwnership C.int32_t, CityPtr C.uintptr_t, CityLen C.int32_t, CityOwnership C.int32_t, stream *C.int32_t) C.int32_t {
	ctx := context.Background()
	if stream != nil {
		*stream = 0
	}
	if stream == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: native client handle pointer is nil")))
	}
	var err error
	nameValue, cityValue, err := decodeGreeterBroadcastNativeServerStreamRequest(uintptr(NamePtr), int32(NameLen), int32(NameOwnership), uintptr(CityPtr), int32(CityLen), int32(CityOwnership))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	handle, err := proto.GreeterNativeBroadcastStart(ctx, nameValue, cityValue)
	if cleanupErr := errors.Join(nameValue.Release(), cityValue.Release()); cleanupErr != nil {
		err = errors.Join(err, cleanupErr)
	}
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	*stream = C.int32_t(int32(handle))
	return 0
}

// rpccgoNativeGreeterv1GreeterBroadcastRecv receives native response values from the server-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Broadcast.
//
//export rpccgoNativeGreeterv1GreeterBroadcastRecv
func rpccgoNativeGreeterv1GreeterBroadcastRecv(stream C.int32_t, outMessagePtr *C.uintptr_t, outMessageLen *C.int32_t, outMessageOwnership *C.int32_t) C.int32_t {
	ctx := context.Background()
	if outMessagePtr != nil {
		*outMessagePtr = 0
	}
	if outMessageLen != nil {
		*outMessageLen = 0
	}
	if outMessageOwnership != nil {
		*outMessageOwnership = 0
	}
	if outMessagePtr == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: native client output pointer is nil")))
	}
	if outMessageLen == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: native client output pointer is nil")))
	}
	handle := int32(stream)
	if err := validateGreeterBroadcastNativeServerStreamResponse((*uintptr)(unsafe.Pointer(outMessagePtr)), (*int32)(unsafe.Pointer(outMessageLen))); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	var err error
	var messageResult string
	messageResult, err = proto.GreeterNativeBroadcastRecv(ctx, rpcruntime.StreamHandle(handle))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	if err := encodeGreeterBroadcastNativeServerStreamResponse(messageResult, (*uintptr)(unsafe.Pointer(outMessagePtr)), (*int32)(unsafe.Pointer(outMessageLen))); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	return 0
}

// rpccgoNativeGreeterv1GreeterBroadcastFinish finishes the native server-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Broadcast.
//
//export rpccgoNativeGreeterv1GreeterBroadcastFinish
func rpccgoNativeGreeterv1GreeterBroadcastFinish(stream C.int32_t) C.int32_t {
	ctx := context.Background()
	handle := int32(stream)
	var err error
	err = proto.GreeterNativeBroadcastFinish(ctx, rpcruntime.StreamHandle(handle))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	return 0
}

// rpccgoNativeGreeterv1GreeterBroadcastCancel cancels the native server-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Broadcast.
//
//export rpccgoNativeGreeterv1GreeterBroadcastCancel
func rpccgoNativeGreeterv1GreeterBroadcastCancel(stream C.int32_t) C.int32_t {
	ctx := context.Background()
	handle := int32(stream)
	var err error
	err = proto.GreeterNativeBroadcastCancel(ctx, rpcruntime.StreamHandle(handle))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	return 0
}

func decodeGreeterChatNativeBidiStreamRequest(NamePtr uintptr, NameLen int32, NameOwnership int32, CityPtr uintptr, CityLen int32, CityOwnership int32) (*rpcruntime.RpcString, *rpcruntime.RpcString, error) {
	var decoded rpcruntime.NativeReleaseStack
	if _, err := rpcruntime.LengthFromInt32(NameLen); err != nil {
		return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.name: %w", err), decoded.Release())
	}
	var nameValue *rpcruntime.RpcString
	if NamePtr == 0 || NameLen == 0 {
		nameValue = rpcruntime.EmptyRpcString()
	} else {
		var decodeErr error
		nameValue, decodeErr = rpcruntime.NewRpcStringChecked((*byte)(unsafe.Pointer(NamePtr)), NameLen, NameOwnership > 0)
		if decodeErr != nil {
			return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.name: %w", decodeErr), decoded.Release())
		}
	}
	decoded = append(decoded, nameValue)
	if _, err := rpcruntime.LengthFromInt32(CityLen); err != nil {
		return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.city: %w", err), decoded.Release())
	}
	var cityValue *rpcruntime.RpcString
	if CityPtr == 0 || CityLen == 0 {
		cityValue = rpcruntime.EmptyRpcString()
	} else {
		var decodeErr error
		cityValue, decodeErr = rpcruntime.NewRpcStringChecked((*byte)(unsafe.Pointer(CityPtr)), CityLen, CityOwnership > 0)
		if decodeErr != nil {
			return nil, nil, errors.Join(fmt.Errorf("examples.connect.greeter.v1.SayHelloRequest.city: %w", decodeErr), decoded.Release())
		}
	}
	decoded = append(decoded, cityValue)
	return nameValue, cityValue, nil
}

func validateGreeterChatNativeBidiStreamResponse(outMessagePtr *uintptr, outMessageLen *int32) error {
	if outMessagePtr == nil {
		return errors.New("rpccgo: native client output pointer is nil")
	}
	if outMessageLen == nil {
		return errors.New("rpccgo: native client output pointer is nil")
	}
	return nil
}

func encodeGreeterChatNativeBidiStreamResponse(messageResult string, outMessagePtr *uintptr, outMessageLen *int32) error {
	if err := validateGreeterChatNativeBidiStreamResponse(outMessagePtr, outMessageLen); err != nil {
		return err
	}
	messageLenValue, err := rpcruntime.LengthToInt32(len(messageResult))
	if err != nil {
		return err
	}
	data, messagePtrValue, err := rpcruntime.PinString(messageResult)
	_ = data
	if err != nil {
		return err
	}
	_ = messagePtrValue
	*outMessagePtr = messagePtrValue
	*outMessageLen = messageLenValue
	return nil
}

// rpccgoNativeGreeterv1GreeterChatStart starts the native bidi-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Chat.
//
//export rpccgoNativeGreeterv1GreeterChatStart
func rpccgoNativeGreeterv1GreeterChatStart(stream *C.int32_t) C.int32_t {
	ctx := context.Background()
	if stream != nil {
		*stream = 0
	}
	if stream == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: native client handle pointer is nil")))
	}
	handle, err := proto.GreeterNativeChatStart(ctx)
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	*stream = C.int32_t(int32(handle))
	return 0
}

// rpccgoNativeGreeterv1GreeterChatSend sends native request values to the bidi-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Chat.
//
//export rpccgoNativeGreeterv1GreeterChatSend
func rpccgoNativeGreeterv1GreeterChatSend(stream C.int32_t, NamePtr C.uintptr_t, NameLen C.int32_t, NameOwnership C.int32_t, CityPtr C.uintptr_t, CityLen C.int32_t, CityOwnership C.int32_t) C.int32_t {
	ctx := context.Background()
	handle := int32(stream)
	var err error
	nameValue, cityValue, err := decodeGreeterChatNativeBidiStreamRequest(uintptr(NamePtr), int32(NameLen), int32(NameOwnership), uintptr(CityPtr), int32(CityLen), int32(CityOwnership))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	err = proto.GreeterNativeChatSend(ctx, rpcruntime.StreamHandle(handle), nameValue, cityValue)
	if cleanupErr := errors.Join(nameValue.Release(), cityValue.Release()); cleanupErr != nil {
		err = errors.Join(err, cleanupErr)
	}
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	return 0
}

// rpccgoNativeGreeterv1GreeterChatRecv receives native response values from the bidi-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Chat.
//
//export rpccgoNativeGreeterv1GreeterChatRecv
func rpccgoNativeGreeterv1GreeterChatRecv(stream C.int32_t, outMessagePtr *C.uintptr_t, outMessageLen *C.int32_t, outMessageOwnership *C.int32_t) C.int32_t {
	ctx := context.Background()
	if outMessagePtr != nil {
		*outMessagePtr = 0
	}
	if outMessageLen != nil {
		*outMessageLen = 0
	}
	if outMessageOwnership != nil {
		*outMessageOwnership = 0
	}
	if outMessagePtr == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: native client output pointer is nil")))
	}
	if outMessageLen == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: native client output pointer is nil")))
	}
	handle := int32(stream)
	if err := validateGreeterChatNativeBidiStreamResponse((*uintptr)(unsafe.Pointer(outMessagePtr)), (*int32)(unsafe.Pointer(outMessageLen))); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	var err error
	var messageResult string
	messageResult, err = proto.GreeterNativeChatRecv(ctx, rpcruntime.StreamHandle(handle))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	if err := encodeGreeterChatNativeBidiStreamResponse(messageResult, (*uintptr)(unsafe.Pointer(outMessagePtr)), (*int32)(unsafe.Pointer(outMessageLen))); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	return 0
}

// rpccgoNativeGreeterv1GreeterChatCloseSend closes the native bidi-streaming client send side for examples.connect.greeter.v1.Greeter.Chat.
//
//export rpccgoNativeGreeterv1GreeterChatCloseSend
func rpccgoNativeGreeterv1GreeterChatCloseSend(stream C.int32_t) C.int32_t {
	ctx := context.Background()
	handle := int32(stream)
	var err error
	err = proto.GreeterNativeChatCloseSend(ctx, rpcruntime.StreamHandle(handle))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	return 0
}

// rpccgoNativeGreeterv1GreeterChatFinish finishes the native bidi-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Chat.
//
//export rpccgoNativeGreeterv1GreeterChatFinish
func rpccgoNativeGreeterv1GreeterChatFinish(stream C.int32_t) C.int32_t {
	ctx := context.Background()
	handle := int32(stream)
	var err error
	err = proto.GreeterNativeChatFinish(ctx, rpcruntime.StreamHandle(handle))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	return 0
}

// rpccgoNativeGreeterv1GreeterChatCancel cancels the native bidi-streaming client entrypoint for examples.connect.greeter.v1.Greeter.Chat.
//
//export rpccgoNativeGreeterv1GreeterChatCancel
func rpccgoNativeGreeterv1GreeterChatCancel(stream C.int32_t) C.int32_t {
	ctx := context.Background()
	handle := int32(stream)
	var err error
	err = proto.GreeterNativeChatCancel(ctx, rpcruntime.StreamHandle(handle))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	return 0
}
