// Code generated by protoc-gen-rpc-cgo. DO NOT EDIT.
//
// Shared: rpccgo cgo export support

package main

/*
#include <stdint.h>

typedef void (*rpccgo_free_callback)(void*);

static inline void rpccgo_call_free_callback(rpccgo_free_callback callback, void* ptr) {
callback(ptr);
}
*/
import "C"

import (
	errors "errors"
	fmt "fmt"
	rpcruntime "github.com/ygrpc/rpccgo/rpcruntime"
	unsafe "unsafe"
)

// rpccgo cgo support generated file for shared exports

//export rpccgo_register_free
func rpccgo_register_free(callback C.rpccgo_free_callback) C.int32_t {
	if callback == nil {
		return -1
	}
	rpcruntime.RegisterFreeCallback(func(ptr unsafe.Pointer) {
		C.rpccgo_call_free_callback(callback, ptr)
	})
	return 0
}

//export rpccgo_store_error_text
func rpccgo_store_error_text(text *C.char, textLen C.int32_t) C.int32_t {
	length, err := rpcruntime.LengthFromInt32(int32(textLen))
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(fmt.Errorf("rpccgo: cgo error text: %w", err)))
	}
	if text == nil && length != 0 {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: cgo error text pointer is nil")))
	}
	var data []byte
	if length != 0 {
		data = unsafe.Slice((*byte)(unsafe.Pointer(text)), length)
	}
	return C.int32_t(rpcruntime.StoreError(errors.New(string(data))))
}

//export rpccgo_take_error_text
func rpccgo_take_error_text(errID C.int32_t, textPtr *C.uintptr_t, textLen *C.int32_t) C.int32_t {
	if textPtr == nil || textLen == nil {
		return -1
	}
	var goPtr uintptr
	var goLen int32
	status := rpcruntime.TakeErrorTextForExport(int32(errID), &goPtr, &goLen)
	if status != 0 {
		return C.int32_t(status)
	}
	*textPtr = C.uintptr_t(goPtr)
	*textLen = C.int32_t(goLen)
	return 0
}

//export rpccgo_release
func rpccgo_release(ptr C.uintptr_t) C.int32_t {
	if !rpcruntime.Release(uintptr(ptr)) {
		return -1
	}
	return 0
}
