// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: foreground_service.proto
// Protobuf Java Version: 4.35.0

package examples.android.foregroundservice.v1;

@com.google.protobuf.Generated
public interface WatchTicksRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:examples.android.foregroundservice.v1.WatchTicksRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string caller = 1;</code>
   * @return The caller.
   */
  java.lang.String getCaller();
  /**
   * <code>string caller = 1;</code>
   * @return The bytes for caller.
   */
  com.google.protobuf.ByteString
      getCallerBytes();

  /**
   * <code>int32 interval_millis = 2;</code>
   * @return The intervalMillis.
   */
  int getIntervalMillis();
}
