// Code generated by protoc-gen-rpc-cgo. DO NOT EDIT.
//
// Source: shared_so.proto

package main

import (
	proto "example.com/rpccgo-flutter-shared-so/proto"
)

/*
#include <stdint.h>

typedef int32_t (*AndroidDeviceSetTorchCGOMessageUnaryCallback)(uintptr_t request_ptr, int32_t request_len, uintptr_t* response_ptr, int32_t* response_len);

typedef int32_t (*AndroidDeviceWatchAndroidEchoCGOMessageServerStreamStartCallback)(uintptr_t request_ptr, int32_t request_len, int32_t* stream);
typedef int32_t (*AndroidDeviceWatchAndroidEchoCGOMessageServerStreamRecvCallback)(int32_t stream, uintptr_t* response_ptr, int32_t* response_len);
typedef int32_t (*AndroidDeviceWatchAndroidEchoCGOMessageServerStreamFinishCallback)(int32_t stream);
typedef int32_t (*AndroidDeviceWatchAndroidEchoCGOMessageServerStreamCancelCallback)(int32_t stream);

typedef int32_t (*AndroidDeviceCollectAndroidEchoCGOMessageClientStreamStartCallback)(int32_t* stream);
typedef int32_t (*AndroidDeviceCollectAndroidEchoCGOMessageClientStreamSendCallback)(int32_t stream, uintptr_t request_ptr, int32_t request_len);
typedef int32_t (*AndroidDeviceCollectAndroidEchoCGOMessageClientStreamFinishCallback)(int32_t stream, uintptr_t* response_ptr, int32_t* response_len);
typedef int32_t (*AndroidDeviceCollectAndroidEchoCGOMessageClientStreamCancelCallback)(int32_t stream);

typedef int32_t (*AndroidDeviceChatAndroidEchoCGOMessageBidiStreamStartCallback)(int32_t* stream);
typedef int32_t (*AndroidDeviceChatAndroidEchoCGOMessageBidiStreamSendCallback)(int32_t stream, uintptr_t request_ptr, int32_t request_len);
typedef int32_t (*AndroidDeviceChatAndroidEchoCGOMessageBidiStreamRecvCallback)(int32_t stream, uintptr_t* response_ptr, int32_t* response_len);
typedef int32_t (*AndroidDeviceChatAndroidEchoCGOMessageBidiStreamCloseSendCallback)(int32_t stream);
typedef int32_t (*AndroidDeviceChatAndroidEchoCGOMessageBidiStreamFinishCallback)(int32_t stream);
typedef int32_t (*AndroidDeviceChatAndroidEchoCGOMessageBidiStreamCancelCallback)(int32_t stream);

static inline int32_t callAndroidDeviceSetTorchCGOMessageUnary(AndroidDeviceSetTorchCGOMessageUnaryCallback callback, uintptr_t request_ptr, int32_t request_len, uintptr_t* response_ptr, int32_t* response_len) {
	return callback(request_ptr, request_len, response_ptr, response_len);
}

static inline int32_t callAndroidDeviceWatchAndroidEchoCGOMessageServerStreamStart(AndroidDeviceWatchAndroidEchoCGOMessageServerStreamStartCallback callback, uintptr_t request_ptr, int32_t request_len, int32_t* stream) { return callback(request_ptr, request_len, stream); }
static inline int32_t callAndroidDeviceWatchAndroidEchoCGOMessageServerStreamRecv(AndroidDeviceWatchAndroidEchoCGOMessageServerStreamRecvCallback callback, int32_t stream, uintptr_t* response_ptr, int32_t* response_len) { return callback(stream, response_ptr, response_len); }
static inline int32_t callAndroidDeviceWatchAndroidEchoCGOMessageServerStreamFinish(AndroidDeviceWatchAndroidEchoCGOMessageServerStreamFinishCallback callback, int32_t stream) { return callback(stream); }
static inline int32_t callAndroidDeviceWatchAndroidEchoCGOMessageServerStreamCancel(AndroidDeviceWatchAndroidEchoCGOMessageServerStreamCancelCallback callback, int32_t stream) { return callback(stream); }

static inline int32_t callAndroidDeviceCollectAndroidEchoCGOMessageClientStreamStart(AndroidDeviceCollectAndroidEchoCGOMessageClientStreamStartCallback callback, int32_t* stream) { return callback(stream); }
static inline int32_t callAndroidDeviceCollectAndroidEchoCGOMessageClientStreamSend(AndroidDeviceCollectAndroidEchoCGOMessageClientStreamSendCallback callback, int32_t stream, uintptr_t request_ptr, int32_t request_len) { return callback(stream, request_ptr, request_len); }
static inline int32_t callAndroidDeviceCollectAndroidEchoCGOMessageClientStreamFinish(AndroidDeviceCollectAndroidEchoCGOMessageClientStreamFinishCallback callback, int32_t stream, uintptr_t* response_ptr, int32_t* response_len) { return callback(stream, response_ptr, response_len); }
static inline int32_t callAndroidDeviceCollectAndroidEchoCGOMessageClientStreamCancel(AndroidDeviceCollectAndroidEchoCGOMessageClientStreamCancelCallback callback, int32_t stream) { return callback(stream); }

static inline int32_t callAndroidDeviceChatAndroidEchoCGOMessageBidiStreamStart(AndroidDeviceChatAndroidEchoCGOMessageBidiStreamStartCallback callback, int32_t* stream) { return callback(stream); }
static inline int32_t callAndroidDeviceChatAndroidEchoCGOMessageBidiStreamSend(AndroidDeviceChatAndroidEchoCGOMessageBidiStreamSendCallback callback, int32_t stream, uintptr_t request_ptr, int32_t request_len) { return callback(stream, request_ptr, request_len); }
static inline int32_t callAndroidDeviceChatAndroidEchoCGOMessageBidiStreamRecv(AndroidDeviceChatAndroidEchoCGOMessageBidiStreamRecvCallback callback, int32_t stream, uintptr_t* response_ptr, int32_t* response_len) { return callback(stream, response_ptr, response_len); }
static inline int32_t callAndroidDeviceChatAndroidEchoCGOMessageBidiStreamCloseSend(AndroidDeviceChatAndroidEchoCGOMessageBidiStreamCloseSendCallback callback, int32_t stream) { return callback(stream); }
static inline int32_t callAndroidDeviceChatAndroidEchoCGOMessageBidiStreamFinish(AndroidDeviceChatAndroidEchoCGOMessageBidiStreamFinishCallback callback, int32_t stream) { return callback(stream); }
static inline int32_t callAndroidDeviceChatAndroidEchoCGOMessageBidiStreamCancel(AndroidDeviceChatAndroidEchoCGOMessageBidiStreamCancelCallback callback, int32_t stream) { return callback(stream); }

*/
import "C"

import (
	context "context"
	errors "errors"
	fmt "fmt"
	io "io"
	protobuf "google.golang.org/protobuf/proto"
	rpcruntime "github.com/ygrpc/rpccgo/rpcruntime"
	sync "sync"
	unsafe "unsafe"
)

// rpccgo message direct generated file for AndroidDevice cgo message server callbacks

var (
	androidDeviceCGOMessageServerCallbacksNil              = errors.New("rpccgo: AndroidDevice cgo message server callbacks are nil")
	androidDeviceCGOMessageServerUnaryCallbackMissing      = errors.New("rpccgo: AndroidDevice cgo message server unary callback is missing")
	androidDeviceCGOMessageServerStreamPartiallyRegistered = errors.New("rpccgo: AndroidDevice cgo message server stream callbacks are partially registered")
	androidDeviceCGOMessageServerAdapterMu                 sync.Mutex
	androidDeviceCGOMessageServerAdapter                   = &androidDeviceCGOMessageAdapter{}
)

type androidDeviceCGOMessageAdapter struct {
	SetTorchCallback         C.AndroidDeviceSetTorchCGOMessageUnaryCallback
	watchAndroidEchoStart    C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamStartCallback
	watchAndroidEchoRecv     C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamRecvCallback
	watchAndroidEchoFinish   C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamFinishCallback
	watchAndroidEchoCancel   C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamCancelCallback
	collectAndroidEchoStart  C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamStartCallback
	collectAndroidEchoSend   C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamSendCallback
	collectAndroidEchoFinish C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamFinishCallback
	collectAndroidEchoCancel C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamCancelCallback
	chatAndroidEchoStart     C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamStartCallback
	chatAndroidEchoSend      C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamSendCallback
	chatAndroidEchoRecv      C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamRecvCallback
	chatAndroidEchoCloseSend C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamCloseSendCallback
	chatAndroidEchoFinish    C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamFinishCallback
	chatAndroidEchoCancel    C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamCancelCallback
}

// androidDeviceCGOMessageRecvResult carries the result of a blocking cgo message Recv callback.
type androidDeviceCGOMessageRecvResult[T any] struct {
	value T
	err   error
}

// androidDeviceAwaitCGOMessageRecv waits for a blocking cgo message Recv callback while allowing Finish or Cancel to interrupt the wait.
func androidDeviceAwaitCGOMessageRecv[T any](ctx context.Context, finishRequested <-chan struct{}, recv func() (T, error), finish func() error, cancel func() error) (T, error, bool) {
	select {
	case <-finishRequested:
		var zero T
		return zero, finish(), true
	case <-ctx.Done():
		var zero T
		return zero, errors.Join(ctx.Err(), cancel()), true
	default:
	}
	results := make(chan androidDeviceCGOMessageRecvResult[T], 1)
	go func() {
		value, err := recv()
		results <- androidDeviceCGOMessageRecvResult[T]{value: value, err: err}
	}()
	var zero T
	select {
	case result := <-results:
		return result.value, result.err, false
	case <-finishRequested:
		return zero, finish(), true
	case <-ctx.Done():
		return zero, errors.Join(ctx.Err(), cancel()), true
	}
}

func (a *androidDeviceCGOMessageAdapter) SetTorch(ctx context.Context, req *proto.SetTorchRequest) (*proto.SetTorchResponse, error) {
	if a == nil {
		return nil, androidDeviceCGOMessageServerCallbacksNil
	}
	callback := a.SetTorchCallback
	if callback == nil {
		return nil, errors.New("rpccgo: AndroidDevice.SetTorch cgo message server method is not implemented")
	}
	if req == nil {
		err := errors.New("rpccgo: message request is nil")
		return nil, err
	}
	reqBytes, err := protobuf.Marshal(req)
	if err != nil {
		err = fmt.Errorf("rpccgo: message request protobuf marshal failed: %w", err)
		return nil, err
	}
	var requestPtr uintptr
	if len(reqBytes) != 0 {
		requestPtr = uintptr(unsafe.Pointer(&reqBytes[0]))
	}
	requestLen, err := rpcruntime.LengthToInt32(len(reqBytes))
	if err != nil {
		return nil, err
	}
	var responsePtr C.uintptr_t
	var responseLen C.int32_t
	errID := int32(C.callAndroidDeviceSetTorchCGOMessageUnary(callback, C.uintptr_t(requestPtr), C.int32_t(requestLen), &responsePtr, &responseLen))
	if errID != 0 {
		return nil, androidDeviceCGOMessageServerError(errID)
	}
	resp := &proto.SetTorchResponse{}
	if err := rpcruntime.DecodeMessage(uintptr(responsePtr), int32(responseLen), resp); err != nil {
		return nil, fmt.Errorf("rpccgo: message server response decode failed: %w", err)
	}
	return resp, nil
}

func (a *androidDeviceCGOMessageAdapter) WatchAndroidEchoStart(ctx context.Context, req *proto.AndroidEchoRequest) (rpcruntime.ServerStreamingClient[*proto.AndroidEchoResponse], error) {
	if a == nil {
		return nil, androidDeviceCGOMessageServerCallbacksNil
	}
	if a.watchAndroidEchoStart == nil || a.watchAndroidEchoRecv == nil || a.watchAndroidEchoFinish == nil || a.watchAndroidEchoCancel == nil {
		return nil, errors.New("rpccgo: AndroidDevice.WatchAndroidEcho cgo message server method is not implemented")
	}
	if req == nil {
		err := errors.New("rpccgo: message request is nil")
		return nil, err
	}
	reqBytes, err := protobuf.Marshal(req)
	if err != nil {
		err = fmt.Errorf("rpccgo: message request protobuf marshal failed: %w", err)
		return nil, err
	}
	var requestPtr uintptr
	if len(reqBytes) != 0 {
		requestPtr = uintptr(unsafe.Pointer(&reqBytes[0]))
	}
	requestLen, err := rpcruntime.LengthToInt32(len(reqBytes))
	if err != nil {
		return nil, err
	}
	var stream C.int32_t
	errID := int32(C.callAndroidDeviceWatchAndroidEchoCGOMessageServerStreamStart(a.watchAndroidEchoStart, C.uintptr_t(requestPtr), C.int32_t(requestLen), &stream))
	if errID != 0 {
		return nil, androidDeviceCGOMessageServerError(errID)
	}
	return &androidDeviceWatchAndroidEchoCGOMessageServerStreamingClient{recv: a.watchAndroidEchoRecv, finish: a.watchAndroidEchoFinish, cancel: a.watchAndroidEchoCancel, stream: int32(stream)}, nil
}

func (a *androidDeviceCGOMessageAdapter) WatchAndroidEcho(ctx context.Context, req *proto.AndroidEchoRequest, stream rpcruntime.ServerStreamingServer[*proto.AndroidEchoResponse]) error {
	session, err := a.WatchAndroidEchoStart(ctx, req)
	if err != nil {
		return err
	}
	finishSession := func() error {
		finisher, ok := any(session).(interface{ Finish(context.Context) error })
		if !ok {
			return nil
		}
		return finisher.Finish(ctx)
	}
	for {
		resp, err, stopped := androidDeviceAwaitCGOMessageRecv(ctx, stream.FinishRequested(), func() (*proto.AndroidEchoResponse, error) { return session.Recv(ctx) }, finishSession, func() error { return session.Cancel(ctx) })
		if stopped {
			return err
		}
		if err != nil {
			if errors.Is(err, io.EOF) {
				return finishSession()
			}
			_ = session.Cancel(ctx)
			return err
		}
		if err := stream.Send(ctx, resp); err != nil {
			if errors.Is(err, io.EOF) {
				return finishSession()
			}
			_ = session.Cancel(ctx)
			return err
		}
	}
}

type androidDeviceWatchAndroidEchoCGOMessageServerStreamingClient struct {
	recv   C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamRecvCallback
	finish C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamFinishCallback
	cancel C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamCancelCallback
	stream int32
}

func (s *androidDeviceWatchAndroidEchoCGOMessageServerStreamingClient) Recv(ctx context.Context) (*proto.AndroidEchoResponse, error) {
	var responsePtr C.uintptr_t
	var responseLen C.int32_t
	errID := int32(C.callAndroidDeviceWatchAndroidEchoCGOMessageServerStreamRecv(s.recv, C.int32_t(s.stream), &responsePtr, &responseLen))
	if errID != 0 {
		return nil, androidDeviceCGOMessageServerError(errID)
	}
	resp := &proto.AndroidEchoResponse{}
	if err := rpcruntime.DecodeMessage(uintptr(responsePtr), int32(responseLen), resp); err != nil {
		return nil, fmt.Errorf("rpccgo: message server response decode failed: %w", err)
	}
	return resp, nil
}

func (s *androidDeviceWatchAndroidEchoCGOMessageServerStreamingClient) Finish(ctx context.Context) error {
	errID := int32(C.callAndroidDeviceWatchAndroidEchoCGOMessageServerStreamFinish(s.finish, C.int32_t(s.stream)))
	if errID != 0 {
		return androidDeviceCGOMessageServerError(errID)
	}
	return nil
}

func (s *androidDeviceWatchAndroidEchoCGOMessageServerStreamingClient) Cancel(ctx context.Context) error {
	errID := int32(C.callAndroidDeviceWatchAndroidEchoCGOMessageServerStreamCancel(s.cancel, C.int32_t(s.stream)))
	if errID != 0 {
		return androidDeviceCGOMessageServerError(errID)
	}
	return nil
}

func (a *androidDeviceCGOMessageAdapter) CollectAndroidEchoStart(ctx context.Context) (rpcruntime.ClientStreamingClient[*proto.AndroidEchoRequest, *proto.AndroidEchoResponse], error) {
	if a == nil {
		return nil, androidDeviceCGOMessageServerCallbacksNil
	}
	if a.collectAndroidEchoStart == nil || a.collectAndroidEchoSend == nil || a.collectAndroidEchoFinish == nil || a.collectAndroidEchoCancel == nil {
		return nil, errors.New("rpccgo: AndroidDevice.CollectAndroidEcho cgo message server method is not implemented")
	}
	var stream C.int32_t
	errID := int32(C.callAndroidDeviceCollectAndroidEchoCGOMessageClientStreamStart(a.collectAndroidEchoStart, &stream))
	if errID != 0 {
		return nil, androidDeviceCGOMessageServerError(errID)
	}
	return &androidDeviceCollectAndroidEchoCGOMessageClientStreamingClient{send: a.collectAndroidEchoSend, finish: a.collectAndroidEchoFinish, cancel: a.collectAndroidEchoCancel, stream: int32(stream)}, nil
}

func (a *androidDeviceCGOMessageAdapter) CollectAndroidEcho(ctx context.Context, stream rpcruntime.ClientStreamingServer[*proto.AndroidEchoRequest]) (*proto.AndroidEchoResponse, error) {
	session, err := a.CollectAndroidEchoStart(ctx)
	if err != nil {
		return nil, err
	}
	for {
		req, err := stream.Recv(ctx)
		if err != nil {
			if errors.Is(err, io.EOF) {
				return session.Finish(ctx)
			}
			_ = session.Cancel(ctx)
			return nil, err
		}
		if err := session.Send(ctx, req); err != nil {
			_ = session.Cancel(ctx)
			return nil, err
		}
	}
}

type androidDeviceCollectAndroidEchoCGOMessageClientStreamingClient struct {
	send   C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamSendCallback
	finish C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamFinishCallback
	cancel C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamCancelCallback
	stream int32
}

func (s *androidDeviceCollectAndroidEchoCGOMessageClientStreamingClient) Send(ctx context.Context, req *proto.AndroidEchoRequest) error {
	if req == nil {
		err := errors.New("rpccgo: message request is nil")
		return err
	}
	reqBytes, err := protobuf.Marshal(req)
	if err != nil {
		err = fmt.Errorf("rpccgo: message request protobuf marshal failed: %w", err)
		return err
	}
	var requestPtr uintptr
	if len(reqBytes) != 0 {
		requestPtr = uintptr(unsafe.Pointer(&reqBytes[0]))
	}
	requestLen, err := rpcruntime.LengthToInt32(len(reqBytes))
	if err != nil {
		return err
	}
	errID := int32(C.callAndroidDeviceCollectAndroidEchoCGOMessageClientStreamSend(s.send, C.int32_t(s.stream), C.uintptr_t(requestPtr), C.int32_t(requestLen)))
	if errID != 0 {
		return androidDeviceCGOMessageServerError(errID)
	}
	return nil
}

func (s *androidDeviceCollectAndroidEchoCGOMessageClientStreamingClient) Finish(ctx context.Context) (*proto.AndroidEchoResponse, error) {
	var responsePtr C.uintptr_t
	var responseLen C.int32_t
	errID := int32(C.callAndroidDeviceCollectAndroidEchoCGOMessageClientStreamFinish(s.finish, C.int32_t(s.stream), &responsePtr, &responseLen))
	if errID != 0 {
		return nil, androidDeviceCGOMessageServerError(errID)
	}
	resp := &proto.AndroidEchoResponse{}
	if err := rpcruntime.DecodeMessage(uintptr(responsePtr), int32(responseLen), resp); err != nil {
		return nil, fmt.Errorf("rpccgo: message server response decode failed: %w", err)
	}
	return resp, nil
}

func (s *androidDeviceCollectAndroidEchoCGOMessageClientStreamingClient) Cancel(ctx context.Context) error {
	errID := int32(C.callAndroidDeviceCollectAndroidEchoCGOMessageClientStreamCancel(s.cancel, C.int32_t(s.stream)))
	if errID != 0 {
		return androidDeviceCGOMessageServerError(errID)
	}
	return nil
}

func (a *androidDeviceCGOMessageAdapter) ChatAndroidEchoStart(ctx context.Context) (rpcruntime.BidiStreamingClient[*proto.AndroidEchoRequest, *proto.AndroidEchoResponse], error) {
	if a == nil {
		return nil, androidDeviceCGOMessageServerCallbacksNil
	}
	if a.chatAndroidEchoStart == nil || a.chatAndroidEchoSend == nil || a.chatAndroidEchoRecv == nil || a.chatAndroidEchoCloseSend == nil || a.chatAndroidEchoFinish == nil || a.chatAndroidEchoCancel == nil {
		return nil, errors.New("rpccgo: AndroidDevice.ChatAndroidEcho cgo message server method is not implemented")
	}
	var stream C.int32_t
	errID := int32(C.callAndroidDeviceChatAndroidEchoCGOMessageBidiStreamStart(a.chatAndroidEchoStart, &stream))
	if errID != 0 {
		return nil, androidDeviceCGOMessageServerError(errID)
	}
	return &androidDeviceChatAndroidEchoCGOMessageBidiStreamingClient{send: a.chatAndroidEchoSend, recv: a.chatAndroidEchoRecv, closeSend: a.chatAndroidEchoCloseSend, finish: a.chatAndroidEchoFinish, cancel: a.chatAndroidEchoCancel, stream: int32(stream)}, nil
}

func (a *androidDeviceCGOMessageAdapter) ChatAndroidEcho(ctx context.Context, stream rpcruntime.BidiStreamingServer[*proto.AndroidEchoRequest, *proto.AndroidEchoResponse]) error {
	session, err := a.ChatAndroidEchoStart(ctx)
	if err != nil {
		return err
	}
	bridgeCtx, cancelBridge := context.WithCancel(ctx)
	defer cancelBridge()
	cancelSession := sync.OnceValue(func() error { return session.Cancel(bridgeCtx) })
	errs := make(chan error, 2)
	go func() {
		for {
			req, err := stream.Recv(bridgeCtx)
			if errors.Is(err, io.EOF) {
				errs <- session.CloseSend(bridgeCtx)
				return
			}
			if err != nil {
				errs <- err
				return
			}
			if err := session.Send(bridgeCtx, req); err != nil {
				errs <- err
				return
			}
		}
	}()
	go func() {
		for {
			resp, err, stopped := androidDeviceAwaitCGOMessageRecv(bridgeCtx, stream.FinishRequested(), func() (*proto.AndroidEchoResponse, error) { return session.Recv(bridgeCtx) }, func() error { return session.Finish(bridgeCtx) }, cancelSession)
			if stopped {
				errs <- err
				return
			}
			if errors.Is(err, io.EOF) {
				errs <- session.Finish(bridgeCtx)
				return
			}
			if err != nil {
				errs <- err
				return
			}
			if err := stream.Send(bridgeCtx, resp); err != nil {
				if errors.Is(err, io.EOF) {
					if finishErr := session.Finish(bridgeCtx); finishErr != nil {
						errs <- errors.Join(err, finishErr)
						return
					}
					errs <- nil
					return
				}
				errs <- err
				return
			}
		}
	}()
	var resultErr error
	for range 2 {
		if err := <-errs; err != nil {
			if resultErr == nil {
				_ = cancelSession()
				cancelBridge()
			}
			resultErr = errors.Join(resultErr, err)
		}
	}
	return resultErr
}

type androidDeviceChatAndroidEchoCGOMessageBidiStreamingClient struct {
	send      C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamSendCallback
	recv      C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamRecvCallback
	closeSend C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamCloseSendCallback
	finish    C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamFinishCallback
	cancel    C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamCancelCallback
	stream    int32
}

func (s *androidDeviceChatAndroidEchoCGOMessageBidiStreamingClient) Send(ctx context.Context, req *proto.AndroidEchoRequest) error {
	if req == nil {
		err := errors.New("rpccgo: message request is nil")
		return err
	}
	reqBytes, err := protobuf.Marshal(req)
	if err != nil {
		err = fmt.Errorf("rpccgo: message request protobuf marshal failed: %w", err)
		return err
	}
	var requestPtr uintptr
	if len(reqBytes) != 0 {
		requestPtr = uintptr(unsafe.Pointer(&reqBytes[0]))
	}
	requestLen, err := rpcruntime.LengthToInt32(len(reqBytes))
	if err != nil {
		return err
	}
	errID := int32(C.callAndroidDeviceChatAndroidEchoCGOMessageBidiStreamSend(s.send, C.int32_t(s.stream), C.uintptr_t(requestPtr), C.int32_t(requestLen)))
	if errID != 0 {
		return androidDeviceCGOMessageServerError(errID)
	}
	return nil
}

func (s *androidDeviceChatAndroidEchoCGOMessageBidiStreamingClient) Recv(ctx context.Context) (*proto.AndroidEchoResponse, error) {
	var responsePtr C.uintptr_t
	var responseLen C.int32_t
	errID := int32(C.callAndroidDeviceChatAndroidEchoCGOMessageBidiStreamRecv(s.recv, C.int32_t(s.stream), &responsePtr, &responseLen))
	if errID != 0 {
		return nil, androidDeviceCGOMessageServerError(errID)
	}
	resp := &proto.AndroidEchoResponse{}
	if err := rpcruntime.DecodeMessage(uintptr(responsePtr), int32(responseLen), resp); err != nil {
		return nil, fmt.Errorf("rpccgo: message server response decode failed: %w", err)
	}
	return resp, nil
}

func (s *androidDeviceChatAndroidEchoCGOMessageBidiStreamingClient) CloseSend(ctx context.Context) error {
	errID := int32(C.callAndroidDeviceChatAndroidEchoCGOMessageBidiStreamCloseSend(s.closeSend, C.int32_t(s.stream)))
	if errID != 0 {
		return androidDeviceCGOMessageServerError(errID)
	}
	return nil
}

func (s *androidDeviceChatAndroidEchoCGOMessageBidiStreamingClient) Finish(ctx context.Context) error {
	errID := int32(C.callAndroidDeviceChatAndroidEchoCGOMessageBidiStreamFinish(s.finish, C.int32_t(s.stream)))
	if errID != 0 {
		return androidDeviceCGOMessageServerError(errID)
	}
	return nil
}

func (s *androidDeviceChatAndroidEchoCGOMessageBidiStreamingClient) Cancel(ctx context.Context) error {
	errID := int32(C.callAndroidDeviceChatAndroidEchoCGOMessageBidiStreamCancel(s.cancel, C.int32_t(s.stream)))
	if errID != 0 {
		return androidDeviceCGOMessageServerError(errID)
	}
	return nil
}

// rpccgoMsgFluttersharedv1AndroidDeviceRegister registers cgo message callbacks as the current server for examples.flutter.sharedso.v1.AndroidDevice.
//
//export rpccgoMsgFluttersharedv1AndroidDeviceRegister
func rpccgoMsgFluttersharedv1AndroidDeviceRegister(setTorchCallback C.AndroidDeviceSetTorchCGOMessageUnaryCallback, watchAndroidEchoStart C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamStartCallback, watchAndroidEchoRecv C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamRecvCallback, watchAndroidEchoFinish C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamFinishCallback, watchAndroidEchoCancel C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamCancelCallback, collectAndroidEchoStart C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamStartCallback, collectAndroidEchoSend C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamSendCallback, collectAndroidEchoFinish C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamFinishCallback, collectAndroidEchoCancel C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamCancelCallback, chatAndroidEchoStart C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamStartCallback, chatAndroidEchoSend C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamSendCallback, chatAndroidEchoRecv C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamRecvCallback, chatAndroidEchoCloseSend C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamCloseSendCallback, chatAndroidEchoFinish C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamFinishCallback, chatAndroidEchoCancel C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamCancelCallback) C.int32_t {
	androidDeviceCGOMessageServerAdapterMu.Lock()
	defer androidDeviceCGOMessageServerAdapterMu.Unlock()
	next := androidDeviceCGOMessageServerAdapterForRegister()
	var registerErr error
	if setTorchCallback != nil {
		next.SetTorchCallback = setTorchCallback
	}
	if watchAndroidEchoStart == nil && watchAndroidEchoRecv == nil && watchAndroidEchoFinish == nil && watchAndroidEchoCancel == nil {
		// Preserve existing callbacks for methods omitted from a service-level update.
	} else if watchAndroidEchoStart != nil && watchAndroidEchoRecv != nil && watchAndroidEchoFinish != nil && watchAndroidEchoCancel != nil {
		next.watchAndroidEchoStart = watchAndroidEchoStart
		next.watchAndroidEchoRecv = watchAndroidEchoRecv
		next.watchAndroidEchoFinish = watchAndroidEchoFinish
		next.watchAndroidEchoCancel = watchAndroidEchoCancel
	} else {
		next.watchAndroidEchoStart = nil
		next.watchAndroidEchoRecv = nil
		next.watchAndroidEchoFinish = nil
		next.watchAndroidEchoCancel = nil
		registerErr = errors.Join(registerErr, fmt.Errorf("%w: %s", androidDeviceCGOMessageServerStreamPartiallyRegistered, "examples.flutter.sharedso.v1.AndroidDevice.WatchAndroidEcho"))
	}
	if collectAndroidEchoStart == nil && collectAndroidEchoSend == nil && collectAndroidEchoFinish == nil && collectAndroidEchoCancel == nil {
		// Preserve existing callbacks for methods omitted from a service-level update.
	} else if collectAndroidEchoStart != nil && collectAndroidEchoSend != nil && collectAndroidEchoFinish != nil && collectAndroidEchoCancel != nil {
		next.collectAndroidEchoStart = collectAndroidEchoStart
		next.collectAndroidEchoSend = collectAndroidEchoSend
		next.collectAndroidEchoFinish = collectAndroidEchoFinish
		next.collectAndroidEchoCancel = collectAndroidEchoCancel
	} else {
		next.collectAndroidEchoStart = nil
		next.collectAndroidEchoSend = nil
		next.collectAndroidEchoFinish = nil
		next.collectAndroidEchoCancel = nil
		registerErr = errors.Join(registerErr, fmt.Errorf("%w: %s", androidDeviceCGOMessageServerStreamPartiallyRegistered, "examples.flutter.sharedso.v1.AndroidDevice.CollectAndroidEcho"))
	}
	if chatAndroidEchoStart == nil && chatAndroidEchoSend == nil && chatAndroidEchoRecv == nil && chatAndroidEchoCloseSend == nil && chatAndroidEchoFinish == nil && chatAndroidEchoCancel == nil {
		// Preserve existing callbacks for methods omitted from a service-level update.
	} else if chatAndroidEchoStart != nil && chatAndroidEchoSend != nil && chatAndroidEchoRecv != nil && chatAndroidEchoCloseSend != nil && chatAndroidEchoFinish != nil && chatAndroidEchoCancel != nil {
		next.chatAndroidEchoStart = chatAndroidEchoStart
		next.chatAndroidEchoSend = chatAndroidEchoSend
		next.chatAndroidEchoRecv = chatAndroidEchoRecv
		next.chatAndroidEchoCloseSend = chatAndroidEchoCloseSend
		next.chatAndroidEchoFinish = chatAndroidEchoFinish
		next.chatAndroidEchoCancel = chatAndroidEchoCancel
	} else {
		next.chatAndroidEchoStart = nil
		next.chatAndroidEchoSend = nil
		next.chatAndroidEchoRecv = nil
		next.chatAndroidEchoCloseSend = nil
		next.chatAndroidEchoFinish = nil
		next.chatAndroidEchoCancel = nil
		registerErr = errors.Join(registerErr, fmt.Errorf("%w: %s", androidDeviceCGOMessageServerStreamPartiallyRegistered, "examples.flutter.sharedso.v1.AndroidDevice.ChatAndroidEcho"))
	}
	if err := proto.RegisterAndroidDeviceCGOMessageServer(next); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	androidDeviceCGOMessageServerAdapter = next
	if registerErr != nil {
		return C.int32_t(rpcruntime.StoreError(registerErr))
	}
	return 0
}

// rpccgoMsgFluttersharedv1AndroidDeviceRegisterSetTorch registers cgo message callbacks for examples.flutter.sharedso.v1.AndroidDevice.SetTorch.
//
//export rpccgoMsgFluttersharedv1AndroidDeviceRegisterSetTorch
func rpccgoMsgFluttersharedv1AndroidDeviceRegisterSetTorch(setTorchCallback C.AndroidDeviceSetTorchCGOMessageUnaryCallback) C.int32_t {
	androidDeviceCGOMessageServerAdapterMu.Lock()
	defer androidDeviceCGOMessageServerAdapterMu.Unlock()
	next := androidDeviceCGOMessageServerAdapterForRegister()
	var registerErr error
	next.SetTorchCallback = setTorchCallback
	if err := proto.RegisterAndroidDeviceCGOMessageServer(next); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	androidDeviceCGOMessageServerAdapter = next
	if registerErr != nil {
		return C.int32_t(rpcruntime.StoreError(registerErr))
	}
	return 0
}

// rpccgoMsgFluttersharedv1AndroidDeviceRegisterWatchAndroidEcho registers cgo message callbacks for examples.flutter.sharedso.v1.AndroidDevice.WatchAndroidEcho.
//
//export rpccgoMsgFluttersharedv1AndroidDeviceRegisterWatchAndroidEcho
func rpccgoMsgFluttersharedv1AndroidDeviceRegisterWatchAndroidEcho(watchAndroidEchoStart C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamStartCallback, watchAndroidEchoRecv C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamRecvCallback, watchAndroidEchoFinish C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamFinishCallback, watchAndroidEchoCancel C.AndroidDeviceWatchAndroidEchoCGOMessageServerStreamCancelCallback) C.int32_t {
	androidDeviceCGOMessageServerAdapterMu.Lock()
	defer androidDeviceCGOMessageServerAdapterMu.Unlock()
	next := androidDeviceCGOMessageServerAdapterForRegister()
	var registerErr error
	if watchAndroidEchoStart == nil && watchAndroidEchoRecv == nil && watchAndroidEchoFinish == nil && watchAndroidEchoCancel == nil {
		next.watchAndroidEchoStart = nil
		next.watchAndroidEchoRecv = nil
		next.watchAndroidEchoFinish = nil
		next.watchAndroidEchoCancel = nil
	} else if watchAndroidEchoStart != nil && watchAndroidEchoRecv != nil && watchAndroidEchoFinish != nil && watchAndroidEchoCancel != nil {
		next.watchAndroidEchoStart = watchAndroidEchoStart
		next.watchAndroidEchoRecv = watchAndroidEchoRecv
		next.watchAndroidEchoFinish = watchAndroidEchoFinish
		next.watchAndroidEchoCancel = watchAndroidEchoCancel
	} else {
		next.watchAndroidEchoStart = nil
		next.watchAndroidEchoRecv = nil
		next.watchAndroidEchoFinish = nil
		next.watchAndroidEchoCancel = nil
		registerErr = errors.Join(registerErr, fmt.Errorf("%w: %s", androidDeviceCGOMessageServerStreamPartiallyRegistered, "examples.flutter.sharedso.v1.AndroidDevice.WatchAndroidEcho"))
	}
	if err := proto.RegisterAndroidDeviceCGOMessageServer(next); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	androidDeviceCGOMessageServerAdapter = next
	if registerErr != nil {
		return C.int32_t(rpcruntime.StoreError(registerErr))
	}
	return 0
}

// rpccgoMsgFluttersharedv1AndroidDeviceRegisterCollectAndroidEcho registers cgo message callbacks for examples.flutter.sharedso.v1.AndroidDevice.CollectAndroidEcho.
//
//export rpccgoMsgFluttersharedv1AndroidDeviceRegisterCollectAndroidEcho
func rpccgoMsgFluttersharedv1AndroidDeviceRegisterCollectAndroidEcho(collectAndroidEchoStart C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamStartCallback, collectAndroidEchoSend C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamSendCallback, collectAndroidEchoFinish C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamFinishCallback, collectAndroidEchoCancel C.AndroidDeviceCollectAndroidEchoCGOMessageClientStreamCancelCallback) C.int32_t {
	androidDeviceCGOMessageServerAdapterMu.Lock()
	defer androidDeviceCGOMessageServerAdapterMu.Unlock()
	next := androidDeviceCGOMessageServerAdapterForRegister()
	var registerErr error
	if collectAndroidEchoStart == nil && collectAndroidEchoSend == nil && collectAndroidEchoFinish == nil && collectAndroidEchoCancel == nil {
		next.collectAndroidEchoStart = nil
		next.collectAndroidEchoSend = nil
		next.collectAndroidEchoFinish = nil
		next.collectAndroidEchoCancel = nil
	} else if collectAndroidEchoStart != nil && collectAndroidEchoSend != nil && collectAndroidEchoFinish != nil && collectAndroidEchoCancel != nil {
		next.collectAndroidEchoStart = collectAndroidEchoStart
		next.collectAndroidEchoSend = collectAndroidEchoSend
		next.collectAndroidEchoFinish = collectAndroidEchoFinish
		next.collectAndroidEchoCancel = collectAndroidEchoCancel
	} else {
		next.collectAndroidEchoStart = nil
		next.collectAndroidEchoSend = nil
		next.collectAndroidEchoFinish = nil
		next.collectAndroidEchoCancel = nil
		registerErr = errors.Join(registerErr, fmt.Errorf("%w: %s", androidDeviceCGOMessageServerStreamPartiallyRegistered, "examples.flutter.sharedso.v1.AndroidDevice.CollectAndroidEcho"))
	}
	if err := proto.RegisterAndroidDeviceCGOMessageServer(next); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	androidDeviceCGOMessageServerAdapter = next
	if registerErr != nil {
		return C.int32_t(rpcruntime.StoreError(registerErr))
	}
	return 0
}

// rpccgoMsgFluttersharedv1AndroidDeviceRegisterChatAndroidEcho registers cgo message callbacks for examples.flutter.sharedso.v1.AndroidDevice.ChatAndroidEcho.
//
//export rpccgoMsgFluttersharedv1AndroidDeviceRegisterChatAndroidEcho
func rpccgoMsgFluttersharedv1AndroidDeviceRegisterChatAndroidEcho(chatAndroidEchoStart C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamStartCallback, chatAndroidEchoSend C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamSendCallback, chatAndroidEchoRecv C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamRecvCallback, chatAndroidEchoCloseSend C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamCloseSendCallback, chatAndroidEchoFinish C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamFinishCallback, chatAndroidEchoCancel C.AndroidDeviceChatAndroidEchoCGOMessageBidiStreamCancelCallback) C.int32_t {
	androidDeviceCGOMessageServerAdapterMu.Lock()
	defer androidDeviceCGOMessageServerAdapterMu.Unlock()
	next := androidDeviceCGOMessageServerAdapterForRegister()
	var registerErr error
	if chatAndroidEchoStart == nil && chatAndroidEchoSend == nil && chatAndroidEchoRecv == nil && chatAndroidEchoCloseSend == nil && chatAndroidEchoFinish == nil && chatAndroidEchoCancel == nil {
		next.chatAndroidEchoStart = nil
		next.chatAndroidEchoSend = nil
		next.chatAndroidEchoRecv = nil
		next.chatAndroidEchoCloseSend = nil
		next.chatAndroidEchoFinish = nil
		next.chatAndroidEchoCancel = nil
	} else if chatAndroidEchoStart != nil && chatAndroidEchoSend != nil && chatAndroidEchoRecv != nil && chatAndroidEchoCloseSend != nil && chatAndroidEchoFinish != nil && chatAndroidEchoCancel != nil {
		next.chatAndroidEchoStart = chatAndroidEchoStart
		next.chatAndroidEchoSend = chatAndroidEchoSend
		next.chatAndroidEchoRecv = chatAndroidEchoRecv
		next.chatAndroidEchoCloseSend = chatAndroidEchoCloseSend
		next.chatAndroidEchoFinish = chatAndroidEchoFinish
		next.chatAndroidEchoCancel = chatAndroidEchoCancel
	} else {
		next.chatAndroidEchoStart = nil
		next.chatAndroidEchoSend = nil
		next.chatAndroidEchoRecv = nil
		next.chatAndroidEchoCloseSend = nil
		next.chatAndroidEchoFinish = nil
		next.chatAndroidEchoCancel = nil
		registerErr = errors.Join(registerErr, fmt.Errorf("%w: %s", androidDeviceCGOMessageServerStreamPartiallyRegistered, "examples.flutter.sharedso.v1.AndroidDevice.ChatAndroidEcho"))
	}
	if err := proto.RegisterAndroidDeviceCGOMessageServer(next); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	androidDeviceCGOMessageServerAdapter = next
	if registerErr != nil {
		return C.int32_t(rpcruntime.StoreError(registerErr))
	}
	return 0
}

func androidDeviceCGOMessageServerAdapterForRegister() *androidDeviceCGOMessageAdapter {
	registered, err := proto.LoadAndroidDeviceRegisteredServer()
	if err == nil && registered.Kind == rpcruntime.ServerKindCGOMessage {
		if current, ok := registered.Server.(*androidDeviceCGOMessageAdapter); ok {
			next := *current
			return &next
		}
	}
	return &androidDeviceCGOMessageAdapter{}
}

func androidDeviceCGOMessageServerError(errID int32) error {
	if errID == 0 {
		return nil
	}
	text, ptr, ok := rpcruntime.TakeErrorText(rpcruntime.ErrorID(errID))
	if ok {
		if ptr != 0 {
			defer rpcruntime.Release(ptr)
		}
		if string(text) == io.EOF.Error() {
			return io.EOF
		}
		return errors.New(string(text))
	}
	return fmt.Errorf("rpccgo: cgo message server callback returned unknown error id %d", errID)
}
