// Code generated by protoc-gen-rpc-cgo. DO NOT EDIT.
//
// Source: shared_so.proto

package main

import (
	proto "example.com/rpccgo-flutter-shared-so/proto"
)

/*
#include <stdint.h>

typedef int32_t (*SharedSoDemoComposeGreetingCGOMessageUnaryCallback)(uintptr_t request_ptr, int32_t request_len, uintptr_t* response_ptr, int32_t* response_len);

typedef int32_t (*SharedSoDemoIncrementRuntimeStateCGOMessageUnaryCallback)(uintptr_t request_ptr, int32_t request_len, uintptr_t* response_ptr, int32_t* response_len);

typedef int32_t (*SharedSoDemoReadRuntimeStateCGOMessageUnaryCallback)(uintptr_t request_ptr, int32_t request_len, uintptr_t* response_ptr, int32_t* response_len);

static inline int32_t callSharedSoDemoComposeGreetingCGOMessageUnary(SharedSoDemoComposeGreetingCGOMessageUnaryCallback callback, uintptr_t request_ptr, int32_t request_len, uintptr_t* response_ptr, int32_t* response_len) {
	return callback(request_ptr, request_len, response_ptr, response_len);
}

static inline int32_t callSharedSoDemoIncrementRuntimeStateCGOMessageUnary(SharedSoDemoIncrementRuntimeStateCGOMessageUnaryCallback callback, uintptr_t request_ptr, int32_t request_len, uintptr_t* response_ptr, int32_t* response_len) {
	return callback(request_ptr, request_len, response_ptr, response_len);
}

static inline int32_t callSharedSoDemoReadRuntimeStateCGOMessageUnary(SharedSoDemoReadRuntimeStateCGOMessageUnaryCallback callback, uintptr_t request_ptr, int32_t request_len, uintptr_t* response_ptr, int32_t* response_len) {
	return callback(request_ptr, request_len, response_ptr, response_len);
}

*/
import "C"

import (
	context "context"
	errors "errors"
	fmt "fmt"
	io "io"
	protobuf "google.golang.org/protobuf/proto"
	rpcruntime "github.com/ygrpc/rpccgo/rpcruntime"
	sync "sync"
	unsafe "unsafe"
)

// rpccgo message direct generated file for SharedSoDemo cgo message server callbacks

var (
	sharedSoDemoCGOMessageServerCallbacksNil              = errors.New("rpccgo: SharedSoDemo cgo message server callbacks are nil")
	sharedSoDemoCGOMessageServerUnaryCallbackMissing      = errors.New("rpccgo: SharedSoDemo cgo message server unary callback is missing")
	sharedSoDemoCGOMessageServerStreamPartiallyRegistered = errors.New("rpccgo: SharedSoDemo cgo message server stream callbacks are partially registered")
	sharedSoDemoCGOMessageServerAdapterMu                 sync.Mutex
	sharedSoDemoCGOMessageServerAdapter                   = &sharedSoDemoCGOMessageAdapter{}
)

type sharedSoDemoCGOMessageAdapter struct {
	ComposeGreetingCallback       C.SharedSoDemoComposeGreetingCGOMessageUnaryCallback
	IncrementRuntimeStateCallback C.SharedSoDemoIncrementRuntimeStateCGOMessageUnaryCallback
	ReadRuntimeStateCallback      C.SharedSoDemoReadRuntimeStateCGOMessageUnaryCallback
}

// sharedSoDemoCGOMessageRecvResult carries the result of a blocking cgo message Recv callback.
type sharedSoDemoCGOMessageRecvResult[T any] struct {
	value T
	err   error
}

// sharedSoDemoAwaitCGOMessageRecv waits for a blocking cgo message Recv callback while allowing Finish or Cancel to interrupt the wait.
func sharedSoDemoAwaitCGOMessageRecv[T any](ctx context.Context, finishRequested <-chan struct{}, recv func() (T, error), finish func() error, cancel func() error) (T, error, bool) {
	select {
	case <-finishRequested:
		var zero T
		return zero, finish(), true
	case <-ctx.Done():
		var zero T
		return zero, errors.Join(ctx.Err(), cancel()), true
	default:
	}
	results := make(chan sharedSoDemoCGOMessageRecvResult[T], 1)
	go func() {
		value, err := recv()
		results <- sharedSoDemoCGOMessageRecvResult[T]{value: value, err: err}
	}()
	var zero T
	select {
	case result := <-results:
		return result.value, result.err, false
	case <-finishRequested:
		return zero, finish(), true
	case <-ctx.Done():
		return zero, errors.Join(ctx.Err(), cancel()), true
	}
}

func (a *sharedSoDemoCGOMessageAdapter) ComposeGreeting(ctx context.Context, req *proto.ComposeGreetingRequest) (*proto.ComposeGreetingResponse, error) {
	if a == nil {
		return nil, sharedSoDemoCGOMessageServerCallbacksNil
	}
	callback := a.ComposeGreetingCallback
	if callback == nil {
		return nil, errors.New("rpccgo: SharedSoDemo.ComposeGreeting cgo message server method is not implemented")
	}
	if req == nil {
		err := errors.New("rpccgo: message request is nil")
		return nil, err
	}
	reqBytes, err := protobuf.Marshal(req)
	if err != nil {
		err = fmt.Errorf("rpccgo: message request protobuf marshal failed: %w", err)
		return nil, err
	}
	var requestPtr uintptr
	if len(reqBytes) != 0 {
		requestPtr = uintptr(unsafe.Pointer(&reqBytes[0]))
	}
	requestLen, err := rpcruntime.LengthToInt32(len(reqBytes))
	if err != nil {
		return nil, err
	}
	var responsePtr C.uintptr_t
	var responseLen C.int32_t
	errID := int32(C.callSharedSoDemoComposeGreetingCGOMessageUnary(callback, C.uintptr_t(requestPtr), C.int32_t(requestLen), &responsePtr, &responseLen))
	if errID != 0 {
		return nil, sharedSoDemoCGOMessageServerError(errID)
	}
	resp := &proto.ComposeGreetingResponse{}
	if err := rpcruntime.DecodeMessage(uintptr(responsePtr), int32(responseLen), resp); err != nil {
		return nil, fmt.Errorf("rpccgo: message server response decode failed: %w", err)
	}
	return resp, nil
}

func (a *sharedSoDemoCGOMessageAdapter) IncrementRuntimeState(ctx context.Context, req *proto.IncrementRuntimeStateRequest) (*proto.RuntimeStateResponse, error) {
	if a == nil {
		return nil, sharedSoDemoCGOMessageServerCallbacksNil
	}
	callback := a.IncrementRuntimeStateCallback
	if callback == nil {
		return nil, errors.New("rpccgo: SharedSoDemo.IncrementRuntimeState cgo message server method is not implemented")
	}
	if req == nil {
		err := errors.New("rpccgo: message request is nil")
		return nil, err
	}
	reqBytes, err := protobuf.Marshal(req)
	if err != nil {
		err = fmt.Errorf("rpccgo: message request protobuf marshal failed: %w", err)
		return nil, err
	}
	var requestPtr uintptr
	if len(reqBytes) != 0 {
		requestPtr = uintptr(unsafe.Pointer(&reqBytes[0]))
	}
	requestLen, err := rpcruntime.LengthToInt32(len(reqBytes))
	if err != nil {
		return nil, err
	}
	var responsePtr C.uintptr_t
	var responseLen C.int32_t
	errID := int32(C.callSharedSoDemoIncrementRuntimeStateCGOMessageUnary(callback, C.uintptr_t(requestPtr), C.int32_t(requestLen), &responsePtr, &responseLen))
	if errID != 0 {
		return nil, sharedSoDemoCGOMessageServerError(errID)
	}
	resp := &proto.RuntimeStateResponse{}
	if err := rpcruntime.DecodeMessage(uintptr(responsePtr), int32(responseLen), resp); err != nil {
		return nil, fmt.Errorf("rpccgo: message server response decode failed: %w", err)
	}
	return resp, nil
}

func (a *sharedSoDemoCGOMessageAdapter) ReadRuntimeState(ctx context.Context, req *proto.ReadRuntimeStateRequest) (*proto.RuntimeStateResponse, error) {
	if a == nil {
		return nil, sharedSoDemoCGOMessageServerCallbacksNil
	}
	callback := a.ReadRuntimeStateCallback
	if callback == nil {
		return nil, errors.New("rpccgo: SharedSoDemo.ReadRuntimeState cgo message server method is not implemented")
	}
	if req == nil {
		err := errors.New("rpccgo: message request is nil")
		return nil, err
	}
	reqBytes, err := protobuf.Marshal(req)
	if err != nil {
		err = fmt.Errorf("rpccgo: message request protobuf marshal failed: %w", err)
		return nil, err
	}
	var requestPtr uintptr
	if len(reqBytes) != 0 {
		requestPtr = uintptr(unsafe.Pointer(&reqBytes[0]))
	}
	requestLen, err := rpcruntime.LengthToInt32(len(reqBytes))
	if err != nil {
		return nil, err
	}
	var responsePtr C.uintptr_t
	var responseLen C.int32_t
	errID := int32(C.callSharedSoDemoReadRuntimeStateCGOMessageUnary(callback, C.uintptr_t(requestPtr), C.int32_t(requestLen), &responsePtr, &responseLen))
	if errID != 0 {
		return nil, sharedSoDemoCGOMessageServerError(errID)
	}
	resp := &proto.RuntimeStateResponse{}
	if err := rpcruntime.DecodeMessage(uintptr(responsePtr), int32(responseLen), resp); err != nil {
		return nil, fmt.Errorf("rpccgo: message server response decode failed: %w", err)
	}
	return resp, nil
}

// rpccgoMsgFluttersharedv1SharedSoDemoRegister registers cgo message callbacks as the current server for examples.flutter.sharedso.v1.SharedSoDemo.
//
//export rpccgoMsgFluttersharedv1SharedSoDemoRegister
func rpccgoMsgFluttersharedv1SharedSoDemoRegister(composeGreetingCallback C.SharedSoDemoComposeGreetingCGOMessageUnaryCallback, incrementRuntimeStateCallback C.SharedSoDemoIncrementRuntimeStateCGOMessageUnaryCallback, readRuntimeStateCallback C.SharedSoDemoReadRuntimeStateCGOMessageUnaryCallback) C.int32_t {
	sharedSoDemoCGOMessageServerAdapterMu.Lock()
	defer sharedSoDemoCGOMessageServerAdapterMu.Unlock()
	next := sharedSoDemoCGOMessageServerAdapterForRegister()
	var registerErr error
	if composeGreetingCallback != nil {
		next.ComposeGreetingCallback = composeGreetingCallback
	}
	if incrementRuntimeStateCallback != nil {
		next.IncrementRuntimeStateCallback = incrementRuntimeStateCallback
	}
	if readRuntimeStateCallback != nil {
		next.ReadRuntimeStateCallback = readRuntimeStateCallback
	}
	if err := proto.RegisterSharedSoDemoCGOMessageServer(next); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	sharedSoDemoCGOMessageServerAdapter = next
	if registerErr != nil {
		return C.int32_t(rpcruntime.StoreError(registerErr))
	}
	return 0
}

// rpccgoMsgFluttersharedv1SharedSoDemoRegisterComposeGreeting registers cgo message callbacks for examples.flutter.sharedso.v1.SharedSoDemo.ComposeGreeting.
//
//export rpccgoMsgFluttersharedv1SharedSoDemoRegisterComposeGreeting
func rpccgoMsgFluttersharedv1SharedSoDemoRegisterComposeGreeting(composeGreetingCallback C.SharedSoDemoComposeGreetingCGOMessageUnaryCallback) C.int32_t {
	sharedSoDemoCGOMessageServerAdapterMu.Lock()
	defer sharedSoDemoCGOMessageServerAdapterMu.Unlock()
	next := sharedSoDemoCGOMessageServerAdapterForRegister()
	var registerErr error
	next.ComposeGreetingCallback = composeGreetingCallback
	if err := proto.RegisterSharedSoDemoCGOMessageServer(next); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	sharedSoDemoCGOMessageServerAdapter = next
	if registerErr != nil {
		return C.int32_t(rpcruntime.StoreError(registerErr))
	}
	return 0
}

// rpccgoMsgFluttersharedv1SharedSoDemoRegisterIncrementRuntimeState registers cgo message callbacks for examples.flutter.sharedso.v1.SharedSoDemo.IncrementRuntimeState.
//
//export rpccgoMsgFluttersharedv1SharedSoDemoRegisterIncrementRuntimeState
func rpccgoMsgFluttersharedv1SharedSoDemoRegisterIncrementRuntimeState(incrementRuntimeStateCallback C.SharedSoDemoIncrementRuntimeStateCGOMessageUnaryCallback) C.int32_t {
	sharedSoDemoCGOMessageServerAdapterMu.Lock()
	defer sharedSoDemoCGOMessageServerAdapterMu.Unlock()
	next := sharedSoDemoCGOMessageServerAdapterForRegister()
	var registerErr error
	next.IncrementRuntimeStateCallback = incrementRuntimeStateCallback
	if err := proto.RegisterSharedSoDemoCGOMessageServer(next); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	sharedSoDemoCGOMessageServerAdapter = next
	if registerErr != nil {
		return C.int32_t(rpcruntime.StoreError(registerErr))
	}
	return 0
}

// rpccgoMsgFluttersharedv1SharedSoDemoRegisterReadRuntimeState registers cgo message callbacks for examples.flutter.sharedso.v1.SharedSoDemo.ReadRuntimeState.
//
//export rpccgoMsgFluttersharedv1SharedSoDemoRegisterReadRuntimeState
func rpccgoMsgFluttersharedv1SharedSoDemoRegisterReadRuntimeState(readRuntimeStateCallback C.SharedSoDemoReadRuntimeStateCGOMessageUnaryCallback) C.int32_t {
	sharedSoDemoCGOMessageServerAdapterMu.Lock()
	defer sharedSoDemoCGOMessageServerAdapterMu.Unlock()
	next := sharedSoDemoCGOMessageServerAdapterForRegister()
	var registerErr error
	next.ReadRuntimeStateCallback = readRuntimeStateCallback
	if err := proto.RegisterSharedSoDemoCGOMessageServer(next); err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	sharedSoDemoCGOMessageServerAdapter = next
	if registerErr != nil {
		return C.int32_t(rpcruntime.StoreError(registerErr))
	}
	return 0
}

func sharedSoDemoCGOMessageServerAdapterForRegister() *sharedSoDemoCGOMessageAdapter {
	registered, err := proto.LoadSharedSoDemoRegisteredServer()
	if err == nil && registered.Kind == rpcruntime.ServerKindCGOMessage {
		if current, ok := registered.Server.(*sharedSoDemoCGOMessageAdapter); ok {
			next := *current
			return &next
		}
	}
	return &sharedSoDemoCGOMessageAdapter{}
}

func sharedSoDemoCGOMessageServerError(errID int32) error {
	if errID == 0 {
		return nil
	}
	text, ptr, ok := rpcruntime.TakeErrorText(rpcruntime.ErrorID(errID))
	if ok {
		if ptr != 0 {
			defer rpcruntime.Release(ptr)
		}
		if string(text) == io.EOF.Error() {
			return io.EOF
		}
		return errors.New(string(text))
	}
	return fmt.Errorf("rpccgo: cgo message server callback returned unknown error id %d", errID)
}

// SharedSoDemoCGOMessageStreamEOFErrorID stores io.EOF and returns its error id for cgo message stream callbacks.
func SharedSoDemoCGOMessageStreamEOFErrorID() int32 {
	return int32(rpcruntime.StoreError(io.EOF))
}
