// Code generated by protoc-gen-rpc-cgo. DO NOT EDIT.
//
// Source: shared_so.proto

package main

import (
	proto "example.com/rpccgo-flutter-shared-so/proto"
)

/*
#include <stdint.h>
*/
import "C"

import (
	context "context"
	errors "errors"
	fmt "fmt"
	rpcruntime "github.com/ygrpc/rpccgo/rpcruntime"
)

// rpccgo message direct generated file for SharedSoDemo cgo message client

// rpccgoMsgFluttersharedv1SharedSoDemoComposeGreeting invokes the message unary client entrypoint for examples.flutter.sharedso.v1.SharedSoDemo.ComposeGreeting.
//
//export rpccgoMsgFluttersharedv1SharedSoDemoComposeGreeting
func rpccgoMsgFluttersharedv1SharedSoDemoComposeGreeting(requestPtr C.uintptr_t, requestLen C.int32_t, responsePtr *C.uintptr_t, responseLen *C.int32_t) C.int32_t {
	ctx := context.Background()
	if responsePtr != nil {
		*responsePtr = 0
	}
	if responseLen != nil {
		*responseLen = 0
	}
	if responsePtr == nil || responseLen == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: message client output pointer is nil")))
	}
	req := &proto.ComposeGreetingRequest{}
	if err := rpcruntime.DecodeMessage(uintptr(requestPtr), int32(requestLen), req); err != nil {
		return C.int32_t(rpcruntime.StoreError(fmt.Errorf("rpccgo: message request decode failed: %w", err)))
	}
	resp, err := proto.InvokeSharedSoDemoMessageComposeGreeting(ctx, req)
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	ptr, length, err := rpcruntime.EncodeMessage(resp)
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(fmt.Errorf("rpccgo: message response encode failed: %w", err)))
	}
	*responsePtr = C.uintptr_t(ptr)
	*responseLen = C.int32_t(length)
	return 0
}

// rpccgoMsgFluttersharedv1SharedSoDemoIncrementRuntimeState invokes the message unary client entrypoint for examples.flutter.sharedso.v1.SharedSoDemo.IncrementRuntimeState.
//
//export rpccgoMsgFluttersharedv1SharedSoDemoIncrementRuntimeState
func rpccgoMsgFluttersharedv1SharedSoDemoIncrementRuntimeState(requestPtr C.uintptr_t, requestLen C.int32_t, responsePtr *C.uintptr_t, responseLen *C.int32_t) C.int32_t {
	ctx := context.Background()
	if responsePtr != nil {
		*responsePtr = 0
	}
	if responseLen != nil {
		*responseLen = 0
	}
	if responsePtr == nil || responseLen == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: message client output pointer is nil")))
	}
	req := &proto.IncrementRuntimeStateRequest{}
	if err := rpcruntime.DecodeMessage(uintptr(requestPtr), int32(requestLen), req); err != nil {
		return C.int32_t(rpcruntime.StoreError(fmt.Errorf("rpccgo: message request decode failed: %w", err)))
	}
	resp, err := proto.InvokeSharedSoDemoMessageIncrementRuntimeState(ctx, req)
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	ptr, length, err := rpcruntime.EncodeMessage(resp)
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(fmt.Errorf("rpccgo: message response encode failed: %w", err)))
	}
	*responsePtr = C.uintptr_t(ptr)
	*responseLen = C.int32_t(length)
	return 0
}

// rpccgoMsgFluttersharedv1SharedSoDemoReadRuntimeState invokes the message unary client entrypoint for examples.flutter.sharedso.v1.SharedSoDemo.ReadRuntimeState.
//
//export rpccgoMsgFluttersharedv1SharedSoDemoReadRuntimeState
func rpccgoMsgFluttersharedv1SharedSoDemoReadRuntimeState(requestPtr C.uintptr_t, requestLen C.int32_t, responsePtr *C.uintptr_t, responseLen *C.int32_t) C.int32_t {
	ctx := context.Background()
	if responsePtr != nil {
		*responsePtr = 0
	}
	if responseLen != nil {
		*responseLen = 0
	}
	if responsePtr == nil || responseLen == nil {
		return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: message client output pointer is nil")))
	}
	req := &proto.ReadRuntimeStateRequest{}
	if err := rpcruntime.DecodeMessage(uintptr(requestPtr), int32(requestLen), req); err != nil {
		return C.int32_t(rpcruntime.StoreError(fmt.Errorf("rpccgo: message request decode failed: %w", err)))
	}
	resp, err := proto.InvokeSharedSoDemoMessageReadRuntimeState(ctx, req)
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(err))
	}
	ptr, length, err := rpcruntime.EncodeMessage(resp)
	if err != nil {
		return C.int32_t(rpcruntime.StoreError(fmt.Errorf("rpccgo: message response encode failed: %w", err)))
	}
	*responsePtr = C.uintptr_t(ptr)
	*responseLen = C.int32_t(length)
	return 0
}
