package generator

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func renderRuntimeTransportMessageSessions(g *protogen.GeneratedFile, service ServicePlan, methods []runtimeMethodProjection) {
	for _, method := range methods {
		if service.Generation.MessageTransport == MessageTransportConnect {
			renderConnectDirectMessageSession(g, service, method)
			renderConnectRemoteMessageSession(g, service, method)
		}
		if service.Generation.MessageTransport == MessageTransportGRPC {
			renderGRPCDirectMessageSession(g, service, method)
			renderGRPCRemoteMessageSession(g, service, method)
		}
	}
}

func renderConnectDirectMessageSession(g *protogen.GeneratedFile, service ServicePlan, method runtimeMethodProjection) {
	wrapperName := connectDirectMessageSessionName(service.GoName, method)
	reqType := method.Message.RequestType
	respType := method.Message.ResponseType
	handlerName := service.GoName + "Handler"
	switch method.Stream.Shape {
	case runtimeStreamClient:
		renderConnectDirectGenericClientStream(g, method, wrapperName, reqType, respType, handlerName)
	case runtimeStreamServer:
		renderConnectDirectGenericServerStream(g, method, wrapperName, reqType, respType, handlerName)
	case runtimeStreamBidi:
		renderConnectDirectGenericBidiStream(g, method, wrapperName, reqType, respType, handlerName)
	}
}

func renderConnectDirectGenericClientStream(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, handlerName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, handler ", handlerName, ") rpcruntime.ClientStreamingClient[", reqPtrType, ", ", respPtrType, "] {")
	g.P("client, stream, streamCtx := rpcruntime.NewClientStreaming[", reqPtrType, ", ", respPtrType, "](ctx, rpcruntime.LocalStreamOptions{")
	g.P("RequestBuffer: 16,")
	g.P(`StreamClosed: errors.New("rpccgo: message stream is closed"),`)
	g.P(`NilRequest: errors.New("rpccgo: message request is nil"),`)
	g.P("})")
	g.P("go func() {")
	g.P("conn := &rpcruntime.ConnectStreamingHandlerConn{ReceiveFunc: func(message any) error {")
	g.P("target, ok := message.(", reqPtrType, ")")
	g.P(`if !ok || target == nil { return errors.New("rpccgo: connect handler stream request type mismatch") }`)
	g.P("req, err := stream.Recv(streamCtx)")
	g.P("if err != nil { return err }")
	g.P("*target = *req")
	g.P("return nil")
	g.P("}}")
	g.P("resp, err := handler.", method.Identity.MessageMethodRef, "(streamCtx, rpcruntime.NewConnectClientStream[", reqType, "](conn))")
	g.P("stream.Complete(resp, err)")
	g.P("}()")
	g.P("return client")
	g.P("}")
	g.P()
}

func renderConnectDirectGenericServerStream(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, handlerName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, handler ", handlerName, ", req ", reqPtrType, ") (rpcruntime.ServerStreamingClient[", respPtrType, "], error) {")
	g.P(`if req == nil { return nil, errors.New("rpccgo: message request is nil") }`)
	g.P("client, stream, streamCtx := rpcruntime.NewServerStreaming[", respPtrType, "](ctx, rpcruntime.LocalStreamOptions{")
	g.P("ResponseBuffer: 1,")
	g.P(`StreamClosed: errors.New("rpccgo: message stream is closed"),`)
	g.P(`NilResponse: errors.New("rpccgo: message response is nil"),`)
	g.P("})")
	g.P("go func() {")
	g.P("conn := &rpcruntime.ConnectStreamingHandlerConn{SendFunc: func(message any) error {")
	g.P("resp, ok := message.(", respPtrType, ")")
	g.P(`if !ok || resp == nil { return errors.New("rpccgo: connect handler stream response type mismatch") }`)
	g.P("return stream.Send(streamCtx, resp)")
	g.P("}}")
	g.P("stream.Complete(handler.", method.Identity.MessageMethodRef, "(streamCtx, req, rpcruntime.NewConnectServerStream[", respType, "](conn)))")
	g.P("}()")
	g.P("return client, nil")
	g.P("}")
	g.P()
}

func renderConnectDirectGenericBidiStream(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, handlerName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, handler ", handlerName, ") rpcruntime.BidiStreamingClient[", reqPtrType, ", ", respPtrType, "] {")
	g.P("client, stream, streamCtx := rpcruntime.NewBidiStreaming[", reqPtrType, ", ", respPtrType, "](ctx, rpcruntime.LocalStreamOptions{")
	g.P("RequestBuffer: 16,")
	g.P("ResponseBuffer: 1,")
	g.P(`StreamClosed: errors.New("rpccgo: message stream is closed"),`)
	g.P(`NilRequest: errors.New("rpccgo: message request is nil"),`)
	g.P(`NilResponse: errors.New("rpccgo: message response is nil"),`)
	g.P("})")
	g.P("go func() {")
	g.P("conn := &rpcruntime.ConnectStreamingHandlerConn{")
	g.P("ReceiveFunc: func(message any) error {")
	g.P("target, ok := message.(", reqPtrType, ")")
	g.P(`if !ok || target == nil { return errors.New("rpccgo: connect handler bidi request type mismatch") }`)
	g.P("req, err := stream.Recv(streamCtx)")
	g.P("if err != nil { return err }")
	g.P("*target = *req")
	g.P("return nil")
	g.P("},")
	g.P("SendFunc: func(message any) error {")
	g.P("resp, ok := message.(", respPtrType, ")")
	g.P(`if !ok || resp == nil { return errors.New("rpccgo: connect handler bidi response type mismatch") }`)
	g.P("return stream.Send(streamCtx, resp)")
	g.P("},")
	g.P("}")
	g.P("stream.Complete(handler.", method.Identity.MessageMethodRef, "(streamCtx, rpcruntime.NewConnectBidiStream[", reqType, ", ", respType, "](conn)))")
	g.P("}()")
	g.P("return client")
	g.P("}")
	g.P()
}

func renderConnectRemoteMessageSession(g *protogen.GeneratedFile, service ServicePlan, method runtimeMethodProjection) {
	wrapperName := connectRemoteMessageSessionName(service.GoName, method)
	reqType := method.Message.RequestType
	respType := method.Message.ResponseType
	switch method.Stream.Shape {
	case runtimeStreamClient:
		clientType := "interface { " + method.Identity.MessageMethodRef + "(context.Context) (*connect.ClientStreamForClientSimple[" + strings.TrimPrefix(reqType, "*") + ", " + strings.TrimPrefix(respType, "*") + "], error) }"
		renderConnectRemoteClientStreamSession(g, method, wrapperName, reqType, respType, clientType)
	case runtimeStreamServer:
		clientType := "interface { " + method.Identity.MessageMethodRef + "(context.Context, *" + strings.TrimPrefix(reqType, "*") + ") (*connect.ServerStreamForClient[" + strings.TrimPrefix(respType, "*") + "], error) }"
		renderConnectRemoteServerStreamSession(g, method, wrapperName, reqType, respType, clientType)
	case runtimeStreamBidi:
		clientType := "interface { " + method.Identity.MessageMethodRef + "(context.Context) (*connect.BidiStreamForClientSimple[" + strings.TrimPrefix(reqType, "*") + ", " + strings.TrimPrefix(respType, "*") + "], error) }"
		renderConnectRemoteBidiStreamSession(g, method, wrapperName, reqType, respType, clientType)
	}
}

func renderConnectRemoteClientStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, clientType string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, client ", clientType, ") (*", wrapperName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := client.", method.Identity.MessageMethodRef, "(streamCtx)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", wrapperName, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("stream *connect.ClientStreamForClientSimple[", reqType, ", ", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Send(ctx context.Context, req ", reqPtrType, ") error {")
	g.P("_ = ctx")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("if s == nil {")
	g.P(`return errors.New("rpccgo: connect remote client stream is nil")`)
	g.P("}")
	g.P("if s.stream == nil {")
	g.P(`return errors.New("rpccgo: connect remote client stream is nil")`)
	g.P("}")
	g.P("return s.stream.Send(req)")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) (", respPtrType, ", error) {")
	g.P("_ = ctx")
	g.P("if s == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote client stream is nil")`)
	g.P("}")
	g.P("if s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote client stream is nil")`)
	g.P("}")
	g.P("defer func() { if s.cancel != nil { s.cancel() } }()")
	g.P("resp, err := s.stream.CloseAndReceive()")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("if resp == nil {")
	g.P(`return nil, errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("return resp, nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s != nil && s.stream != nil {")
	g.P("closed := make(chan struct{})")
	g.P("go func() {")
	g.P("_, _ = s.stream.CloseAndReceive()")
	g.P("close(closed)")
	g.P("}()")
	g.P("timer := time.NewTimer(100 * time.Millisecond)")
	g.P("select {")
	g.P("case <-closed:")
	g.P("timer.Stop()")
	g.P("return nil")
	g.P("case <-timer.C:")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("select {")
	g.P("case <-closed:")
	g.P("case <-time.After(500 * time.Millisecond):")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P("if s != nil && s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P()
}

func renderConnectRemoteServerStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, clientType string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, client ", clientType, ", req ", reqPtrType, ") (*", wrapperName, ", error) {")
	g.P("if req == nil {")
	g.P(`return nil, errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := client.", method.Identity.MessageMethodRef, "(streamCtx, req)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", wrapperName, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("stream *connect.ServerStreamForClient[", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()
	renderConnectRemoteRecvFinishCancel(g, wrapperName, "server stream", respPtrType)
}

func renderConnectRemoteBidiStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, clientType string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, client ", clientType, ") (*", wrapperName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := client.", method.Identity.MessageMethodRef, "(streamCtx)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", wrapperName, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("stream *connect.BidiStreamForClientSimple[", reqType, ", ", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Send(ctx context.Context, req ", reqPtrType, ") error {")
	g.P("_ = ctx")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("if s == nil {")
	g.P(`return errors.New("rpccgo: connect remote bidi stream is nil")`)
	g.P("}")
	g.P("if s.stream == nil {")
	g.P(`return errors.New("rpccgo: connect remote bidi stream is nil")`)
	g.P("}")
	g.P("return s.stream.Send(req)")
	g.P("}")
	g.P()
	renderConnectRemoteBidiRecvFinishCancel(g, wrapperName, respPtrType)
	g.P("func (s *", wrapperName, ") CloseSend(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("return s.stream.CloseRequest()")
	g.P("}")
	g.P()
}

func renderConnectRemoteRecvFinishCancel(g *protogen.GeneratedFile, wrapperName, label, respType string) {
	g.P("func (s *", wrapperName, ") Recv(ctx context.Context) (", respType, ", error) {")
	g.P("_ = ctx")
	g.P("if s == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote `, label, ` is nil")`)
	g.P("}")
	g.P("if s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote `, label, ` is nil")`)
	g.P("}")
	g.P("if !s.stream.Receive() {")
	g.P("if err := s.stream.Err(); err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("msg := s.stream.Msg()")
	g.P("if msg == nil {")
	g.P(`return nil, errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("return msg, nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("defer s.cancel()")
	g.P("}")
	g.P("return s.stream.Close()")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P()
}

func renderConnectRemoteBidiRecvFinishCancel(g *protogen.GeneratedFile, wrapperName, respType string) {
	g.P("func (s *", wrapperName, ") Recv(ctx context.Context) (", respType, ", error) {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote bidi stream is nil")`)
	g.P("}")
	g.P("resp, err := s.stream.Receive()")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("if resp == nil {")
	g.P(`return nil, errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("return resp, nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("defer s.cancel()")
	g.P("}")
	g.P("return s.stream.CloseResponse()")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P()
}

func renderGRPCDirectMessageSession(g *protogen.GeneratedFile, service ServicePlan, method runtimeMethodProjection) {
	wrapperName := grpcDirectMessageSessionName(service.GoName, method)
	reqType := method.Message.RequestType
	respType := method.Message.ResponseType
	serverName := service.GoName + "Server"
	switch method.Stream.Shape {
	case runtimeStreamClient:
		renderGRPCDirectGenericClientStream(g, method, wrapperName, reqType, respType, serverName)
	case runtimeStreamServer:
		renderGRPCDirectGenericServerStream(g, method, wrapperName, reqType, respType, serverName)
	case runtimeStreamBidi:
		renderGRPCDirectGenericBidiStream(g, method, wrapperName, reqType, respType, serverName)
	}
}

func renderGRPCDirectGenericClientStream(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, serverName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, server ", serverName, ") rpcruntime.ClientStreamingClient[", reqPtrType, ", ", respPtrType, "] {")
	g.P("client, stream, streamCtx := rpcruntime.NewClientStreaming[", reqPtrType, ", ", respPtrType, "](ctx, rpcruntime.LocalStreamOptions{")
	g.P("RequestBuffer: 16,")
	g.P(`StreamClosed: errors.New("rpccgo: message stream is closed"),`)
	g.P(`NilRequest: errors.New("rpccgo: message request is nil"),`)
	g.P("})")
	g.P("grpcStream := rpcruntime.NewGRPCClientStreamingServer[", reqType, ", ", respType, "](streamCtx, stream)")
	g.P("go func() { grpcStream.Complete(server.", method.Identity.MessageMethodRef, "(grpcStream)) }()")
	g.P("return client")
	g.P("}")
	g.P()
}

func renderGRPCDirectGenericServerStream(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, serverName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, server ", serverName, ", req ", reqPtrType, ") (rpcruntime.ServerStreamingClient[", respPtrType, "], error) {")
	g.P(`if req == nil { return nil, errors.New("rpccgo: message request is nil") }`)
	g.P("client, stream, streamCtx := rpcruntime.NewServerStreaming[", respPtrType, "](ctx, rpcruntime.LocalStreamOptions{")
	g.P("ResponseBuffer: 1,")
	g.P(`StreamClosed: errors.New("rpccgo: message stream is closed"),`)
	g.P(`NilResponse: errors.New("rpccgo: message response is nil"),`)
	g.P("})")
	g.P("grpcStream := rpcruntime.NewGRPCServerStreamingServer[", respType, "](streamCtx, stream)")
	g.P("go func() { stream.Complete(server.", method.Identity.MessageMethodRef, "(req, grpcStream)) }()")
	g.P("return client, nil")
	g.P("}")
	g.P()
}

func renderGRPCDirectGenericBidiStream(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, serverName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, server ", serverName, ") rpcruntime.BidiStreamingClient[", reqPtrType, ", ", respPtrType, "] {")
	g.P("client, stream, streamCtx := rpcruntime.NewBidiStreaming[", reqPtrType, ", ", respPtrType, "](ctx, rpcruntime.LocalStreamOptions{")
	g.P("RequestBuffer: 16,")
	g.P("ResponseBuffer: 1,")
	g.P(`StreamClosed: errors.New("rpccgo: message stream is closed"),`)
	g.P(`NilRequest: errors.New("rpccgo: message request is nil"),`)
	g.P(`NilResponse: errors.New("rpccgo: message response is nil"),`)
	g.P("})")
	g.P("grpcStream := rpcruntime.NewGRPCBidiStreamingServer[", reqType, ", ", respType, "](streamCtx, stream)")
	g.P("go func() { stream.Complete(server.", method.Identity.MessageMethodRef, "(grpcStream)) }()")
	g.P("return client")
	g.P("}")
	g.P()
}

func renderGRPCRemoteMessageSession(g *protogen.GeneratedFile, service ServicePlan, method runtimeMethodProjection) {
	wrapperName := grpcRemoteMessageSessionName(service.GoName, method)
	reqType := method.Message.RequestType
	respType := method.Message.ResponseType
	clientName := service.GoName + "Client"
	switch method.Stream.Shape {
	case runtimeStreamClient:
		renderGRPCRemoteClientStreamSession(g, method, wrapperName, reqType, respType, clientName)
	case runtimeStreamServer:
		renderGRPCRemoteServerStreamSession(g, method, wrapperName, reqType, respType, clientName)
	case runtimeStreamBidi:
		renderGRPCRemoteBidiStreamSession(g, method, wrapperName, reqType, respType, clientName)
	}
}

func renderGRPCRemoteClientStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, clientName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, client ", clientName, ") (*", wrapperName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := client.", method.Identity.MessageMethodRef, "(streamCtx)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", wrapperName, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("stream grpc.ClientStreamingClient[", reqType, ", ", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Send(ctx context.Context, req ", reqPtrType, ") error {")
	g.P("_ = ctx")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return errors.New("rpccgo: grpc remote client stream is nil")`)
	g.P("}")
	g.P("return s.stream.Send(req)")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) (", respPtrType, ", error) {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: grpc remote client stream is nil")`)
	g.P("}")
	g.P("defer func() { if s.cancel != nil { s.cancel() } }()")
	g.P("response, err := s.stream.CloseAndRecv()")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("if response == nil {")
	g.P(`return nil, errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("return response, nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return s.stream.CloseSend()")
	g.P("}")
	g.P()
}

func renderGRPCRemoteServerStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, clientName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, client ", clientName, ", req ", reqPtrType, ") (*", wrapperName, ", error) {")
	g.P("if req == nil {")
	g.P(`return nil, errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := client.", method.Identity.MessageMethodRef, "(streamCtx, req)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", wrapperName, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("stream grpc.ServerStreamingClient[", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()
	renderGRPCRemoteRecvFinishCancel(g, wrapperName, "server stream", respPtrType)
}

func renderGRPCRemoteBidiStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, clientName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, client ", clientName, ") (*", wrapperName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := client.", method.Identity.MessageMethodRef, "(streamCtx)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", wrapperName, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("stream grpc.BidiStreamingClient[", reqType, ", ", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Send(ctx context.Context, req ", reqPtrType, ") error {")
	g.P("_ = ctx")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return errors.New("rpccgo: grpc remote bidi stream is nil")`)
	g.P("}")
	g.P("return s.stream.Send(req)")
	g.P("}")
	g.P()
	renderGRPCRemoteRecvFinishCancel(g, wrapperName, "bidi stream", respPtrType)
	g.P("func (s *", wrapperName, ") CloseSend(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("return s.stream.CloseSend()")
	g.P("}")
	g.P()
}

func renderGRPCRemoteRecvFinishCancel(g *protogen.GeneratedFile, wrapperName, label, respPtrType string) {
	g.P("func (s *", wrapperName, ") Recv(ctx context.Context) (", respPtrType, ", error) {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: grpc remote `, label, ` is nil")`)
	g.P("}")
	g.P("response, err := s.stream.Recv()")
	g.P("if err != nil {")
	g.P("if errors.Is(err, io.EOF) {")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("return nil, err")
	g.P("}")
	g.P("if response == nil {")
	g.P(`return nil, errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("return response, nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s != nil && s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return s.stream.CloseSend()")
	g.P("}")
	g.P()
}

func grpcDirectMessageSessionName(serviceName string, method runtimeMethodProjection) string {
	return lowerInitial(serviceName) + method.Identity.GoName + "GRPCDirectMessageStreamSession"
}

func connectDirectMessageSessionName(serviceName string, method runtimeMethodProjection) string {
	return lowerInitial(serviceName) + method.Identity.GoName + "ConnectDirectMessageStreamSession"
}

func grpcRemoteMessageSessionName(serviceName string, method runtimeMethodProjection) string {
	return lowerInitial(serviceName) + method.Identity.GoName + "GRPCRemoteMessageStreamSession"
}

func connectRemoteMessageSessionName(serviceName string, method runtimeMethodProjection) string {
	return lowerInitial(serviceName) + method.Identity.GoName + "ConnectRemoteMessageStreamSession"
}
