package generator

import "google.golang.org/protobuf/compiler/protogen"

func renderGRPCRemoteFile(plugin *protogen.Plugin, plan FilePlan, service ServicePlan, file GeneratedFilePlan) error {
	g := newGeneratedFile(plugin, plan, file, protogen.GoImportPath(plan.GoImportPath))

	g.P("package ", plan.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`context "context"`)
	g.P(`errors "errors"`)
	if serviceHasStreamingMethod(service) {
		g.P(`io "io"`)
		g.P(`grpc "google.golang.org/grpc"`)
	}
	g.P(`codes "google.golang.org/grpc/codes"`)
	g.P(`status "google.golang.org/grpc/status"`)
	g.P(`proto "google.golang.org/protobuf/proto"`)
	g.P(`rpcruntime "rpccgo/rpcruntime"`)
	g.P(")")
	g.P()
	g.P("// ", messageStageMarker(service, file))
	g.P()

	typeName := service.GoName + "GRPCRemoteServer"
	g.P("type ", typeName, " struct {")
	g.P("client ", service.GoName, "Client")
	g.P("}")
	g.P()

	g.P("func New", typeName, "(client ", service.GoName, "Client) (*", typeName, ", error) {")
	g.P("if client == nil {")
	g.P(`return nil, errors.New("rpccgo: grpc remote client is nil")`)
	g.P("}")
	g.P("return &", typeName, "{client: client}, nil")
	g.P("}")
	g.P()

	g.P("func Register", typeName, "(client ", service.GoName, "Client) (rpcruntime.AdapterSnapshot[", service.GoName, "MessageAdapter], error) {")
	g.P("adapter, err := New", typeName, "(client)")
	g.P("if err != nil {")
	g.P("return rpcruntime.AdapterSnapshot[", service.GoName, "MessageAdapter]{}, err")
	g.P("}")
	g.P("return Register", service.GoName, "CGOMessageActiveServer(rpcruntime.ServerKindGRPCRemote, adapter)")
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		switch method.Streaming {
		case StreamingKindUnary:
			renderGRPCRemoteUnary(g, method, typeName)
		case StreamingKindClientStreaming:
			renderGRPCRemoteClientStreaming(g, service, method, typeName)
		case StreamingKindServerStreaming:
			renderGRPCRemoteServerStreaming(g, service, method, typeName)
		case StreamingKindBidiStreaming:
			renderGRPCRemoteBidiStreaming(g, service, method, typeName)
		}
	}

	return nil
}

func renderGRPCRemoteUnary(g *protogen.GeneratedFile, method MethodPlan, typeName string) {
	reqType := qualifiedMethodType(g, method.Request)

	g.P("func (s *", typeName, ") ", method.GoName, "Message(ctx context.Context, req []byte) ([]byte, error) {")
	g.P("if s == nil || s.client == nil {")
	g.P(`return nil, errors.New("rpccgo: grpc remote client is nil")`)
	g.P("}")
	g.P("request := new(", reqType, ")")
	g.P("if err := proto.Unmarshal(req, request); err != nil {")
	g.P(`return nil, status.Errorf(codes.InvalidArgument, "rpccgo: grpc remote request protobuf unmarshal failed: %v", err)`)
	g.P("}")
	g.P("response, err := s.client.", method.GoName, "(ctx, request)")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("respData, err := proto.Marshal(response)")
	g.P("if err != nil {")
	g.P(`return nil, status.Errorf(codes.Internal, "rpccgo: grpc remote response protobuf marshal failed: %v", err)`)
	g.P("}")
	g.P("return respData, nil")
	g.P("}")
	g.P()
}

func renderGRPCRemoteClientStreaming(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan, typeName string) {
	reqType := qualifiedMethodType(g, method.Request)
	respType := qualifiedMethodType(g, method.Response)
	sessionType := service.GoName + method.GoName + "GRPCRemoteClientStreamSession"

	g.P("func (s *", typeName, ") Start", method.GoName, "Message(ctx context.Context) (", service.GoName, method.GoName, "MessageStreamSession, error) {")
	g.P("if s == nil || s.client == nil {")
	g.P(`return nil, errors.New("rpccgo: grpc remote client is nil")`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := s.client.", method.GoName, "(streamCtx)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", sessionType, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()

	g.P("type ", sessionType, " struct {")
	g.P("stream grpc.ClientStreamingClient[", reqType, ", ", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Send(ctx context.Context, req []byte) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return errors.New("rpccgo: grpc remote client stream is nil")`)
	g.P("}")
	g.P("request := new(", reqType, ")")
	g.P("if err := proto.Unmarshal(req, request); err != nil {")
	g.P(`return status.Errorf(codes.InvalidArgument, "rpccgo: grpc remote stream request protobuf unmarshal failed: %v", err)`)
	g.P("}")
	g.P("return s.stream.Send(request)")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Finish(ctx context.Context) ([]byte, error) {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: grpc remote client stream is nil")`)
	g.P("}")
	g.P("defer func() {")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("}()")
	g.P("response, err := s.stream.CloseAndRecv()")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("respData, err := proto.Marshal(response)")
	g.P("if err != nil {")
	g.P(`return nil, status.Errorf(codes.Internal, "rpccgo: grpc remote stream response protobuf marshal failed: %v", err)`)
	g.P("}")
	g.P("return respData, nil")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return s.stream.CloseSend()")
	g.P("}")
	g.P()
}

func renderGRPCRemoteServerStreaming(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan, typeName string) {
	reqType := qualifiedMethodType(g, method.Request)
	respType := qualifiedMethodType(g, method.Response)
	sessionType := service.GoName + method.GoName + "GRPCRemoteServerStreamSession"

	g.P("func (s *", typeName, ") Start", method.GoName, "Message(ctx context.Context, req []byte) (", service.GoName, method.GoName, "MessageStreamSession, error) {")
	g.P("if s == nil || s.client == nil {")
	g.P(`return nil, errors.New("rpccgo: grpc remote client is nil")`)
	g.P("}")
	g.P("request := new(", reqType, ")")
	g.P("if err := proto.Unmarshal(req, request); err != nil {")
	g.P(`return nil, status.Errorf(codes.InvalidArgument, "rpccgo: grpc remote request protobuf unmarshal failed: %v", err)`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := s.client.", method.GoName, "(streamCtx, request)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", sessionType, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()

	g.P("type ", sessionType, " struct {")
	g.P("stream grpc.ServerStreamingClient[", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Recv(ctx context.Context) ([]byte, error) {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: grpc remote server stream is nil")`)
	g.P("}")
	g.P("response, err := s.stream.Recv()")
	g.P("if err != nil {")
	g.P("if errors.Is(err, io.EOF) {")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("return nil, err")
	g.P("}")
	g.P("respData, err := proto.Marshal(response)")
	g.P("if err != nil {")
	g.P(`return nil, status.Errorf(codes.Internal, "rpccgo: grpc remote stream response protobuf marshal failed: %v", err)`)
	g.P("}")
	g.P("return respData, nil")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Done(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s != nil && s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return s.stream.CloseSend()")
	g.P("}")
	g.P()
}

func renderGRPCRemoteBidiStreaming(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan, typeName string) {
	reqType := qualifiedMethodType(g, method.Request)
	respType := qualifiedMethodType(g, method.Response)
	sessionType := service.GoName + method.GoName + "GRPCRemoteBidiStreamSession"

	g.P("func (s *", typeName, ") Start", method.GoName, "Message(ctx context.Context) (", service.GoName, method.GoName, "MessageStreamSession, error) {")
	g.P("if s == nil || s.client == nil {")
	g.P(`return nil, errors.New("rpccgo: grpc remote client is nil")`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := s.client.", method.GoName, "(streamCtx)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", sessionType, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()

	g.P("type ", sessionType, " struct {")
	g.P("stream grpc.BidiStreamingClient[", reqType, ", ", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Send(ctx context.Context, req []byte) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return errors.New("rpccgo: grpc remote bidi stream is nil")`)
	g.P("}")
	g.P("request := new(", reqType, ")")
	g.P("if err := proto.Unmarshal(req, request); err != nil {")
	g.P(`return status.Errorf(codes.InvalidArgument, "rpccgo: grpc remote bidi request protobuf unmarshal failed: %v", err)`)
	g.P("}")
	g.P("return s.stream.Send(request)")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Recv(ctx context.Context) ([]byte, error) {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: grpc remote bidi stream is nil")`)
	g.P("}")
	g.P("response, err := s.stream.Recv()")
	g.P("if err != nil {")
	g.P("if errors.Is(err, io.EOF) {")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("return nil, err")
	g.P("}")
	g.P("respData, err := proto.Marshal(response)")
	g.P("if err != nil {")
	g.P(`return nil, status.Errorf(codes.Internal, "rpccgo: grpc remote bidi response protobuf marshal failed: %v", err)`)
	g.P("}")
	g.P("return respData, nil")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") CloseSend(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("return s.stream.CloseSend()")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Done(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s != nil && s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return s.stream.CloseSend()")
	g.P("}")
	g.P()
}
