package generator

import "google.golang.org/protobuf/compiler/protogen"

func renderMessageBinding(g *protogen.GeneratedFile, service ServicePlan, methods []runtimeAdapterMethod, serverName, adapterName, bindingName string) {
	if len(methods) == 0 {
		return
	}
	g.P("// ", adapterName, " exposes a message server implementation through the")
	g.P("// method shape used while building a ", bindingName, ".")
	g.P("type ", adapterName, " struct {")
	g.P("server ", serverName)
	g.P("}")
	g.P()
	for _, method := range methods {
		if !method.Streaming {
			g.P("func (a *", adapterName, ") ", method.MethodGoName, "(ctx context.Context, req []byte) ([]byte, error) {")
			g.P("return a.server.", method.MethodGoName, "(ctx, req)")
			g.P("}")
			g.P()
			continue
		}
		switch runtimeStreamShapeFor(method) {
		case runtimeStreamClient:
			renderMessageServerClientStreamAdapter(g, service.GoName, adapterName, method)
		case runtimeStreamServer:
			renderMessageServerServerStreamAdapter(g, service.GoName, adapterName, method)
		case runtimeStreamBidi:
			renderMessageServerBidiStreamAdapter(g, service.GoName, adapterName, method)
		}
	}
}

func renderMessageServerClientStreamAdapter(g *protogen.GeneratedFile, serviceName, adapterName string, method runtimeAdapterMethod) {
	sessionName := methodMessageSessionName(method)
	receiver := lowerInitial(serviceName) + method.MethodGoName + "MessageServerClientStreamSession"
	g.P("func (a *", adapterName, ") Start", method.MethodGoName, "(ctx context.Context) (", sessionName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("session := &", receiver, "{ctx: streamCtx, cancel: cancel, requests: make(chan ", receiver, "Request, 16), sendDone: make(chan struct{}), done: make(chan struct{})}")
	g.P("go func() {")
	g.P("defer close(session.done)")
	g.P("session.resp, session.err = a.server.", method.MethodGoName, "(streamCtx, session)")
	g.P("}()")
	g.P("return session, nil")
	g.P("}")
	g.P()
	g.P("type ", receiver, "Request struct {")
	g.P("data []byte")
	g.P("received chan struct{}")
	g.P("}")
	g.P()
	g.P("type ", receiver, " struct {")
	g.P("ctx context.Context")
	g.P("cancel context.CancelFunc")
	g.P("requests chan ", receiver, "Request")
	g.P("sendDone chan struct{}")
	g.P("closeSendOnce sync.Once")
	g.P("received chan struct{}")
	g.P("done chan struct{}")
	g.P("resp []byte")
	g.P("err error")
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") Recv(ctx context.Context) ([]byte, error) {")
	g.P("select {")
	g.P("case req := <-s.requests:")
	g.P("close(req.received)")
	g.P("return req.data, nil")
	g.P("default:")
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return nil, ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return nil, s.ctx.Err()")
	g.P("case req := <-s.requests:")
	g.P("close(req.received)")
	g.P("return req.data, nil")
	g.P("case <-s.sendDone:")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") Send(ctx context.Context, req []byte) error {")
	g.P("select {")
	g.P("case <-s.sendDone:")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("default:")
	g.P("}")
	g.P("queued := ", receiver, "Request{data: append([]byte(nil), req...), received: make(chan struct{})}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case <-s.done:")
	g.P("select {")
	g.P("case <-queued.received:")
	g.P("return nil")
	g.P("default:")
	g.P("}")
	g.P("if s.err != nil { return s.err }")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case <-s.sendDone:")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case s.requests <- queued:")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case <-s.done:")
	g.P("select {")
	g.P("case <-queued.received:")
	g.P("return nil")
	g.P("default:")
	g.P("}")
	g.P("if s.err != nil { return s.err }")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case <-s.sendDone:")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case <-queued.received:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") Finish(ctx context.Context) ([]byte, error) {")
	g.P("s.closeSendOnce.Do(func() { close(s.sendDone) })")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return nil, ctx.Err()")
	g.P("case <-s.done:")
	g.P("s.cancel()")
	g.P("return s.resp, s.err")
	g.P("}")
	g.P("}")
	g.P()
	renderMessageServerGeneratedCancel(g, receiver, true)
}

func renderMessageServerServerStreamAdapter(g *protogen.GeneratedFile, serviceName, adapterName string, method runtimeAdapterMethod) {
	sessionName := methodMessageSessionName(method)
	receiver := lowerInitial(serviceName) + method.MethodGoName + "MessageServerServerStreamSession"
	g.P("func (a *", adapterName, ") Start", method.MethodGoName, "(ctx context.Context, req []byte) (", sessionName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("session := &", receiver, "{ctx: streamCtx, cancel: cancel, responses: make(chan ", receiver, "Response, 1), done: make(chan struct{})}")
	g.P("req = append([]byte(nil), req...)")
	g.P("go func() {")
	g.P("defer close(session.done)")
	g.P("defer close(session.responses)")
	g.P("session.err = a.server.", method.MethodGoName, "(streamCtx, req, session)")
	g.P("}()")
	g.P("return session, nil")
	g.P("}")
	g.P()
	g.P("type ", receiver, "Response struct {")
	g.P("data []byte")
	g.P("received chan struct{}")
	g.P("}")
	g.P()
	g.P("type ", receiver, " struct {")
	g.P("ctx context.Context")
	g.P("cancel context.CancelFunc")
	g.P("responses chan ", receiver, "Response")
	g.P("received chan struct{}")
	g.P("doneRequested bool")
	g.P("done chan struct{}")
	g.P("err error")
	g.P("}")
	g.P()
	renderMessageServerStreamSend(g, receiver)
	renderMessageServerStreamRecv(g, receiver)
	renderMessageServerGeneratedFinish(g, receiver)
	renderMessageServerGeneratedCancel(g, receiver, false)
}

func renderMessageServerBidiStreamAdapter(g *protogen.GeneratedFile, serviceName, adapterName string, method runtimeAdapterMethod) {
	sessionName := methodMessageSessionName(method)
	receiver := lowerInitial(serviceName) + method.MethodGoName + "MessageServerBidiStreamSession"
	facadeName := lowerInitial(serviceName) + method.MethodGoName + "MessageServerBidiStreamFacade"
	g.P("func (a *", adapterName, ") Start", method.MethodGoName, "(ctx context.Context) (", sessionName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("session := &", receiver, "{ctx: streamCtx, cancel: cancel, requests: make(chan ", receiver, "Request, 16), sendDone: make(chan struct{}), sendDoneReceived: make(chan struct{}), responses: make(chan ", receiver, "Response, 1), done: make(chan struct{})}")
	g.P("go func() {")
	g.P("defer close(session.done)")
	g.P("defer close(session.responses)")
	g.P("session.err = a.server.", method.MethodGoName, "(streamCtx, &", facadeName, "{session: session})")
	g.P("}()")
	g.P("return session, nil")
	g.P("}")
	g.P()
	g.P("type ", receiver, "Request struct {")
	g.P("data []byte")
	g.P("received chan struct{}")
	g.P("}")
	g.P()
	g.P("type ", receiver, "Response struct {")
	g.P("data []byte")
	g.P("received chan struct{}")
	g.P("}")
	g.P()
	g.P("type ", receiver, " struct {")
	g.P("ctx context.Context")
	g.P("cancel context.CancelFunc")
	g.P("requests chan ", receiver, "Request")
	g.P("sendDone chan struct{}")
	g.P("sendDoneReceived chan struct{}")
	g.P("sendDoneReceivedOnce sync.Once")
	g.P("closeSendOnce sync.Once")
	g.P("responses chan ", receiver, "Response")
	g.P("received chan struct{}")
	g.P("doneRequested bool")
	g.P("done chan struct{}")
	g.P("err error")
	g.P("}")
	g.P()
	g.P("type ", facadeName, " struct {")
	g.P("session *", receiver)
	g.P("}")
	g.P()
	g.P("func (s *", facadeName, ") Recv(ctx context.Context) ([]byte, error) {")
	g.P("return s.session.recvRequest(ctx)")
	g.P("}")
	g.P()
	g.P("func (s *", facadeName, ") Send(ctx context.Context, resp []byte) error {")
	g.P("return s.session.sendResponse(ctx, resp)")
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") recvRequest(ctx context.Context) ([]byte, error) {")
	g.P("select {")
	g.P("case req := <-s.requests:")
	g.P("close(req.received)")
	g.P("return req.data, nil")
	g.P("default:")
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return nil, ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return nil, s.ctx.Err()")
	g.P("case req := <-s.requests:")
	g.P("close(req.received)")
	g.P("return req.data, nil")
	g.P("case <-s.sendDone:")
	g.P("s.sendDoneReceivedOnce.Do(func() { close(s.sendDoneReceived) })")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") sendResponse(ctx context.Context, resp []byte) error {")
	g.P("response := ", receiver, "Response{data: append([]byte(nil), resp...), received: make(chan struct{})}")
	renderMessageServerSendResponseBody(g)
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") Send(ctx context.Context, req []byte) error {")
	g.P("select {")
	g.P("case <-s.sendDone:")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("default:")
	g.P("}")
	g.P("queued := ", receiver, "Request{data: append([]byte(nil), req...), received: make(chan struct{})}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case <-s.done:")
	g.P("select {")
	g.P("case <-queued.received:")
	g.P("return nil")
	g.P("default:")
	g.P("}")
	g.P("return nil")
	g.P("case <-s.sendDone:")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case s.requests <- queued:")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case <-s.done:")
	g.P("select {")
	g.P("case <-queued.received:")
	g.P("return nil")
	g.P("default:")
	g.P("}")
	g.P("return nil")
	g.P("case <-s.sendDone:")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case <-queued.received:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") Recv(ctx context.Context) ([]byte, error) {")
	renderMessageServerStreamRecvBody(g)
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") CloseSend(ctx context.Context) error {")
	g.P("s.closeSendOnce.Do(func() { close(s.sendDone) })")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case <-s.done:")
	g.P("if s.err != nil { return s.err }")
	g.P("return nil")
	g.P("case <-s.sendDoneReceived:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P()
	renderMessageServerGeneratedFinish(g, receiver)
	renderMessageServerGeneratedCancel(g, receiver, true)
}

func renderMessageServerStreamSend(g *protogen.GeneratedFile, receiver string) {
	g.P("func (s *", receiver, ") Send(ctx context.Context, resp []byte) error {")
	g.P("response := ", receiver, "Response{data: append([]byte(nil), resp...), received: make(chan struct{})}")
	renderMessageServerSendResponseBody(g)
	g.P("}")
	g.P()
}

func renderMessageServerSendResponseBody(g *protogen.GeneratedFile) {
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("if s.doneRequested { return io.EOF }")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("if s.doneRequested { return io.EOF }")
	g.P("return s.ctx.Err()")
	g.P("case <-s.done:")
	g.P("if s.err != nil { return s.err }")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case s.responses <- response:")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("if s.doneRequested { return io.EOF }")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("if s.doneRequested { return io.EOF }")
	g.P("return s.ctx.Err()")
	g.P("case <-s.done:")
	g.P("if s.err != nil { return s.err }")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case <-response.received:")
	g.P("if s.ctx.Err() != nil {")
	g.P("if s.doneRequested { return io.EOF }")
	g.P("return s.ctx.Err()")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P("}")
}

func renderMessageServerStreamRecv(g *protogen.GeneratedFile, receiver string) {
	g.P("func (s *", receiver, ") Recv(ctx context.Context) ([]byte, error) {")
	renderMessageServerStreamRecvBody(g)
	g.P("}")
	g.P()
}

func renderMessageServerStreamRecvBody(g *protogen.GeneratedFile) {
	g.P("if s.received != nil {")
	g.P("close(s.received)")
	g.P("s.received = nil")
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return nil, ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return nil, s.ctx.Err()")
	g.P("case resp, ok := <-s.responses:")
	g.P("if ok {")
	g.P("s.received = resp.received")
	g.P("return resp.data, nil")
	g.P("}")
	g.P("if s.received != nil {")
	g.P("close(s.received)")
	g.P("s.received = nil")
	g.P("}")
	g.P("<-s.done")
	g.P("if s.err != nil {")
	g.P("err := s.err")
	g.P("s.err = nil")
	g.P("return nil, err")
	g.P("}")
	g.P("return nil, io.EOF")
	g.P("}")
}

func renderMessageServerGeneratedFinish(g *protogen.GeneratedFile, receiver string) {
	g.P("func (s *", receiver, ") Finish(ctx context.Context) error {")
	g.P("s.doneRequested = true")
	g.P("s.cancel()")
	g.P("if s.received != nil {")
	g.P("close(s.received)")
	g.P("s.received = nil")
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.done:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P()
}

func renderMessageServerGeneratedCancel(g *protogen.GeneratedFile, receiver string, closeSend bool) {
	g.P("func (s *", receiver, ") Cancel(ctx context.Context) error {")
	g.P("s.cancel()")
	g.P("if s.received != nil {")
	g.P("close(s.received)")
	g.P("s.received = nil")
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.done:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P()
	_ = closeSend
}
