package generator

import "google.golang.org/protobuf/compiler/protogen"

func renderConnectRemoteFile(plugin *protogen.Plugin, plan FilePlan, service ServicePlan, file GeneratedFilePlan) error {
	g := plugin.NewGeneratedFile(file.Filename, protogen.GoImportPath(plan.GoImportPath))

	g.P("package ", plan.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`context "context"`)
	g.P(`errors "errors"`)
	g.P(`fmt "fmt"`)
	if serviceHasStreamingMethod(service) {
		g.P(`io "io"`)
	}
	g.P(`http "net/http"`)
	g.P(`strings "strings"`)
	g.P(`connect "connectrpc.com/connect"`)
	g.P(`proto "google.golang.org/protobuf/proto"`)
	g.P(`rpcruntime "rpccgo/rpcruntime"`)
	g.P(")")
	g.P()
	g.P("// ", messageStageMarker(service, file))
	g.P()
	g.P("var _ *http.Client")

	typeName := service.GoName + "ConnectRemoteServer"
	g.P("var _ ", service.GoName, "MessageAdapter = (*", typeName, ")(nil)")
	g.P()
	g.P("type ", typeName, " struct {")
	for _, method := range service.Methods {
		reqType := qualifiedMethodType(g, method.Request)
		respType := qualifiedMethodType(g, method.Response)
		g.P(lowerInitial(method.GoName), " *connect.Client[", reqType, ", ", respType, "]")
	}
	g.P("}")
	g.P()

	g.P("func New", typeName, "(httpClient connect.HTTPClient, baseURL string, options ...connect.ClientOption) (*", typeName, ", error) {")
	g.P("if httpClient == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote http client is nil")`)
	g.P("}")
	g.P("if baseURL == \"\" {")
	g.P(`return nil, errors.New("rpccgo: connect remote base URL is empty")`)
	g.P("}")
	g.P("baseURL = strings.TrimRight(baseURL, \"/\")")
	g.P("return &", typeName, "{")
	for _, method := range service.Methods {
		reqType := qualifiedMethodType(g, method.Request)
		respType := qualifiedMethodType(g, method.Response)
		g.P(lowerInitial(method.GoName), ": connect.NewClient[", reqType, ", ", respType, "](httpClient, baseURL+", connectProcedureConstName(service, method), ", options...),")
	}
	g.P("}, nil")
	g.P("}")
	g.P()

	g.P("func Register", typeName, "(httpClient connect.HTTPClient, baseURL string, options ...connect.ClientOption) (rpcruntime.AdapterSnapshot[", service.GoName, "MessageAdapter], error) {")
	g.P("adapter, err := New", typeName, "(httpClient, baseURL, options...)")
	g.P("if err != nil {")
	g.P("return rpcruntime.AdapterSnapshot[", service.GoName, "MessageAdapter]{}, err")
	g.P("}")
	g.P("return Register", service.GoName, "CGOMessageActiveServer(rpcruntime.ServerKindConnectRemote, adapter)")
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		switch method.Streaming {
		case StreamingKindUnary:
			renderConnectRemoteUnary(g, service, method, typeName)
		case StreamingKindClientStreaming:
			renderConnectRemoteClientStreaming(g, service, method, typeName)
		case StreamingKindServerStreaming:
			renderConnectRemoteServerStreaming(g, service, method, typeName)
		case StreamingKindBidiStreaming:
			renderConnectRemoteBidiStreaming(g, service, method, typeName)
		}
	}

	if serviceHasStreamingMethod(service) {
		renderConnectRemoteConnCloser(g)
	}
	return nil
}

func renderConnectRemoteUnary(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan, typeName string) {
	reqType := qualifiedMethodType(g, method.Request)
	field := lowerInitial(method.GoName)
	g.P("func (s *", typeName, ") ", method.GoName, "Message(ctx context.Context, req []byte) ([]byte, error) {")
	g.P("if s == nil || s.", field, " == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote server is nil")`)
	g.P("}")
	g.P("request := new(", reqType, ")")
	g.P("if err := proto.Unmarshal(req, request); err != nil {")
	g.P(`return nil, fmt.Errorf("rpccgo: connect remote request protobuf unmarshal failed: %w", err)`)
	g.P("}")
	g.P("resp, err := s.", field, ".CallUnary(ctx, connect.NewRequest(request))")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("if resp == nil || resp.Msg == nil {")
	g.P("return nil, nil")
	g.P("}")
	g.P("data, err := proto.Marshal(resp.Msg)")
	g.P("if err != nil {")
	g.P(`return nil, fmt.Errorf("rpccgo: connect remote response protobuf marshal failed: %w", err)`)
	g.P("}")
	g.P("return data, nil")
	g.P("}")
	g.P()
}

func renderConnectRemoteClientStreaming(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan, typeName string) {
	reqType := qualifiedMethodType(g, method.Request)
	respType := qualifiedMethodType(g, method.Response)
	sessionType := service.GoName + method.GoName + "ConnectRemoteClientStreamSession"
	field := lowerInitial(method.GoName)

	g.P("func (s *", typeName, ") Start", method.GoName, "Message(ctx context.Context) (", service.GoName, method.GoName, "MessageStreamSession, error) {")
	g.P("if s == nil || s.", field, " == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote server is nil")`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream := s.", field, ".CallClientStream(streamCtx)")
	g.P("return &", sessionType, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()

	g.P("type ", sessionType, " struct {")
	g.P("stream *connect.ClientStreamForClient[", reqType, ", ", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Send(ctx context.Context, req []byte) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return errors.New("rpccgo: connect remote client stream is nil")`)
	g.P("}")
	g.P("request := new(", reqType, ")")
	g.P("if err := proto.Unmarshal(req, request); err != nil {")
	g.P(`return fmt.Errorf("rpccgo: connect remote stream request protobuf unmarshal failed: %w", err)`)
	g.P("}")
	g.P("return s.stream.Send(request)")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Finish(ctx context.Context) ([]byte, error) {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote client stream is nil")`)
	g.P("}")
	g.P("defer func() {")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("}()")
	g.P("resp, err := s.stream.CloseAndReceive()")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("if resp == nil || resp.Msg == nil {")
	g.P("return nil, nil")
	g.P("}")
	g.P("data, err := proto.Marshal(resp.Msg)")
	g.P("if err != nil {")
	g.P(`return nil, fmt.Errorf("rpccgo: connect remote stream response protobuf marshal failed: %w", err)`)
	g.P("}")
	g.P("return data, nil")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("conn, err := s.stream.Conn()")
	g.P("if err != nil {")
	g.P("return nil")
	g.P("}")
	g.P("return closeConnectRemoteConn(conn)")
	g.P("}")
	g.P()
}

func renderConnectRemoteServerStreaming(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan, typeName string) {
	reqType := qualifiedMethodType(g, method.Request)
	respType := qualifiedMethodType(g, method.Response)
	sessionType := service.GoName + method.GoName + "ConnectRemoteServerStreamSession"
	field := lowerInitial(method.GoName)

	g.P("func (s *", typeName, ") Start", method.GoName, "Message(ctx context.Context, req []byte) (", service.GoName, method.GoName, "MessageStreamSession, error) {")
	g.P("if s == nil || s.", field, " == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote server is nil")`)
	g.P("}")
	g.P("request := new(", reqType, ")")
	g.P("if err := proto.Unmarshal(req, request); err != nil {")
	g.P(`return nil, fmt.Errorf("rpccgo: connect remote request protobuf unmarshal failed: %w", err)`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := s.", field, ".CallServerStream(streamCtx, connect.NewRequest(request))")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", sessionType, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()

	g.P("type ", sessionType, " struct {")
	g.P("stream *connect.ServerStreamForClient[", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Recv(ctx context.Context) ([]byte, error) {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote server stream is nil")`)
	g.P("}")
	g.P("if !s.stream.Receive() {")
	g.P("if err := s.stream.Err(); err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("msg := s.stream.Msg()")
	g.P("if msg == nil {")
	g.P("return nil, nil")
	g.P("}")
	g.P("data, err := proto.Marshal(msg)")
	g.P("if err != nil {")
	g.P(`return nil, fmt.Errorf("rpccgo: connect remote stream response protobuf marshal failed: %w", err)`)
	g.P("}")
	g.P("return data, nil")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Done(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("defer s.cancel()")
	g.P("}")
	g.P("return s.stream.Close()")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("conn, err := s.stream.Conn()")
	g.P("if err != nil {")
	g.P("return s.stream.Close()")
	g.P("}")
	g.P("return closeConnectRemoteConn(conn)")
	g.P("}")
	g.P()
}

func renderConnectRemoteBidiStreaming(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan, typeName string) {
	reqType := qualifiedMethodType(g, method.Request)
	respType := qualifiedMethodType(g, method.Response)
	sessionType := service.GoName + method.GoName + "ConnectRemoteBidiStreamSession"
	field := lowerInitial(method.GoName)

	g.P("func (s *", typeName, ") Start", method.GoName, "Message(ctx context.Context) (", service.GoName, method.GoName, "MessageStreamSession, error) {")
	g.P("if s == nil || s.", field, " == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote server is nil")`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream := s.", field, ".CallBidiStream(streamCtx)")
	g.P("return &", sessionType, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()

	g.P("type ", sessionType, " struct {")
	g.P("stream *connect.BidiStreamForClient[", reqType, ", ", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Send(ctx context.Context, req []byte) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return errors.New("rpccgo: connect remote bidi stream is nil")`)
	g.P("}")
	g.P("request := new(", reqType, ")")
	g.P("if err := proto.Unmarshal(req, request); err != nil {")
	g.P(`return fmt.Errorf("rpccgo: connect remote bidi request protobuf unmarshal failed: %w", err)`)
	g.P("}")
	g.P("return s.stream.Send(request)")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Recv(ctx context.Context) ([]byte, error) {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote bidi stream is nil")`)
	g.P("}")
	g.P("resp, err := s.stream.Receive()")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("if resp == nil {")
	g.P("return nil, nil")
	g.P("}")
	g.P("data, err := proto.Marshal(resp)")
	g.P("if err != nil {")
	g.P(`return nil, fmt.Errorf("rpccgo: connect remote bidi response protobuf marshal failed: %w", err)`)
	g.P("}")
	g.P("return data, nil")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") CloseSend(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("return s.stream.CloseRequest()")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Done(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("defer s.cancel()")
	g.P("}")
	g.P("return s.stream.CloseResponse()")
	g.P("}")
	g.P()

	g.P("func (s *", sessionType, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("conn, err := s.stream.Conn()")
	g.P("if err == nil {")
	g.P("return closeConnectRemoteConn(conn)")
	g.P("}")
	g.P("err = s.stream.CloseRequest()")
	g.P("if closeErr := s.stream.CloseResponse(); err == nil {")
	g.P("err = closeErr")
	g.P("}")
	g.P("return err")
	g.P("}")
	g.P()
}

func renderConnectRemoteConnCloser(g *protogen.GeneratedFile) {
	g.P("func closeConnectRemoteConn(conn connect.StreamingClientConn) error {")
	g.P("if conn == nil {")
	g.P("return nil")
	g.P("}")
	g.P("err := conn.CloseRequest()")
	g.P("if closeErr := conn.CloseResponse(); err == nil {")
	g.P("err = closeErr")
	g.P("}")
	g.P("return err")
	g.P("}")
	g.P()
}
