package generator

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func renderRuntimeTransportMessageSessions(g *protogen.GeneratedFile, service ServicePlan, methods []runtimeMethodProjection) {
	for _, method := range methods {
		if service.Generation.MessageTransport == MessageTransportConnect {
			renderConnectDirectMessageSession(g, service, method)
			renderConnectRemoteMessageSession(g, service, method)
		}
		if service.Generation.MessageTransport == MessageTransportGRPC {
			renderGRPCDirectMessageSession(g, service, method)
			renderGRPCRemoteMessageSession(g, service, method)
		}
	}
}

func renderConnectDirectMessageSession(g *protogen.GeneratedFile, service ServicePlan, method runtimeMethodProjection) {
	wrapperName := connectDirectMessageSessionName(service.GoName, method)
	resultName := wrapperName + "Result"
	reqType := method.Message.RequestType
	respType := method.Message.ResponseType
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	handlerName := service.GoName + "Handler"
	g.P("type ", resultName, " struct {")
	g.P("data ", respPtrType)
	g.P("err error")
	g.P("terminal bool")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("ctx context.Context")
	g.P("cancel context.CancelFunc")
	if method.Stream.CanSend {
		g.P("requests chan ", reqPtrType)
		g.P("closeRequests sync.Once")
	}
	if method.Stream.FinishReturnsResponse {
		g.P("result chan ", resultName)
	} else {
		g.P("responses chan ", resultName)
	}
	g.P("}")
	g.P()
	switch method.Stream.Shape {
	case runtimeStreamClient:
		renderConnectDirectClientStreamSession(g, method, wrapperName, resultName, reqType, respType, handlerName)
	case runtimeStreamServer:
		renderConnectDirectServerStreamSession(g, method, wrapperName, resultName, reqType, respType, handlerName)
	case runtimeStreamBidi:
		renderConnectDirectBidiStreamSession(g, method, wrapperName, resultName, reqType, respType, handlerName)
	}
}

func renderConnectDirectClientStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, resultName, reqType, respType, handlerName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, handler ", handlerName, ") *", wrapperName, " {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("session := &", wrapperName, "{ctx: streamCtx, cancel: cancel, requests: make(chan ", reqPtrType, "), result: make(chan ", resultName, ", 1)}")
	g.P("go func() {")
	g.P("conn := &rpcruntime.ConnectStreamingHandlerConn{ReceiveFunc: func(msg any) error {")
	g.P("req, ok := <-session.requests")
	g.P("if !ok {")
	g.P("return io.EOF")
	g.P("}")
	g.P("target, ok := msg.(", reqPtrType, ")")
	g.P("if !ok {")
	g.P(`return fmt.Errorf("rpccgo: connect handler stream request type mismatch")`)
	g.P("}")
	g.P("*target = *req")
	g.P("return nil")
	g.P("}}")
	g.P("resp, err := handler.", method.Identity.MessageMethodRef, "(streamCtx, rpcruntime.NewConnectClientStream[", reqType, "](conn))")
	g.P("if err != nil {")
	g.P("session.result <- ", resultName, "{err: err, terminal: true}")
	g.P("return")
	g.P("}")
	g.P("session.result <- ", resultName, "{data: resp, terminal: true}")
	g.P("}()")
	g.P("return session")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Send(ctx context.Context, req ", reqPtrType, ") error {")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case s.requests <- req:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) (", respPtrType, ", error) {")
	g.P("s.closeRequests.Do(func() { close(s.requests) })")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return nil, ctx.Err()")
	g.P("case result := <-s.result:")
	g.P("s.cancel()")
	g.P("return result.data, result.err")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("s.cancel()")
	g.P("s.closeRequests.Do(func() { close(s.requests) })")
	g.P("return nil")
	g.P("}")
	g.P()
}

func renderConnectDirectServerStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, resultName, reqType, respType, handlerName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, handler ", handlerName, ", req ", reqPtrType, ") (*", wrapperName, ", error) {")
	g.P("if req == nil {")
	g.P(`return nil, errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("session := &", wrapperName, "{ctx: streamCtx, cancel: cancel, responses: make(chan ", resultName, ", 1)}")
	g.P("go func() {")
	g.P("conn := &rpcruntime.ConnectStreamingHandlerConn{SendFunc: func(msg any) error {")
	g.P("resp, ok := msg.(*", respType, ")")
	g.P("if !ok {")
	g.P("return fmt.Errorf(\"rpccgo: connect handler stream response type mismatch\")")
	g.P("}")
	g.P("if resp == nil {")
	g.P(`return errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("select {")
	g.P("case <-streamCtx.Done():")
	g.P("return streamCtx.Err()")
	g.P("case session.responses <- ", resultName, "{data: resp}:")
	g.P("return nil")
	g.P("}")
	g.P("}}")
	g.P("err := handler.", method.Identity.MessageMethodRef, "(streamCtx, req, rpcruntime.NewConnectServerStream[", respType, "](conn))")
	g.P("session.responses <- ", resultName, "{err: err, terminal: true}")
	g.P("}()")
	g.P("return session, nil")
	g.P("}")
	g.P()
	renderConnectDirectRecvFinishCancel(g, wrapperName, respPtrType)
}

func renderConnectDirectBidiStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, resultName, reqType, respType, handlerName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, handler ", handlerName, ") *", wrapperName, " {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("session := &", wrapperName, "{ctx: streamCtx, cancel: cancel, requests: make(chan ", reqPtrType, "), responses: make(chan ", resultName, ", 1)}")
	g.P("go func() {")
	g.P("conn := &rpcruntime.ConnectStreamingHandlerConn{")
	g.P("ReceiveFunc: func(msg any) error {")
	g.P("req, ok := <-session.requests")
	g.P("if !ok {")
	g.P("return io.EOF")
	g.P("}")
	g.P("target, ok := msg.(", reqPtrType, ")")
	g.P("if !ok {")
	g.P(`return fmt.Errorf("rpccgo: connect handler bidi request type mismatch")`)
	g.P("}")
	g.P("*target = *req")
	g.P("return nil")
	g.P("},")
	g.P("SendFunc: func(msg any) error {")
	g.P("resp, ok := msg.(*", respType, ")")
	g.P("if !ok {")
	g.P("return fmt.Errorf(\"rpccgo: connect handler bidi response type mismatch\")")
	g.P("}")
	g.P("if resp == nil {")
	g.P(`return errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("select {")
	g.P("case <-streamCtx.Done():")
	g.P("return streamCtx.Err()")
	g.P("case session.responses <- ", resultName, "{data: resp}:")
	g.P("return nil")
	g.P("}")
	g.P("},")
	g.P("}")
	g.P("err := handler.", method.Identity.MessageMethodRef, "(streamCtx, rpcruntime.NewConnectBidiStream[", reqType, ", ", respType, "](conn))")
	g.P("session.responses <- ", resultName, "{err: err, terminal: true}")
	g.P("}()")
	g.P("return session")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Send(ctx context.Context, req ", reqPtrType, ") error {")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case s.requests <- req:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") CloseSend(ctx context.Context) error {")
	g.P("s.closeRequests.Do(func() { close(s.requests) })")
	g.P("return nil")
	g.P("}")
	g.P()
	renderConnectDirectRecvFinishCancel(g, wrapperName, respPtrType)
}

func renderConnectDirectRecvFinishCancel(g *protogen.GeneratedFile, wrapperName, respType string) {
	g.P("func (s *", wrapperName, ") Recv(ctx context.Context) (", respType, ", error) {")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return nil, ctx.Err()")
	g.P("case result := <-s.responses:")
	g.P("if result.terminal {")
	g.P("s.cancel()")
	g.P("if result.err != nil {")
	g.P("return nil, result.err")
	g.P("}")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("return result.data, result.err")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) error {")
	g.P("s.cancel()")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("s.cancel()")
	g.P("return nil")
	g.P("}")
	g.P()
}

func renderConnectRemoteMessageSession(g *protogen.GeneratedFile, service ServicePlan, method runtimeMethodProjection) {
	wrapperName := connectRemoteMessageSessionName(service.GoName, method)
	reqType := method.Message.RequestType
	respType := method.Message.ResponseType
	switch method.Stream.Shape {
	case runtimeStreamClient:
		clientType := "interface { " + method.Identity.MessageMethodRef + "(context.Context) (*connect.ClientStreamForClientSimple[" + strings.TrimPrefix(reqType, "*") + ", " + strings.TrimPrefix(respType, "*") + "], error) }"
		renderConnectRemoteClientStreamSession(g, method, wrapperName, reqType, respType, clientType)
	case runtimeStreamServer:
		clientType := "interface { " + method.Identity.MessageMethodRef + "(context.Context, *" + strings.TrimPrefix(reqType, "*") + ") (*connect.ServerStreamForClient[" + strings.TrimPrefix(respType, "*") + "], error) }"
		renderConnectRemoteServerStreamSession(g, method, wrapperName, reqType, respType, clientType)
	case runtimeStreamBidi:
		clientType := "interface { " + method.Identity.MessageMethodRef + "(context.Context) (*connect.BidiStreamForClientSimple[" + strings.TrimPrefix(reqType, "*") + ", " + strings.TrimPrefix(respType, "*") + "], error) }"
		renderConnectRemoteBidiStreamSession(g, method, wrapperName, reqType, respType, clientType)
	}
}

func renderConnectRemoteClientStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, clientType string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, client ", clientType, ") (*", wrapperName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := client.", method.Identity.MessageMethodRef, "(streamCtx)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", wrapperName, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("stream *connect.ClientStreamForClientSimple[", reqType, ", ", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Send(ctx context.Context, req ", reqPtrType, ") error {")
	g.P("_ = ctx")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("if s == nil {")
	g.P(`return errors.New("rpccgo: connect remote client stream is nil")`)
	g.P("}")
	g.P("if s.stream == nil {")
	g.P(`return errors.New("rpccgo: connect remote client stream is nil")`)
	g.P("}")
	g.P("return s.stream.Send(req)")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) (", respPtrType, ", error) {")
	g.P("_ = ctx")
	g.P("if s == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote client stream is nil")`)
	g.P("}")
	g.P("if s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote client stream is nil")`)
	g.P("}")
	g.P("defer func() { if s.cancel != nil { s.cancel() } }()")
	g.P("resp, err := s.stream.CloseAndReceive()")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("if resp == nil {")
	g.P(`return nil, errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("return resp, nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s != nil && s.stream != nil {")
	g.P("closed := make(chan struct{})")
	g.P("go func() {")
	g.P("_, _ = s.stream.CloseAndReceive()")
	g.P("close(closed)")
	g.P("}()")
	g.P("timer := time.NewTimer(100 * time.Millisecond)")
	g.P("select {")
	g.P("case <-closed:")
	g.P("timer.Stop()")
	g.P("return nil")
	g.P("case <-timer.C:")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("select {")
	g.P("case <-closed:")
	g.P("case <-time.After(500 * time.Millisecond):")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P("if s != nil && s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P()
}

func renderConnectRemoteServerStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, clientType string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, client ", clientType, ", req ", reqPtrType, ") (*", wrapperName, ", error) {")
	g.P("if req == nil {")
	g.P(`return nil, errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := client.", method.Identity.MessageMethodRef, "(streamCtx, req)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", wrapperName, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("stream *connect.ServerStreamForClient[", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()
	renderConnectRemoteRecvFinishCancel(g, wrapperName, "server stream", respPtrType)
}

func renderConnectRemoteBidiStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, clientType string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, client ", clientType, ") (*", wrapperName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := client.", method.Identity.MessageMethodRef, "(streamCtx)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", wrapperName, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("stream *connect.BidiStreamForClientSimple[", reqType, ", ", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Send(ctx context.Context, req ", reqPtrType, ") error {")
	g.P("_ = ctx")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("if s == nil {")
	g.P(`return errors.New("rpccgo: connect remote bidi stream is nil")`)
	g.P("}")
	g.P("if s.stream == nil {")
	g.P(`return errors.New("rpccgo: connect remote bidi stream is nil")`)
	g.P("}")
	g.P("return s.stream.Send(req)")
	g.P("}")
	g.P()
	renderConnectRemoteBidiRecvFinishCancel(g, wrapperName, respPtrType)
	g.P("func (s *", wrapperName, ") CloseSend(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("return s.stream.CloseRequest()")
	g.P("}")
	g.P()
}

func renderConnectRemoteRecvFinishCancel(g *protogen.GeneratedFile, wrapperName, label, respType string) {
	g.P("func (s *", wrapperName, ") Recv(ctx context.Context) (", respType, ", error) {")
	g.P("_ = ctx")
	g.P("if s == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote `, label, ` is nil")`)
	g.P("}")
	g.P("if s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote `, label, ` is nil")`)
	g.P("}")
	g.P("if !s.stream.Receive() {")
	g.P("if err := s.stream.Err(); err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("msg := s.stream.Msg()")
	g.P("if msg == nil {")
	g.P(`return nil, errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("return msg, nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("defer s.cancel()")
	g.P("}")
	g.P("return s.stream.Close()")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P()
}

func renderConnectRemoteBidiRecvFinishCancel(g *protogen.GeneratedFile, wrapperName, respType string) {
	g.P("func (s *", wrapperName, ") Recv(ctx context.Context) (", respType, ", error) {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: connect remote bidi stream is nil")`)
	g.P("}")
	g.P("resp, err := s.stream.Receive()")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("if resp == nil {")
	g.P(`return nil, errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("return resp, nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("defer s.cancel()")
	g.P("}")
	g.P("return s.stream.CloseResponse()")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P()
}

func renderGRPCDirectMessageSession(g *protogen.GeneratedFile, service ServicePlan, method runtimeMethodProjection) {
	wrapperName := grpcDirectMessageSessionName(service.GoName, method)
	resultName := wrapperName + "Result"
	reqType := method.Message.RequestType
	respType := method.Message.ResponseType
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	serverName := service.GoName + "Server"
	g.P("type ", resultName, " struct {")
	g.P("data ", respPtrType)
	g.P("err error")
	g.P("terminal bool")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("ctx context.Context")
	g.P("cancel context.CancelFunc")
	if method.Stream.CanSend {
		g.P("requests chan ", reqPtrType)
		g.P("closeRequests sync.Once")
	}
	if method.Stream.FinishReturnsResponse {
		g.P("result chan ", resultName)
		g.P("resultOnce sync.Once")
	} else {
		g.P("responses chan ", resultName)
	}
	g.P("header metadata.MD")
	g.P("trailer metadata.MD")
	g.P("}")
	g.P()
	switch method.Stream.Shape {
	case runtimeStreamClient:
		renderGRPCDirectClientStreamSession(g, method, wrapperName, resultName, reqType, respType, serverName)
	case runtimeStreamServer:
		renderGRPCDirectServerStreamSession(g, method, wrapperName, resultName, reqType, respType, serverName)
	case runtimeStreamBidi:
		renderGRPCDirectBidiStreamSession(g, method, wrapperName, resultName, reqType, respType, serverName)
	}
}

func renderGRPCDirectClientStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, resultName, reqType, respType, serverName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, server ", serverName, ") *", wrapperName, " {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("session := &", wrapperName, "{ctx: streamCtx, cancel: cancel, requests: make(chan ", reqPtrType, "), result: make(chan ", resultName, ", 1)}")
	g.P("go func() {")
	g.P("err := server.", method.Identity.MessageMethodRef, "(session)")
	g.P("if err != nil {")
	g.P("session.deliver(", resultName, "{err: err, terminal: true})")
	g.P("return")
	g.P("}")
	g.P("session.deliver(", resultName, `{err: fmt.Errorf("rpccgo: grpc direct client stream completed without SendAndClose"), terminal: true})`)
	g.P("}()")
	g.P("return session")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") deliver(result ", resultName, ") {")
	g.P("s.resultOnce.Do(func() {")
	g.P("s.result <- result")
	g.P("})")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Recv() (*", reqType, ", error) {")
	g.P("select {")
	g.P("case <-s.ctx.Done():")
	g.P("return nil, s.ctx.Err()")
	g.P("case msg, ok := <-s.requests:")
	g.P("if !ok {")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("return msg, nil")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") RecvMsg(m any) error {")
	g.P("msg, err := s.Recv()")
	g.P("if err != nil {")
	g.P("return err")
	g.P("}")
	g.P("typed, ok := m.(*", reqType, ")")
	g.P("if !ok || typed == nil {")
	g.P(`return fmt.Errorf("rpccgo: grpc direct client stream request type mismatch")`)
	g.P("}")
	g.P("*typed = *msg")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") SendAndClose(resp *", respType, ") error {")
	g.P("if resp == nil {")
	g.P(`return fmt.Errorf("rpccgo: grpc direct client stream response is nil")`)
	g.P("}")
	g.P("s.deliver(", resultName, "{data: resp, terminal: true})")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") SendMsg(m any) error {")
	g.P("typed, ok := m.(*", respType, ")")
	g.P("if !ok || typed == nil {")
	g.P(`return fmt.Errorf("rpccgo: grpc direct client stream response type mismatch")`)
	g.P("}")
	g.P("return s.SendAndClose(typed)")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") SetHeader(md metadata.MD) error {")
	g.P("if md == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.header == nil {")
	g.P("s.header = md.Copy()")
	g.P("return nil")
	g.P("}")
	g.P("s.header = metadata.Join(s.header, md)")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") SendHeader(md metadata.MD) error {")
	g.P("return s.SetHeader(md)")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") SetTrailer(md metadata.MD) {")
	g.P("if md == nil {")
	g.P("return")
	g.P("}")
	g.P("if s.trailer == nil {")
	g.P("s.trailer = md.Copy()")
	g.P("return")
	g.P("}")
	g.P("s.trailer = metadata.Join(s.trailer, md)")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Context() context.Context { return s.ctx }")
	g.P()
	g.P("func (s *", wrapperName, ") Send(ctx context.Context, req ", reqPtrType, ") error {")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case s.requests <- req:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) (", respPtrType, ", error) {")
	g.P("s.closeRequests.Do(func() { close(s.requests) })")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return nil, ctx.Err()")
	g.P("case result := <-s.result:")
	g.P("s.cancel()")
	g.P("return result.data, result.err")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("s.cancel()")
	g.P("s.closeRequests.Do(func() { close(s.requests) })")
	g.P("return nil")
	g.P("}")
	g.P()
}

func renderGRPCDirectServerStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, resultName, reqType, respType, serverName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, server ", serverName, ", req ", reqPtrType, ") (*", wrapperName, ", error) {")
	g.P("if req == nil {")
	g.P(`return nil, errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("session := &", wrapperName, "{ctx: streamCtx, cancel: cancel, responses: make(chan ", resultName, ", 1)}")
	g.P("go func() {")
	g.P("err := server.", method.Identity.MessageMethodRef, "(req, session)")
	g.P("session.responses <- ", resultName, "{err: err, terminal: true}")
	g.P("}()")
	g.P("return session, nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Send(resp *", respType, ") error {")
	g.P("if resp == nil {")
	g.P(`return fmt.Errorf("rpccgo: grpc direct server stream response is nil")`)
	g.P("}")
	g.P("select {")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case s.responses <- ", resultName, "{data: resp}:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") SendMsg(m any) error {")
	g.P("typed, ok := m.(*", respType, ")")
	g.P("if !ok || typed == nil {")
	g.P(`return fmt.Errorf("rpccgo: grpc direct server stream response type mismatch")`)
	g.P("}")
	g.P("return s.Send(typed)")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") RecvMsg(m any) error {")
	g.P("return io.EOF")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") SetHeader(md metadata.MD) error {")
	g.P("if md == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.header == nil {")
	g.P("s.header = md.Copy()")
	g.P("return nil")
	g.P("}")
	g.P("s.header = metadata.Join(s.header, md)")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") SendHeader(md metadata.MD) error {")
	g.P("return s.SetHeader(md)")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") SetTrailer(md metadata.MD) {")
	g.P("if md == nil {")
	g.P("return")
	g.P("}")
	g.P("if s.trailer == nil {")
	g.P("s.trailer = md.Copy()")
	g.P("return")
	g.P("}")
	g.P("s.trailer = metadata.Join(s.trailer, md)")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Context() context.Context { return s.ctx }")
	g.P()
	renderConnectDirectRecvFinishCancel(g, wrapperName, respPtrType)
}

func renderGRPCDirectBidiStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, resultName, reqType, respType, serverName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	streamName := wrapperName + "GRPCStream"
	g.P("type ", streamName, " struct {")
	g.P("source *", wrapperName)
	g.P("}")
	g.P()
	g.P("func new", wrapperName, "(ctx context.Context, server ", serverName, ") *", wrapperName, " {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("session := &", wrapperName, "{ctx: streamCtx, cancel: cancel, requests: make(chan ", reqPtrType, "), responses: make(chan ", resultName, ", 1)}")
	g.P("go func() {")
	g.P("err := server.", method.Identity.MessageMethodRef, "(&", streamName, "{source: session})")
	g.P("session.responses <- ", resultName, "{err: err, terminal: true}")
	g.P("}()")
	g.P("return session")
	g.P("}")
	g.P()
	g.P("func (s *", streamName, ") Recv() (*", reqType, ", error) {")
	g.P("select {")
	g.P("case <-s.source.ctx.Done():")
	g.P("return nil, s.source.ctx.Err()")
	g.P("case msg, ok := <-s.source.requests:")
	g.P("if !ok {")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("return msg, nil")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", streamName, ") RecvMsg(m any) error {")
	g.P("msg, err := s.Recv()")
	g.P("if err != nil {")
	g.P("return err")
	g.P("}")
	g.P("typed, ok := m.(*", reqType, ")")
	g.P("if !ok || typed == nil {")
	g.P(`return fmt.Errorf("rpccgo: grpc direct bidi request type mismatch")`)
	g.P("}")
	g.P("*typed = *msg")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("func (s *", streamName, ") Send(resp *", respType, ") error {")
	g.P("if resp == nil {")
	g.P(`return fmt.Errorf("rpccgo: grpc direct bidi response is nil")`)
	g.P("}")
	g.P("select {")
	g.P("case <-s.source.ctx.Done():")
	g.P("return s.source.ctx.Err()")
	g.P("case s.source.responses <- ", resultName, "{data: resp}:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", streamName, ") SendMsg(m any) error {")
	g.P("typed, ok := m.(*", respType, ")")
	g.P("if !ok || typed == nil {")
	g.P(`return fmt.Errorf("rpccgo: grpc direct bidi response type mismatch")`)
	g.P("}")
	g.P("return s.Send(typed)")
	g.P("}")
	g.P()
	g.P("func (s *", streamName, ") SetHeader(md metadata.MD) error {")
	g.P("return s.source.SetHeader(md)")
	g.P("}")
	g.P()
	g.P("func (s *", streamName, ") SendHeader(md metadata.MD) error {")
	g.P("return s.source.SendHeader(md)")
	g.P("}")
	g.P()
	g.P("func (s *", streamName, ") SetTrailer(md metadata.MD) {")
	g.P("s.source.SetTrailer(md)")
	g.P("}")
	g.P()
	g.P("func (s *", streamName, ") Context() context.Context { return s.source.ctx }")
	g.P()
	g.P("func (s *", wrapperName, ") SetHeader(md metadata.MD) error {")
	g.P("if md == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.header == nil {")
	g.P("s.header = md.Copy()")
	g.P("return nil")
	g.P("}")
	g.P("s.header = metadata.Join(s.header, md)")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") SendHeader(md metadata.MD) error {")
	g.P("return s.SetHeader(md)")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") SetTrailer(md metadata.MD) {")
	g.P("if md == nil {")
	g.P("return")
	g.P("}")
	g.P("if s.trailer == nil {")
	g.P("s.trailer = md.Copy()")
	g.P("return")
	g.P("}")
	g.P("s.trailer = metadata.Join(s.trailer, md)")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Send(ctx context.Context, req ", reqPtrType, ") error {")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case s.requests <- req:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") CloseSend(ctx context.Context) error {")
	g.P("s.closeRequests.Do(func() { close(s.requests) })")
	g.P("return nil")
	g.P("}")
	g.P()
	renderConnectDirectRecvFinishCancel(g, wrapperName, respPtrType)
}

func renderGRPCRemoteMessageSession(g *protogen.GeneratedFile, service ServicePlan, method runtimeMethodProjection) {
	wrapperName := grpcRemoteMessageSessionName(service.GoName, method)
	reqType := method.Message.RequestType
	respType := method.Message.ResponseType
	clientName := service.GoName + "Client"
	switch method.Stream.Shape {
	case runtimeStreamClient:
		renderGRPCRemoteClientStreamSession(g, method, wrapperName, reqType, respType, clientName)
	case runtimeStreamServer:
		renderGRPCRemoteServerStreamSession(g, method, wrapperName, reqType, respType, clientName)
	case runtimeStreamBidi:
		renderGRPCRemoteBidiStreamSession(g, method, wrapperName, reqType, respType, clientName)
	}
}

func renderGRPCRemoteClientStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, clientName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, client ", clientName, ") (*", wrapperName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := client.", method.Identity.MessageMethodRef, "(streamCtx)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", wrapperName, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("stream grpc.ClientStreamingClient[", reqType, ", ", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Send(ctx context.Context, req ", reqPtrType, ") error {")
	g.P("_ = ctx")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return errors.New("rpccgo: grpc remote client stream is nil")`)
	g.P("}")
	g.P("return s.stream.Send(req)")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) (", respPtrType, ", error) {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: grpc remote client stream is nil")`)
	g.P("}")
	g.P("defer func() { if s.cancel != nil { s.cancel() } }()")
	g.P("response, err := s.stream.CloseAndRecv()")
	g.P("if err != nil {")
	g.P("return nil, err")
	g.P("}")
	g.P("if response == nil {")
	g.P(`return nil, errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("return response, nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return s.stream.CloseSend()")
	g.P("}")
	g.P()
}

func renderGRPCRemoteServerStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, clientName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, client ", clientName, ", req ", reqPtrType, ") (*", wrapperName, ", error) {")
	g.P("if req == nil {")
	g.P(`return nil, errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := client.", method.Identity.MessageMethodRef, "(streamCtx, req)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", wrapperName, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("stream grpc.ServerStreamingClient[", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()
	renderGRPCRemoteRecvFinishCancel(g, wrapperName, "server stream", respPtrType)
}

func renderGRPCRemoteBidiStreamSession(g *protogen.GeneratedFile, method runtimeMethodProjection, wrapperName, reqType, respType, clientName string) {
	reqPtrType := runtimeMessageRequestType(method)
	respPtrType := runtimeMessageResponseType(method)
	g.P("func new", wrapperName, "(ctx context.Context, client ", clientName, ") (*", wrapperName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("stream, err := client.", method.Identity.MessageMethodRef, "(streamCtx)")
	g.P("if err != nil {")
	g.P("cancel()")
	g.P("return nil, err")
	g.P("}")
	g.P("return &", wrapperName, "{stream: stream, cancel: cancel}, nil")
	g.P("}")
	g.P()
	g.P("type ", wrapperName, " struct {")
	g.P("stream grpc.BidiStreamingClient[", reqType, ", ", respType, "]")
	g.P("cancel context.CancelFunc")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Send(ctx context.Context, req ", reqPtrType, ") error {")
	g.P("_ = ctx")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return errors.New("rpccgo: grpc remote bidi stream is nil")`)
	g.P("}")
	g.P("return s.stream.Send(req)")
	g.P("}")
	g.P()
	renderGRPCRemoteRecvFinishCancel(g, wrapperName, "bidi stream", respPtrType)
	g.P("func (s *", wrapperName, ") CloseSend(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("return s.stream.CloseSend()")
	g.P("}")
	g.P()
}

func renderGRPCRemoteRecvFinishCancel(g *protogen.GeneratedFile, wrapperName, label, respPtrType string) {
	g.P("func (s *", wrapperName, ") Recv(ctx context.Context) (", respPtrType, ", error) {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P(`return nil, errors.New("rpccgo: grpc remote `, label, ` is nil")`)
	g.P("}")
	g.P("response, err := s.stream.Recv()")
	g.P("if err != nil {")
	g.P("if errors.Is(err, io.EOF) {")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("return nil, err")
	g.P("}")
	g.P("if response == nil {")
	g.P(`return nil, errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("return response, nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Finish(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s != nil && s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P()
	g.P("func (s *", wrapperName, ") Cancel(ctx context.Context) error {")
	g.P("_ = ctx")
	g.P("if s == nil || s.stream == nil {")
	g.P("return nil")
	g.P("}")
	g.P("if s.cancel != nil {")
	g.P("s.cancel()")
	g.P("}")
	g.P("return s.stream.CloseSend()")
	g.P("}")
	g.P()
}

func grpcDirectMessageSessionName(serviceName string, method runtimeMethodProjection) string {
	return lowerInitial(serviceName) + method.Identity.GoName + "GRPCDirectMessageStreamSession"
}

func connectDirectMessageSessionName(serviceName string, method runtimeMethodProjection) string {
	return lowerInitial(serviceName) + method.Identity.GoName + "ConnectDirectMessageStreamSession"
}

func grpcRemoteMessageSessionName(serviceName string, method runtimeMethodProjection) string {
	return lowerInitial(serviceName) + method.Identity.GoName + "GRPCRemoteMessageStreamSession"
}

func connectRemoteMessageSessionName(serviceName string, method runtimeMethodProjection) string {
	return lowerInitial(serviceName) + method.Identity.GoName + "ConnectRemoteMessageStreamSession"
}
