package generator

import (
	"fmt"
	"path"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// RenderDartGeneratedFiles writes every Dart FFI client artifact in a validated
// generation plan into the plugin response.
func RenderDartGeneratedFiles(plugin *protogen.Plugin, plan GenerationPlan, config DartGeneratorConfig) error {
	if plugin == nil {
		return fmt.Errorf("dart generator plugin is nil")
	}
	if err := ValidateGenerationPlan(plan); err != nil {
		return err
	}
	return renderDartGeneratedFiles(plugin, plan, config)
}

func renderDartGeneratedFiles(plugin *protogen.Plugin, plan GenerationPlan, config DartGeneratorConfig) error {
	renderDartEntryFile(plugin, plan)
	for _, pkg := range plan.Packages {
		for _, file := range pkg.Files {
			for _, service := range file.Services {
				renderDartServiceClientFile(plugin, file, service, config)
			}
		}
	}
	return nil
}

func renderDartEntryFile(plugin *protogen.Plugin, plan GenerationPlan) {
	g := plugin.NewGeneratedFile(defaultDartNativeAssetName, "")
	g.P("// Code generated by protoc-gen-rpc-cgo-dart. DO NOT EDIT.")
	g.P()
	g.P("library;")
	g.P()

	exports := make(map[string]struct{})
	for _, pkg := range plan.Packages {
		for _, file := range pkg.Files {
			exports[file.GeneratedFilenamePrefix+".pb.dart"] = struct{}{}
			for _, service := range file.Services {
				exports[dartServiceClientFilename(file, service)] = struct{}{}
			}
		}
	}

	paths := make([]string, 0, len(exports))
	for export := range exports {
		paths = append(paths, export)
	}
	sort.Strings(paths)
	for _, export := range paths {
		g.P("export '", export, "';")
	}
}

func renderDartServiceClientFile(plugin *protogen.Plugin, file FilePlan, service ServicePlan, config DartGeneratorConfig) {
	filename := dartServiceClientFilename(file, service)
	g := plugin.NewGeneratedFile(filename, "")

	g.P("// Code generated by protoc-gen-rpc-cgo-dart. DO NOT EDIT.")
	g.P("//")
	g.P("// Source: ", file.ProtoPath)
	g.P()
	g.P("@ffi.DefaultAsset('", dartNativeAssetID(config), "')")
	g.P("library;")
	g.P()
	g.P("import 'dart:convert' as convert;")
	g.P("import 'dart:ffi' as ffi;")
	g.P("import 'dart:typed_data' as typed_data;")
	g.P()
	g.P("import 'package:ffi/ffi.dart' as pkg_ffi;")
	g.P()
	g.P("import '", dartPBImport(file), "' as pb;")
	g.P()
	g.P("// rpccgo Dart FFI message client generated file for ", service.GoName)
	g.P()
	renderDartSharedTypedefs(g)
	renderDartSharedNativeBindings(g)
	for _, method := range service.Methods {
		renderDartNativeBinding(g, file, service, method)
	}
	g.P("class ", dartClientClassName(service), " {")
	dartP(g, 1, "const ", dartClientClassName(service), "();")
	for _, method := range service.Methods {
		renderDartClientMethod(g, file, service, method)
	}
	renderDartErrorHelpers(g)
	g.P("}")
	g.P()
	for _, method := range service.Methods {
		renderDartStreamHandleClass(g, service, method)
	}
}

func dartP(g *protogen.GeneratedFile, indent int, v ...any) {
	if indent <= 0 {
		g.P(v...)
		return
	}
	args := make([]any, 0, len(v)+1)
	args = append(args, strings.Repeat("  ", indent))
	args = append(args, v...)
	g.P(args...)
}

func renderDartSharedTypedefs(g *protogen.GeneratedFile) {
	g.P("typedef _RpccgoReleaseCAbi = ffi.Int32 Function(ffi.UintPtr ptr);")
	g.P("typedef _RpccgoTakeErrorTextCAbi = ffi.Int32 Function(ffi.Int32 errID, ffi.Pointer<ffi.UintPtr> textPtr, ffi.Pointer<ffi.Int32> textLen);")
	g.P("typedef _RpccgoMessageUnaryCAbi = ffi.Int32 Function(ffi.UintPtr requestPtr, ffi.Int32 requestLen, ffi.Pointer<ffi.UintPtr> responsePtr, ffi.Pointer<ffi.Int32> responseLen);")
	g.P("typedef _RpccgoStreamStartCAbi = ffi.Int32 Function(ffi.Pointer<ffi.Int32> handle);")
	g.P("typedef _RpccgoServerStreamStartCAbi = ffi.Int32 Function(ffi.UintPtr requestPtr, ffi.Int32 requestLen, ffi.Pointer<ffi.Int32> handle);")
	g.P("typedef _RpccgoStreamSendCAbi = ffi.Int32 Function(ffi.Int32 handle, ffi.UintPtr requestPtr, ffi.Int32 requestLen);")
	g.P("typedef _RpccgoStreamRecvCAbi = ffi.Int32 Function(ffi.Int32 handle, ffi.Pointer<ffi.UintPtr> responsePtr, ffi.Pointer<ffi.Int32> responseLen);")
	g.P("typedef _RpccgoStreamFinishCAbi = ffi.Int32 Function(ffi.Int32 handle, ffi.Pointer<ffi.UintPtr> responsePtr, ffi.Pointer<ffi.Int32> responseLen);")
	g.P("typedef _RpccgoStreamFinishVoidCAbi = ffi.Int32 Function(ffi.Int32 handle);")
	g.P("typedef _RpccgoStreamCancelCAbi = ffi.Int32 Function(ffi.Int32 handle);")
	g.P()
}

func renderDartSharedNativeBindings(g *protogen.GeneratedFile) {
	g.P("@ffi.Native<_RpccgoReleaseCAbi>(symbol: '", cgoSharedExportName("release"), "')")
	g.P("external int ", dartSharedNativeBindingName("release"), "(int ptr);")
	g.P()
	g.P("@ffi.Native<_RpccgoTakeErrorTextCAbi>(symbol: '", cgoSharedExportName("take_error_text"), "')")
	g.P("external int ", dartSharedNativeBindingName("take_error_text"), "(int errID, ffi.Pointer<ffi.UintPtr> textPtr, ffi.Pointer<ffi.Int32> textLen);")
	g.P()
}

func renderDartNativeBinding(g *protogen.GeneratedFile, file FilePlan, service ServicePlan, method MethodPlan) {
	switch method.Streaming {
	case StreamingKindUnary:
		renderDartNativeBindingOperation(g, file, service, method, "", "_RpccgoMessageUnaryCAbi", dartNativeBindingName(method, ""))
	case StreamingKindClientStreaming:
		renderDartNativeBindingOperation(g, file, service, method, "start", "_RpccgoStreamStartCAbi", dartNativeBindingName(method, "start"))
		renderDartNativeBindingOperation(g, file, service, method, "send", "_RpccgoStreamSendCAbi", dartNativeBindingName(method, "send"))
		renderDartNativeBindingOperation(g, file, service, method, "finish", "_RpccgoStreamFinishCAbi", dartNativeBindingName(method, "finish"))
		renderDartNativeBindingOperation(g, file, service, method, "cancel", "_RpccgoStreamCancelCAbi", dartNativeBindingName(method, "cancel"))
	case StreamingKindServerStreaming:
		renderDartNativeBindingOperation(g, file, service, method, "start", "_RpccgoServerStreamStartCAbi", dartNativeBindingName(method, "start"))
		renderDartNativeBindingOperation(g, file, service, method, "recv", "_RpccgoStreamRecvCAbi", dartNativeBindingName(method, "recv"))
		renderDartNativeBindingOperation(g, file, service, method, "finish", "_RpccgoStreamFinishVoidCAbi", dartNativeBindingName(method, "finish"))
		renderDartNativeBindingOperation(g, file, service, method, "cancel", "_RpccgoStreamCancelCAbi", dartNativeBindingName(method, "cancel"))
	case StreamingKindBidiStreaming:
		renderDartNativeBindingOperation(g, file, service, method, "start", "_RpccgoStreamStartCAbi", dartNativeBindingName(method, "start"))
		renderDartNativeBindingOperation(g, file, service, method, "send", "_RpccgoStreamSendCAbi", dartNativeBindingName(method, "send"))
		renderDartNativeBindingOperation(g, file, service, method, "recv", "_RpccgoStreamRecvCAbi", dartNativeBindingName(method, "recv"))
		renderDartNativeBindingOperation(g, file, service, method, "close_send", "_RpccgoStreamFinishVoidCAbi", dartNativeBindingName(method, "close_send"))
		renderDartNativeBindingOperation(g, file, service, method, "finish", "_RpccgoStreamFinishVoidCAbi", dartNativeBindingName(method, "finish"))
		renderDartNativeBindingOperation(g, file, service, method, "cancel", "_RpccgoStreamCancelCAbi", dartNativeBindingName(method, "cancel"))
	}
}

func renderDartNativeBindingOperation(g *protogen.GeneratedFile, file FilePlan, service ServicePlan, method MethodPlan, operation, nativeType, bindingName string) {
	g.P("@ffi.Native<", nativeType, ">(symbol: '", messageCExportFuncName(file, service, method, operation), "')")
	switch method.Streaming {
	case StreamingKindUnary:
		g.P("external int ", bindingName, "(int requestPtr, int requestLen, ffi.Pointer<ffi.UintPtr> responsePtr, ffi.Pointer<ffi.Int32> responseLen);")
	case StreamingKindClientStreaming:
		switch operation {
		case "start":
			g.P("external int ", bindingName, "(ffi.Pointer<ffi.Int32> handle);")
		case "send":
			g.P("external int ", bindingName, "(int handle, int requestPtr, int requestLen);")
		case "finish":
			g.P("external int ", bindingName, "(int handle, ffi.Pointer<ffi.UintPtr> responsePtr, ffi.Pointer<ffi.Int32> responseLen);")
		case "cancel":
			g.P("external int ", bindingName, "(int handle);")
		}
	case StreamingKindServerStreaming:
		switch operation {
		case "start":
			g.P("external int ", bindingName, "(int requestPtr, int requestLen, ffi.Pointer<ffi.Int32> handle);")
		case "recv":
			g.P("external int ", bindingName, "(int handle, ffi.Pointer<ffi.UintPtr> responsePtr, ffi.Pointer<ffi.Int32> responseLen);")
		case "finish", "cancel":
			g.P("external int ", bindingName, "(int handle);")
		}
	case StreamingKindBidiStreaming:
		switch operation {
		case "start":
			g.P("external int ", bindingName, "(ffi.Pointer<ffi.Int32> handle);")
		case "send":
			g.P("external int ", bindingName, "(int handle, int requestPtr, int requestLen);")
		case "recv":
			g.P("external int ", bindingName, "(int handle, ffi.Pointer<ffi.UintPtr> responsePtr, ffi.Pointer<ffi.Int32> responseLen);")
		case "close_send", "finish", "cancel":
			g.P("external int ", bindingName, "(int handle);")
		}
	}
	g.P()
}

func renderDartClientMethod(g *protogen.GeneratedFile, file FilePlan, service ServicePlan, method MethodPlan) {
	switch method.Streaming {
	case StreamingKindUnary:
		renderDartUnaryMethod(g, method)
	case StreamingKindClientStreaming:
		renderDartClientStreamingMethods(g, service, method)
	case StreamingKindServerStreaming:
		renderDartServerStreamingMethods(g, service, method)
	case StreamingKindBidiStreaming:
		renderDartBidiStreamingMethods(g, service, method)
	}
}

func renderDartUnaryMethod(g *protogen.GeneratedFile, method MethodPlan) {
	dartP(g, 1, "({pb.", method.Response.GoName, "? value, String? error}) ", dartMethodName(method), "(pb.", method.Request.GoName, " request) {")
	dartP(g, 2, "final responsePtr = pkg_ffi.calloc<ffi.UintPtr>();")
	dartP(g, 2, "final responseLen = pkg_ffi.calloc<ffi.Int32>();")
	dartP(g, 2, "final requestBytes = request.writeToBuffer();")
	dartP(g, 2, "final requestPtr = _allocateBytes(requestBytes);")
	dartP(g, 2, "try {")
	dartP(g, 3, "final errID = ", dartNativeBindingName(method, ""), "(requestPtr.address, requestBytes.length, responsePtr, responseLen);")
	dartP(g, 3, "final error = _takeErrorResult(errID);")
	dartP(g, 3, "if (error != null) {")
	dartP(g, 4, "return (value: null, error: error);")
	dartP(g, 3, "}")
	dartP(g, 3, "final responseBytes = _takeBytes(responsePtr.value, responseLen.value);")
	dartP(g, 3, "if (responseBytes.error != null) {")
	dartP(g, 4, "return (value: null, error: responseBytes.error);")
	dartP(g, 3, "}")
	dartP(g, 3, "return (value: pb.", method.Response.GoName, ".fromBuffer(responseBytes.value!), error: null);")
	dartP(g, 2, "} finally {")
	dartP(g, 3, "pkg_ffi.calloc.free(requestPtr);")
	dartP(g, 3, "pkg_ffi.calloc.free(responsePtr);")
	dartP(g, 3, "pkg_ffi.calloc.free(responseLen);")
	dartP(g, 2, "}")
	dartP(g, 1, "}")
	g.P()
}

func renderDartClientStreamingMethods(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan) {
	className := dartStreamClassName(service, method)
	dartP(g, 1, "({", className, "? value, String? error}) ", dartStartMethodName(method), "() {")
	dartP(g, 2, "final handlePtr = pkg_ffi.calloc<ffi.Int32>();")
	dartP(g, 2, "try {")
	dartP(g, 3, "final errID = ", dartNativeBindingName(method, "start"), "(handlePtr);")
	dartP(g, 3, "final error = _takeErrorResult(errID);")
	dartP(g, 3, "if (error != null) {")
	dartP(g, 4, "return (value: null, error: error);")
	dartP(g, 3, "}")
	dartP(g, 3, "return (value: ", className, "._(this, handlePtr.value), error: null);")
	dartP(g, 2, "} finally {")
	dartP(g, 3, "pkg_ffi.calloc.free(handlePtr);")
	dartP(g, 2, "}")
	dartP(g, 1, "}")
	g.P()
}

func renderDartServerStreamingMethods(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan) {
	className := dartStreamClassName(service, method)
	dartP(g, 1, "({", className, "? value, String? error}) ", dartStartMethodName(method), "(pb.", method.Request.GoName, " request) {")
	dartP(g, 2, "final handlePtr = pkg_ffi.calloc<ffi.Int32>();")
	dartP(g, 2, "final requestBytes = request.writeToBuffer();")
	dartP(g, 2, "final requestPtr = _allocateBytes(requestBytes);")
	dartP(g, 2, "try {")
	dartP(g, 3, "final errID = ", dartNativeBindingName(method, "start"), "(requestPtr.address, requestBytes.length, handlePtr);")
	dartP(g, 3, "final error = _takeErrorResult(errID);")
	dartP(g, 3, "if (error != null) {")
	dartP(g, 4, "return (value: null, error: error);")
	dartP(g, 3, "}")
	dartP(g, 3, "return (value: ", className, "._(this, handlePtr.value), error: null);")
	dartP(g, 2, "} finally {")
	dartP(g, 3, "pkg_ffi.calloc.free(requestPtr);")
	dartP(g, 3, "pkg_ffi.calloc.free(handlePtr);")
	dartP(g, 2, "}")
	dartP(g, 1, "}")
	g.P()
}

func renderDartBidiStreamingMethods(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan) {
	className := dartStreamClassName(service, method)
	dartP(g, 1, "({", className, "? value, String? error}) ", dartStartMethodName(method), "() {")
	dartP(g, 2, "final handlePtr = pkg_ffi.calloc<ffi.Int32>();")
	dartP(g, 2, "try {")
	dartP(g, 3, "final errID = ", dartNativeBindingName(method, "start"), "(handlePtr);")
	dartP(g, 3, "final error = _takeErrorResult(errID);")
	dartP(g, 3, "if (error != null) {")
	dartP(g, 4, "return (value: null, error: error);")
	dartP(g, 3, "}")
	dartP(g, 3, "return (value: ", className, "._(this, handlePtr.value), error: null);")
	dartP(g, 2, "} finally {")
	dartP(g, 3, "pkg_ffi.calloc.free(handlePtr);")
	dartP(g, 2, "}")
	dartP(g, 1, "}")
	g.P()
}

func renderDartStreamHandleClass(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan) {
	switch method.Streaming {
	case StreamingKindClientStreaming:
		renderDartStreamClass(g, dartClientClassName(service), dartStreamClassName(service, method), method, true, false, true, false)
	case StreamingKindServerStreaming:
		renderDartStreamClass(g, dartClientClassName(service), dartStreamClassName(service, method), method, false, true, false, false)
	case StreamingKindBidiStreaming:
		renderDartStreamClass(g, dartClientClassName(service), dartStreamClassName(service, method), method, true, true, false, true)
	}
}

func renderDartStreamClass(g *protogen.GeneratedFile, clientClassName, className string, method MethodPlan, canSend, canRecv, finishReturnsResponse, canCloseSend bool) {
	g.P("class ", className, " {")
	dartP(g, 1, className, "._(this._client, this._handle);")
	dartP(g, 1, "final ", clientClassName, " _client;")
	dartP(g, 1, "final int _handle;")
	if canSend {
		dartP(g, 1, "String? Send(pb.", method.Request.GoName, " request) {")
		dartP(g, 2, "final requestBytes = request.writeToBuffer();")
		dartP(g, 2, "final requestPtr = _client._allocateBytes(requestBytes);")
		dartP(g, 2, "try {")
		dartP(g, 3, "final errID = ", dartNativeBindingName(method, "send"), "(_handle, requestPtr.address, requestBytes.length);")
		dartP(g, 3, "return _client._takeErrorResult(errID);")
		dartP(g, 2, "} finally {")
		dartP(g, 3, "pkg_ffi.calloc.free(requestPtr);")
		dartP(g, 2, "}")
		dartP(g, 1, "}")
	}
	if canRecv {
		dartP(g, 1, "({pb.", method.Response.GoName, "? value, String? error}) Recv() {")
		dartP(g, 2, "final responsePtr = pkg_ffi.calloc<ffi.UintPtr>();")
		dartP(g, 2, "final responseLen = pkg_ffi.calloc<ffi.Int32>();")
		dartP(g, 2, "try {")
		dartP(g, 3, "final errID = ", dartNativeBindingName(method, "recv"), "(_handle, responsePtr, responseLen);")
		dartP(g, 3, "final error = _client._takeErrorResult(errID);")
		dartP(g, 3, "if (error != null) {")
		dartP(g, 4, "return (value: null, error: error);")
		dartP(g, 3, "}")
		dartP(g, 3, "final responseBytes = _client._takeBytes(responsePtr.value, responseLen.value);")
		dartP(g, 3, "if (responseBytes.error != null) {")
		dartP(g, 4, "return (value: null, error: responseBytes.error);")
		dartP(g, 3, "}")
		dartP(g, 3, "return (value: pb.", method.Response.GoName, ".fromBuffer(responseBytes.value!), error: null);")
		dartP(g, 2, "} finally {")
		dartP(g, 3, "pkg_ffi.calloc.free(responsePtr);")
		dartP(g, 3, "pkg_ffi.calloc.free(responseLen);")
		dartP(g, 2, "}")
		dartP(g, 1, "}")
	}
	if canCloseSend {
		dartP(g, 1, "String? CloseSend() {")
		dartP(g, 2, "final errID = ", dartNativeBindingName(method, "close_send"), "(_handle);")
		dartP(g, 2, "return _client._takeErrorResult(errID);")
		dartP(g, 1, "}")
	}
	if finishReturnsResponse {
		dartP(g, 1, "({pb.", method.Response.GoName, "? value, String? error}) Finish() {")
		dartP(g, 2, "final responsePtr = pkg_ffi.calloc<ffi.UintPtr>();")
		dartP(g, 2, "final responseLen = pkg_ffi.calloc<ffi.Int32>();")
		dartP(g, 2, "try {")
		dartP(g, 3, "final errID = ", dartNativeBindingName(method, "finish"), "(_handle, responsePtr, responseLen);")
		dartP(g, 3, "final error = _client._takeErrorResult(errID);")
		dartP(g, 3, "if (error != null) {")
		dartP(g, 4, "return (value: null, error: error);")
		dartP(g, 3, "}")
		dartP(g, 3, "final responseBytes = _client._takeBytes(responsePtr.value, responseLen.value);")
		dartP(g, 3, "if (responseBytes.error != null) {")
		dartP(g, 4, "return (value: null, error: responseBytes.error);")
		dartP(g, 3, "}")
		dartP(g, 3, "return (value: pb.", method.Response.GoName, ".fromBuffer(responseBytes.value!), error: null);")
		dartP(g, 2, "} finally {")
		dartP(g, 3, "pkg_ffi.calloc.free(responsePtr);")
		dartP(g, 3, "pkg_ffi.calloc.free(responseLen);")
		dartP(g, 2, "}")
		dartP(g, 1, "}")
	} else {
		dartP(g, 1, "String? Finish() {")
		dartP(g, 2, "final errID = ", dartNativeBindingName(method, "finish"), "(_handle);")
		dartP(g, 2, "return _client._takeErrorResult(errID);")
		dartP(g, 1, "}")
	}
	dartP(g, 1, "String? Cancel() {")
	dartP(g, 2, "final errID = ", dartNativeBindingName(method, "cancel"), "(_handle);")
	dartP(g, 2, "return _client._takeErrorResult(errID);")
	dartP(g, 1, "}")
	g.P("}")
	g.P()
}

func renderDartErrorHelpers(g *protogen.GeneratedFile) {
	dartP(g, 1, "ffi.Pointer<ffi.Uint8> _allocateBytes(List<int> data) {")
	dartP(g, 2, "final ptr = pkg_ffi.calloc<ffi.Uint8>(data.length);")
	dartP(g, 2, "ptr.asTypedList(data.length).setAll(0, data);")
	dartP(g, 2, "return ptr;")
	dartP(g, 1, "}")
	g.P()
	dartP(g, 1, "({typed_data.Uint8List? value, String? error}) _takeBytes(int ptr, int length) {")
	dartP(g, 2, "if (length < 0) {")
	dartP(g, 3, "return (value: null, error: 'rpccgo: response length is negative');")
	dartP(g, 2, "}")
	dartP(g, 2, "if (length == 0) {")
	dartP(g, 3, "return (value: typed_data.Uint8List(0), error: null);")
	dartP(g, 2, "}")
	dartP(g, 2, "if (ptr == 0) {")
	dartP(g, 3, "return (value: null, error: 'rpccgo: response pointer is nil');")
	dartP(g, 2, "}")
	dartP(g, 2, "final data = typed_data.Uint8List.fromList(ffi.Pointer<ffi.Uint8>.fromAddress(ptr).asTypedList(length));")
	dartP(g, 2, "final status = ", dartSharedNativeBindingName("release"), "(ptr);")
	dartP(g, 2, "if (status != 0) {")
	dartP(g, 3, "return (value: null, error: 'rpccgo: failed to release response buffer');")
	dartP(g, 2, "}")
	dartP(g, 2, "return (value: data, error: null);")
	dartP(g, 1, "}")
	g.P()
	dartP(g, 1, "String? _takeErrorResult(int errID) {")
	dartP(g, 2, "if (errID == 0) {")
	dartP(g, 3, "return null;")
	dartP(g, 2, "}")
	dartP(g, 2, "return _takeError(errID);")
	dartP(g, 1, "}")
	g.P()
	dartP(g, 1, "String _takeError(int errID) {")
	dartP(g, 2, "final textPtr = pkg_ffi.calloc<ffi.UintPtr>();")
	dartP(g, 2, "final textLen = pkg_ffi.calloc<ffi.Int32>();")
	dartP(g, 2, "try {")
	dartP(g, 3, "final status = ", dartSharedNativeBindingName("take_error_text"), "(errID, textPtr, textLen);")
	dartP(g, 3, "if (status != 0) {")
	dartP(g, 4, "return 'rpccgo error $errID';")
	dartP(g, 3, "}")
	dartP(g, 3, "final data = _takeBytes(textPtr.value, textLen.value);")
	dartP(g, 3, "if (data.error != null) {")
	dartP(g, 4, "return data.error!;")
	dartP(g, 3, "}")
	dartP(g, 3, "return convert.utf8.decode(data.value!);")
	dartP(g, 2, "} finally {")
	dartP(g, 3, "pkg_ffi.calloc.free(textPtr);")
	dartP(g, 3, "pkg_ffi.calloc.free(textLen);")
	dartP(g, 2, "}")
	dartP(g, 1, "}")
}

func dartServiceClientFilename(file FilePlan, service ServicePlan) string {
	return fmt.Sprintf("%s.%s.rpccgo.dart", file.GeneratedFilenamePrefix, lowerSnakeCase(service.GoName))
}

func dartPBImport(file FilePlan) string {
	base := path.Base(file.GeneratedFilenamePrefix)
	return base + ".pb.dart"
}

func dartClientClassName(service ServicePlan) string {
	return service.GoName + "RpccgoClient"
}

func dartStreamClassName(service ServicePlan, method MethodPlan) string {
	return service.GoName + method.GoName + "Stream"
}

func dartMethodName(method MethodPlan) string {
	return method.Name
}

func dartStartMethodName(method MethodPlan) string {
	return method.GoName + "Start"
}

func dartNativeAssetID(config DartGeneratorConfig) string {
	return "package:" + config.DartPackage + "/" + defaultDartNativeAssetPath
}

func dartFunctionFieldName(method MethodPlan, operation string) string {
	name := "_" + lowerInitial(method.GoName)
	if operation != "" {
		name += upperCamelFromSnake(operation)
	}
	return name
}

func dartNativeBindingName(method MethodPlan, operation string) string {
	return dartFunctionFieldName(method, operation) + "Raw"
}

func dartSharedNativeBindingName(name string) string {
	return "_rpccgo" + upperCamelFromSnake(name) + "Raw"
}
