package generator

import "google.golang.org/protobuf/compiler/protogen"

const kotlinMissingStreamLifecycleError = "rpccgo: no stream lifecycle is registered; use Rpccgo.withLifecycle(...) or Rpccgo.registerGlobalLifecycle(...) before starting a stream"

func renderJNIKotlinFile(plugin *protogen.Plugin, plan FilePlan, service ServicePlan, config JNIGeneratorConfig) {
	g := plugin.NewGeneratedFile(jniKotlinFilename(config), "")
	renderGeneratedHeaderForTool(g, "protoc-gen-rpc-cgo-jni")
	g.P("// Source: ", plan.ProtoPath)
	g.P()
	pkg, className := jniClassPackageAndSimpleName(config.JNIClass)
	g.P("package ", pkg)
	g.P()
	g.P("import android.app.Activity")
	g.P("import android.app.Application")
	g.P("import android.os.Bundle")
	g.P("import java.util.WeakHashMap")
	g.P("import java.nio.ByteBuffer")
	g.P("import java.nio.ByteOrder")
	g.P("import java.util.Collections")
	g.P("import java.util.concurrent.CopyOnWriteArraySet")
	g.P("import java.util.concurrent.atomic.AtomicBoolean")
	g.P("import java.util.concurrent.atomic.AtomicReference")
	g.P()
	g.P("/** Implemented by generated streams that should be cancelled with a lifecycle. */")
	g.P("private interface RpccgoLifecycleBoundStream {")
	g.P("    /** Cancels the stream because its bound lifecycle has ended. */")
	g.P("    fun cancelFromLifecycle()")
	g.P("}")
	g.P()
	g.P("/** Tracks generated streams that should be cancelled together. */")
	g.P("class RpccgoStreamLifecycle {")
	g.P("    private val streams = CopyOnWriteArraySet<RpccgoLifecycleBoundStream>()")
	g.P("    private val disposed = AtomicBoolean(false)")
	g.P()
	g.P("    /** Attaches a stream to this lifecycle. */")
	g.P("    fun attach(stream: RpccgoLifecycleBoundStream): String? {")
	g.P("        if (disposed.get()) return \"rpccgo: stream lifecycle is disposed\"")
	g.P("        streams.add(stream)")
	g.P("        if (disposed.get() && streams.remove(stream)) {")
	g.P("            stream.cancelFromLifecycle()")
	g.P("            return \"rpccgo: stream lifecycle is disposed\"")
	g.P("        }")
	g.P("        return null")
	g.P("    }")
	g.P()
	g.P("    /** Detaches a stream that has already finished or been cancelled. */")
	g.P("    fun detach(stream: RpccgoLifecycleBoundStream) {")
	g.P("        streams.remove(stream)")
	g.P("    }")
	g.P()
	g.P("    /** Cancels every attached stream and prevents future attachments. */")
	g.P("    fun dispose() {")
	g.P("        if (!disposed.compareAndSet(false, true)) return")
	g.P("        val active = streams.toList()")
	g.P("        streams.clear()")
	g.P("        active.forEach { it.cancelFromLifecycle() }")
	g.P("    }")
	g.P("}")
	g.P()
	g.P("object Rpccgo {")
	g.P("    private val activityLifecycles = Collections.synchronizedMap(WeakHashMap<Activity, RpccgoStreamLifecycle>())")
	g.P("    private val scopedLifecycle = ThreadLocal<RpccgoStreamLifecycle?>()")
	g.P("    @Volatile private var globalLifecycle: RpccgoStreamLifecycle? = null")
	g.P("    @Volatile private var lifecycleCallbacksRegistered = false")
	g.P()
	g.P("    /** Returns the scoped, global, or current Android Activity stream lifecycle. */")
	g.P("    fun currentLifecycle(): RpccgoStreamLifecycle? =")
	g.P("        scopedLifecycle.get() ?: globalLifecycle ?: currentActivity()?.let { lifecycleForActivity(it) }")
	g.P()
	g.P("    /** Registers the fallback lifecycle used when no scoped lifecycle exists. */")
	g.P("    fun registerGlobalLifecycle(lifecycle: RpccgoStreamLifecycle?) {")
	g.P("        globalLifecycle = lifecycle")
	g.P("    }")
	g.P()
	g.P("    /** Runs [block] with [lifecycle] bound as the current stream lifecycle. */")
	g.P("    fun <T> withLifecycle(lifecycle: RpccgoStreamLifecycle, block: () -> T): T {")
	g.P("        val previous = scopedLifecycle.get()")
	g.P("        scopedLifecycle.set(lifecycle)")
	g.P("        return try {")
	g.P("            block()")
	g.P("        } finally {")
	g.P("            if (previous == null) {")
	g.P("                scopedLifecycle.remove()")
	g.P("            } else {")
	g.P("                scopedLifecycle.set(previous)")
	g.P("            }")
	g.P("        }")
	g.P("    }")
	g.P()
	g.P("    private fun lifecycleForActivity(activity: Activity): RpccgoStreamLifecycle {")
	g.P("        registerActivityCallbacks(activity.application)")
	g.P("        synchronized(activityLifecycles) {")
	g.P("            return activityLifecycles.getOrPut(activity) { RpccgoStreamLifecycle() }")
	g.P("        }")
	g.P("    }")
	g.P()
	g.P("    private fun registerActivityCallbacks(application: Application) {")
	g.P("        if (lifecycleCallbacksRegistered) return")
	g.P("        synchronized(activityLifecycles) {")
	g.P("            if (lifecycleCallbacksRegistered) return")
	g.P("            application.registerActivityLifecycleCallbacks(object : Application.ActivityLifecycleCallbacks {")
	g.P("                override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {}")
	g.P("                override fun onActivityStarted(activity: Activity) {}")
	g.P("                override fun onActivityResumed(activity: Activity) {}")
	g.P("                override fun onActivityPaused(activity: Activity) {}")
	g.P("                override fun onActivityStopped(activity: Activity) {}")
	g.P("                override fun onActivitySaveInstanceState(activity: Activity, outState: Bundle) {}")
	g.P("                override fun onActivityDestroyed(activity: Activity) {")
	g.P("                    synchronized(activityLifecycles) { activityLifecycles.remove(activity) }?.dispose()")
	g.P("                }")
	g.P("            })")
	g.P("            lifecycleCallbacksRegistered = true")
	g.P("        }")
	g.P("    }")
	g.P()
	g.P("    private fun currentActivity(): Activity? = try {")
	g.P("        val threadClass = Class.forName(\"android.app.ActivityThread\")")
	g.P("        val currentThread = threadClass.getMethod(\"currentActivityThread\").invoke(null)")
	g.P("        val activitiesField = threadClass.getDeclaredField(\"mActivities\")")
	g.P("        activitiesField.isAccessible = true")
	g.P("        val activities = activitiesField.get(currentThread) as? Map<*, *> ?: return null")
	g.P("        for (record in activities.values) {")
	g.P("            val recordClass = record?.javaClass ?: continue")
	g.P("            val pausedField = recordClass.getDeclaredField(\"paused\")")
	g.P("            pausedField.isAccessible = true")
	g.P("            if (pausedField.getBoolean(record)) continue")
	g.P("            val activityField = recordClass.getDeclaredField(\"activity\")")
	g.P("            activityField.isAccessible = true")
	g.P("            return activityField.get(record) as? Activity")
	g.P("        }")
	g.P("        null")
	g.P("    } catch (_: Throwable) {")
	g.P("        null")
	g.P("    }")
	g.P("}")
	g.P()
	g.P("data class RpccgoResult<T>(val value: T?, val error: String?) {")
	g.P("    val ok: Boolean get() = error == null")
	g.P("    companion object {")
	g.P("        fun <T> success(value: T): RpccgoResult<T> = RpccgoResult(value, null)")
	g.P("        fun <T> failure(error: String): RpccgoResult<T> = RpccgoResult(null, error)")
	g.P("    }")
	g.P("}")
	g.P()
	g.P("object ", className, " {")
	for _, method := range service.Methods {
		renderKotlinCallbackListener(g, service, method)
		renderKotlinNativeDeclarations(g, service, method)
	}
	g.P()
	for _, method := range service.Methods {
		renderKotlinCallbackBindingState(g, service, method, className)
	}
	for _, method := range service.Methods {
		switch method.Streaming {
		case StreamingKindUnary:
			renderKotlinUnaryMethod(g, service, method)
		case StreamingKindClientStreaming:
			renderKotlinClientStreamingMethod(g, service, method, className)
		case StreamingKindServerStreaming:
			renderKotlinServerStreamingMethod(g, service, method, className)
		case StreamingKindBidiStreaming:
			renderKotlinBidiStreamingMethod(g, service, method, className)
		}
	}
	g.P("    private fun decodeResultPayload(bytes: ByteArray?): RpccgoResult<ByteArray> {")
	g.P(`        if (bytes == null) return RpccgoResult.failure("rpccgo: JNI returned null")`)
	g.P(`        if (bytes.size < 5) return RpccgoResult.failure("rpccgo: JNI returned malformed result")`)
	g.P("        val ok = bytes[0].toInt() != 0")
	g.P("        val length = ByteBuffer.wrap(bytes, 1, 4).order(ByteOrder.BIG_ENDIAN).int")
	g.P(`        if (length < 0 || length != bytes.size - 5) return RpccgoResult.failure("rpccgo: JNI returned invalid result length")`)
	g.P("        val payload = bytes.copyOfRange(5, bytes.size)")
	g.P("        if (!ok) return RpccgoResult.failure(payload.toString(Charsets.UTF_8))")
	g.P("        return RpccgoResult.success(payload)")
	g.P("    }")
	g.P()
	g.P("    private fun <T> decodeResult(bytes: ByteArray?, parser: (ByteArray) -> T): RpccgoResult<T> {")
	g.P("        val payload = decodeResultPayload(bytes)")
	g.P(`        if (!payload.ok) return RpccgoResult.failure(payload.error ?: "rpccgo: JNI call failed")`)
	g.P("        return try {")
	g.P("            RpccgoResult.success(parser(payload.value ?: ByteArray(0)))")
	g.P("        } catch (e: Exception) {")
	g.P(`            RpccgoResult.failure("rpccgo: JNI payload decode failed: ${e.message ?: e::class.java.name}")`)
	g.P("        }")
	g.P("    }")
	g.P()
	g.P("    private fun decodeUnitResult(bytes: ByteArray?): RpccgoResult<Unit> =")
	g.P("        decodeResult(bytes) { Unit }")
	g.P()
	g.P("    private fun decodeHandleResult(bytes: ByteArray?): RpccgoResult<Int> {")
	g.P("        val payload = decodeResultPayload(bytes)")
	g.P(`        if (!payload.ok) return RpccgoResult.failure(payload.error ?: "rpccgo: stream start failed")`)
	g.P("        val value = payload.value ?: ByteArray(0)")
	g.P(`        if (value.size != 4) return RpccgoResult.failure("rpccgo: JNI returned invalid stream handle")`)
	g.P("        return RpccgoResult.success(ByteBuffer.wrap(value).order(ByteOrder.BIG_ENDIAN).int)")
	g.P("    }")
	g.P("}")
	g.P()
}

func renderKotlinNativeDeclarations(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan) {
	prefix := lowerInitial(service.GoName) + method.GoName
	switch method.Streaming {
	case StreamingKindUnary:
		g.P("    private external fun ", prefix, "(request: ByteArray): ByteArray?")
	case StreamingKindClientStreaming:
		g.P("    private external fun ", prefix, "Start(): ByteArray?")
		g.P("    private external fun ", prefix, "Send(handle: Int, request: ByteArray): ByteArray?")
		g.P("    private external fun ", prefix, "Finish(handle: Int): ByteArray?")
		g.P("    private external fun ", prefix, "Cancel(handle: Int): ByteArray?")
	case StreamingKindServerStreaming:
		g.P("    private external fun ", prefix, "Start(request: ByteArray): ByteArray?")
		g.P("    private external fun ", prefix, "Recv(handle: Int): ByteArray?")
		g.P("    private external fun ", prefix, "Cancel(handle: Int): ByteArray?")
		g.P("    private external fun ", prefix, "StartCallback(request: ByteArray, listener: ", jniKotlinListenerType(service, method), "): Boolean")
		g.P("    private external fun ", prefix, "CancelCallback(): Boolean")
	case StreamingKindBidiStreaming:
		g.P("    private external fun ", prefix, "Start(): ByteArray?")
		g.P("    private external fun ", prefix, "Send(handle: Int, request: ByteArray): ByteArray?")
		g.P("    private external fun ", prefix, "Recv(handle: Int): ByteArray?")
		g.P("    private external fun ", prefix, "CloseSend(handle: Int): ByteArray?")
		g.P("    private external fun ", prefix, "Finish(handle: Int): ByteArray?")
		g.P("    private external fun ", prefix, "Cancel(handle: Int): ByteArray?")
		g.P("    private external fun ", prefix, "StartCallback(listener: ", jniKotlinListenerType(service, method), "): Boolean")
		g.P("    private external fun ", prefix, "CancelCallback(): Boolean")
	}
}

func renderKotlinCallbackListener(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan) {
	if method.Streaming != StreamingKindServerStreaming && method.Streaming != StreamingKindBidiStreaming {
		return
	}
	g.P("    interface ", jniKotlinListenerType(service, method), " {")
	g.P("        fun onMessage(responseBytes: ByteArray)")
	g.P("        fun onDone(error: String?)")
	g.P("    }")
	g.P()
}

func renderKotlinCallbackBindingState(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan, className string) {
	if method.Streaming != StreamingKindServerStreaming && method.Streaming != StreamingKindBidiStreaming {
		return
	}
	listenerType := jniKotlinListenerType(service, method)
	bindingType := service.GoName + method.GoName + "CallbackBinding"
	bindingField := lowerInitial(method.GoName) + "CallbackBinding"
	cancelName := lowerInitial(service.GoName) + method.GoName + "CancelCallback"
	g.P("    private val ", bindingField, " = AtomicReference<", bindingType, "?>()")
	g.P()
	g.P("    private class ", bindingType, "(private val lifecycle: RpccgoStreamLifecycle) : RpccgoLifecycleBoundStream {")
	g.P("        private val releasedLifecycle = AtomicBoolean(false)")
	g.P()
	g.P("        fun attach(): String? = lifecycle.attach(this)")
	g.P()
	g.P("        fun releaseLifecycle() {")
	g.P("            if (!releasedLifecycle.compareAndSet(false, true)) return")
	g.P("            lifecycle.detach(this)")
	g.P("            ", bindingField, ".compareAndSet(this, null)")
	g.P("        }")
	g.P()
	g.P("        fun wrap(listener: ", listenerType, "): ", listenerType, " = object : ", listenerType, " {")
	g.P("            override fun onMessage(responseBytes: ByteArray) {")
	g.P("                listener.onMessage(responseBytes)")
	g.P("            }")
	g.P()
	g.P("            override fun onDone(error: String?) {")
	g.P("                releaseLifecycle()")
	g.P("                listener.onDone(error)")
	g.P("            }")
	g.P("        }")
	g.P()
	g.P("        override fun cancelFromLifecycle() {")
	g.P("            ", bindingField, ".compareAndSet(this, null)")
	g.P("            try {")
	g.P("                ", className, ".", cancelName, "()")
	g.P("            } finally {")
	g.P("                releaseLifecycle()")
	g.P("            }")
	g.P("        }")
	g.P("    }")
	g.P()
}

func renderKotlinUnaryMethod(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan) {
	reqType := rpccgoKotlinMessageType(method.Request)
	respType := rpccgoKotlinMessageType(method.Response)
	nativeName := lowerInitial(service.GoName) + method.GoName
	g.P("    fun ", method.GoName, "(req: ", reqType, "): RpccgoResult<", respType, "> =")
	g.P("        decodeResult(", nativeName, "(req.toByteArray())) { ", respType, ".parseFrom(it) }")
	g.P()
}

func renderKotlinClientStreamingMethod(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan, className string) {
	reqType := rpccgoKotlinMessageType(method.Request)
	respType := rpccgoKotlinMessageType(method.Response)
	streamType := service.GoName + method.GoName + "ClientStream"
	nativeName := lowerInitial(service.GoName) + method.GoName
	g.P("    /** Starts the stream bound to the current stream lifecycle. */")
	g.P("    fun ", method.GoName, "Start(): RpccgoResult<", streamType, "> {")
	g.P("        val lifecycle = Rpccgo.currentLifecycle()")
	g.P("        if (lifecycle == null) return RpccgoResult.failure(\"", kotlinMissingStreamLifecycleError, "\")")
	g.P("        val handle = decodeHandleResult(", nativeName, "Start())")
	g.P("        if (!handle.ok) return RpccgoResult.failure(handle.error ?: \"rpccgo: stream start failed\")")
	g.P("        val stream = ", streamType, "(lifecycle, handle.value ?: 0)")
	g.P("        val lifecycleError = lifecycle.attach(stream)")
	g.P("        if (lifecycleError != null) {")
	g.P("            stream.cancelFromLifecycle()")
	g.P("            return RpccgoResult.failure(lifecycleError)")
	g.P("        }")
	g.P("        return RpccgoResult.success(stream)")
	g.P("    }")
	g.P()
	g.P("    class ", streamType, " internal constructor(private val lifecycle: RpccgoStreamLifecycle, private val handle: Int) : RpccgoLifecycleBoundStream {")
	g.P("        private val releasedLifecycle = AtomicBoolean(false)")
	g.P()
	g.P("        fun releaseLifecycle() {")
	g.P("            if (!releasedLifecycle.compareAndSet(false, true)) return")
	g.P("            lifecycle.detach(this)")
	g.P("        }")
	g.P()
	g.P("        override fun cancelFromLifecycle() {")
	g.P("            Cancel()")
	g.P("        }")
	g.P()
	g.P("        fun Send(req: ", reqType, "): RpccgoResult<Unit> =")
	g.P("            decodeUnitResult(", className, ".", nativeName, "Send(handle, req.toByteArray()))")
	g.P("        fun Finish(): RpccgoResult<", respType, "> =")
	g.P("            try {")
	g.P("                decodeResult(", className, ".", nativeName, "Finish(handle)) { ", respType, ".parseFrom(it) }")
	g.P("            } finally {")
	g.P("                releaseLifecycle()")
	g.P("            }")
	g.P("        fun Cancel(): RpccgoResult<Unit> =")
	g.P("            if (releasedLifecycle.get()) RpccgoResult.success(Unit) else")
	g.P("                try {")
	g.P("                    decodeUnitResult(", className, ".", nativeName, "Cancel(handle))")
	g.P("                } finally {")
	g.P("                    releaseLifecycle()")
	g.P("                }")
	g.P("    }")
	g.P()
}

func renderKotlinServerStreamingMethod(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan, className string) {
	reqType := rpccgoKotlinMessageType(method.Request)
	respType := rpccgoKotlinMessageType(method.Response)
	streamType := service.GoName + method.GoName + "ServerStream"
	nativeName := lowerInitial(service.GoName) + method.GoName
	bindingType := service.GoName + method.GoName + "CallbackBinding"
	bindingField := lowerInitial(method.GoName) + "CallbackBinding"
	g.P("    /** Starts the stream bound to the current stream lifecycle. */")
	g.P("    fun ", method.GoName, "Start(req: ", reqType, "): RpccgoResult<", streamType, "> {")
	g.P("        val lifecycle = Rpccgo.currentLifecycle()")
	g.P("        if (lifecycle == null) return RpccgoResult.failure(\"", kotlinMissingStreamLifecycleError, "\")")
	g.P("        val handle = decodeHandleResult(", nativeName, "Start(req.toByteArray()))")
	g.P("        if (!handle.ok) return RpccgoResult.failure(handle.error ?: \"rpccgo: stream start failed\")")
	g.P("        val stream = ", streamType, "(lifecycle, handle.value ?: 0)")
	g.P("        val lifecycleError = lifecycle.attach(stream)")
	g.P("        if (lifecycleError != null) {")
	g.P("            stream.cancelFromLifecycle()")
	g.P("            return RpccgoResult.failure(lifecycleError)")
	g.P("        }")
	g.P("        return RpccgoResult.success(stream)")
	g.P("    }")
	g.P("    /** Starts callback delivery bound to the current stream lifecycle. */")
	g.P("    fun ", method.GoName, "StartCallback(req: ", reqType, ", listener: ", jniKotlinListenerType(service, method), "): Boolean {")
	g.P("        val lifecycle = Rpccgo.currentLifecycle() ?: return false")
	g.P("        val binding = ", bindingType, "(lifecycle)")
	g.P("        val lifecycleError = binding.attach()")
	g.P("        if (lifecycleError != null) return false")
	g.P("        val previous = ", bindingField, ".getAndSet(binding)")
	g.P("        previous?.releaseLifecycle()")
	g.P("        if (!", nativeName, "StartCallback(req.toByteArray(), binding.wrap(listener))) {")
	g.P("            ", bindingField, ".compareAndSet(binding, null)")
	g.P("            binding.releaseLifecycle()")
	g.P("            return false")
	g.P("        }")
	g.P("        return true")
	g.P("    }")
	g.P("    fun ", method.GoName, "CancelCallback(): Boolean {")
	g.P("        val binding = ", bindingField, ".getAndSet(null)")
	g.P("        if (binding == null) return true")
	g.P("        return try {")
	g.P("            ", nativeName, "CancelCallback()")
	g.P("        } finally {")
	g.P("            binding?.releaseLifecycle()")
	g.P("        }")
	g.P("    }")
	g.P()
	g.P("    class ", streamType, " internal constructor(private val lifecycle: RpccgoStreamLifecycle, private val handle: Int) : RpccgoLifecycleBoundStream {")
	g.P("        private val releasedLifecycle = AtomicBoolean(false)")
	g.P("        private val receiving = AtomicBoolean(false)")
	g.P()
	g.P("        fun releaseLifecycle() {")
	g.P("            if (!releasedLifecycle.compareAndSet(false, true)) return")
	g.P("            lifecycle.detach(this)")
	g.P("        }")
	g.P()
	g.P("        override fun cancelFromLifecycle() {")
	g.P("            Cancel()")
	g.P("        }")
	g.P()
	g.P("        private fun recvUnchecked(): RpccgoResult<", respType, "> =")
	g.P("            decodeResult(", className, ".", nativeName, "Recv(handle)) { ", respType, ".parseFrom(it) }")
	g.P("        /** Receives one response. Do not call while RecvEach is running on this stream. */")
	g.P("        fun Recv(): RpccgoResult<", respType, "> {")
	g.P("            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure(\"rpccgo: stream already has an active receiver\")")
	g.P("            val next = try {")
	g.P("                recvUnchecked()")
	g.P("            } finally {")
	g.P("                receiving.set(false)")
	g.P("            }")
	g.P("            if (!next.ok) releaseLifecycle()")
	g.P("            return next")
	g.P("        }")
	g.P("        fun Cancel(): RpccgoResult<Unit> =")
	g.P("            if (releasedLifecycle.get()) RpccgoResult.success(Unit) else")
	g.P("                try {")
	g.P("                    decodeUnitResult(", className, ".", nativeName, "Cancel(handle))")
	g.P("                } finally {")
	g.P("                    releaseLifecycle()")
	g.P("                }")
	renderKotlinReceiveEachMethod(g, respType)
	g.P("    }")
	g.P()
}

func renderKotlinBidiStreamingMethod(g *protogen.GeneratedFile, service ServicePlan, method MethodPlan, className string) {
	reqType := rpccgoKotlinMessageType(method.Request)
	respType := rpccgoKotlinMessageType(method.Response)
	streamType := service.GoName + method.GoName + "BidiStream"
	nativeName := lowerInitial(service.GoName) + method.GoName
	bindingType := service.GoName + method.GoName + "CallbackBinding"
	bindingField := lowerInitial(method.GoName) + "CallbackBinding"
	g.P("    /** Starts the stream bound to the current stream lifecycle. */")
	g.P("    fun ", method.GoName, "Start(): RpccgoResult<", streamType, "> {")
	g.P("        val lifecycle = Rpccgo.currentLifecycle()")
	g.P("        if (lifecycle == null) return RpccgoResult.failure(\"", kotlinMissingStreamLifecycleError, "\")")
	g.P("        val handle = decodeHandleResult(", nativeName, "Start())")
	g.P("        if (!handle.ok) return RpccgoResult.failure(handle.error ?: \"rpccgo: stream start failed\")")
	g.P("        val stream = ", streamType, "(lifecycle, handle.value ?: 0)")
	g.P("        val lifecycleError = lifecycle.attach(stream)")
	g.P("        if (lifecycleError != null) {")
	g.P("            stream.cancelFromLifecycle()")
	g.P("            return RpccgoResult.failure(lifecycleError)")
	g.P("        }")
	g.P("        return RpccgoResult.success(stream)")
	g.P("    }")
	g.P("    /** Starts callback delivery bound to the current stream lifecycle. */")
	g.P("    fun ", method.GoName, "StartCallback(listener: ", jniKotlinListenerType(service, method), "): Boolean {")
	g.P("        val lifecycle = Rpccgo.currentLifecycle() ?: return false")
	g.P("        val binding = ", bindingType, "(lifecycle)")
	g.P("        val lifecycleError = binding.attach()")
	g.P("        if (lifecycleError != null) return false")
	g.P("        val previous = ", bindingField, ".getAndSet(binding)")
	g.P("        previous?.releaseLifecycle()")
	g.P("        if (!", nativeName, "StartCallback(binding.wrap(listener))) {")
	g.P("            ", bindingField, ".compareAndSet(binding, null)")
	g.P("            binding.releaseLifecycle()")
	g.P("            return false")
	g.P("        }")
	g.P("        return true")
	g.P("    }")
	g.P("    fun ", method.GoName, "CancelCallback(): Boolean {")
	g.P("        val binding = ", bindingField, ".getAndSet(null)")
	g.P("        if (binding == null) return true")
	g.P("        return try {")
	g.P("            ", nativeName, "CancelCallback()")
	g.P("        } finally {")
	g.P("            binding?.releaseLifecycle()")
	g.P("        }")
	g.P("    }")
	g.P()
	g.P("    class ", streamType, " internal constructor(private val lifecycle: RpccgoStreamLifecycle, private val handle: Int) : RpccgoLifecycleBoundStream {")
	g.P("        private val releasedLifecycle = AtomicBoolean(false)")
	g.P("        private val receiving = AtomicBoolean(false)")
	g.P()
	g.P("        fun releaseLifecycle() {")
	g.P("            if (!releasedLifecycle.compareAndSet(false, true)) return")
	g.P("            lifecycle.detach(this)")
	g.P("        }")
	g.P()
	g.P("        override fun cancelFromLifecycle() {")
	g.P("            Cancel()")
	g.P("        }")
	g.P()
	g.P("        fun Send(req: ", reqType, "): RpccgoResult<Unit> =")
	g.P("            decodeUnitResult(", className, ".", nativeName, "Send(handle, req.toByteArray()))")
	g.P("        private fun recvUnchecked(): RpccgoResult<", respType, "> =")
	g.P("            decodeResult(", className, ".", nativeName, "Recv(handle)) { ", respType, ".parseFrom(it) }")
	g.P("        /** Receives one response. Do not call while RecvEach is running on this stream. */")
	g.P("        fun Recv(): RpccgoResult<", respType, "> {")
	g.P("            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure(\"rpccgo: stream already has an active receiver\")")
	g.P("            val next = try {")
	g.P("                recvUnchecked()")
	g.P("            } finally {")
	g.P("                receiving.set(false)")
	g.P("            }")
	g.P("            if (!next.ok) releaseLifecycle()")
	g.P("            return next")
	g.P("        }")
	g.P("        fun CloseSend(): RpccgoResult<Unit> =")
	g.P("            decodeUnitResult(", className, ".", nativeName, "CloseSend(handle))")
	g.P("        fun Finish(): RpccgoResult<Unit> =")
	g.P("            try {")
	g.P("                decodeUnitResult(", className, ".", nativeName, "Finish(handle))")
	g.P("            } finally {")
	g.P("                releaseLifecycle()")
	g.P("            }")
	g.P("        fun Cancel(): RpccgoResult<Unit> =")
	g.P("            if (releasedLifecycle.get()) RpccgoResult.success(Unit) else")
	g.P("                try {")
	g.P("                    decodeUnitResult(", className, ".", nativeName, "Cancel(handle))")
	g.P("                } finally {")
	g.P("                    releaseLifecycle()")
	g.P("                }")
	renderKotlinReceiveEachMethod(g, respType)
	g.P("    }")
	g.P()
}

func renderKotlinReceiveEachMethod(g *protogen.GeneratedFile, respType string) {
	g.P("        /** Starts a background Recv loop. Do not mix with manual Recv calls on this stream. */")
	g.P("        fun RecvEach(onMessage: (", respType, ") -> Unit, onError: (String) -> Unit = {}): RpccgoResult<Thread> {")
	g.P("            if (!receiving.compareAndSet(false, true)) return RpccgoResult.failure(\"rpccgo: stream already has an active receiver\")")
	g.P("            val worker = Thread {")
	g.P("                try {")
	g.P("                    while (true) {")
	g.P("                        val next = recvUnchecked()")
	g.P("                        if (!next.ok) {")
	g.P("                            releaseLifecycle()")
	g.P("                            onError(next.error ?: \"rpccgo: stream recv failed\")")
	g.P("                            return@Thread")
	g.P("                        }")
	g.P("                        val value = next.value ?: return@Thread")
	g.P("                        onMessage(value)")
	g.P("                    }")
	g.P("                } finally {")
	g.P("                    receiving.set(false)")
	g.P("                    Cancel()")
	g.P("                }")
	g.P("            }")
	g.P("            worker.start()")
	g.P("            return RpccgoResult.success(worker)")
	g.P("        }")
}

func serviceHasRecvStreamingMethod(service ServicePlan) bool {
	for _, method := range service.Methods {
		if method.Streaming == StreamingKindServerStreaming || method.Streaming == StreamingKindBidiStreaming {
			return true
		}
	}
	return false
}

func jniKotlinListenerType(service ServicePlan, method MethodPlan) string {
	return service.GoName + method.GoName + "Listener"
}
