package generator

import "google.golang.org/protobuf/compiler/protogen"

func renderMessageStartHelpers(g *protogen.GeneratedFile, service ServicePlan, methods []runtimeMethodProjection, serverName string) {
	for _, method := range methods {
		if !method.Stream.Streaming {
			continue
		}
		switch method.Stream.Shape {
		case runtimeStreamClient:
			renderMessageServerClientStreamStartHelper(g, service.GoName, serverName, method)
		case runtimeStreamServer:
			renderMessageServerServerStreamStartHelper(g, service.GoName, serverName, method)
		case runtimeStreamBidi:
			renderMessageServerBidiStreamStartHelper(g, service.GoName, serverName, method)
		}
	}
}

func cgoMessageStartHelperName(serviceName, methodName string) string {
	return "start" + serviceName + "CGOMessage" + methodName
}

func renderMessageServerClientStreamStartHelper(g *protogen.GeneratedFile, serviceName, serverName string, method runtimeMethodProjection) {
	sessionName := runtimeCGOMessageSessionInterface(method)
	receiver := lowerInitial(serviceName) + method.Identity.GoName + "MessageServerClientStreamSession"
	reqType := runtimeMessageRequestType(method)
	respType := runtimeMessageResponseType(method)
	g.P("func ", cgoMessageStartHelperName(serviceName, method.Identity.GoName), "(ctx context.Context, server ", serverName, ") (", sessionName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("session := &", receiver, "{ctx: streamCtx, cancel: cancel, requests: make(chan ", receiver, "Request, 16), sendDone: make(chan struct{}), done: make(chan struct{})}")
	g.P("go func() {")
	g.P("defer close(session.done)")
	g.P("session.resp, session.err = server.", method.Identity.GoName, "(streamCtx, session)")
	g.P("}()")
	g.P("return session, nil")
	g.P("}")
	g.P()
	g.P("type ", receiver, "Request struct {")
	g.P("data ", reqType)
	g.P("received chan struct{}")
	g.P("}")
	g.P()
	g.P("type ", receiver, " struct {")
	g.P("ctx context.Context")
	g.P("cancel context.CancelFunc")
	g.P("requests chan ", receiver, "Request")
	g.P("sendDone chan struct{}")
	g.P("closeSendOnce sync.Once")
	g.P("received chan struct{}")
	g.P("done chan struct{}")
	g.P("resp ", respType)
	g.P("err error")
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") Recv(ctx context.Context) (", reqType, ", error) {")
	g.P("select {")
	g.P("case req := <-s.requests:")
	g.P("close(req.received)")
	g.P("return req.data, nil")
	g.P("default:")
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return nil, ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return nil, s.ctx.Err()")
	g.P("case req := <-s.requests:")
	g.P("close(req.received)")
	g.P("return req.data, nil")
	g.P("case <-s.sendDone:")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") Send(ctx context.Context, req ", reqType, ") error {")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("select {")
	g.P("case <-s.sendDone:")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("default:")
	g.P("}")
	g.P("queued := ", receiver, "Request{data: req, received: make(chan struct{})}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case <-s.done:")
	g.P("select {")
	g.P("case <-queued.received:")
	g.P("return nil")
	g.P("default:")
	g.P("}")
	g.P("if s.err != nil { return s.err }")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case <-s.sendDone:")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case s.requests <- queued:")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case <-s.done:")
	g.P("select {")
	g.P("case <-queued.received:")
	g.P("return nil")
	g.P("default:")
	g.P("}")
	g.P("if s.err != nil { return s.err }")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case <-s.sendDone:")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case <-queued.received:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") Finish(ctx context.Context) (", respType, ", error) {")
	g.P("s.closeSendOnce.Do(func() { close(s.sendDone) })")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return nil, ctx.Err()")
	g.P("case <-s.done:")
	g.P("s.cancel()")
	g.P("return s.resp, s.err")
	g.P("}")
	g.P("}")
	g.P()
	renderMessageServerGeneratedCancel(g, receiver, true)
}

func renderMessageServerServerStreamStartHelper(g *protogen.GeneratedFile, serviceName, serverName string, method runtimeMethodProjection) {
	sessionName := runtimeCGOMessageSessionInterface(method)
	receiver := lowerInitial(serviceName) + method.Identity.GoName + "MessageServerServerStreamSession"
	reqType := runtimeMessageRequestType(method)
	respType := runtimeMessageResponseType(method)
	g.P("func ", cgoMessageStartHelperName(serviceName, method.Identity.GoName), "(ctx context.Context, server ", serverName, ", req ", reqType, ") (", sessionName, ", error) {")
	g.P("if req == nil {")
	g.P(`return nil, errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("finishCtx, finishCancel := context.WithCancel(context.Background())")
	g.P("session := &", receiver, "{ctx: streamCtx, cancel: cancel, finishCtx: finishCtx, finishCancel: finishCancel, responses: make(chan ", receiver, "Response, 1), done: make(chan struct{})}")
	g.P("go func() {")
	g.P("defer close(session.done)")
	g.P("session.err = server.", method.Identity.GoName, "(streamCtx, req, session)")
	g.P("}()")
	g.P("return session, nil")
	g.P("}")
	g.P()
	g.P("type ", receiver, "Response struct {")
	g.P("data ", respType)
	g.P("received chan struct{}")
	g.P("}")
	g.P()
	g.P("type ", receiver, " struct {")
	g.P("ctx context.Context")
	g.P("cancel context.CancelFunc")
	g.P("finishCtx context.Context")
	g.P("finishCancel context.CancelFunc")
	g.P("responses chan ", receiver, "Response")
	g.P("received chan struct{}")
	g.P("done chan struct{}")
	g.P("err error")
	g.P("}")
	g.P()
	renderMessageServerStreamSend(g, receiver, respType)
	renderMessageServerStreamRecv(g, receiver, respType)
	renderMessageServerGeneratedFinish(g, receiver)
	renderMessageServerGeneratedCancel(g, receiver, false)
}

func renderMessageServerBidiStreamStartHelper(g *protogen.GeneratedFile, serviceName, serverName string, method runtimeMethodProjection) {
	sessionName := runtimeCGOMessageSessionInterface(method)
	receiver := lowerInitial(serviceName) + method.Identity.GoName + "MessageServerBidiStreamSession"
	facadeName := lowerInitial(serviceName) + method.Identity.GoName + "MessageServerBidiStreamFacade"
	reqType := runtimeMessageRequestType(method)
	respType := runtimeMessageResponseType(method)
	g.P("func ", cgoMessageStartHelperName(serviceName, method.Identity.GoName), "(ctx context.Context, server ", serverName, ") (", sessionName, ", error) {")
	g.P("streamCtx, cancel := context.WithCancel(ctx)")
	g.P("finishCtx, finishCancel := context.WithCancel(context.Background())")
	g.P("session := &", receiver, "{ctx: streamCtx, cancel: cancel, finishCtx: finishCtx, finishCancel: finishCancel, requests: make(chan ", receiver, "Request, 16), sendDone: make(chan struct{}), sendDoneReceived: make(chan struct{}), responses: make(chan ", receiver, "Response, 1), done: make(chan struct{})}")
	g.P("go func() {")
	g.P("defer close(session.done)")
	g.P("session.err = server.", method.Identity.GoName, "(streamCtx, &", facadeName, "{source: session})")
	g.P("}()")
	g.P("return session, nil")
	g.P("}")
	g.P()
	g.P("type ", receiver, "Request struct {")
	g.P("data ", reqType)
	g.P("received chan struct{}")
	g.P("}")
	g.P()
	g.P("type ", receiver, "Response struct {")
	g.P("data ", respType)
	g.P("received chan struct{}")
	g.P("}")
	g.P()
	g.P("type ", receiver, " struct {")
	g.P("ctx context.Context")
	g.P("cancel context.CancelFunc")
	g.P("finishCtx context.Context")
	g.P("finishCancel context.CancelFunc")
	g.P("requests chan ", receiver, "Request")
	g.P("sendDone chan struct{}")
	g.P("sendDoneReceived chan struct{}")
	g.P("sendDoneReceivedOnce sync.Once")
	g.P("closeSendOnce sync.Once")
	g.P("responses chan ", receiver, "Response")
	g.P("received chan struct{}")
	g.P("done chan struct{}")
	g.P("err error")
	g.P("}")
	g.P()
	g.P("type ", facadeName, " struct {")
	g.P("source *", receiver)
	g.P("}")
	g.P()
	g.P("func (s *", facadeName, ") Recv(ctx context.Context) (", reqType, ", error) {")
	g.P("return s.source.recvRequest(ctx)")
	g.P("}")
	g.P()
	g.P("func (s *", facadeName, ") Send(ctx context.Context, resp ", respType, ") error {")
	g.P("return s.source.sendResponse(ctx, resp)")
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") recvRequest(ctx context.Context) (", reqType, ", error) {")
	g.P("select {")
	g.P("case req := <-s.requests:")
	g.P("close(req.received)")
	g.P("return req.data, nil")
	g.P("default:")
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return nil, ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return nil, s.ctx.Err()")
	g.P("case req := <-s.requests:")
	g.P("close(req.received)")
	g.P("return req.data, nil")
	g.P("case <-s.sendDone:")
	g.P("s.sendDoneReceivedOnce.Do(func() { close(s.sendDoneReceived) })")
	g.P("return nil, io.EOF")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") sendResponse(ctx context.Context, resp ", respType, ") error {")
	g.P("if resp == nil {")
	g.P(`return errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("response := ", receiver, "Response{data: resp, received: make(chan struct{})}")
	renderMessageServerSendResponseBody(g)
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") Send(ctx context.Context, req ", reqType, ") error {")
	g.P("if req == nil {")
	g.P(`return errors.New("rpccgo: message request is nil")`)
	g.P("}")
	g.P("select {")
	g.P("case <-s.sendDone:")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("default:")
	g.P("}")
	g.P("queued := ", receiver, "Request{data: req, received: make(chan struct{})}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case <-s.done:")
	g.P("select {")
	g.P("case <-queued.received:")
	g.P("return nil")
	g.P("default:")
	g.P("}")
	g.P("return nil")
	g.P("case <-s.sendDone:")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case s.requests <- queued:")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case <-s.done:")
	g.P("select {")
	g.P("case <-queued.received:")
	g.P("return nil")
	g.P("default:")
	g.P("}")
	g.P("return nil")
	g.P("case <-s.sendDone:")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case <-queued.received:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") Recv(ctx context.Context) (", respType, ", error) {")
	renderMessageServerStreamRecvBody(g)
	g.P("}")
	g.P()
	g.P("func (s *", receiver, ") CloseSend(ctx context.Context) error {")
	g.P("s.closeSendOnce.Do(func() { close(s.sendDone) })")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return s.ctx.Err()")
	g.P("case <-s.done:")
	g.P("if s.err != nil { return s.err }")
	g.P("return nil")
	g.P("case <-s.sendDoneReceived:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P()
	renderMessageServerGeneratedFinish(g, receiver)
	renderMessageServerGeneratedCancel(g, receiver, true)
}

func renderMessageServerStreamSend(g *protogen.GeneratedFile, receiver, responseType string) {
	g.P("func (s *", receiver, ") Send(ctx context.Context, resp ", responseType, ") error {")
	g.P("if resp == nil {")
	g.P(`return errors.New("rpccgo: message response is nil")`)
	g.P("}")
	g.P("response := ", receiver, "Response{data: resp, received: make(chan struct{})}")
	renderMessageServerSendResponseBody(g)
	g.P("}")
	g.P()
}

func renderMessageServerSendResponseBody(g *protogen.GeneratedFile) {
	g.P("select {")
	g.P("case <-s.done:")
	g.P("if s.err != nil { return s.err }")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case <-s.finishCtx.Done():")
	g.P("return io.EOF")
	g.P("default:")
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("select {")
	g.P("case <-s.finishCtx.Done():")
	g.P("return io.EOF")
	g.P("default:")
	g.P("}")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("select {")
	g.P("case <-s.finishCtx.Done():")
	g.P("return io.EOF")
	g.P("default:")
	g.P("}")
	g.P("return s.ctx.Err()")
	g.P("case <-s.finishCtx.Done():")
	g.P("return io.EOF")
	g.P("case <-s.done:")
	g.P("if s.err != nil { return s.err }")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case s.responses <- response:")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("select {")
	g.P("case <-s.finishCtx.Done():")
	g.P("return io.EOF")
	g.P("default:")
	g.P("}")
	g.P("return ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("select {")
	g.P("case <-s.finishCtx.Done():")
	g.P("return io.EOF")
	g.P("default:")
	g.P("}")
	g.P("return s.ctx.Err()")
	g.P("case <-s.finishCtx.Done():")
	g.P("return io.EOF")
	g.P("case <-s.done:")
	g.P("if s.err != nil { return s.err }")
	g.P(`return errors.New("rpccgo: message stream is closed")`)
	g.P("case <-response.received:")
	g.P("if s.ctx.Err() != nil {")
	g.P("select {")
	g.P("case <-s.finishCtx.Done():")
	g.P("return io.EOF")
	g.P("default:")
	g.P("}")
	g.P("return s.ctx.Err()")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P("}")
}

func renderMessageServerStreamRecv(g *protogen.GeneratedFile, receiver, responseType string) {
	g.P("func (s *", receiver, ") Recv(ctx context.Context) (", responseType, ", error) {")
	renderMessageServerStreamRecvBody(g)
	g.P("}")
	g.P()
}

func renderMessageServerStreamRecvBody(g *protogen.GeneratedFile) {
	g.P("if s.received != nil {")
	g.P("close(s.received)")
	g.P("s.received = nil")
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return nil, ctx.Err()")
	g.P("case <-s.ctx.Done():")
	g.P("return nil, s.ctx.Err()")
	g.P("case resp := <-s.responses:")
	g.P("s.received = resp.received")
	g.P("return resp.data, nil")
	g.P("case <-s.done:")
	g.P("if s.received != nil {")
	g.P("close(s.received)")
	g.P("s.received = nil")
	g.P("}")
	g.P("if s.err != nil {")
	g.P("return nil, s.err")
	g.P("}")
	g.P("return nil, io.EOF")
	g.P("}")
}

func renderMessageServerGeneratedFinish(g *protogen.GeneratedFile, receiver string) {
	g.P("func (s *", receiver, ") Finish(ctx context.Context) error {")
	g.P("s.finishCancel()")
	g.P("s.cancel()")
	g.P("if s.received != nil {")
	g.P("close(s.received)")
	g.P("s.received = nil")
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.done:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P()
}

func renderMessageServerGeneratedCancel(g *protogen.GeneratedFile, receiver string, closeSend bool) {
	g.P("func (s *", receiver, ") Cancel(ctx context.Context) error {")
	g.P("s.cancel()")
	g.P("if s.received != nil {")
	g.P("close(s.received)")
	g.P("s.received = nil")
	g.P("}")
	g.P("select {")
	g.P("case <-ctx.Done():")
	g.P("return ctx.Err()")
	g.P("case <-s.done:")
	g.P("return nil")
	g.P("}")
	g.P("}")
	g.P()
	_ = closeSend
}
