package generator

import "google.golang.org/protobuf/compiler/protogen"

func renderCGOExportSupportFile(plugin *protogen.Plugin, pkg PackagePlan, file GeneratedArtifactPlan) {
	g := newGeneratedSharedFile(plugin, file, protogen.GoImportPath(packageCGOImportPath(pkg)), "rpccgo cgo export support")
	g.P("package main")
	g.P()
	g.P("/*")
	g.P("#include <stdint.h>")
	g.P()
	g.P("typedef void (*rpccgo_free_callback)(void*);")
	g.P()
	g.P("static inline void rpccgo_call_free_callback(rpccgo_free_callback callback, void* ptr) {")
	g.P("callback(ptr);")
	g.P("}")
	g.P("*/")
	g.P(`import "C"`)
	g.P()
	g.P("import (")
	g.P(`errors "errors"`)
	g.P(`fmt "fmt"`)
	g.P(`rpcruntime "`, rpcruntimeImportPath, `"`)
	g.P(`unsafe "unsafe"`)
	g.P(")")
	g.P()
	g.P("// rpccgo cgo support generated file for shared exports")
	g.P()
	renderCGOExportDoc(g, "rpccgo_register_free", "registers the C free callback used to release C-owned memory.")
	g.P("//export rpccgo_register_free")
	g.P("func rpccgo_register_free(callback C.rpccgo_free_callback) C.int32_t {")
	g.P("if callback == nil {")
	g.P("return -1")
	g.P("}")
	g.P("rpcruntime.RegisterFreeCallback(func(ptr unsafe.Pointer) {")
	g.P("C.rpccgo_call_free_callback(callback, ptr)")
	g.P("})")
	g.P("return 0")
	g.P("}")
	g.P()
	renderCGOExportDoc(g, "rpccgo_store_error_text", "stores C error text in the Go error registry and returns its error id.")
	g.P("//export rpccgo_store_error_text")
	g.P("func rpccgo_store_error_text(text *C.char, textLen C.int32_t) C.int32_t {")
	g.P("length, err := rpcruntime.LengthFromInt32(int32(textLen))")
	g.P("if err != nil {")
	g.P(`return C.int32_t(rpcruntime.StoreError(fmt.Errorf("rpccgo: cgo error text: %w", err)))`)
	g.P("}")
	g.P("if text == nil && length != 0 {")
	g.P(`return C.int32_t(rpcruntime.StoreError(errors.New("rpccgo: cgo error text pointer is nil")))`)
	g.P("}")
	g.P("var data []byte")
	g.P("if length != 0 {")
	g.P("data = unsafe.Slice((*byte)(unsafe.Pointer(text)), length)")
	g.P("}")
	g.P("return C.int32_t(rpcruntime.StoreError(errors.New(string(data))))")
	g.P("}")
	g.P()
	renderCGOExportDoc(g, "rpccgo_take_error_text", "takes stored Go error text for a C caller and releases the error id.")
	g.P("//export rpccgo_take_error_text")
	g.P("func rpccgo_take_error_text(errID C.int32_t, textPtr *C.uintptr_t, textLen *C.int32_t) C.int32_t {")
	g.P("if textPtr == nil || textLen == nil {")
	g.P("return -1")
	g.P("}")
	g.P("var goPtr uintptr")
	g.P("var goLen int32")
	g.P("status := rpcruntime.TakeErrorTextForExport(int32(errID), &goPtr, &goLen)")
	g.P("if status != 0 {")
	g.P("return C.int32_t(status)")
	g.P("}")
	g.P("*textPtr = C.uintptr_t(goPtr)")
	g.P("*textLen = C.int32_t(goLen)")
	g.P("return 0")
	g.P("}")
	g.P()
	renderCGOExportDoc(g, "rpccgo_release", "releases memory previously handed to C through rpccgo ABI helpers.")
	g.P("//export rpccgo_release")
	g.P("func rpccgo_release(ptr C.uintptr_t) C.int32_t {")
	g.P("if !rpcruntime.Release(uintptr(ptr)) {")
	g.P("return -1")
	g.P("}")
	g.P("return 0")
	g.P("}")
}
